import type { ArtistConfig } from './types';

export const aapgoldConfig: ArtistConfig = {
  slug: 'aapgold',
  hasGroupbuysTab: true,
  hasAlbumCopiesTab: true,
  SITE_NAME: 'A$APGOLD',
  SITE_DESCRIPTION: 'The Best A$AP Rocky Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/aapgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'aapgold_',
  HARDCODED_SHEET_ID: '1rbt_VyQyHEfVRv_XmVBNrwMyF0uMx7FF-1T8-N0wf0E',
  HARDCODED_SHEET_GID: '1701548408',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1rbt_VyQyHEfVRv_XmVBNrwMyF0uMx7FF-1T8-N0wf0E/export?format=csv&gid=575509772',
  accentColor: '#7c3aed',
  artistLabel: 'A$AP Rocky',
  sheetCreator: 'KILLRITE, geroerg, Digital Hendryk',
  cardLetter: 'ASAP',
  logoUrl: '/logos/aapgold.png',
  artistPhotoUrl: '/artists/asaprocky-v2.jpg',

  getArtistName() {
    return 'A$AP Rocky';
  },

  CUSTOM_IMAGES: {
    'Pre-MDB': '/aapgold/eras/pre-mdb.jpg',
    'MDB': '/aapgold/eras/mdb.jpg',
    'A$AP (2007-2009)': '/aapgold/eras/asap-2007-2009.jpg',
    'A$AP (Mob Collab)': '/aapgold/eras/asap-mob-collab.jpg',
    'A$AP (2010)': '/aapgold/eras/asap-2010.jpg',
    'Untitled': '/aapgold/eras/untitled.jpg',
    'Untitled Mixtape with Seth Narley': '/aapgold/eras/untitled-mixtape-with-seth-narley.jpg',
    'Rug Of War 1994': '/aapgold/eras/rug-of-war-1994.jpg',
    'Purple Swag': '/aapgold/eras/purple-swag.jpg',
    'Me, Myself & A$AP': '/aapgold/eras/me-myself-and-asap.jpg',
    'Mouth Fulla Gold': '/aapgold/eras/mouth-fulla-gold.jpg',
    'LIVE.LOVE.A$AP [V1]': '/aapgold/eras/live-love-asap-v1.jpg',
    'LIVE.LOVE.A$AP [V2]': '/aapgold/eras/live-love-asap-v2.jpg',
    'B.M.W': '/aapgold/eras/b-m-w.jpg',
    'LIVE.LOVE.A$AP [Deluxe]': '/aapgold/eras/live-love-asap-deluxe.jpg',
    'LIVE.LOVE.A$AP [Re-Release]': '/aapgold/eras/gr1m-v3.jpg',
    'Pre-LONG.LIVE.A$AP': '/aapgold/eras/pre-long-live-asap.jpg',
    'Last Cab 2 Harlem [V2]': '/aapgold/eras/lords-never-worry.jpg',
    "Lord$ Never Worry": '/aapgold/eras/lords-never-worry.jpg',
    'LONG.LIVE.A$AP': '/aapgold/eras/long-live-asap.jpg',
    'Pre-AT.LONG.LAST.A$AP': '/aapgold/eras/pre-at-long-last-asap.jpg',
    'BEAUTY AND THE BEAST: SLOWED DOWN SESSIONS, CHAPTER 1': '/aapgold/eras/beauty-and-the-beast-slowed-down-sessions-chapter-1.jpg',
    'L.O.R.D.': '/aapgold/eras/l-o-r-d.jpg',
    'AT.LONG.LAST.A$AP': '/aapgold/eras/at-long-last-asap.jpg',
    'Cozy Tapes Vol. 1: Friends -': '/aapgold/eras/cozy-tapes-vol-1-friends.jpg',
    'Pre-TESTING': '/aapgold/eras/pre-testing.jpg',
    'TESTING [V1]': '/aapgold/eras/testing-v1.jpg',
    'Rocky Montana': '/aapgold/eras/rocky-montana.jpg',
    'DUMMY [V1]': '/aapgold/eras/dummy-v1.jpg',
    'Cozy Tapes Vol. 2: Too Cozy': '/aapgold/eras/cozy-tapes-vol-2-too-cozy.jpg',
    'DUMMIE [V2]': '/aapgold/eras/dummie-v2.jpg',
    'TESTING [V2]': '/aapgold/eras/testing-v2.jpg',
    'TESTING [Deluxe]': '/aapgold/eras/testing-deluxe.jpg',
    'TESTING [Chopped & Screwed]': '/aapgold/eras/testing-chopped-and-screwed.jpg',
    'Cozy Tapes Vol. 3 [V1]': '/aapgold/eras/cozy-tapes-vol-3-v1.jpg',
    'WANG$AP': '/aapgold/eras/wangsap.jpg',
    'TESTING': '/aapgold/eras/testing.jpg',
    'ALL $MILE$ [V1]': '/aapgold/eras/all-smiles-v1.jpg',
    'ALL $MILE$ [V2]': '/aapgold/eras/all-smiles-v2.jpg',
    'Cozy Tapes Vol. 3 [V2]': '/aapgold/eras/cozy-tapes-vol-3-v2.jpg',
    'THE GR1M [V1]': '/aapgold/eras/the-gr1m-v1.jpg',
    'Cozy Tapes Vol. 3 [V3]': '/aapgold/eras/cozy-tapes-vol-3-v3.jpg',
    'GR1M [V2]': '/aapgold/eras/gr1m-v2.jpg',
    'GR1M [V3]': '/aapgold/eras/don-t-be-dumb-v1.jpg',
    "DON'T BE DUMB [V1]": "/aapgold/eras/asap-jean.jpg",
    'A$AP JEAN': '/aapgold/eras/don-t-be-dumb-v2.jpg',
    "DON'T BE DUMB [V2]": "/aapgold/eras/don-t-be-dumb-v3.jpg",
    "DON'T BE DUMB [V3]": "/aapgold/eras/don-t-be-dumb-v4.jpg",
    "DON'T BE DUMB [V4]": "/aapgold/eras/don-t-be-dumb.jpg",
    "DON'T BE DUMB": '/artists/asaprocky-v2.jpg',
    "DON'T BE DUMB [DISC 2]": '/artists/asaprocky-v2.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Pre-MDB': '??/??/????',
    'MDB': '??/??/????',
    'A$AP (2007-2009)': '??/??/????',
    'A$AP (Mob Collab)': '??/??/????',
    'A$AP (2010)': '09/13/2010',
    'Untitled': '??/??/????',
    'Untitled Mixtape with Seth Narley': '??/??/2010',
    'Rug Of War 1994': '??/??/????',
    'Purple Swag': '10/28/2010',
    'Me, Myself & A$AP': '04/14/2011',
    'Mouth Fulla Gold': '05/21/2011',
    'LIVE.LOVE.A$AP [V1]': '10/31/2011',
    'LIVE.LOVE.A$AP [Promo CD]': '??/??/2011',
    'LIVE.LOVE.A$AP [V2]': '??/??/????',
    'B.M.W': '??/??/????',
    'LIVE.LOVE.A$AP [Deluxe]': '03/23/2012',
    'LIVE.LOVE.A$AP [Re-Release]': '??/??/2021',
    'Pre-LONG.LIVE.A$AP': '11/08/2011',
    'LONG.LIVE.A$AP (with A$AP Mob) [V1]': '??/??/2011',
    'Last Cab 2 Harlem [V2]': '01/01/2012',
    "Lord$ Never Worry": '01/07/2012',
    'LONG.LIVE.A$AP': '01/15/2013',
    'Pre-AT.LONG.LAST.A$AP': '??/??/????',
    'BEAUTY AND THE BEAST: SLOWED DOWN SESSIONS, CHAPTER 1': '03/03/2014',
    'L.O.R.D.': '07/08/2013',
    'AT.LONG.LAST.A$AP': '05/26/2015',
    'Cozy Tapes Vol. 1: Friends -': '09/30/2016',
    'Pre-TESTING': '06/22/2015',
    'Wavy Wednesdays': '01/27/2016',
    'TESTING [V1]': '??/??/????',
    'Rocky Montana': '??/??/????',
    'DUMMY [V1]': '??/??/????',
    'Cozy Tapes Vol. 2: Too Cozy': '11/17/2017',
    'DUMMIE [V2]': '??/??/????',
    'DUMMIE': '01/??/2018',
    'TESTING [V2]': '??/??/????',
    'TESTING [Deluxe]': '??/??/????',
    'TESTING [Chopped & Screwed]': '05/02/2019',
    'Cozy Tapes Vol. 3 [V1]': '??/??/????',
    'WANG$AP': '??/??/????',
    'TESTING': '12/21/2018',
    'ALL $MILE$ [V1]': '06/15/2018',
    'ALL $MILE$ [V2]': '??/??/????',
    'ALL $MILE$': '??/??/2019',
    'Cozy Tapes Vol. 3 [V2]': '??/??/????',
    'THE GR1M [V1]': '??/??/????',
    'Cozy Tapes Vol. 3 [V3]': '??/??/????',
    'GR1M [V2]': '??/??/????',
    'GR1M [V3]': '09/02/2022',
    "DON'T BE DUMB [V1]": '11/29/2022',
    'A$AP JEAN': '??/??/????',
    "DON'T BE DUMB [V2]": '12/15/2023',
    "DON'T BE DUMB [V3]": '07/04/2025',
    "DON'T BE DUMB [V4]": '09/10/2025',
    "DON'T BE DUMB": '??/??/????',
    "DON'T BE DUMB [DISC 2]": '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Pre-MDB': "Born and raised in Harlem, New York, Rakim Mayers was no stranger to the culture of hip-hop growing up with his name even being named after artist Rakim by his mother, but getting the nickname Rocky at a very young age. While just starting to rap at the young age of eight years old Rocky’s brother Ricky Black had a huge influence on his career and motivated him to keep pursuing music, the same year his dad—who was “into the streets back then”—moved his family to Pennsylvania. His father went to jail for selling drugs when Rocky was 12, and his mother moved the family to North Carolina. Homeless, they ended up living in a shelter. Their luck never got better, and Rocky’s mother moved the family back to New York. Unfortunately, Ricky Mayers then was sadly shot and killed just a block away from where Rocky was born on February 26th, 2002 and this tragic event motivated Rocky to start rapping a bit more seriously at the age of thirteen. Soon enough, while bouncing around homeless shelters in the city with his mother, out of options and tired of grinding it out, Rocky got involved in the drug trade. He started selling weed, and by age 15 had graduated to selling crack in the Bronx.",
    'MDB': "When Rocky was around 17 Rah Money introduced him to a group started by one of Rocky's closest friends, Knocka. Around the time that Knocka turned 18 years old he started this group when he had gotten a lawsuit, obtaining one million dollars, Knocka named this group \"Million Dollar Baby\", but was oftentimes stated as \"MDB\". Rocky has described the group as \"really Harlem\", and he would often be seen with the likes of Knocka, Rell Money and Rah Money, as this was Rocky's main friend group at the time. In 2007 Rocky joined the A$AP Mob and started going by A$AP Rocky, but was still associated with MDB, but eventually, around 2008 Rodky differed away from MDB and was mainly focused on being a part of A$AP. Seemingly, Rocky did made music during this era but it will likely never be recovered as it is probably only still owned by very few people.",
    'A$AP (2007-2009)': 'Batch of early unreleased songs recorded between 2007 and 2009, before Rocky adopted the A$AP name commercially.',
    'A$AP (Mob Collab)': 'Early unreleased collaborative recordings with fellow A$AP Mob members.',
    'A$AP (2010)': "Sometime during 2006, while Rocky was still an active member in 'MDB', another Harlem based group was founded, entitled the 'A$AP Mob'. The collective was founded by A$AP Yams, A$AP Bari and A$AP Illz while together in SoHo as Bari explains, \"I was like, 'Yo, we're always trying to come up with different names and shit. We should just be called PIF Unit.' The shit was like, Paid In Full, something. So one day, Yams was like, 'Fuck that. We're called A$AP'\". The monicker 'A$AP' is an acronym meaning to 'Always $trive And Prosper', a saying Yams had gotten from another forgotten founder of A$AP unfinished WIP. Rocky joined the A$AP Mob in 2007. Rocky met A$AP Yams in 2008. In 2010, Yams would begin to release throwaways on the YouTube channel “HarlemzMostHated\" while acting like he didn't know who Rocky was to try and gain fame, which would be featured on a fan-made mixtape titled “Deep Purple” which was released on April 22nd, 2011 and is commonly confused to be Rocky’s first project. While this compilation isn't official, it began to give Rocky more traction with his music.",
    'Untitled': "It is not exactly clear when Rocky and fellow artist Seth Narley met, but seemingly through A$AP Bari. The two supposedly moved in together somewhere around 2010. While living together the two up and coming rappers would being to collaborate on a lot of music according to a friend of Seth. What is seemingly the first single for the project titled \"Grown Up\" was released on December 23rd, 2010 in a video in which it states the song was intended for Seth Narley's \"Freshmen N High School\" EP, while also showing the tracklist with the song appearing, as well as stating the song would appear on a Rocky mixtape titled \"Purple Swagg\" which turned out to be fake. A while later another single titled \"Grippin' Woodgrain\" was released on October 26th, 2011. This single was the last collaboration we would ever see with the duo as Rocky then blew up with \"LIVE.LOVE.A$AP\" and the two went their separate ways. On March 17th, 2024 Seth Narley would confirm in Instagram direct messages that him and Rocky actually had a mixtape planned together with \"some releases some not\" confirming the previously stated singles would have appeared.",
    'Untitled Mixtape with Seth Narley': 'Scrapped collaborative mixtape planned with producer Seth Narley around 2010, never officially released.',
    'Rug Of War 1994': "It has been said by A$AP Ferg in the now deleted April 21st, 2015 episode of Complex’s “Magnum Opus” series about the song \"Purple Swag\" that before the release \"LIVE.LOVE.A$AP\" Rocky wanted him and A$AP Ferg to be in a duo that went by the name of A$AP Red. It was then confirmed that him and Rocky worked on a mixtape under the title of \"Rug Of War 1994\" seemingly worked on under that alias. The only confirmed song on this mixtape is the notorious September 3rd, 2010 song \"Get High\"",
    'Purple Swag': "According to multiple A$AP Bari interviews, Rocky had a whole mixtape before \"LIVE.LOVE.A$AP\" but the engineer Rocky was working with deleted all of the songs and the only songs recovered were \"Purple Swag\", \"Roll One Up\" and \"Demons\". This means this project was deleted inbetween March 7th, 2011, the day the \"Numb\" instrumental was released by Clams Casino, which Rocky would later use to make \"Demons\" and April 14th, 2011, the day \"Purple Swag\" was released as a single and Rocky would not have to recover a released song. In another interview he mentioned \"Get High\" and \"Toast To The Gods\" were on the tracklist. It's unknown what the other songs that would have appeared are but those are lost forever. The cover included for this era is the single cover for the original version of \"Houston Old Head\".",
    'Me, Myself & A$AP': "After the \"Purple Swagg\" mixtape was deleted, Rocky was forced to start over on making his first mixtape. While feeling uninspired A$AP Yams convinced Rocky to let Yams upload the song \"Purple Swag\", which later blew up online giving Rocky new motivation to start over on the tape. Many ideas were circulating on what to do with this new tape, such as selling physical copies exclusively on cassetes, and releasing sometime in the summer of 2011. Eventually this tape would morph into Mouth Fulla Gold in May of 2011, making this era very short lived. The cover for this era is the YouTube thumbnail for the original upload of Purple Swag.",
    'Mouth Fulla Gold': "Following the deletion of his previous mixtape, Rocky began working on a new project titled \"Mouth Fulla Gold\" and had a copy of the mixtape ready on May 16th, 2011, which was sent out to select fans by A$AP Yams. During that month, likely around the time “Wassup” was released, Rocky stopped selling drugs and started take his brother's advice and truly started to focus on his rap career. On April 14th, 2011, Rocky released the song \"Purple Swag\" on the HarlemzMostHated YouTube channel. The track did not gain much recognition right away until it was put on the \"Deep Purple\" compilation as track three and had a music video release on July 5th, 2011, which led to the song becoming his first breakout hit. Rocky would continue to work on \"Mouth Fulla Gold\" as another copy was put together on June 17th, 2011. The same day the \"Purple Swag\" music video was released, A$AP Yams took to his now deleted Tumblr \"realniggatumblr\" and mentioned the name \"LIVE.LOVE.A$AP\" for the first time, which was then due at the end of July 2011.",
    'LIVE.LOVE.A$AP [V1]': "First version of Rocky's official debut mixtape, released October 31, 2011.",
    'LIVE.LOVE.A$AP [Promo CD]': 'Promotional CD pressing of the debut mixtape distributed to press and industry contacts.',
    'LIVE.LOVE.A$AP [V2]': "Following the hype and high expectations from the first single's music video, Rocky then released another single on July 21st, 2011 titled “Peso”, another hit under Rocky’s belt. From here, the mixtape was then delayed to August for unknown reasons. Rocky later 'leaked' an early version of \"Trilla\" on September 17th, 2011. In early October, Rocky signed a revolutionary two-year $3 million dollar record deal. Finally after all the waiting, on Halloween 2011 the project “LIVE.LOVE.A$AP” was officially released. This mixtape is widely known for its slowed down, Houstan influenced, psychedelic and dream-like sounds which made it stand out from many other hip-hop projects from this time period and it would become a gigantic pioneer for the genre of cloud rap for many years to come. Much later in 2021 the mixtape was re-released on streaming services, missing certain songs such as \"Kissin' Pink\" \"Out Of This World\" and \"Purple Swag: Chapter 2\" along with featuring different versions of the songs \"Leaf\" and \"Acid Drip\", but added a new song titled “Sandman” dedicated to the late A$AP Yams with production by long time collaborator Clams Casino along with a newer producer Kelvin Krash.",
    'B.M.W': "It was revealed in a interview at Ballers Eve on September 14th, 2011 that Rocky and SpaceGhostPurrp planned to release a six track collaboration EP titled \"B.M.W\" under the group name of TWIN meaning \"two wild ignorant niggas\" as the two would often call each other their twin at the time. On Rocky's debut mixtape SpaceGhostPurrp featured on two songs which were \"Purple Swag: Chapter 2\" and \"Keep It G\". Later on, SpaceGhostPurrp would produce Rocky's song \"Pretty Flacko\", but as April 2012 was underway the two artists started to have some beef as SpaceGhostPurrp claimed Rocky stole his style in music, fashion style among other things such as how the A$AP Mob began to use hieroglyphics just as the SpaceGhostPurrp lead Raider Klan would. He called out Rocky for using lyrics from his song \"My Enemie\" on his \"Goldie\" single in April. From there the beef got worse and SpaceGhostPurrp would often diss Rocky while even Rocky would throw disses his way telling him to stick to making beats. On December 17th, 2012 SpaceGhostPurrp released a solo EP with the same title so it's possible some of the songs that appeared on that project were originally for the collab tape. On the deluxe version of Rocky's first studio album the songs \"Jodye\" and \"Angels\" have direct disses to SpaceGhostPurrp.",
    'LIVE.LOVE.A$AP [Deluxe]': "Deluxe edition of Rocky's debut mixtape, released March 23, 2012 with additional tracks.",
    'Pre-LONG.LIVE.A$AP': "After the massive success of \"LIVE.LOVE.A$AP\" and a revolutionary three million dollar record deal, Rocky decided to go full force into his first studio album seemingly right away. While being a part of the Club Paradise Tour with Drake and Kendrick Lamar he began to make connections with bigger names in the industry. In an interview with HipHopDX on November 29th, 2011 Rocky talked about making a compilation album with the A$AP Mob then titled \"LONG.LIVE.A$AP\", indicating that the solo album around that time was named something entirely different. By March 2012, the album was still being worked on and was rumored to be titled \"A$AP Rocky Forever Part 1\", which was quickly debunked and was now titled \"LONG.LIVE.A$AP\", with the Mob's project being renamed to \"Trilluminati\".",
    'LONG.LIVE.A$AP (with A$AP Mob) [V1]': 'Early planned version of the debut album, at one point conceived as a joint project with A$AP Mob.',
    'Last Cab 2 Harlem [V2]': 'Working title used at one point during the debut album sessions.',
    "Lord$ Never Worry": "With Rocky on the rise with massive success from his mixtape “LIVE.LOVE.A$AP” it only made sense for the A$AP Mob to all make a project together so more of the other members of A$AP could be recognized for their talents, and they did just that. The project was first announced by Rocky in a November 29th, 2011 interview with HipHopDX with him stating “Yeah, “LONG.LIVE.A$AP.” That’s like the joint with everybody on it. It’s a compilation. I plan on dropping that after “LIVE.LOVE.A$AP” drops again, because we gonna do a deluxe version of “LIVE.LOVE.A$AP”. Right after that, we gonna drop the A$AP compilation with everybody on it.” The project has been described as a compilation at the time and the title would later become the name of Rocky’s first studio album. The project was said for a February 2012 release which was eventually pushed back for an April release but by the time March came around a May release was revealed. This was revealed in a Tumblr post from the A$AP Mob speaking on the release of A$AP Ant and Bodega Bamz song “Told Ya” on March 26th, 2012 states “The baby goon of the year A$AP Ant brings you his first visual alongside Bodega Bamz produced by DJ Carnage. Look out for TRILLUMINVTI this May featuring new music from Pretty Flacko, Nasty Baby 90’s Nigga, Twelvy the Good Goon, Fergenstein aka Diamond Dolla$ Page, and the rest of the Mob”. In this post a new name for the project can be seen “Trilluminati” and again, was set to be released in May 2012. A fan asked where the project was in April and Yams responded on his Tumblr on May 2nd, 2012 saying that the A$AP Mob thought moving to LA “would be the move”, but it ended up being the total opposite. He claimed “The energy is dead here there was no motivation here to make music”. He then said they’re going back to New York City to get the inspiration they needed again, Yams stated “the music will be rawer than ever believe that....TRILLUMINATI will be here” again confirming the title. With the project still not coming out in May many still wondered if it would be released any time soon, finally in July Yams announced the first single for the album “Bath Salt” which was released on July 27th. Yams stated there were no more delays and the album would come out on August 28th officially announcing the title “Lord$ Never Worry”. Before this another single “Purple Kisses” released on August 13th and the last single “Work” released on August 20th. Finally, after all the delays “Lord$ Never Worry” released on the planned date of August 28th, 2012.",
    'LONG.LIVE.A$AP': "On March 15th, 2012 \"LONG.LIVE.A$AP\" was announced to be dropping on July 4th, 2012, but the album would later be delayed. Fans were hungry for more solo Rocky music as he had been featuring on a handful of songs up until April 16th, 2012 when the first single for his album \"Goldie\" released with production from a very well respected producer Hit-Boy. The album was delayed once the July release day hit for unknown reasons, but Rocky still worked on the album with a second single titled \"Fuckin' Problems\" releasing on October 24th, 2012. This song has the likes of Drake, Kendrick Lamar and 2 Chainz and quickly became Rocky's most popular song at that point, and remains as one of them to this day. It was then announced in December 2012 that the album would release on January 15th, 2013 with the title track \"Long Live A$AP\" releasing as a single on December 18th, 2012. Just two days later on December 20th, 2012 a listening event for the album took place at a local Harlem music store. The album was completely finished and ready to release on its planned day, this was when just two days after that on December 22nd, 2012 the whole album was leaked online for everyone to hear. Surprisingly, Rocky was not upset by this, infact he was completely okay with it as long as people liked the album as he spent so much time making it. Just four days before the album the last pre-release single titled \"Wild for the Night\" with Skrillex and Birdy Nam Nam, which was also a huge hit. The album then released on the planned date of January 15th, 2013 along with a deluxe edition adding four more songs to the tracklist. The album is credited for its creative direction as well as big time features after being for the most part unknown not too long before the release. Despite this, Rocky knew the songs such as \"Fuckin' Problems\" and \"Wild for the Night\" were made as hits for his record label in a sense and knew he wanted to create a more personal and creative album next.",
    'Pre-AT.LONG.LAST.A$AP': "Early sessions for Rocky's second studio album, before it took its final shape as AT.LONG.LAST.A$AP.",
    'BEAUTY AND THE BEAST: SLOWED DOWN SESSIONS, CHAPTER 1': "It was revealed in a 2019 interview with Kerwin Frost that Rocky was taught how to make beats in 2011 by close collaborators at the time A$AP Ty Beats and SpaceGhostPurrp, so on his first studio album that was titled \"LONG.LIVE.A$AP\" he had a number of production credits. Some songs that he had a large amount of production on is \"Suddenly\" and \"Jodye\" which he produced with the likes of Héctor Delgado and Joey Fatts. After the release of that studio album Rocky had a plan to being working on a mixtape full of self-produced instrumentals. This mixtape would not be announced until a interview with WiLD 94.9 on April 12th, 2013 where he said \"I'm working on an instrumental album right now. I'm doing all my own beats,\" he says. \"It's going to be interesting to see how people react towards my production.\" Rocky said he's \"not even going to announce it, just drop it\" very soon. Although fans would not see a release of the mixtape anytime in 2013 Rocky continued to work on it while touring with the likes of Héctor Delgado, who evidently had a lot of influence on the project. Then later on Rocky would speak on the project in a interview with MTV saying \"I think people are gonna be intrigued by it because it's actually good,\" he continued. \"I wouldn't do nothing that I didn't feel confident or comfortable about. I think people gonna like this shit\". He revealed the title to be \"Beauty and the Beast: Slowed Down Sessions, Chapter 1\" and described the mixtape as \"really druggy, ambient shit\", following up saying \"everything is like classical beautiful music and boom-bap Wu-Tang shit mixed together. It's slowed down and it's real vibey, with no lyrics. I feel like it's gonna get people through the summer\" stating it would release for free that summer of 2013 with visuals. Nothing happened with the project until February 2014 when Rocky would have riots in New York, getting him banned from filming there for a few years, and he announced a new single \"Riot Rave\". That song had an accompanied music video promoting Vlone having footage from the riots, and another song released titled \"Unicorn\" with its own music video in March 4th, 2014 revealing the cover art while simply zooming into different parts of the cover. In the description of the \"Unicorn\" video it states the album was going to be executive produced by The Dukes, but it is not currently known who they are. There was no word on the album until April 21st, 2015 where Rocky would preview a music video for the album directed by Dexter Navy titled \"Chevy\", Rocky explained that the instrumental album was delayed because he said he knew fans wanted to hear rapping first, so \"AT.LONG.LAST.A$AP\" was set to release first. After this, the album was mentioned on \"AT.LONG.LAST.A$AP\" on the song \"Jukebox Joints\" where Rocky says he \"took the whole year off, just to learn to make beats\", but after this there was no mention of the album from Rocky for years. A fan asked Dexter Navy about releasing the \"Chevy\" music video in 2016, but he said Rocky told him he was not allowed. In a June 2019 interview with Kerwin Frost Rocky revealed the project was scrapped because he wanted to master production and mixing/mastering and essentially not have any help. He said he gave the album to director Dexter Navy for a passion project of his, so it is unknown if Dexter will ever release this.",
    'L.O.R.D.': "During a A$AP Ferg interview during the VMAs on August 26th, 2013 a upcoming, then untitled, project from the A$AP Mob was revealed by one of the the founders A$AP Yams to be releasing on October 15th, 2013, but on that date Yams revealed that he only revealed the initial release date because Amazon had leaked the target date without it being confirmed. He went on to say the album was pushed back because of features and sample clearances. Then the first single for the album was released on December 4th, 2013 which was “Trillmatic” with A$AP Nast and Method Man with the album's second single coming out not long after this time being titled “See Me” and only featuring A$AP Ant. The album was said to be finished on February 20th, 2014 with a new March 4th, 2014 release date. That release date slowly approached and it eventually became delayed until sometime in April with the album's third single releasing on April 22nd, 2014 titled “Xscape” featuring only A$AP Twelvyy. The album continued to be worked on and the fourth single was released on June 6th, 2014 featuring the likes of A$AP Rocky, A$AP Ferg, A$AP Twelvyy and A$AP Nast titled “Hella Hoes”. After the release of that last single the album’s development went relatively radio silent for the most part until September 26th, 2014 when A$AP Yams confirmed on his Tumblr account that “L.O.R.D.” was officially scrapped. The reasons he gave as for what reason the project was scrapped was there was “too many energies” as it was “hard to get everybody on the same page. He then stated that the best tracks from the album would eventually make their way onto Rocky, Twelvvy and Nast’s solo albums, it’s possible that some made their way onto “AT.LONG.LAST.A$AP” in 2015 after Yams’ unfortunate passing, but that is unclear. The solo project from Twelvvy “12” which was released in 2017 only features one confirmed song from “L.O.R.D.”, and Nast never has released a solo project throughout his entire career. As previously stated, A$AP Yams passed away on January 18th, 2015 and even though “L.O.R.D.” was scrapped the A$AP Mob got together to make the first album in the “Cozy Tapes” series “Cozy Tapes: Vol. 1 Friends -“ on October 31st, 2016.",
    'AT.LONG.LAST.A$AP': "When Rocky’s second album “AT.LONG.LAST.A$AP” was in production it was first going to have a similar idea to its predecessor until the tragic death of Rocky’s friend and mentor A$AP Yams in January 18th, 2015. After this devastating event he changed the entire concept of the album to a new direction; he had some lesser known features such as a homeless man from London named Joe Fox who featured on a plethora of tracks while still having big names such as Kanye West and Lil Wayne. The project again gained attention through its singles such as “L$D” and “Everyday” among many other songs on the album.",
    'Cozy Tapes Vol. 1: Friends -': "Around the time of A$AP Yams' unfortunate death in January of 2015 the A$AP Mob decided to produce an album as a whole group, with this being the first one since 2012’s ‘Lord$ Never Worry’. The title of this project was titled ‘Cozy Tapes Vol. 1: Friends -‘ with the friends in the title signifying the many other collaborators outside of the mob including people such as Tyler, The Creator, Playboi Carti and even Lil Uzi Vert. This project gained lots of success through songs like ‘Telephone Calls’ and ‘Yamborghini High’, two of the singles for the tape, the success of this project motivated the A$AP Mob to release a second volume in the future.",
    'Pre-TESTING': "Early sessions for Rocky's third studio album, before it became TESTING.",
    'Wavy Wednesdays': 'Batch of loose unreleased songs that circulated around January 2016.',
    'TESTING [V1]': "Similar to Rocky’s previous solo project he totally changed the direction of his third studio album “TESTING”, for example the well known psychedelic production of Rocky’s music now had a more industrial feel and the style in overall took a big turn compared to his last release. He worked with many new faces such as Dean Blunt and Kelvin Krash for this project making a big difference. The album saw some success through songs such as ‘Praise The Lord (Da Shine)’ which is now Rocky’s most popular song to date, though was not praised as much as his past releases and failed to chart number one on the Billboard 200, which motivated him to change his sound on his next release.",
    'Rocky Montana': "Sources have stated that the collaboration project between Rocky and French Montana started out as a single, which was likely ‘Said N Done’, then a mixtape then developed into a full fledged album. It’s been said that “They had a lot of chemistry in the studio”. In August of 2017 French Montana revealed that the project would release very soon and sources stated in November of 2017 that the album would be released by the end of the year. Some of the songs from the project were released later by Montana which were ‘Straight For The Bag’ in 2020 and ‘Chit Chat’ in 2023. Through file names the project is said to be titled \"Rocky Montana\". It is currently unknown if an album cover exists yet it is likely since the project was heavily considered to be released, the photo used here is from a March 2017 photoshoot which was possibly tied to the album.",
    'DUMMY [V1]': "Sometime while working on “TESTING” in 2016 Rocky began work on a second project, which was intended to release alongside the main album, then titled “DUMMY”. On June 23rd, 2017 Rocky played a snippet of a song from the album titled “Darkside” at a fashion show. Later, on September 21st, 2017 Instagram user blamedemcracka shared a video showing snippets for the songs “Pretty Guy”, “Keep It Trill” and “Smokin’ Dope” and the tracks “Tropical” and “Smokin’ Dope” leaked not long after. Around this time a leaked tracklist for the album surfaced that would only resurface on October 8th, 2023, it was also stated by Mod that multiple unleaked tracklists for the album exist but it is unknown how different they may be.",
    'Cozy Tapes Vol. 2: Too Cozy': "Around nine months after the release of the first tape Rocky announced that the highly anticipated second volume of the ‘Cozy Tapes’ series was finished, being titled “Cozy Tapes: Vol. 2 Too Cozy”. One of the singles titled ‘Wrong’ didn’t end up making the album. Two of the singles that did end up on the album were ‘Feels So Good’ and ‘RAF’ with a super-star roster of artists like Frank Ocean, Lil Uzi Vert, Playboi Carti and Quavo. Other collaborators like ScHoolboy Q, Joey Bada$$, Gucci Mane and many others appeared on the album.",
    'DUMMIE [V2]': "The project had gone under the radar until January 13th, 2018 when Rocky would release a single titled “☆☆☆☆☆ 5IVE $TAR$” onto SoundCloud with the songs “Above” and “Money Bags Freestyle” releasing on Janurary 14th and 15th respectively. These three SoundCloud singles all had the same cover art with the new title of “DUMMIE” with a which would have likely been the final album art. It has been stated by Mod that the album was intended to drop with “TESTING” on May 25th, 2018, but the whole album was entirely scrapped just a few weeks before for unknown reasons.",
    'DUMMIE': 'Working title used for songs recorded around January 2018, connected to the TESTING sessions.',
    'TESTING [V2]': "Similar to Rocky’s previous solo project he totally changed the direction of his third studio album “TESTING”, for example the well known psychedelic production of Rocky’s music now had a more industrial feel and the style in overall took a big turn compared to his last release. He worked with many new faces such as Dean Blunt and Kelvin Krash for this project making a big difference. The album saw some success through songs such as ‘Praise The Lord (Da Shine)’ which is now Rocky’s most popular song to date, though was not praised as much as his past releases and failed to chart number one on the Billboard 200, which motivated him to change his sound on his next release.",
    'TESTING [Deluxe]': 'Planned deluxe edition of the TESTING album with additional tracks.',
    'TESTING [Chopped & Screwed]': 'Chopped and screwed version of the TESTING album, released May 2, 2019.',
    'Cozy Tapes Vol. 3 [V1]': "Directly after releasing “Cozy Tapes Vol. 2: Too Cozy” the A$AP Mob was still at work to make the third installment to the “Cozy Tapes” album series. This album was confirmed to be in the works through various Instagram posts and stories along with A$AP Mob member A$AP Ant speaking about the project. The album was expected by fans to drop in August 2018 as a part of AWGEST, similar to the second installment, but nothing ended up dropping and no word was given.",
    'WANG$AP': "While working on “Flower Boy” in 2017 Tyler, The Creator and A$AP Rocky had the idea to create a collaboration album called ‘WANG$AP’. The two had collaborated on songs in the past and decided to bring their talents together for a album. In late 2018 the two released a single called ‘Potato Salad’. Although this is the only official release we ever got from this project there were more songs made. Tyler stated in early 2019 on twitter “i wish rocky would shut the fuck up and stop always saying what he's working on 40 years before its even a fleshed out idea.” and “that shit dont exist yall =)”. Tyler later revealed in 2025 that him and Rocky as a duo were originally meant to be called \"DON'T TAP THE GLASS\", a phrase which he would eventually reuse as the name of his ninth studio album.",
    'TESTING': "Rocky's third studio album, released December 21, 2018.",
    'ALL $MILE$ [V1]': "After the release of Rocky’s third album he continued to make music for a new project, this timespan is commonly known as ALL SMILES. Although this era has no official title In an interview Rocky stated that he “never publicly said that my album was called All Smiles,” but that it “is more of a concept project, it’s music and more,” so this whole time frame of music will be categorized by the name. This era is often stylized as ‘ALL.$MILE$’ by many members in the community.",
    'ALL $MILE$ [V2]': "After the release of Rocky’s third album he continued to make music for a new project, this timespan is commonly known as ALL SMILES. Although this era has no official title In an interview Rocky stated that he “never publicly said that my album was called All Smiles,” but that it “is more of a concept project, it’s music and more,” so this whole time frame of music will be categorized by the name. This era is often stylized as ‘ALL.$MILE$’ by many members in the community.",
    'ALL $MILE$': 'Working title used for shelved album sessions around 2019.',
    'Cozy Tapes Vol. 3 [V2]': "After the Cozy Tapes Vol. 3 album failed to release during AWGEST 2018, many had lost all hope for this project's release. Later on, A$AP Ant confirmed the album was still in the works on April 20th, 2019 through a Tweet stating “Just got offf phone 12vy, a$ap mob up, cozy tapes 3 coming soon.” Through leaks we can see there were sessions for the album in December 2019 just before Yams Day in January 2020 in which the same month A$AP Nast Tweeted \"Cozy Tapes 3\", but again, with no avail. It was speculated in 2021 after seeing many members of the mob together again after drama within the group's members that the album would still be released. The album wasn’t mentioned again until January 2022 in an interview with A$AP Ant saying that they have to get the chemistry right and that it’s still coming. The project has not seen a release since. Often referred to as “Cozy For Lyfe” but a true title is unconfirmed. The cover used here is promo for Yams Day 2020.",
    'THE GR1M [V1]': "After seemingly scrapping the “ALL $MILE$” concept, Rocky began to work on his newest body of work. The first sign of this new album was when he previewed a song he began to play live at most of his live performances from that point titled “NO I.D. (GRIM FREESTYLE)” on December 22nd, 2020 in collaboration with Marine Serre. The project at that time was called \"THE GRIM\", as confirmed by producer HItkidd. In an interview with GQ from May 2021 Rocky expressed that he estimated the album was 90% complete, but the album didn’t see a release after that point. In the same interview he described the project as being a “ghetto love tale”.",
    'Cozy Tapes Vol. 3 [V3]': 'Third known working version of the unreleased Cozy Tapes Vol. 3.',
    'GR1M [V2]': 'Later working version of the scrapped GR1M album sessions.',
    'LIVE.LOVE.A$AP [Re-Release]': "Official re-release of Rocky's debut mixtape, put out in 2021.",
    'GR1M [V3]': "By mid 2021, \"THE GRIM\" was eventually renamed to simply \"GRIM\". On May 5th, 2022 a track titled “D.M.B.” was released, an ode to his now wife Rihanna, as he proposed to her in the music video for the track. Not long after they introduced their first born baby RZA Mayers into the world on May 13th, 2022. An interview with DAZED from May 22nd, 2022 Rocky officially confirmed the album’s title would not be “ALL $MILE$” and that the album was being wrapped up with him “shooting so many visuals for it”. In that interview he stated his sound would change from the more industrial sound from his previous album “TESTING” into a more “polished” sound. The project has never seen, as Rocky scrapped the \"GRIM\" idea all together sometime in October-November 2022 and changed the album to \"DON'T BE DUMB\" which was announced in December.",
    "DON'T BE DUMB [V1]": "Eventually, the GRIM project was scrapped and by 2022 Rocky was seemingly working on a new album. The second single for the album “Shittin’ Me”, a fan-favorite song, released on December 2nd, 2022. Not long after on December 8th, 2022 Rocky stated during a football game “Thursday Night Football, Amazon, my first time back on the stage, my album is done, don’t be dumb, let’s go” officially stating the albums title and the next day he performed for Amazon Music on December 9th, 2022 previewing his next single “Same Problems?” which would officially release on Yams Day, January 18th, 2023. Another single would release on July 20th, 2023 titled “RIOT (Rowdy Pipe’n)” and with an interview with Complex the next day Rocky confirmed plenty of the production that would appear on the album and claimed he’s in “album mode”.",
    'A$AP JEAN': "Zach Fogarty (one of the prods of \"HIGHJACK\") stated that Jean Dawson and Rocky were working on a project together, while also working on their own albums, and started working on it in early-mid 2023, planning to release after Jean’s album and possibly before or after Rocky’s. Jean said in one of the messages to Zach that the project was gonna be 8 songs long with “unique features” on some of the tracks. Jean dropped his album “Glimmer of God” October 18th, 2024, so it was set to be after \"DON'T BE DUMB\" if anything. The screenshots of the messages between Zach & Jean are dated as far up to September 2023, so it is unknown if this is still being worked on or not.",
    "DON'T BE DUMB [V2]": "Since delaying the album, Rocky has now had a second child, Riot Rose, and said in late October 2023 that the album would release by the end of that year, which never happened. Later on throughout 2024, Rocky would release merchandise related to the album in April, then in August confirming the albums original release date at the AWGE SS25 as August 30, 2024 previewing 2 new songs, and releasing a new one \"HIGHJACK\" before he inexplicitly delayed the album once again due to \"SAMPLE CLEAREANCES AND LEAKS\", dropping the song Tailor Swif instead on that date, and surprise released Ruby Rosary featuring J. Cole the week after, stating the album will be dropping sometime in Fall 2024. Rocky would later say in an interview that the album features influences from Wu-Tang Clan, Diplomatic Immunity, Tim Burton's films, Memphis hip-hop, Portishead, and 1930's German Expressionist silent films.",
    "DON'T BE DUMB [V3]": "The album was then announced to be delayed to early 2025, and then said to be releasing before Rolling Loud on March 15th. Instead Playboi Carti released his album \"MUSIC\" on March 14th after much speculation Rocky would do so, after his Rolling Loud Los Angeles performance on March 16th, 2025 many fans believe Rocky is ready to start his rollout after previewing four new songs. And later previewing two more at his second AWGE fashion show.",
    "DON'T BE DUMB [V4]": "After all of 2025 passed by, on December 16 of 2025 Don't Be Dumb would finally be offically annoucned with its cover. Afterwards two singles, \"Punk Rocky\" and \"Helicopter\" Will release on their respective dates. And finally, one month after being offically announced, Don't Be Dumb will release on all DPS services",
    "DON'T BE DUMB": "Fans are upset that Rocky left out songs that were otherwise a staple on the album. As a result, a deluxe is on the way. Fan favourites such as \"GEMSTONES\" and \"YOUR HONOR\" are expected on the deluxe, as well as unheard songs from the era.",
    "DON'T BE DUMB [DISC 2]": "Bonus or second-disc material connected to the DON'T BE DUMB album sessions.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    'Pre-A.L.L.A.': 'Pre-AT.LONG.LAST.A$AP',
    'A$AP (with A$AP Mob)': 'A$AP (Mob Collab)',
    'THE GRIM [V1]': 'THE GR1M [V1]',
    'Rug Of War 1984': 'Rug Of War 1994',
    'LIVE.LOVE.A$AP (Re-Release)': 'LIVE.LOVE.A$AP [Re-Release]',
    'GRIM': 'GR1M [V3]',
  },
  ALBUM_ORDER: [
    'Pre-MDB', 'MDB', 'A$AP (2007-2009)', 'A$AP (Mob Collab)', 'A$AP (2010)', 'Untitled',
    'Untitled Mixtape with Seth Narley',
    'Rug Of War 1994', 'Purple Swag', 'Me, Myself & A$AP', 'Mouth Fulla Gold',
    'LIVE.LOVE.A$AP [V1]', 'LIVE.LOVE.A$AP [Promo CD]', 'LIVE.LOVE.A$AP [V2]', 'B.M.W', 'LIVE.LOVE.A$AP [Deluxe]',
    'Pre-LONG.LIVE.A$AP', 'LONG.LIVE.A$AP (with A$AP Mob) [V1]', 'Last Cab 2 Harlem [V2]', "Lord$ Never Worry", 'LONG.LIVE.A$AP',
    'Pre-AT.LONG.LAST.A$AP', 'BEAUTY AND THE BEAST: SLOWED DOWN SESSIONS, CHAPTER 1', 'L.O.R.D.',
    'AT.LONG.LAST.A$AP', 'Cozy Tapes Vol. 1: Friends -', 'Pre-TESTING', 'Wavy Wednesdays',
    'TESTING [V1]', 'Rocky Montana', 'DUMMY [V1]', 'Cozy Tapes Vol. 2: Too Cozy', 'DUMMIE [V2]', 'DUMMIE',
    'TESTING [V2]', 'TESTING [Deluxe]', 'TESTING [Chopped & Screwed]', 'Cozy Tapes Vol. 3 [V1]', 'WANG$AP', 'TESTING',
    'ALL $MILE$ [V1]', 'ALL $MILE$ [V2]', 'ALL $MILE$', 'Cozy Tapes Vol. 3 [V2]', 'THE GR1M [V1]',
    'Cozy Tapes Vol. 3 [V3]', 'GR1M [V2]', 'LIVE.LOVE.A$AP [Re-Release]', 'GR1M [V3]', "DON'T BE DUMB [V1]", 'A$AP JEAN',
    "DON'T BE DUMB [V2]", "DON'T BE DUMB [V3]", "DON'T BE DUMB [V4]", "DON'T BE DUMB",
    "DON'T BE DUMB [DISC 2]",
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
  hasSubAlbumsTab: false,
};
