import type { ArtistConfig } from './types';

export const aapgoldConfig: ArtistConfig = {
  slug: 'aapgold',
  SITE_NAME: 'A$APGOLD',
  SITE_DESCRIPTION: 'The Best A$AP Rocky Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/aapgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'aapgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#7c3aed',
  artistLabel: 'A$AP Rocky',
  cardLetter: 'ASAP',
  logoUrl: '/logos/aapgold.png',
  artistPhotoUrl: '/artists/asaprocky.jpg',

  getArtistName() {
    return 'A$AP Rocky';
  },

  CUSTOM_IMAGES: {
    'Pre-MDB': '/aapgold/eras/pre-mdb.jpg',
    'MDB': '/aapgold/eras/mdb.jpg',
    'A$AP (2007-2009)': '/aapgold/eras/asap-2007-2009.jpg',
    'A$AP (Mob Collab)': '/aapgold/eras/asap-mob-collab.jpg',
    'A$AP (2010)': '/aapgold/eras/asap-2010.jpg',
    'Untitled': '/aapgold/eras/untitled.jpg',
    'Rug Of War 1994': '/aapgold/eras/rug-of-war-1994.jpg',
    'Purple Swag': '/aapgold/eras/purple-swag.jpg',
    'Me, Myself & A$AP': '/aapgold/eras/me-myself-and-asap.jpg',
    'Mouth Fulla Gold': '/aapgold/eras/mouth-fulla-gold.jpg',
    'LIVE.LOVE.A$AP [V1]': '/aapgold/eras/live-love-asap-v1.jpg',
    'LIVE.LOVE.A$AP [V2]': '/aapgold/eras/live-love-asap-v2.jpg',
    'B.M.W': '/aapgold/eras/b-m-w.jpg',
    'LIVE.LOVE.A$AP [Deluxe]': '/aapgold/eras/live-love-asap-deluxe.jpg',
    'Pre-LONG.LIVE.A$AP': '/aapgold/eras/pre-long-live-asap.jpg',
    'Last Cab 2 Harlem [V2]': '/aapgold/eras/lords-never-worry.jpg',
    "Lord$ Never Worry": '/aapgold/eras/lords-never-worry.jpg',
    'LONG.LIVE.A$AP': '/aapgold/eras/long-live-asap.jpg',
    'Pre-AT.LONG.LAST.A$AP': '/aapgold/eras/pre-at-long-last-asap.jpg',
    'BEAUTY AND THE BEAST: SLOWED DOWN SESSIONS, CHAPTER 1': '/aapgold/eras/beauty-and-the-beast-slowed-down-sessions-chapter-1.jpg',
    'L.O.R.D.': '/aapgold/eras/l-o-r-d.jpg',
    'AT.LONG.LAST.A$AP': '/aapgold/eras/at-long-last-asap.jpg',
    'Cozy Tapes Vol. 1: Friends -': '/aapgold/eras/cozy-tapes-vol-1-friends.jpg',
    'Pre-TESTING': '/aapgold/eras/pre-testing.jpg',
    'TESTING [V1]': '/aapgold/eras/testing-v1.jpg',
    'Rocky Montana': '/aapgold/eras/rocky-montana.jpg',
    'DUMMY [V1]': '/aapgold/eras/dummy-v1.jpg',
    'Cozy Tapes Vol. 2: Too Cozy': '/aapgold/eras/cozy-tapes-vol-2-too-cozy.jpg',
    'DUMMIE [V2]': '/aapgold/eras/dummie-v2.jpg',
    'TESTING [V2]': '/aapgold/eras/testing-v2.jpg',
    'TESTING [Deluxe]': '/aapgold/eras/testing-deluxe.jpg',
    'Cozy Tapes Vol. 3 [V1]': '/aapgold/eras/cozy-tapes-vol-3-v1.jpg',
    'WANG$AP': '/aapgold/eras/wangsap.jpg',
    'TESTING': '/aapgold/eras/testing.jpg',
    'ALL $MILE$ [V1]': '/aapgold/eras/all-smiles-v1.jpg',
    'ALL $MILE$ [V2]': '/aapgold/eras/all-smiles-v2.jpg',
    'Cozy Tapes Vol. 3 [V2]': '/aapgold/eras/cozy-tapes-vol-3-v2.jpg',
    'THE GR1M [V1]': '/aapgold/eras/the-gr1m-v1.jpg',
    'Cozy Tapes Vol. 3 [V3]': '/aapgold/eras/cozy-tapes-vol-3-v3.jpg',
    'GR1M [V2]': '/aapgold/eras/gr1m-v2.jpg',
    'GR1M [V3]': '/aapgold/eras/gr1m-v3.jpg',
    "DON'T BE DUMB [V1]": "/aapgold/eras/don-t-be-dumb-v1.jpg",
    'A$AP JEAN': '/aapgold/eras/asap-jean.jpg',
    "DON'T BE DUMB [V2]": "/aapgold/eras/don-t-be-dumb-v2.jpg",
    "DON'T BE DUMB [V3]": "/aapgold/eras/don-t-be-dumb-v3.jpg",
    "DON'T BE DUMB [V4]": "/aapgold/eras/don-t-be-dumb-v4.jpg",
    "DON'T BE DUMB": "/aapgold/eras/don-t-be-dumb.jpg",
  },

  ALBUM_RELEASE_DATES: {
    'Pre-MDB': '??/??/????',
    'MDB': '??/??/????',
    'A$AP (2007-2009)': '??/??/????',
    'A$AP (Mob Collab)': '??/??/????',
    'A$AP (2010)': '09/13/2010',
    'Untitled': '??/??/????',
    'Rug Of War 1994': '??/??/????',
    'Purple Swag': '10/28/2010',
    'Me, Myself & A$AP': '04/14/2011',
    'Mouth Fulla Gold': '05/21/2011',
    'LIVE.LOVE.A$AP [V1]': '10/31/2011',
    'LIVE.LOVE.A$AP [V2]': '??/??/????',
    'B.M.W': '??/??/????',
    'LIVE.LOVE.A$AP [Deluxe]': '03/23/2012',
    'Pre-LONG.LIVE.A$AP': '11/08/2011',
    'Last Cab 2 Harlem [V2]': '01/01/2012',
    "Lord$ Never Worry": '01/07/2012',
    'LONG.LIVE.A$AP': '01/15/2013',
    'Pre-AT.LONG.LAST.A$AP': '??/??/????',
    'BEAUTY AND THE BEAST: SLOWED DOWN SESSIONS, CHAPTER 1': '03/03/2014',
    'L.O.R.D.': '07/08/2013',
    'AT.LONG.LAST.A$AP': '05/26/2015',
    'Cozy Tapes Vol. 1: Friends -': '09/30/2016',
    'Pre-TESTING': '06/22/2015',
    'Wavy Wednesdays': '01/27/2016',
    'TESTING [V1]': '??/??/????',
    'Rocky Montana': '??/??/????',
    'DUMMY [V1]': '??/??/????',
    'Cozy Tapes Vol. 2: Too Cozy': '11/17/2017',
    'DUMMIE [V2]': '??/??/????',
    'TESTING [V2]': '??/??/????',
    'TESTING [Deluxe]': '??/??/????',
    'Cozy Tapes Vol. 3 [V1]': '??/??/????',
    'WANG$AP': '??/??/????',
    'TESTING': '12/21/2018',
    'ALL $MILE$ [V1]': '06/15/2018',
    'ALL $MILE$ [V2]': '??/??/????',
    'Cozy Tapes Vol. 3 [V2]': '??/??/????',
    'THE GR1M [V1]': '??/??/????',
    'Cozy Tapes Vol. 3 [V3]': '??/??/????',
    'GR1M [V2]': '??/??/????',
    'GR1M [V3]': '09/02/2022',
    "DON'T BE DUMB [V1]": '11/29/2022',
    'A$AP JEAN': '??/??/????',
    "DON'T BE DUMB [V2]": '12/15/2023',
    "DON'T BE DUMB [V3]": '07/04/2025',
    "DON'T BE DUMB [V4]": '09/10/2025',
    "DON'T BE DUMB": '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Pre-MDB', 'MDB', 'A$AP (2007-2009)', 'A$AP (Mob Collab)', 'A$AP (2010)', 'Untitled',
    'Rug Of War 1994', 'Purple Swag', 'Me, Myself & A$AP', 'Mouth Fulla Gold',
    'LIVE.LOVE.A$AP [V1]', 'LIVE.LOVE.A$AP [V2]', 'B.M.W', 'LIVE.LOVE.A$AP [Deluxe]',
    'Pre-LONG.LIVE.A$AP', 'Last Cab 2 Harlem [V2]', "Lord$ Never Worry", 'LONG.LIVE.A$AP',
    'Pre-AT.LONG.LAST.A$AP', 'BEAUTY AND THE BEAST: SLOWED DOWN SESSIONS, CHAPTER 1', 'L.O.R.D.',
    'AT.LONG.LAST.A$AP', 'Cozy Tapes Vol. 1: Friends -', 'Pre-TESTING', 'Wavy Wednesdays',
    'TESTING [V1]', 'Rocky Montana', 'DUMMY [V1]', 'Cozy Tapes Vol. 2: Too Cozy', 'DUMMIE [V2]',
    'TESTING [V2]', 'TESTING [Deluxe]', 'Cozy Tapes Vol. 3 [V1]', 'WANG$AP', 'TESTING',
    'ALL $MILE$ [V1]', 'ALL $MILE$ [V2]', 'Cozy Tapes Vol. 3 [V2]', 'THE GR1M [V1]',
    'Cozy Tapes Vol. 3 [V3]', 'GR1M [V2]', 'GR1M [V3]', "DON'T BE DUMB [V1]", 'A$AP JEAN',
    "DON'T BE DUMB [V2]", "DON'T BE DUMB [V3]", "DON'T BE DUMB [V4]", "DON'T BE DUMB",
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
};
