import type { ArtistConfig } from './types';

export const cactigoldConfig: ArtistConfig = {
  slug: 'cactigold',
  SITE_NAME: 'CACTIgold',
  SITE_DESCRIPTION: 'The Best Travis Scott Tracker In The World!',
  SITE_URL: 'https://vaultgold.net/cactigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'cactigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#ff4500',
  artistLabel: 'Travis Scott',
  cardLetter: 'CCT',

  getArtistName(_eraName) { return 'Travis Scott'; },

  CUSTOM_IMAGES: {
    "The Graduates": "",
    "The Classmates": "",
    "Owl Pharaoh": "https://i.ibb.co/3yHnBdZ/owl-pharaoh.jpg",
    "Days Before Rodeo": "https://i.ibb.co/k8Q6vhV/days-before-rodeo.jpg",
    "Days Before Rodeo (Re-Release)": "https://i.ibb.co/k8Q6vhV/days-before-rodeo.jpg",
    "Rodeo": "https://i.ibb.co/Gp4V1bX/rodeo.jpg",
    "Birds": "https://i.ibb.co/jMpV5sB/birds-in-the-trap.jpg",
    "Huncho Jack, Jack Huncho": "https://i.ibb.co/FqMzNgY/huncho-jack.jpg",
    "Astroworld": "https://i.ibb.co/Gp1rq4N/astroworld.jpg",
    "JackBoys": "https://i.ibb.co/NWkyqzG/jackboys.jpg",
    "The Scotts": "https://i.ibb.co/MnKtGkq/the-scotts.jpg",
    "Utopia [P1]": "https://i.ibb.co/Kz3mVnF/utopia.jpg",
    "Utopia [P2]": "https://i.ibb.co/Kz3mVnF/utopia.jpg",
    "Utopia": "https://i.ibb.co/Kz3mVnF/utopia.jpg",
    "JackBoys 2": "",
    "Post-Utopia": "",
    "Unknown": "",
  },

  ALBUM_RELEASE_DATES: {
    "The Graduates": "??/??/????",
    "The Classmates": "??/??/????",
    "Owl Pharaoh": "05/25/2013",
    "Days Before Rodeo": "08/27/2014",
    "Rodeo": "09/04/2015",
    "Birds": "09/02/2016",
    "Huncho Jack, Jack Huncho": "12/21/2017",
    "Astroworld": "08/03/2018",
    "JackBoys": "12/27/2019",
    "The Scotts": "04/29/2020",
    "Utopia [P1]": "??/??/????",
    "Utopia [P2]": "07/28/2023",
    "JackBoys 2": "??/??/????",
    "Post-Utopia": "??/??/????",
    "Unknown": "??/??/????",
  },

  HIDDEN_ALBUMS: ["Unknown"],

  ALBUM_DESCRIPTIONS: {
    "The Graduates": "Travis Scott's early duo work with childhood friend Christopher Jones (as Chris Holloway). Era spans April 2007–April 2009.",
    "The Classmates": "Collaborative era with OG Chess. Era spans April 2009–2011.",
    "Owl Pharaoh": "Travis Scott's breakout mixtape, featuring heavy Kanye West collaboration. Era spans 2011–2013.",
    "Days Before Rodeo": "Acclaimed free mixtape released August 27, 2014, featuring production from Kanye West and Mike Dean.",
    "Rodeo": "Travis Scott's debut studio album, released September 4, 2015 on Epic Records.",
    "Birds": "Birds in the Trap Sing McKnight — Travis Scott's second studio album, released September 2, 2016.",
    "Huncho Jack, Jack Huncho": "Collaborative album with Quavo of Migos, released December 21, 2017.",
    "Astroworld": "Travis Scott's third studio album, released August 3, 2018. Named after a defunct Houston amusement park.",
    "JackBoys": "Cactus Jack Records collective EP released December 27, 2019.",
    "The Scotts": "Collaborative project between Travis Scott and Kid Cudi, released April 29, 2020.",
    "Utopia [P1]": "First phase of sessions for Travis Scott's fourth studio album Utopia, circa 2019–2021.",
    "Utopia [P2]": "Second phase of Utopia sessions leading to the album's release on July 28, 2023.",
    "JackBoys 2": "Sequel to the JackBoys collective EP, status currently unknown.",
    "Post-Utopia": "Travis Scott's ongoing musical era following the release of Utopia in 2023.",
  },

  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},

  ERA_MAPPINGS: {
    "The Graduates*": "The Graduates",
    "The Classmates*": "The Classmates",
    "Owl Pharaoh*": "Owl Pharaoh",
    "Days Before Rodeo*": "Days Before Rodeo",
    "Rodeo*": "Rodeo",
    "Birds*": "Birds",
    "Astroworld*": "Astroworld",
    "JackBoys*": "JackBoys",
    "Utopia [P1]*": "Utopia [P1]",
    "Utopia [P2]*": "Utopia [P2]",
    "JackBoys 2*": "JackBoys 2",
    "Post-Utopia*": "Post-Utopia",
    "Utopia": "Utopia [P2]",
  },

  TAG_MAP: {
    "⭐": "Best Of", "🏆": "Grails", "🥇": "Wanted", "🏅": "Wanted",
    "✨": "Notable", "💛": "By CACTIgold", "🗑️": "Worst Of", "🗑": "Worst Of",
    "🚮": "Unwanted", "🤖": "AI", "⁉️": "Lost Media", "⁉": "Lost Media", "❓": "Unknown",
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    "Best Of": "Some of the best leaks hosted on the tracker.",
    "Grails": "The most wanted songs that have not yet leaked in full.",
    "Wanted": "Songs that are wanted, but not as much as Grails.",
    "Notable": "Notable songs worth highlighting.",
    "Worst Of": "Some of the worst leaks on the tracker.",
    "Unwanted": "Songs we don't want to see leak in full.",
    "AI": "Track contains AI vocals.",
    "Lost Media": "Currently lost, or no link to the media is known.",
    "By CACTIgold": "Leaks & songs added by the owner of the site.",
  },
};
