import type { ArtistConfig } from './types';

export const colegoldConfig: ArtistConfig = {
  slug: 'colegold',
  SITE_NAME: 'COLEGOLD',
  SITE_DESCRIPTION: 'The Best J. Cole Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/colegold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'colegold_',
  HARDCODED_SHEET_ID: '1hjMtB-acUEpXYkR6TWQVeVoUzSLrAVIdy1lMoM6aFFw',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#dc2626',
  artistLabel: 'J. Cole',
  cardLetter: 'COLE',
  logoUrl: '/logos/colegold.png',
  artistPhotoUrl: '/artists/jcole.webp',

  getArtistName() {
    return 'J. Cole';
  },

  CUSTOM_IMAGES: {
    'Before The Come Up': '/colegold/eras/before-the-come-up.jpg',
    'The Come Up': '/colegold/eras/the-come-up.jpg',
    'The Warm Up': '/colegold/eras/the-warm-up.jpg',
    'Friday Night Lights': '/colegold/eras/friday-night-lights.jpg',
    'Cole World: The Sideline Story': '/colegold/eras/cole-world.jpg',
    'Truly Yours': '/colegold/eras/truly-yours.jpg',
    'Truly Yours 2': '/colegold/eras/truly-yours-2.jpg',
    'Born Sinner': '/colegold/eras/born-sinner.jpg',
    'Collaboration with Kendrick Lamar': '/colegold/eras/kendrick-collab.jpg',
    'J. Cole x Chance Project': '/colegold/eras/chance-collab.jpg',
    '2014 Forest Hills Drive': '/colegold/eras/2014-forest-hills-drive.jpg',
    '4 Your Eyez Only': '/colegold/eras/4-your-eyez-only.jpg',
    'KOD': '/colegold/eras/kod.jpg',
    'The Off-Season': '/colegold/eras/the-off-season.jpg',
    'Might Delete Later': '/colegold/eras/might-delete-later.jpg',
    'Ongoing': '/artists/jcole.webp',
  },

  ALBUM_RELEASE_DATES: {
    'Before The Come Up': '??/??/2006',
    'The Come Up': '05/04/2007',
    'The Warm Up': '06/15/2009',
    'Friday Night Lights': '11/14/2010',
    'Cole World: The Sideline Story': '09/27/2011',
    'Truly Yours': '02/12/2013',
    'Truly Yours 2': '04/30/2013',
    'Born Sinner': '06/18/2013',
    'Truly Yours 4': '??/??/2014',
    'Collaboration with Kendrick Lamar': '??/??/????',
    'J. Cole x Chance Project': '??/??/????',
    'Revenge of the Dreamers 2 [V1]': '??/??/????',
    '2014 Forest Hills Drive': '12/09/2014',
    '4 Your Eyez Only': '12/09/2016',
    'The Fall-Off [V1]': '??/??/????',
    'KOD': '04/20/2018',
    'The Off-Season': '05/14/2021',
    'Collaboration with JID': '??/??/????',
    'Might Delete Later': '04/05/2024',
    'The Fall-Off [V2]': '??/??/????',
    "It's A Boy": '??/??/????',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Before The Come Up',
    'The Come Up',
    'The Warm Up',
    'Friday Night Lights',
    'Cole World: The Sideline Story',
    'Truly Yours',
    'Truly Yours 2',
    'Born Sinner',
    'Truly Yours 4',
    'Collaboration with Kendrick Lamar',
    'J. Cole x Chance Project',
    'Revenge of the Dreamers 2 [V1]',
    '2014 Forest Hills Drive',
    '4 Your Eyez Only',
    'The Fall-Off [V1]',
    'KOD',
    'The Off-Season',
    'Collaboration with JID',
    'Might Delete Later',
    'The Fall-Off [V2]',
    "It's A Boy",
    'Ongoing',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
};
