import type { ArtistConfig } from './types';

export const colegoldConfig: ArtistConfig = {
  slug: 'colegold',
  SITE_NAME: 'COLEGOLD',
  SITE_DESCRIPTION: 'The Best J. Cole Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/colegold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'colegold_',
  HARDCODED_SHEET_ID: '1hjMtB-acUEpXYkR6TWQVeVoUzSLrAVIdy1lMoM6aFFw',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1hjMtB-acUEpXYkR6TWQVeVoUzSLrAVIdy1lMoM6aFFw/gviz/tq?tqx=out:csv&sheet=Recent',
  accentColor: '#dc2626',
  artistLabel: 'J. Cole',
  cardLetter: 'COLE',
  logoUrl: '/logos/colegold.png',
  artistPhotoUrl: '/artists/jcole.webp',

  getArtistName() {
    return 'J. Cole';
  },

  CUSTOM_IMAGES: {
    'Before The Come Up': '/colegold/eras/before-the-come-up.jpg',
    'The Come Up': '/colegold/eras/the-come-up.jpg',
    'The Warm Up': '/colegold/eras/the-warm-up.jpg',
    'Friday Night Lights': '/colegold/eras/friday-night-lights.jpg',
    'Cole World: The Sideline Story': '/colegold/eras/cole-world.jpg',
    'Truly Yours': '/colegold/eras/truly-yours.jpg',
    'Truly Yours 2': '/colegold/eras/truly-yours-2.jpg',
    'Born Sinner': '/colegold/eras/born-sinner.jpg',
    'Truly Yours 4': '/colegold/eras/truly-yours-4.jpg',
    'Collaboration with Kendrick Lamar': '/colegold/eras/kendrick-collab.jpg',
    'J. Cole x Chance Project': '/colegold/eras/chance-collab.jpg',
    'Revenge of the Dreamers 2 [V1]': '/colegold/eras/revenge-of-the-dreamers-2.jpg',
    '2014 Forest Hills Drive': '/colegold/eras/2014-forest-hills-drive.jpg',
    '4 Your Eyez Only': '/colegold/eras/4-your-eyez-only.jpg',
    'The Fall-Off [V1]': '/colegold/eras/fall-off-v1.jpg',
    'KOD': '/colegold/eras/kod.jpg',
    'The Off-Season': '/colegold/eras/the-off-season.jpg',
    'Collaboration with JID': '/colegold/eras/jid-collab.jpg',
    'Might Delete Later': '/colegold/eras/fall-off-v2.jpg',
    'The Fall-Off [V2]': '/colegold/eras/might-delete-later.jpg',
    "It's A Boy": '/colegold/eras/its-a-boy.jpg',
    'Ongoing': '/artists/jcole.webp',
  },

  ALBUM_RELEASE_DATES: {
    'Before The Come Up': '??/??/2006',
    'The Come Up': '05/04/2007',
    'The Warm Up': '06/15/2009',
    'Friday Night Lights': '11/14/2010',
    'Cole World: The Sideline Story': '09/27/2011',
    'Truly Yours': '02/12/2013',
    'Truly Yours 2': '04/30/2013',
    'Born Sinner': '06/18/2013',
    'Truly Yours 4': '??/??/2014',
    'Collaboration with Kendrick Lamar': '??/??/????',
    'J. Cole x Chance Project': '??/??/????',
    'Revenge of the Dreamers 2 [V1]': '??/??/????',
    '2014 Forest Hills Drive': '12/09/2014',
    '4 Your Eyez Only': '12/09/2016',
    'The Fall-Off [V1]': '??/??/????',
    'KOD': '04/20/2018',
    'The Off-Season': '05/14/2021',
    'Collaboration with JID': '??/??/????',
    'Might Delete Later': '04/05/2024',
    'The Fall-Off [V2]': '??/??/????',
    "It's A Boy": '??/??/????',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Before The Come Up': 'Before The Come Up is J. Cole\'s first mixtape, self-released in 2006 before he signed with Jay-Z\'s Roc Nation.',
    'The Come Up': 'The Come Up is J. Cole\'s second mixtape, released May 4, 2007, and part of his early underground buzz-building run.',
    'The Warm Up': 'The Warm Up is J. Cole\'s third mixtape, released June 15, 2009, and is credited with catching Jay-Z\'s attention ahead of his Roc Nation signing.',
    'Friday Night Lights': 'Friday Night Lights is J. Cole\'s fourth mixtape, released November 14, 2010, and is widely regarded as one of his best pre-debut projects.',
    'Cole World: The Sideline Story': 'Cole World: The Sideline Story is J. Cole\'s debut studio album, released September 27, 2011 on Roc Nation/Columbia Records.',
    'Truly Yours': 'Truly Yours is a free EP released by J. Cole on February 12, 2013, marking the one-year anniversary of Cole World: The Sideline Story.',
    'Truly Yours 2': 'Truly Yours 2 is a follow-up EP released by J. Cole on April 30, 2013, ahead of Born Sinner.',
    'Born Sinner': 'Born Sinner is J. Cole\'s second studio album, released June 18, 2013, notable for its head-to-head release date against Kanye West\'s Yeezus.',
    'Truly Yours 4': 'Truly Yours 4 was a planned fourth installment of the Truly Yours EP series, considered for release in 2014 but ultimately scrapped.',
    'Collaboration with Kendrick Lamar': 'Scrapped joint project between J. Cole and Kendrick Lamar, recorded in sessions around May 2012 but never officially released.',
    'J. Cole x Chance Project': 'Unreleased collaborative project between J. Cole and Chance the Rapper, worked on around 2014.',
    'Revenge of the Dreamers 2 [V1]': 'Early version of what became the 2015 compilation Revenge of the Dreamers II, worked on in 2014 before being reworked.',
    '2014 Forest Hills Drive': '2014 Forest Hills Drive is J. Cole\'s third studio album, released December 9, 2014, and his first album certified multi-platinum with no featured guests.',
    '4 Your Eyez Only': '4 Your Eyez Only is J. Cole\'s fourth studio album, released December 9, 2016, a concept album told through the story of a close friend.',
    'The Fall-Off [V1]': 'Early version of the sessions for The Fall-Off, J. Cole\'s long-teased upcoming album, reportedly including guest verses later removed.',
    'KOD': 'KOD is J. Cole\'s fifth studio album, released April 20, 2018, exploring themes of addiction and released with no guest features.',
    'The Off-Season': 'The Off-Season is J. Cole\'s sixth studio album, released May 14, 2021, framed as preparation for his long-teased final album The Fall-Off.',
    'Collaboration with JID': 'Teased collaborative project between J. Cole and JID, mentioned in interviews but never released.',
    'Might Delete Later': 'Might Delete Later is a surprise mixtape released by J. Cole on April 5, 2024, serving as a lead-in to The Fall-Off.',
    'The Fall-Off [V2]': 'Later version of the sessions for The Fall-Off, J. Cole\'s long-teased and reportedly final studio album.',
    "It's A Boy": 'Working title associated with unreleased J. Cole material.',
    'Ongoing': 'Catch-all for recent J. Cole material without a confirmed era or project.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Before The Come Up',
    'The Come Up',
    'The Warm Up',
    'Friday Night Lights',
    'Cole World: The Sideline Story',
    'Truly Yours',
    'Truly Yours 2',
    'Born Sinner',
    'Truly Yours 4',
    'Collaboration with Kendrick Lamar',
    'J. Cole x Chance Project',
    'Revenge of the Dreamers 2 [V1]',
    '2014 Forest Hills Drive',
    '4 Your Eyez Only',
    'The Fall-Off [V1]',
    'KOD',
    'The Off-Season',
    'Collaboration with JID',
    'Might Delete Later',
    'The Fall-Off [V2]',
    "It's A Boy",
    'Ongoing',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
  hasMiscTab: false,
  hasSubAlbumsTab: false,
};
