import type { ArtistConfig } from './types';

export const colegoldConfig: ArtistConfig = {
  slug: 'colegold',
  SITE_NAME: 'COLEGOLD',
  SITE_DESCRIPTION: 'The Best J. Cole Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/colegold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'colegold_',
  HARDCODED_SHEET_ID: '1hjMtB-acUEpXYkR6TWQVeVoUzSLrAVIdy1lMoM6aFFw',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1hjMtB-acUEpXYkR6TWQVeVoUzSLrAVIdy1lMoM6aFFw/gviz/tq?tqx=out:csv&sheet=Recent',
  accentColor: '#dc2626',
  artistLabel: 'J. Cole',
  cardLetter: 'COLE',
  logoUrl: '/logos/colegold.png',
  artistPhotoUrl: '/artists/jcole.webp',

  getArtistName() {
    return 'J. Cole';
  },

  CUSTOM_IMAGES: {
    'Before The Come Up': '/colegold/eras/before-the-come-up.jpg',
    'The Come Up': '/colegold/eras/the-come-up.jpg',
    'The Warm Up': '/colegold/eras/the-warm-up.jpg',
    'Friday Night Lights': '/colegold/eras/friday-night-lights.jpg',
    'Cole World: The Sideline Story': '/colegold/eras/cole-world.jpg',
    'Truly Yours': '/colegold/eras/truly-yours.jpg',
    'Truly Yours 2': '/colegold/eras/truly-yours-2.jpg',
    'Born Sinner': '/colegold/eras/born-sinner.jpg',
    'Truly Yours 4': '/colegold/eras/truly-yours-4.jpg',
    'Collaboration with Kendrick Lamar': '/colegold/eras/kendrick-collab.jpg',
    'J. Cole x Chance Project': '/colegold/eras/chance-collab.jpg',
    'Revenge of the Dreamers 2 [V1]': '/colegold/eras/revenge-of-the-dreamers-2.jpg',
    '2014 Forest Hills Drive': '/colegold/eras/2014-forest-hills-drive.jpg',
    '4 Your Eyez Only': '/colegold/eras/4-your-eyez-only.jpg',
    'The Fall-Off [V1]': '/colegold/eras/fall-off-v1.jpg',
    'KOD': '/colegold/eras/kod.jpg',
    'The Off-Season': '/colegold/eras/the-off-season.jpg',
    'Collaboration with JID': '/colegold/eras/jid-collab.jpg',
    'Might Delete Later': '/colegold/eras/fall-off-v2.jpg',
    'The Fall-Off [V2]': '/colegold/eras/might-delete-later.jpg',
    "It's A Boy": '/colegold/eras/its-a-boy.jpg',
    'Ongoing': '/artists/jcole.webp',
  },

  ALBUM_RELEASE_DATES: {
    'Before The Come Up': '??/??/2006',
    'The Come Up': '05/04/2007',
    'The Warm Up': '06/15/2009',
    'Friday Night Lights': '11/14/2010',
    'Cole World: The Sideline Story': '09/27/2011',
    'Truly Yours': '02/12/2013',
    'Truly Yours 2': '04/30/2013',
    'Born Sinner': '06/18/2013',
    'Truly Yours 4': '??/??/2014',
    'Collaboration with Kendrick Lamar': '??/??/????',
    'J. Cole x Chance Project': '??/??/????',
    'Revenge of the Dreamers 2 [V1]': '??/??/????',
    '2014 Forest Hills Drive': '12/09/2014',
    '4 Your Eyez Only': '12/09/2016',
    'The Fall-Off [V1]': '??/??/????',
    'KOD': '04/20/2018',
    'The Off-Season': '05/14/2021',
    'Collaboration with JID': '??/??/????',
    'Might Delete Later': '04/05/2024',
    'The Fall-Off [V2]': '??/??/????',
    "It's A Boy": '??/??/????',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Before The Come Up': 'Before The Come Up is J. Cole\'s first mixtape, self-released in 2006 before he signed with Jay-Z\'s Roc Nation.',
    'The Come Up': 'The Come Up is J. Cole\'s second mixtape, released May 4, 2007, and part of his early underground buzz-building run.',
    'The Warm Up': "The Warm Up is the second official mixtape from rapper J. Cole, released on June 15th, 2009. This album is the turning point for J. Cole since the lead single for this album, \"Lights Please,\" got the attention of Jay-Z, who later signed him to Roc Nation. On November 22, 2024, the mixtape was re-released onto streaming platforms, accompanying the third episode release of Cole's audio podcast series Inevitable, which focused on this mixtape.",
    'Friday Night Lights': "Friday Night Lights is the third official mixtape from rapper J. Cole, released on November 12th, 2010. This album contains songs that were scrapped from Cole World: The Sideline Story because the label didn't believe it would sell. \"In The Morning\" is the only song seen in Cole World. The mixtape was eventually re-released onto streaming platforms on November 27, 2024, accompanying the fifth episode release of Cole's audio podcast series Inevitable, which focused on this mixtape.",
    'Cole World: The Sideline Story': "Cole World: The Sideline Story is the debut studio album by rapper J. Cole, released on September 27th, 2011. Cole and Ib would talk on it further on the audio series \"inevitable\"",
    'Truly Yours': "Truly Yours, is J. Cole's first Extended Play released on Febuary 12th, 2013 to generate hype around his second album \"Born sinner\" and to also release tracks Cole knew wouldn't make it onto the offical release of the album.",
    'Truly Yours 2': "Truly Yours 2, is J. Cole's second Extended Play released on April 30th, 2013 to generate hype around his second album \"Born sinner\" and to also release tracks Cole knew wouldn't make it onto the offical release of the album.",
    'Born Sinner': "Born Sinner is the second studio album by rapper J. Cole, released on June 18th, 2013. This album was supposed to release on June 25, 2013, but dropped early alongside Kanye West's Yeezus.",
    'Truly Yours 4': "Seen on J. Cole's computer where he took a picture of it and posted it on his instagram, not much is known about \"Truly Yours 4\" other then it was on the table.",
    'Collaboration with Kendrick Lamar': "In late 2010, Kendrick and J. Cole decided to work on a collab project. They were able to finish a couple of songs, with a couple beats laying around waiting to be used. It's been delayed since, possibly, 2013. The idea of the album coming into fruition is still possible, but as of right now neither Cole or Kendrick are focused on it. Kendrick put his focus on \"To Pimp A Butterfly\" and J. Cole put his focus on \"2014 Forest Hills Drive\". Most of the descriptions come from the Kendrick Music Tracker.",
    'J. Cole x Chance Project': "Around 2014, J. Cole posted a tracklist that was likely a collaboration project with Chance The Rapper. The tracklist had seven tracks and was around 21 minutes long. Very little is known about this project since neither Cole nor Chance has spoke about this project.",
    'Revenge of the Dreamers 2 [V1]': "Seen on J. Cole's computer where he took of picture of it and posted on his instragram what seems to be an 2014 version of \"Revenge of the Dreamers 2\" an original version potentially? Unknown if it was already made or just an idea.",
    '2014 Forest Hills Drive': "2014 Forest Hills Drive is the third studio album by rapper J. Cole, released on December 9th, 2014. The album's title is the address of a home in Fayetteville, North Carolina, where Cole lived from his early youth, until 2003.",
    '4 Your Eyez Only': "4 Your Eyez Only is the fourth studio album by rapper J. Cole, released on December 9th, 2016. The album tells the story of Cole’s slain friend given the pseudonym James McMillian Jr, as he goes from selling crack, to falling in love and starting a family.",
    'The Fall-Off [V1]': "The original vision for The Fall-Off was wildly different yet pretty unknown. What we know is that the album wasn't going to be a double-disc album in the beginning. We also know this album would've had a Kendrick Lamar feature up until the Kendrick & Drake beef in 2024.",
    'KOD': 'KOD is J. Cole\'s fifth studio album, released April 20, 2018, exploring themes of addiction and released with no guest features.',
    'The Off-Season': "The Off-Season is the sixth studio album by rapper J. Cole, released on May 14th, 2021.",
    'Collaboration with JID': 'Teased collaborative project between J. Cole and JID, mentioned in interviews but never released.',
    'Might Delete Later': 'Might Delete Later is a surprise mixtape released by J. Cole on April 5, 2024, serving as a lead-in to The Fall-Off.',
    'The Fall-Off [V2]': "The Fall-Off is the seventh and final studio album released by J. Cole on Feb 6th, 2026.",
    "It's A Boy": "It's A Boy is a supposed project that was first mentioned on a timeline released by Cole on December 29th, 2020 as being the second to last. It's truly unknown what this project would've been. When asked about it after The Fall-Off released, Cole stated \"No it's not scrapped. it will release. we almost put it out before the album. but with the birthday blizzard tape and 24 song album we was like it's a lot of music to process.\"",
    'Ongoing': 'Catch-all for recent J. Cole material without a confirmed era or project.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Before The Come Up',
    'The Come Up',
    'The Warm Up',
    'Friday Night Lights',
    'Cole World: The Sideline Story',
    'Truly Yours',
    'Truly Yours 2',
    'Born Sinner',
    'Truly Yours 4',
    'Collaboration with Kendrick Lamar',
    'J. Cole x Chance Project',
    'Revenge of the Dreamers 2 [V1]',
    '2014 Forest Hills Drive',
    '4 Your Eyez Only',
    'The Fall-Off [V1]',
    'KOD',
    'The Off-Season',
    'Collaboration with JID',
    'Might Delete Later',
    'The Fall-Off [V2]',
    "It's A Boy",
    'Ongoing',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
  hasMiscTab: false,
  hasSubAlbumsTab: false,
};
