import type { ArtistConfig } from './types';

export const cudigoldConfig: ArtistConfig = {
  slug: 'cudigold',
  SITE_NAME: 'CUDIGOLD',
  SITE_DESCRIPTION: 'The Best Kid Cudi Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/cudigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'cudigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#6366f1',
  artistLabel: 'Kid Cudi',
  cardLetter: 'CUDI',
  logoUrl: '/logos/cudigold.webp',
  artistPhotoUrl: '/artists/kidcudi.jpg',

  getArtistName() {
    return 'Kid Cudi';
  },

  CUSTOM_IMAGES: {
    'A Kid Named Cudi': '/cudigold/eras/a-kid-named-cudi.jpg',
    'Rap Hard': '/cudigold/eras/rap-hard.jpg',
    'Man On The Moon': '/cudigold/eras/man-on-the-moon.jpg',
    'Cudder: The Revolution Of Evolution': '/cudigold/eras/cudder.jpg',
    'Man On The Moon II': '/cudigold/eras/man-on-the-moon-ii.jpg',
    'A Man Named Scott': '/artists/kidcudi.jpg',
    'WZRD': '/cudigold/eras/wzrd.jpg',
    'INDICUD': '/cudigold/eras/indicud.jpg',
    'Satellite Flight': '/cudigold/eras/satellite-flight.jpg',
    "Speedin' Bullet 2 Heaven": '/cudigold/eras/speedin-bullet-2-heaven.jpg',
    'Passion Pain & Demon Slayin': '/cudigold/eras/passion-pain-demon-slayin.jpg',
    'KIDS SEE GHOSTS': '/cudigold/eras/kids-see-ghosts.jpg',
    'Man On The Moon III': '/cudigold/eras/man-on-the-moon-iii.jpg',
    'The Boy Who Flew To The Moon (Vol .1)': '/cudigold/eras/man-on-the-moon-iii.jpg',
    'Entergalactic': '/cudigold/eras/entergalactic.jpg',
    'INSANO': '/cudigold/eras/insano.jpg',
    'INSANO (NITRO MEGA)': '/cudigold/eras/insano.jpg',
    'FREE': '/cudigold/eras/free.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'A Kid Named Cudi': '07/17/2008',
    'Rap Hard': '??/??/2003',
    'Man On The Moon': '09/15/2009',
    'Cudder: The Revolution Of Evolution': '??/??/????',
    'Man On The Moon II': '11/09/2010',
    'A Man Named Scott': '??/??/????',
    'WZRD': '02/28/2012',
    'INDICUD': '04/12/2013',
    'Satellite Flight': '02/25/2014',
    "Speedin' Bullet 2 Heaven": '04/14/2015',
    'Passion Pain & Demon Slayin': '12/09/2016',
    'KIDS SEE GHOSTS': '06/08/2018',
    'Man On The Moon III': '12/11/2020',
    'The Boy Who Flew To The Moon (Vol .1)': '07/08/2022',
    'Entergalactic': '09/30/2022',
    'INSANO': '01/12/2024',
    'INSANO (NITRO MEGA)': '01/12/2024',
    'FREE': '08/22/2025',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'A Kid Named Cudi': '"A Kid Named Cudi" is the debut mixtape by Kid Cudi, released in 2008 by independent record label "Fool\'s Gold Records" & New York City streetwear brand 10 Deep. The album was Cudi\'s first big success, establishing his fan base, being reviewed well by critics, and catching the ear of hip-hop superstar Kanye West, who would sign Cudi to G.O.O.D. Music later that year. Three of the mixtape\'s songs, "Man On The Moon," "Day N Nite," and "TGIF," would later make it onto Cudi\'s debut album "Man on the Moon: The End of Day." In June 2008, Cudi quit his job at the Bape store.',
    'Rap Hard': '"Rap Hard" is a demo tape made by Kid Cudi under the name "Kid Mesc" between 2002 and 2003. On November 13th, 2011, the tape leaked online, to which Cudi would reply "I actually never wanted anyone to hear those songs ever, but it\'s cool. Ha."',
    'Man On The Moon': '"Man on the Moon: The End of Day" is the debut studio album by Kid Cudi. It was released on September 15, 2009, through Dream On, GOOD Music, and Universal Motown Records. Narrated by fellow American rapper Common, it follows the release of his first full-length project \'A Kid Named Cudi\' (2008), and is the first installment of the Man on the Moon trilogy. Production was handled by several high-profile record producers, including Kanye West, Emile Haynie, Plain Pat, and Jeff Bhasker, as well as contributions from Dot da Genius, Free School and The Kickdrums, among others.',
    'Cudder: The Revolution Of Evolution': 'On August 25th, 2009, Kid Cudi announced that his second album was going to be in a trilogy, it was originally going to be titled "Man on the Moon: The Ghost in the Machine." In the same interview, he said he was still working on the title for the third "Man on the Moon." In an MTV interview, Cudi announced that the follow-up to his debut album would be a compilation album entitled "Cudder," which would have many collaborations. He stated he had already recorded songs with Snoop Dogg, Travis Barker, Clipse, Cage and Pharrell and had many more he wanted to work with. On January 7th, 2010, Cudi revealed in a video interview with Karmaloop TV that he was working with Pharrell in Miami for the album. A week later, he changed the title from "Cudder" to "Cudder and the Revolution of Evolution" at a show in Milwaukee. A few months later, Cudi took to his blog to announce that he scrapped the collaborative theme of \'Cudder\' for a project that is much more personal, being "Man On The Moon II: The Legend Of Mr. Rager."',
    'Man On The Moon II': '"Man on the Moon II: The Legend of Mr. Rager" is the second studio album by American rapper Kid Cudi. It was released on November 9th, 2010, through Dream On and G.O.O.D. Music, and distributed by Universal Motown Records. It serves as a sequel to his debut studio album "Man on the Moon: The End of Day," and is the second installment of the Man on the Moon trilogy. The album incorporates alternative and psychedelic elements to the sound that Cudi explored in his previous album. It features a blend of dark and emotional lyrics, exploring themes of depression, loneliness, detachment, and isolation. The album also highlights other topics, such as Cudi\'s former cocaine addiction, fame, and alcoholism, as well as family issues and women. Evolved from \'Cudder\' (\'Cudder: The Revolution Of Evolution\')',
    'A Man Named Scott': "Scrapped mixtape Kid Cudi worked on around 2011; the title was later reused for his 2021 Amazon Prime documentary of the same name.",
    'WZRD': "Self-titled debut album from WZRD, Kid Cudi's rock-oriented duo with producer Dot da Genius, released February 28, 2012.",
    'INDICUD': "Kid Cudi's third solo studio album, released April 12, 2013.",
    'Satellite Flight': "Kid Cudi's fourth studio album, Satellite Flight: The Journey to Mother Moon, released February 25, 2014.",
    "Speedin' Bullet 2 Heaven": "Kid Cudi's fifth studio album, a rock-leaning double-disc project released April 14, 2015.",
    'Passion Pain & Demon Slayin': "Kid Cudi's sixth studio album, released December 9, 2016.",
    'KIDS SEE GHOSTS': 'Collaborative studio album with Kanye West, released June 8, 2018.',
    'Man On The Moon III': "Kid Cudi's seventh studio album, Man on the Moon III: The Chosen, released December 11, 2020.",
    'The Boy Who Flew To The Moon (Vol .1)': "Kid Cudi's first greatest-hits compilation, released July 8, 2022, spanning tracks from seven of his studio albums.",
    'Entergalactic': "Companion album to Kid Cudi's Netflix animated special of the same name, released September 30, 2022.",
    'INSANO': "Studio album released January 12, 2024, featuring Travis Scott, A$AP Rocky, Pharrell Williams, and others.",
    'INSANO (NITRO MEGA)': 'Expanded deluxe edition of INSANO, released alongside the standard album.',
    'FREE': "Kid Cudi's eleventh studio album, released August 22, 2025, his first pop-leaning record and one with no guest features.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    'Man On The Moon [V1]': 'Man On The Moon',
    'Entergalactic [V1]': 'Entergalactic',
    'Entergalactic [V2]': 'Entergalactic',
    'Entergalactic (Soundtrack)': 'Entergalactic',
    'INSANO [V1]': 'INSANO',
    'A Kid Named Cudi (2022)': 'A Kid Named Cudi',
  },
  ALBUM_ORDER: [
    'A Kid Named Cudi',
    'Rap Hard',
    'Man On The Moon',
    'Cudder: The Revolution Of Evolution',
    'Man On The Moon II',
    'A Man Named Scott',
    'WZRD',
    'INDICUD',
    'Satellite Flight',
    "Speedin' Bullet 2 Heaven",
    'Passion Pain & Demon Slayin',
    'KIDS SEE GHOSTS',
    'Man On The Moon III',
    'The Boy Who Flew To The Moon (Vol .1)',
    'Entergalactic',
    'INSANO',
    'INSANO (NITRO MEGA)',
    'FREE',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
  hasRecentTab: false,
  hasTracklistsTab: false,
  hasSubAlbumsTab: false,
};
