import type { ArtistConfig } from './types';

export const cudigoldConfig: ArtistConfig = {
  slug: 'cudigold',
  SITE_NAME: 'CUDIGOLD',
  SITE_DESCRIPTION: 'The Best Kid Cudi Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/cudigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'cudigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#6366f1',
  artistLabel: 'Kid Cudi',
  cardLetter: 'CUDI',
  logoUrl: '/logos/cudigold.webp',
  artistPhotoUrl: '/artists/kidcudi.jpg',

  getArtistName() {
    return 'Kid Cudi';
  },

  CUSTOM_IMAGES: {
    'A Kid Named Cudi': '/cudigold/eras/a-kid-named-cudi.jpg',
    'Rap Hard': '/cudigold/eras/rap-hard.jpg',
    'Man On The Moon': '/cudigold/eras/man-on-the-moon.jpg',
    'Cudder: The Revolution Of Evolution': '/cudigold/eras/cudder.jpg',
    'Man On The Moon II': '/cudigold/eras/man-on-the-moon-ii.jpg',
    'A Man Named Scott': '/artists/kidcudi.jpg',
    'WZRD': '/cudigold/eras/wzrd.jpg',
    'INDICUD': '/cudigold/eras/indicud.jpg',
    'Satellite Flight': '/cudigold/eras/satellite-flight.jpg',
    "Speedin' Bullet 2 Heaven": '/cudigold/eras/speedin-bullet-2-heaven.jpg',
    'Passion Pain & Demon Slayin': '/cudigold/eras/passion-pain-demon-slayin.jpg',
    'KIDS SEE GHOSTS': '/cudigold/eras/kids-see-ghosts.jpg',
    'Man On The Moon III': '/cudigold/eras/man-on-the-moon-iii.jpg',
    'The Boy Who Flew To The Moon (Vol .1)': '/cudigold/eras/man-on-the-moon-iii.jpg',
    'Entergalactic': '/cudigold/eras/entergalactic.jpg',
    'INSANO': '/cudigold/eras/insano.jpg',
    'INSANO (NITRO MEGA)': '/cudigold/eras/insano.jpg',
    'FREE': '/cudigold/eras/free.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'A Kid Named Cudi': '07/17/2008',
    'Rap Hard': '??/??/2003',
    'Man On The Moon': '09/15/2009',
    'Cudder: The Revolution Of Evolution': '??/??/????',
    'Man On The Moon II': '11/09/2010',
    'A Man Named Scott': '??/??/????',
    'WZRD': '02/28/2012',
    'INDICUD': '04/12/2013',
    'Satellite Flight': '02/25/2014',
    "Speedin' Bullet 2 Heaven": '04/14/2015',
    'Passion Pain & Demon Slayin': '12/09/2016',
    'KIDS SEE GHOSTS': '06/08/2018',
    'Man On The Moon III': '12/11/2020',
    'The Boy Who Flew To The Moon (Vol .1)': '07/08/2022',
    'Entergalactic': '09/30/2022',
    'INSANO': '01/12/2024',
    'INSANO (NITRO MEGA)': '01/12/2024',
    'FREE': '08/22/2025',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'A Kid Named Cudi': "Kid Cudi's debut mixtape, released July 17, 2008, the free project that first brought him mainstream attention.",
    'Rap Hard': 'A demo tape recorded around 2002-2003 under the pseudonym Kid Mesc, capturing some of Cudi\'s earliest recordings. It leaked online in November 2011.',
    'Man On The Moon': "Kid Cudi's debut studio album, Man on the Moon: The End of Day, released September 15, 2009.",
    'Cudder: The Revolution Of Evolution': 'Little-documented mixtape from around 2010.',
    'Man On The Moon II': "Kid Cudi's second studio album, Man on the Moon II: The Legend of Mr. Rager, released November 9, 2010.",
    'A Man Named Scott': "Scrapped mixtape Kid Cudi worked on around 2011; the title was later reused for his 2021 Amazon Prime documentary of the same name.",
    'WZRD': "Self-titled debut album from WZRD, Kid Cudi's rock-oriented duo with producer Dot da Genius, released February 28, 2012.",
    'INDICUD': "Kid Cudi's third solo studio album, released April 12, 2013.",
    'Satellite Flight': "Kid Cudi's fourth studio album, Satellite Flight: The Journey to Mother Moon, released February 25, 2014.",
    "Speedin' Bullet 2 Heaven": "Kid Cudi's fifth studio album, a rock-leaning double-disc project released April 14, 2015.",
    'Passion Pain & Demon Slayin': "Kid Cudi's sixth studio album, released December 9, 2016.",
    'KIDS SEE GHOSTS': 'Collaborative studio album with Kanye West, released June 8, 2018.',
    'Man On The Moon III': "Kid Cudi's seventh studio album, Man on the Moon III: The Chosen, released December 11, 2020.",
    'The Boy Who Flew To The Moon (Vol .1)': "Kid Cudi's first greatest-hits compilation, released July 8, 2022, spanning tracks from seven of his studio albums.",
    'Entergalactic': "Companion album to Kid Cudi's Netflix animated special of the same name, released September 30, 2022.",
    'INSANO': "Studio album released January 12, 2024, featuring Travis Scott, A$AP Rocky, Pharrell Williams, and others.",
    'INSANO (NITRO MEGA)': 'Expanded deluxe edition of INSANO, released alongside the standard album.',
    'FREE': "Kid Cudi's eleventh studio album, released August 22, 2025, his first pop-leaning record and one with no guest features.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    'Man On The Moon [V1]': 'Man On The Moon',
    'Entergalactic [V1]': 'Entergalactic',
    'Entergalactic [V2]': 'Entergalactic',
    'Entergalactic (Soundtrack)': 'Entergalactic',
    'INSANO [V1]': 'INSANO',
    'A Kid Named Cudi (2022)': 'A Kid Named Cudi',
  },
  ALBUM_ORDER: [
    'A Kid Named Cudi',
    'Rap Hard',
    'Man On The Moon',
    'Cudder: The Revolution Of Evolution',
    'Man On The Moon II',
    'A Man Named Scott',
    'WZRD',
    'INDICUD',
    'Satellite Flight',
    "Speedin' Bullet 2 Heaven",
    'Passion Pain & Demon Slayin',
    'KIDS SEE GHOSTS',
    'Man On The Moon III',
    'The Boy Who Flew To The Moon (Vol .1)',
    'Entergalactic',
    'INSANO',
    'INSANO (NITRO MEGA)',
    'FREE',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
