import type { ArtistConfig } from './types';

export const cudigoldConfig: ArtistConfig = {
  slug: 'cudigold',
  SITE_NAME: 'CUDIGOLD',
  SITE_DESCRIPTION: 'The Best Kid Cudi Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/cudigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'cudigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#6366f1',
  artistLabel: 'Kid Cudi',
  cardLetter: 'CUDI',
  logoUrl: '/logos/cudigold.webp',
  artistPhotoUrl: '/artists/kidcudi.jpg',

  getArtistName() {
    return 'Kid Cudi';
  },

  CUSTOM_IMAGES: {
    'A Kid Named Cudi': '/cudigold/eras/a-kid-named-cudi.jpg',
    'Rap Hard': '/cudigold/eras/rap-hard.jpg',
    'Man On The Moon': '/cudigold/eras/man-on-the-moon.jpg',
    'Cudder: The Revolution Of Evolution': '/cudigold/eras/cudder.jpg',
    'Man On The Moon II': '/cudigold/eras/man-on-the-moon-ii.jpg',
    'A Man Named Scott': '/artists/kidcudi.jpg',
    'WZRD': '/cudigold/eras/wzrd.jpg',
    'INDICUD': '/cudigold/eras/indicud.jpg',
    'Satellite Flight': '/cudigold/eras/satellite-flight.jpg',
    "Speedin' Bullet 2 Heaven": '/cudigold/eras/speedin-bullet-2-heaven.jpg',
    'Passion Pain & Demon Slayin': '/cudigold/eras/passion-pain-demon-slayin.jpg',
    'KIDS SEE GHOSTS': '/cudigold/eras/kids-see-ghosts.jpg',
    'Man On The Moon III': '/cudigold/eras/man-on-the-moon-iii.jpg',
    'The Boy Who Flew To The Moon (Vol .1)': '/cudigold/eras/man-on-the-moon-iii.jpg',
    'Entergalactic': '/cudigold/eras/entergalactic.jpg',
    'INSANO': '/cudigold/eras/insano.jpg',
    'INSANO (NITRO MEGA)': '/cudigold/eras/insano.jpg',
    'FREE': '/cudigold/eras/free.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'A Kid Named Cudi': '07/17/2008',
    'Rap Hard': '??/??/2003',
    'Man On The Moon': '09/15/2009',
    'Cudder: The Revolution Of Evolution': '??/??/????',
    'Man On The Moon II': '11/09/2010',
    'A Man Named Scott': '??/??/????',
    'WZRD': '02/28/2012',
    'INDICUD': '04/12/2013',
    'Satellite Flight': '02/25/2014',
    "Speedin' Bullet 2 Heaven": '04/14/2015',
    'Passion Pain & Demon Slayin': '12/09/2016',
    'KIDS SEE GHOSTS': '06/08/2018',
    'Man On The Moon III': '12/11/2020',
    'The Boy Who Flew To The Moon (Vol .1)': '07/08/2022',
    'Entergalactic': '09/30/2022',
    'INSANO': '01/12/2024',
    'INSANO (NITRO MEGA)': '01/12/2024',
    'FREE': '08/22/2025',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    'Man On The Moon [V1]': 'Man On The Moon',
    'Entergalactic [V1]': 'Entergalactic',
    'Entergalactic [V2]': 'Entergalactic',
    'Entergalactic (Soundtrack)': 'Entergalactic',
    'INSANO [V1]': 'INSANO',
    'A Kid Named Cudi (2022)': 'A Kid Named Cudi',
  },
  ALBUM_ORDER: [
    'A Kid Named Cudi',
    'Rap Hard',
    'Man On The Moon',
    'Cudder: The Revolution Of Evolution',
    'Man On The Moon II',
    'A Man Named Scott',
    'WZRD',
    'INDICUD',
    'Satellite Flight',
    "Speedin' Bullet 2 Heaven",
    'Passion Pain & Demon Slayin',
    'KIDS SEE GHOSTS',
    'Man On The Moon III',
    'The Boy Who Flew To The Moon (Vol .1)',
    'Entergalactic',
    'INSANO',
    'INSANO (NITRO MEGA)',
    'FREE',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
