import type { ArtistConfig } from './types';

export const denzelgoldConfig: ArtistConfig = {
  slug: 'denzelgold',
  SITE_NAME: 'DENZELGOLD',
  SITE_DESCRIPTION: 'The Best Denzel Curry Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/denzelgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'denzelgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1Pyi72FNT6KWuQE3g4BmIDCV26HMfKFcE650Duyia43o/export?format=csv&gid=70327685',
  accentColor: '#c026d3',
  artistLabel: 'Denzel Curry',
  cardLetter: 'DC',
  logoUrl: '/logos/denzelgold.webp',
  artistPhotoUrl: '/artists/denzelcurry.webp',

  getArtistName() {
    return 'Denzel Curry';
  },

  CUSTOM_IMAGES: {
    'CuRRy Wuz Here': '/denzelgold/eras/curry-wuz-here.jpg',
    'Nostalgic 64': '/denzelgold/eras/nostalgic-64.jpg',
    '32 Zel/Planet Shrooms': '/denzelgold/eras/32-zel-planet-shrooms.jpg',
    'Imperial': '/denzelgold/eras/imperial.jpg',
    'TA13OO': '/denzelgold/eras/ta13oo.jpg',
    'ZUU': '/denzelgold/eras/zuu.jpg',
    'UNLOCKED': '/denzelgold/eras/unlocked.jpg',
    'Melt My Eyez, See Your Future': '/denzelgold/eras/melt-my-eyez-see-your-future.jpg',
    'Designed By Angels': '/denzelgold/eras/designed-by-angels.jpg',
    'KING OF THE MISCHIEVOUS SOUTH VOL 2': '/denzelgold/eras/king-of-the-mischievous-south-vol-2.jpg',
    'Strictly 4 The Scythe': '/denzelgold/eras/strictly-4-the-scythe.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'CuRRy Wuz Here': '01/16/2011',
    'King Remembered': '??/??/????',
    'King of the Mischievous South': '01/12/2012',
    'Strictly 4 My R.V.I.D.X.R.Z.': '05/13/2012',
    'Before Nostalgic 64': '??/??/????',
    'Mental Vendetta': '12/31/2012',
    'Nostalgic 64': '09/03/2013',
    '32 Zel/Planet Shrooms': '06/09/2015',
    'CUNT $WAB MAFIA': '??/??/????',
    'Imperial': '03/09/2016',
    'TA13OO': '07/27/2018',
    'ZUU': '05/31/2019',
    'UNLOCKED': '02/07/2020',
    'ULTRAGROUND': '??/??/????',
    'Melt My Eyez, See Your Future': '03/25/2022',
    'Designed By Angels': '??/??/????',
    'KING OF THE MISCHIEVOUS SOUTH VOL 2': '07/19/2024',
    'Strictly 4 The Scythe': '03/06/2026',
    'Ongoing': '??/??/????',
    'Unknown Era': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'CuRRy Wuz Here': "CuRRy Wuz Here is Denzel Curry's debut mixtape, released January 16, 2011.",
    'King Remembered': 'Early scrapped project from Denzel Curry\'s beginnings as a rapper.',
    'King of the Mischievous South': "King of the Mischievous South is Denzel Curry's second mixtape, released January 12, 2012.",
    'Strictly 4 My R.V.I.D.X.R.Z.': "Early mixtape released May 13, 2012, made during Denzel Curry's time with the Raider Klan collective.",
    'Before Nostalgic 64': "Umbrella era consisting of mixtapes Denzel released before his debut studio album \"Nostalgic 64\". * King Of The Mischievous South Vol 1 Underground Tape 1996 and Strictly 4 My R.V.I.D.X.R.Z (1993) were not actually made in those years.",
    'Mental Vendetta': 'Mixtape released December 31, 2012, from early in Denzel Curry\'s career.',
    'Nostalgic 64': "Nostalgic 64 is the debut studio album by American rapper Denzel Curry. It was released on September 3, 2013.",
    '32 Zel/Planet Shrooms': "32 Zel/Planet Shrooms is the debut double EP by American rapper Denzel Curry. It was released on June 9, 2015 by C9 Records. On October 14, 2016, 32 Zel/Planet Shrooms was removed from iTunes and streaming services. Denzel stated that it would return soon and be remastered. On September 22, 2017, a remastered version of 32 Zel with re-recorded vocals was released to iTunes and streaming services, however the original version is still available on YouTube Music, but completely missing 32 Zel while still having the name 32 Zel/Planet Shrooms.",
    'CUNT $WAB MAFIA': 'Obscure early group/crew name associated with unreleased Denzel Curry material.',
    'Imperial': "Imperial is the second studio album by American rapper Denzel Curry. It was released and made available for free download and streaming on SoundCloud on March 9, 2016, then re-released later on Spotify as the deluxe version on October 14, 2016.",
    'TA13OO': "TA13OO is the third studio album by American rapper Denzel Curry. It was released in 3 acts between July 25 to 27, 2018, through PH Recordings and distributed by Loma Vista Recordings. Across the three sections of TA13OO, Denzel explores topics including molestation, the presidential election, fame, hatred, paranoia, revenge, love, the current state of music and personal tales of his own near-death experiences. Sonically, the album ranges just as widely as its subject matter, sounds of paranoia, fear of loss, brooding melancholy and mood swings straight from hell all find their way onto TA13OO.",
    'ZUU': "ZUU is the fourth studio album by American rapper Denzel Curry, released through PH Recordings and Loma Vista on May 31, 2019. The title is a nickname for his home city, Carol City, Florida. Denzel Curry said that while his previous album TA13OO was rooted in darker themes, ZUU came from homesickness for Miami. He explained: \"it goes from the sounds of where I grew up, to what I was raised around, to the people I was raised around, to the sounds that pretty much shaped the person I am.",
    'UNLOCKED': "UNLOCKED is an collaborative EP by American rapper Denzel Curry in collaboration with American record producer Kenny Beats. It was released on February 7, 2020, by PH Recordings and Loma Vista Recordings. The album was accompanied by a short film that was released on February 6, 2020. While Denzel Curry was touring for his 2018 album, TA13OO, his manager, Mark Maturah, expressed interest in pairing Curry in a recording booth with Kenny Beats. The two had a feud over one of these beats being used by another artist as it was supposed to be used on Curry's 2019 album, Zuu, causing Curry to hate Kenny for \"months\".",
    'ULTRAGROUND': "Album that might have been worked on when ULTRAGROUND was made. It was thought that this album was called \"DON'T FOLD\" but this was later proven false after Key Nyata dropped his album with the same name.",
    'Melt My Eyez, See Your Future': "Melt My Eyez See Your Future is the fifth studio album by American rapper Denzel Curry, released through PH and Loma Vista Recordings on March 25, 2022. Denzel Curry first began envisioning the album's themes in 2018, and began working on it after the completion of his 2019 album, Zuu. He revealed the album title in a November 2021 interview with Las Vegas Weekly. Melt My Eyez is a metaphor for people's tendency to avoid facing difficult topics in day-to-day life, while See Your Future is motivation for moving on by putting one's past behind and focusing on what's yet to come.",
    'Designed By Angels': "Designed By Angels is an R&B album Denzel was working on post Melt My Eyez. Currently have no material from this era. Said to \"not be the next album\" so it might still come out. as he said in a QnA his only scrapped albums are MMESYF pt 2 & 3. He claimed its inspired by Andre 3000's The Love Below and Frank Ocean's Blonde.",
    'KING OF THE MISCHIEVOUS SOUTH VOL 2': "King of the Mischievous South Vol. 2 is the debut commercial mixtape by Denzel Curry, released on July 19, 2024, via PH Recordings and Loma Vista. It serves as the sequel to his third mixtape King of the Mischievous South Vol. 1 Underground Tape 1996 (2012).",
    'Strictly 4 The Scythe': "Denzel said on an Instagram post that he will be dropping new music if people comment on the post. The post has the caption \"FUCK WITH THE SCYTHE YOU GET SLICED\", referring to the lyrics of the snippet tentatively titled \"The Scythe\".",
    'Ongoing': "Denzel has confirmed the existance of a solo album in DMs with a fan. In an interview, he then stated he will be \"lyrically at his best\" on this project.",
    'Unknown Era': "This is an umbrella era for tracks that aren't dated, and lack a sound reminiscent of another era.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'CuRRy Wuz Here',
    'King Remembered',
    'King of the Mischievous South',
    'Strictly 4 My R.V.I.D.X.R.Z.',
    'Before Nostalgic 64',
    'Mental Vendetta',
    'Nostalgic 64',
    '32 Zel/Planet Shrooms',
    'CUNT $WAB MAFIA',
    'Imperial',
    'TA13OO',
    'ZUU',
    'UNLOCKED',
    'ULTRAGROUND',
    'Melt My Eyez, See Your Future',
    'Designed By Angels',
    'KING OF THE MISCHIEVOUS SOUTH VOL 2',
    'Strictly 4 The Scythe',
    'Ongoing',
    'Unknown Era',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
  hasMiscTab: false,
  hasSubAlbumsTab: false,
};
