import type { ArtistConfig } from './types';

export const denzelgoldConfig: ArtistConfig = {
  slug: 'denzelgold',
  SITE_NAME: 'DENZELGOLD',
  SITE_DESCRIPTION: 'The Best Denzel Curry Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/denzelgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'denzelgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#c026d3',
  artistLabel: 'Denzel Curry',
  cardLetter: 'DC',
  logoUrl: '/logos/denzelgold.webp',
  artistPhotoUrl: '/artists/denzelcurry.jpg',

  getArtistName() {
    return 'Denzel Curry';
  },

  CUSTOM_IMAGES: {
    'CuRRy Wuz Here': '/denzelgold/eras/curry-wuz-here.jpg',
    'Nostalgic 64': '/denzelgold/eras/nostalgic-64.jpg',
    '32 Zel/Planet Shrooms': '/denzelgold/eras/32-zel-planet-shrooms.jpg',
    'Imperial': '/denzelgold/eras/imperial.jpg',
    'TA13OO': '/denzelgold/eras/ta13oo.jpg',
    'ZUU': '/denzelgold/eras/zuu.jpg',
    'UNLOCKED': '/denzelgold/eras/unlocked.jpg',
    'Melt My Eyez, See Your Future': '/denzelgold/eras/melt-my-eyez-see-your-future.jpg',
    'KING OF THE MISCHIEVOUS SOUTH VOL 2': '/denzelgold/eras/king-of-the-mischievous-south-vol-2.jpg',
    'Strictly 4 The Scythe': '/denzelgold/eras/strictly-4-the-scythe.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'CuRRy Wuz Here': '01/16/2011',
    'King Remembered': '??/??/????',
    'King of the Mischievous South': '01/12/2012',
    'Strictly 4 My R.V.I.D.X.R.Z.': '05/13/2012',
    'Before Nostalgic 64': '??/??/????',
    'Mental Vendetta': '12/31/2012',
    'Nostalgic 64': '09/03/2013',
    '32 Zel/Planet Shrooms': '06/09/2015',
    'CUNT $WAB MAFIA': '??/??/????',
    'Imperial': '03/09/2016',
    'TA13OO': '07/27/2018',
    'ZUU': '05/31/2019',
    'UNLOCKED': '02/07/2020',
    'ULTRAGROUND': '??/??/????',
    'Melt My Eyez, See Your Future': '03/25/2022',
    'Designed By Angels': '??/??/????',
    'KING OF THE MISCHIEVOUS SOUTH VOL 2': '07/19/2024',
    'Strictly 4 The Scythe': '03/06/2026',
    'Ongoing': '??/??/????',
    'Unknown Era': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'CuRRy Wuz Here': "CuRRy Wuz Here is Denzel Curry's debut mixtape, released January 16, 2011.",
    'King Remembered': 'Early scrapped project from Denzel Curry\'s beginnings as a rapper.',
    'King of the Mischievous South': "King of the Mischievous South is Denzel Curry's second mixtape, released January 12, 2012.",
    'Strictly 4 My R.V.I.D.X.R.Z.': "Early mixtape released May 13, 2012, made during Denzel Curry's time with the Raider Klan collective.",
    'Before Nostalgic 64': 'Early sessions and scrapped material that preceded Nostalgic 64.',
    'Mental Vendetta': 'Mixtape released December 31, 2012, from early in Denzel Curry\'s career.',
    'Nostalgic 64': "Nostalgic 64 is Denzel Curry's breakout project, released September 3, 2013.",
    '32 Zel/Planet Shrooms': 'Double project combining the 32 Zel and Planet Shrooms EPs, released June 9, 2015.',
    'CUNT $WAB MAFIA': 'Obscure early group/crew name associated with unreleased Denzel Curry material.',
    'Imperial': "Imperial is Denzel Curry's second studio album, released March 9, 2016.",
    'TA13OO': "TA13OO is Denzel Curry's third studio album, released July 27, 2018, structured as a three-act concept album.",
    'ZUU': "ZUU is Denzel Curry's fourth studio album, released May 31, 2019, an homage to his hometown of Carol City, Florida.",
    'UNLOCKED': 'Collaborative EP with producer Kenny Beats, released February 7, 2020.',
    'ULTRAGROUND': 'Unreleased/scrapped project from Denzel Curry\'s career.',
    'Melt My Eyez, See Your Future': "Melt My Eyez, See Your Future is Denzel Curry's fifth studio album, released March 25, 2022.",
    'Designed By Angels': 'Unreleased/scrapped Denzel Curry project.',
    'KING OF THE MISCHIEVOUS SOUTH VOL 2': 'Sequel to King of the Mischievous South, released July 19, 2024.',
    'Strictly 4 The Scythe': "Strictly 4 The Scythe is Denzel Curry's newest studio album, released March 6, 2026.",
    'Ongoing': 'Songs without a confirmed era or still being worked on.',
    'Unknown Era': 'Miscellaneous material without a confirmed era.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'CuRRy Wuz Here',
    'King Remembered',
    'King of the Mischievous South',
    'Strictly 4 My R.V.I.D.X.R.Z.',
    'Before Nostalgic 64',
    'Mental Vendetta',
    'Nostalgic 64',
    '32 Zel/Planet Shrooms',
    'CUNT $WAB MAFIA',
    'Imperial',
    'TA13OO',
    'ZUU',
    'UNLOCKED',
    'ULTRAGROUND',
    'Melt My Eyez, See Your Future',
    'Designed By Angels',
    'KING OF THE MISCHIEVOUS SOUTH VOL 2',
    'Strictly 4 The Scythe',
    'Ongoing',
    'Unknown Era',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
