import type { ArtistConfig } from './types';

export const dongoldConfig: ArtistConfig = {
  slug: 'dongold',
  SITE_NAME: 'DONGOLD',
  SITE_DESCRIPTION: 'The Best Don Toliver Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/dongold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'dongold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#9333ea',
  artistLabel: 'Don Toliver',
  cardLetter: 'DON',
  logoUrl: '/logos/dongold.png',
  artistPhotoUrl: '/artists/dontoliver.jpg',

  getArtistName() {
    return 'Don Toliver';
  },

  CUSTOM_IMAGES: {
    'Before Space Age Pimping': '/dongold/eras/before-space-age-pimping.jpg',
    'Space Age Pimping Trilogy': '/dongold/eras/space-age-pimping-trilogy.jpg',
    'Pimp Olympics': '/dongold/eras/pimp-olympics.jpg',
    'Life Before Death': '/dongold/eras/life-before-death.jpg',
    'Playa Familia': '/dongold/eras/playa-familia.jpg',
    'Playa Familia 2': '/dongold/eras/playa-familia-2.jpg',
    'Donny Womack': '/dongold/eras/donny-womack.jpg',
    'JACKBOYS': '/dongold/eras/jackboys.jpg',
    'Heaven Or Hell': '/dongold/eras/heaven-or-hell.jpg',
    'Escapism': '/dongold/eras/escapism.jpg',
    'Life of a DON': '/dongold/eras/life-of-a-don.jpg',
    'Love Sick': '/dongold/eras/love-sick.jpg',
    'Hardstone Psycho': '/dongold/eras/hardstone-psycho.jpg',
    'JACKBOYS 2': '/dongold/eras/jackboys-2.jpg',
    'OCTANE': '/dongold/eras/octane.jpg',
    'DT6': '/dongold/eras/dt6.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Before Space Age Pimping': '04/09/2012',
    'Space Age Pimping Trilogy': '03/04/2015',
    'Pimp Olympics': '05/15/2015',
    'Life Before Death': '12/10/2016',
    'Playa Familia': '05/17/2017',
    'Playa Familia 2': '01/01/2018',
    'Donny Womack': '11/06/2017',
    'JACKBOYS': '12/27/2019',
    'Heaven Or Hell': '03/13/2020',
    'Escapism': '08/07/2020',
    'Life of a DON': '02/03/2023',
    'Love Sick': '01/31/2023',
    'Hardstone Psycho': '06/14/2024',
    'OCTANE': '07/12/2024',
    'JACKBOYS 2': '07/08/2025',
    'DT6': '01/30/2026',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Before Space Age Pimping',
    'Space Age Pimping Trilogy',
    'Pimp Olympics',
    'Life Before Death',
    'Playa Familia',
    'Playa Familia 2',
    'Donny Womack',
    'JACKBOYS',
    'Heaven Or Hell',
    'Escapism',
    'Life of a DON',
    'Love Sick',
    'Hardstone Psycho',
    'JACKBOYS 2',
    'OCTANE',
    'DT6',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: true,
};
