import type { ArtistConfig } from './types';

export const dongoldConfig: ArtistConfig = {
  slug: 'dongold',
  SITE_NAME: 'DONGOLD',
  SITE_DESCRIPTION: 'The Best Don Toliver Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/dongold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'dongold_',
  HARDCODED_SHEET_ID: '1qsO4SuzzB17d5orqbKWHsaQsRdk0lzTSF9rV2FwQf-Q',
  HARDCODED_SHEET_GID: '1535277716',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1qsO4SuzzB17d5orqbKWHsaQsRdk0lzTSF9rV2FwQf-Q/export?format=csv&gid=1891166449',
  accentColor: '#9333ea',
  artistLabel: 'Don Toliver',
  cardLetter: 'DON',
  logoUrl: '/logos/dongold.png',
  artistPhotoUrl: '/artists/dontoliver.jpg',

  getArtistName() {
    return 'Don Toliver';
  },

  CUSTOM_IMAGES: {
    'Before Space Age Pimping': '/dongold/eras/before-space-age-pimping.jpg',
    'Space Age Pimping Trilogy': '/dongold/eras/space-age-pimping-trilogy.jpg',
    'Pimp Olympics': '/dongold/eras/pimp-olympics.jpg',
    'Life Before Death': '/dongold/eras/life-before-death.jpg',
    'Playa Familia': '/dongold/eras/playa-familia.jpg',
    'Playa Familia 2': '/dongold/eras/playa-familia-2.jpg',
    'Donny Womack': '/dongold/eras/donny-womack.jpg',
    'JACKBOYS': '/dongold/eras/jackboys.jpg',
    'Heaven Or Hell': '/dongold/eras/heaven-or-hell.jpg',
    'Escapism': '/dongold/eras/escapism.jpg',
    'Life of a DON': '/dongold/eras/life-of-a-don.jpg',
    'Love Sick': '/dongold/eras/love-sick.jpg',
    'Hardstone Psycho': '/dongold/eras/hardstone-psycho.jpg',
    'JACKBOYS 2': '/dongold/eras/jackboys-2.jpg',
    'OCTANE': '/dongold/eras/octane.jpg',
    'DT6': '/dongold/eras/dt6.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Before Space Age Pimping': '04/09/2012',
    'Space Age Pimping Trilogy': '03/04/2015',
    'Pimp Olympics': '05/15/2015',
    'Life Before Death': '12/10/2016',
    'Playa Familia': '05/17/2017',
    'Playa Familia 2': '01/01/2018',
    'Donny Womack': '11/06/2017',
    'JACKBOYS': '12/27/2019',
    'Heaven Or Hell': '03/13/2020',
    'Escapism': '08/07/2020',
    'Life of a DON': '02/03/2023',
    'Love Sick': '01/31/2023',
    'Hardstone Psycho': '06/14/2024',
    'OCTANE': '07/12/2024',
    'JACKBOYS 2': '07/08/2025',
    'DT6': '01/30/2026',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Before Space Age Pimping': "Caleb Zackery \"Don\" Toliver (born June 12, 1994) is an American singer, rapper, and songwriter. Toliver was born and raised in Houston, Texas. His father was a rapper during the Swishahouse movement in the early 2000s, and would commonly play music around him growing up. As a young opera singer, he was bullied because of his passion, so he pursued rap. Don began rapping in 2010 by using the microphone on his PlayStation 3 to record songs. He began collaborating with his childhood friend Yung Josh in early 2014.",
    'Space Age Pimping Trilogy': "Space Age Pimping is a deleted trilogy of collaborative mixtapes with Yung Josh released on SoundCloud. The name \"Space Age Pimping\" likely comes from 8Ball & MJG's song of the same name. Little is known about Don's early work with Yung Josh because they deleted their old accounts due to running out of space for not paying for SoundCloud Pro.",
    'Pimp Olympics': "This project was mentioned in the description of the music video for \"Dear Summer / Global Wide Pimping\" released on October 24, 2015. Little is known about Don's early work with Yung Josh because they deleted their old accounts due to running out of space for not paying for SoundCloud Pro.",
    'Life Before Death': "Only physical copies exist of this lost EP. On December 10, 2016, Don personally handed out the disc to his friends and at a pop-up at a store called Lo-Fi from 4pm to 10pm. Some people are known to own the CD, but it hasn’t surfaced yet. There’s a few videos of him handing out the CD in New York on Yung Josh’s YouTube channel. Pictures of the tracklist confirm there are 5 songs on the EP with 2 bonus tracks.",
    'Playa Familia': "PLAYA FAMILIA is a collaborative mixtape by Houston artists YungJosh93 and Don Toliver. It was released on SoundCloud on May 17, 2017. The mixtape was preceded by two singles: “Play Me” which was released November 16, 2016, and “Magic & Bird” which released February 27, 2017.",
    'Playa Familia 2': "After the release of Playa Familia, Yung Josh and Don get together again to record several songs together for a second mixtape. At some point in 2018, the project was scrapped and Don began working on Donny Womack. \"Thot Hoe\" featuring Yung Josh was intended to be the lead single to Donny Womack, but was replaced by \"I Gotta.\" The two have not collaborated since, but they remain good friends to this day.",
    'Donny Womack': "According to Don, work for Donny Womack started about 6 or 7 months before the Miami sessions for ASTROWORLD. This is not his first studio album, as it is described as a commercial mixtape. Three early tracklists have leaked, reavealing that the following unreleased tracks were being considered: \"C4,\" \"Thrasher,\" \"Options,\" \"In The Field,\" \"My City,\" \"All I See,\" \"High No More,\" \"Stove,\" and \"Time.\" Donny Womack released the day before Don's breakout feature on ASTROWORLD.",
    'JACKBOYS': "Travis Scott founded Cactus Jack Records in 2017, and in February 2018 Sheck Wes was the first permanent signee. Don Toliver joined the collective on August 6, 2018, days afrer the release of ASTROWORLD. JACKBOYS is the collective's first collaborative compilation album. The project was first teased by Travis in an interview on October 3, 2019, and Don tweeted the album's title the following day. On November 29, 2019, about a month before its release, Travis released merch bundles with an album pre-order. The release date wasn't confirmed until the day before it dropped.",
    'Heaven Or Hell': "Don started working on his debut studio album in July 2018 at the Hawaii sessions for Travis Scott's album ASTROWORLD. \"After Party,\" \"Spaceship,\" and \"Candy\" were recorded in these sessions. \"Slippy Slide\" and \"Clap\" were both cut last-minute, as seen in a whiteboard where the final tracklist is being decided with Mike Dean. On November 24, 2020, a folder named \"Don Toliver Deluxe\" was seen on Mike Dean's computer, but nothing came of it.",
    'Escapism': "Don Toliver and Chase B worked together in sessions for JACKBOYS and Heaven Or Hell throughout 2019 and 2020. After Don's album released, Chase B wanted \"Cafeteria\" to be a single for his own producer album. Don suggested they drop a collab album since they have so much music together. Although the lead single was released, the idea was scrapped due to several album tracks leaking in August 2020. In Summer 2023, Chase B hinted at the album now being called BE VERY AFRAID.",
    'Life of a DON': "Don began teasing the album's title on his Instagram stories throughout 2021 after releasing the lead single in May. After releasing a second single, Don performed \"BOGUS\" live on July 31 in anticipation of the album's release. Life of a DON was originally meant to drop on September 3 with \"Theme Song\" as the first track. It is unknown why the tracklist was changed or why the album was pushed back. Many throwaways from this era are seen on whiteboards and computer screens in the \"Behind The Scenes\" documentary.",
    'Love Sick': "Love Sick's album title was first introduced by Don Toliver in April 2022. Prior to this, Don had already previewed four songs on social media, including “Time Heals All” and “No Pole.” On July 1, 2022, Don performed \"Rolling Stone\" live. The song appears in early tracklists along with other throwaways, but was cut last-minute. In the week leading up to the album's release, 7 visual episodes were released which would later make up the \"Love Sick\" short film. On the night of the album drop, Don teased a deluxe and went back in the studio for four days to release an additional 4 tracks.",
    'Hardstone Psycho': "In October 2023, Don first started teasing the new era by performing \"Bandit\" and \"It's Up\" during the European leg of the Love Sick tour. On November 16, 2023, Don retweeted a fan asking for Life of a DON 2. However, on March 17, 2024, the album title Hardstone Psycho was officially announced at Rolling Loud California when he performed \"Tore Up.\" The album was released on June 14, 2024, and a digital deluxe was released 4 days later including 4 new songs with features from Yeat and Lil Uzi Vert.",
    'JACKBOYS 2': "The sequel to the 2019 Cactus Jack collaborative project was first mentioned by Travis Scott at Summer Smash on June 15, 2024. An official announcement for JACKBOYS 2 was seen lighting up the side of a building in Hong Kong on March 19, 2025. The album released on July 13, 2025 and Don is featured on 5 tracks.",
    'OCTANE': "OCTANE is the upcoming studio album by singer Don Toliver, announced for release in 2025. The title was revealed through collaborations and merchandise, including one with Complex Con and another involving a new Reebok x BBC Icecream Board Flips collaboration.",
    'DT6': "On March 13, 2026 Don Toliver announced in an interview with Billboard at SXSW that he has begun working on his next album",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Before Space Age Pimping',
    'Space Age Pimping Trilogy',
    'Pimp Olympics',
    'Life Before Death',
    'Playa Familia',
    'Playa Familia 2',
    'Donny Womack',
    'JACKBOYS',
    'Heaven Or Hell',
    'Escapism',
    'Life of a DON',
    'Love Sick',
    'Hardstone Psycho',
    'JACKBOYS 2',
    'OCTANE',
    'DT6',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: true,
};
