import type { ArtistConfig } from './types';

export const dregoldConfig: ArtistConfig = {
  slug: 'dregold',
  SITE_NAME: 'DREGOLD',
  SITE_DESCRIPTION: 'The Best Dr. Dre Tracker In The World!',
  SITE_URL: 'https://vaultgold.net/dregold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'dregold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#e53e3e',
  artistLabel: 'Dr. Dre',
  cardLetter: 'DRE',
  logoUrl: '/logos/dregold.png',

  getArtistName(_eraName) { return 'Dr. Dre'; },

  CUSTOM_IMAGES: {
    "N.W.A. And The Posse": "https://i.ibb.co/v6vtw0vc/Nwafirstalbum.jpg",
    "Straight Outta Compton": "https://i.ibb.co/2YNM2mb0/NWAStraight-Outta-Compton600-Gb-2.jpg",
    "efiL4zaggiN": "https://i.ibb.co/0pVKTYcG/ab67616d0000b27377cf4557b2899021f216c8dd.jpg",
    "The Chronic": "https://i.ibb.co/4ZRkX8KH/Dr-Dre-The-Chronic.jpg",
    "Helter Skelter": "https://i.ibb.co/nNvsnsB9/Screenshot-2026-05-25-at-4-25-32-PM.png",
    "The Chronic II": "https://i.ibb.co/8LW3fn0M/lld2wwx6w40a1.png",
    "2001": "https://i.ibb.co/4ZNNbG7q/Dr-Dre-2001-1.jpg",
    "Break Up To Make Up": "https://i.ibb.co/QFwmCK6L/dre-snoop-1993.webp",
    "N.W.A. Reunion": "https://i.ibb.co/bgwTKd8N/IMG-4156.jpg",
    "Detox [V1]": "https://i.ibb.co/jkSv1MkM/IMG-4159.png",
    "Detox [V2]": "https://i.ibb.co/fdCtV29F/IMG-4177.png",
    "Detox [V3]": "https://i.ibb.co/7d79N6gs/IMG-4186.png",
    "Planets [V1]": "https://i.ibb.co/9kPCFjb3/IMG-4188.png",
    "Detox [V4]": "https://i.ibb.co/6RkFj8pm/IMG-4189.png",
    "Detox [V5]": "https://i.ibb.co/xSd6hwSd/IMG-4198.jpg",
    "Compton": "https://i.ibb.co/Fp7tWm8/dr-dre-compton-vinyl-record-rapbay-cover-74961.jpg",
    "Detox [V6]": "https://i.ibb.co/ZzKBpkQ9/IMG-4203.png",
    "JESUS IS KING: The Dr. Dre Version": "https://i.ibb.co/QFS24gkV/IMG-4206.jpg",
    "Detox [V7]": "https://i.ibb.co/mr3y7dCk/IMG-4208.png",
    "Missionary": "https://i.ibb.co/pj6R4Qr6/IMG-4209.jpg",
    "LP4": "https://i.ibb.co/N6vkwn6X/IMG-4212.png",
    "Planets [V2]": "https://i.ibb.co/yct1HRHw/IMG-4213.jpg",
    "The Wash": "https://i.ibb.co/dwZ4cwmd/image-2026-04-27-185921217.png",
  },

  ALBUM_RELEASE_DATES: {
    "N.W.A. And The Posse": "11/06/1987",
    "Straight Outta Compton": "01/25/1989",
    "100 Miles & Runnin'": "08/14/1990",
    "efiL4zaggiN": "05/28/1991",
    "The Chronic": "12/15/1992",
    "Helter Skelter": "??/??/????",
    "The Chronic II": "??/??/????",
    "2001": "11/16/1999",
    "The Wash": "11/20/2001",
    "Break Up To Make Up": "??/??/????",
    "N.W.A. Reunion": "??/??/????",
    "Detox [V1]": "??/??/????",
    "Detox [V2]": "??/??/????",
    "Detox [V3]": "??/??/????",
    "Planets [V1]": "??/??/????",
    "Detox [V4]": "??/??/????",
    "Detox [V5]": "??/??/????",
    "Compton": "08/07/2015",
    "Detox [V6]": "??/??/????",
    "JESUS IS KING: The Dr. Dre Version": "??/??/????",
    "Detox [V7]": "??/??/????",
    "Missionary": "??/??/????",
    "LP4": "??/??/????",
    "Planets [V2]": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By DREgold', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By DREgold': 'Leaks & Songs added by the owner of the site.',
  },
};
