import type { ArtistConfig } from './types';

export const dregoldConfig: ArtistConfig = {
  slug: 'dregold',
  SITE_NAME: 'DREGOLD',
  SITE_DESCRIPTION: 'The Best Dr. Dre Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/dregold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'dregold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/10_QK8xP-WCdrfO6RaIkhdDtYUXaM966e6D1xWD__iIo/export?format=csv&gid=2048130339',
  SHEET_URL_RECENT_PRODUCTION: 'https://docs.google.com/spreadsheets/d/10_QK8xP-WCdrfO6RaIkhdDtYUXaM966e6D1xWD__iIo/export?format=csv&gid=1876275343',
  accentColor: '#e53e3e',
  artistLabel: 'Dr. Dre',
  sheetCreator: 'G-Man Junior, Franki8000, Kali Kush, GrimR3xx, HighSpeedChase, OnlyTwentyCharacters, Loony',
  cardLetter: 'DRE',
  logoUrl: '/logos/dregold.png',
  artistPhotoUrl: '/artists/drdre.jpg',

  hasProductionTab: true,

  getArtistName(_eraName) { return 'Dr. Dre'; },

  CUSTOM_IMAGES: {
    // Production Projects tab
    "Eazy-Duz-It": "https://i.ibb.co/4nC7Dx4S/eazy-e-eazy-duz-it-cd-rapbay-97655.jpg",
    "No One Can Do It Better": "https://i.ibb.co/VWxFgK59/No-One-Can-Do-It-Better-big.jpg",
    "Doggystyle": "https://i.ibb.co/0yJbk9JC/61k-Llr-QWt-QL-UF1000-1000-QL80.jpg",
    "Eargasm": "https://i.ibb.co/svv3zVWk/270de453a3baf106fa65d840a94916bcc4ccf26b.jpg",
    "Murder Was the Case: The Soundtrack": "https://i.ibb.co/27BCYC9P/Snoop-Dogg-Murder-Was-the-Case.jpg",
    "Dogg Food": "https://i.ibb.co/1fsTzRrg/Dogg-Pound-Dogg-Food.jpg",
    "Dr. Dre Presents... The Aftermath": "https://i.ibb.co/1GvrGh7H/images.jpg",
    "Choices": "https://i.ibb.co/dwHbpYQn/R-34157635-1748892235-9153.jpg",
    "Hands-On, Hands-Off": "https://i.ibb.co/gMb2gSLB/Screenshot-2026-05-25-at-4-29-55-PM.png",
    "Untitled Nowl Album": "https://i.ibb.co/TMCZCmGz/Screenshot-2026-05-25-at-4-30-42-PM.png",
    "Sexy Dancer": "https://i.ibb.co/kVK2fqP3/Screenshot-2026-05-25-at-8-39-46-PM.png",
    "Untitled Serenade Album": "https://i.ibb.co/pvtcLnW0/Screenshot-2026-05-25-at-4-31-16-PM.png",
    "Untitled Sharief (AKA Killa Ben) Album": "https://i.ibb.co/Nng36LRj/Screenshot-2026-05-25-at-4-31-25-PM.png",
    "Thy Kingdom Come": "https://i.ibb.co/mFtSYxfc/R-25535383-1674342394-1423.jpg",
    "Who'z Who Rulez": "https://i.ibb.co/ycvk2QwN/Screenshot-2026-05-25-at-4-31-55-PM.png",
    "The Album": "https://i.ibb.co/mrczktJJ/Screenshot-2026-05-25-at-4-32-04-PM.png",
    "Untitled Sticky Fingaz Album": "https://i.ibb.co/zVGQkhxx/Screenshot-2026-05-25-at-4-33-04-PM.png",
    "Untitled The Last Emperor Album": "https://i.ibb.co/DHWd1pBr/Screenshot-2026-05-25-at-4-33-12-PM.png",
    "The Slim Shady LP": "https://i.ibb.co/GQjdtgDQ/Eminem-The-Slim-Shady-LP-CD-cover.jpg",
    "Hitt's Big Skore": "https://i.ibb.co/M5n9rtVH/IMG-4153.jpg",
    "Knoc's Landin'": "https://i.ibb.co/spwpzKBV/IMG-4154.jpg",
    "Deuce": "https://i.ibb.co/bRHgmD0j/IMG-4155.jpg",
    "The Marshall Mathers LP": "https://i.ibb.co/Mx3P9nJV/IMG-4157.jpg",
    "Restless": "https://i.ibb.co/v6XL3FS8/IMG-4158.jpg",
    "Untitled Shaunta Album": "https://i.ibb.co/nqVGVcV3/IMG-4160.jpg",
    "Melt Down Music": "https://i.ibb.co/6JRbGrV0/IMG-4161.jpg",
    "Untitled Ab-Liva Album": "https://i.ibb.co/Vc2Zwgc1/IMG-4162.jpg",
    "The Eminem Show": "https://i.ibb.co/vCPM1NcN/IMG-4163.jpg",
    "Oh My God": "https://i.ibb.co/whtZvHLy/IMG-4165.jpg",
    "Man vs. Machine": "https://i.ibb.co/tPFG92v1/IMG-4166.jpg",
    "The Wash (The Original Motion Picture Soundtrack)": "https://i.ibb.co/8DxZ3HLN/IMG-4167.jpg",
    "Love For Sale": "https://i.ibb.co/JRrL7994/IMG-4168.jpg",
    "Encore": "https://i.ibb.co/JFBD8f6n/IMG-4169.jpg",
    "Get Rich Or Die Tryin'": "https://i.ibb.co/mCV3WSZm/IMG-4170.jpg",
    "The Massacre": "https://i.ibb.co/4nMdvWf1/IMG-4171.png",
    "Untitled Antonio Album": "https://i.ibb.co/7tjV9mhq/IMG-4172.jpg",
    "The Documentary": "https://i.ibb.co/d4QttHMm/IMG-4173.jpg",
    "Untitled Ne-Yo Album": "https://i.ibb.co/G4q5Kdsv/IMG-4174.jpg",
    "The Big Bang": "https://i.ibb.co/Mk8yd3wF/IMG-4175.jpg",
    "Statlanta": "https://i.ibb.co/hFLptvP1/IMG-4176.jpg",
    "Dr. Dre & Timbaland Present: Hayes": "https://i.ibb.co/FbRr6FqJ/download-1.jpg",
    "The Soundtrack To My Life": "https://i.ibb.co/0pqTWkDb/IMG-4178.png",
    "Only Built 4 Cuban Linx... Pt. II": "https://i.ibb.co/4nKNJbVP/IMG-4179.png",
    "The Reformation": "https://i.ibb.co/4gVVZnvr/IMG-4180.jpg",
    "Here I Am": "https://i.ibb.co/r2pKdbPM/IMG-4181.jpg",
    "Untitled Dion Album": "https://i.ibb.co/s9gyPDs6/IMG-4182.jpg",
    "Blessed": "https://i.ibb.co/bRdVKXnJ/IMG-4183.jpg",
    "Untitled Joell Ortiz Album": "https://i.ibb.co/C3Xc5MtL/IMG-4184.jpg",
    "King Mathers": "https://i.ibb.co/C5zxFtpr/IMG-4185.png",
    "Relapse": "https://i.ibb.co/Y4GTg0qz/Relapse-album.jpg",
    "Relapse 2": "https://i.ibb.co/ZpHM1V0V/IMG-4191.png",
    "The R.E.D. Album": "https://i.ibb.co/mCqCJ9Vz/IMG-4190.png",
    "S.O.O.N. (Something Out of Nothing)": "https://i.ibb.co/3mw0PyBv/IMG-4892.jpg",
    "Recovery": "https://i.ibb.co/dsFxBBHm/IMG-4193.jpg",
    "The Marshall Mathers LP 2": "https://i.ibb.co/xtSLz6y1/IMG-4194.jpg",
    "good kid, m.A.A.d city": "https://i.ibb.co/3YvW46Lb/good-kid-m-A-A-d-city.jpg",
    "Kingmaker": "https://i.ibb.co/fdBpKBc8/IMG-4196.jpg",
    "Vehicle City": "https://i.ibb.co/1fZ8ptcR/IMG-4197.png",
    "Untitled Mez Album": "https://i.ibb.co/ynJc7ybT/IMG-4199.png",
    "Oxnard": "https://i.ibb.co/7Jh3thtj/IMG-4201.jpg",
    "Revival": "https://i.ibb.co/HfJJpZMD/IMG-4202.jpg",
    "Untitled K.A.A.N. Album": "https://i.ibb.co/DdR2zJv/IMG-4204.jpg",
    "Music To Be Murdered By": "https://i.ibb.co/QFYrmqPH/IMG-4205.jpg",
    "Music To Be Murdered By: Side B": "https://i.ibb.co/S4v9LjzY/IMG-4207.jpg",
    "Casablanco": "https://i.ibb.co/84mz53BD/IMG-4210.jpg",
    "Hot Water": "https://i.ibb.co/fzvdJTFh/IMG-4211.png",
    // Main Projects tab
    "N.W.A. And The Posse": "https://i.ibb.co/v6vtw0vc/Nwafirstalbum.jpg",
    "Straight Outta Compton": "https://i.ibb.co/2YNM2mb0/NWAStraight-Outta-Compton600-Gb-2.jpg",
    "efiL4zaggiN": "https://i.ibb.co/0pVKTYcG/ab67616d0000b27377cf4557b2899021f216c8dd.jpg",
    "The Chronic": "https://i.ibb.co/4ZRkX8KH/Dr-Dre-The-Chronic.jpg",
    "Helter Skelter": "https://i.ibb.co/nNvsnsB9/Screenshot-2026-05-25-at-4-25-32-PM.png",
    "The Chronic II": "https://i.ibb.co/8LW3fn0M/lld2wwx6w40a1.png",
    "2001": "https://i.ibb.co/4ZNNbG7q/Dr-Dre-2001-1.jpg",
    "Break Up To Make Up": "https://i.ibb.co/QFwmCK6L/dre-snoop-1993.webp",
    "N.W.A. Reunion": "https://i.ibb.co/bgwTKd8N/IMG-4156.jpg",
    "Detox [V1]": "https://i.ibb.co/jkSv1MkM/IMG-4159.png",
    "Detox [V2]": "https://i.ibb.co/fdCtV29F/IMG-4177.png",
    "Detox [V3]": "https://i.ibb.co/7d79N6gs/IMG-4186.png",
    "Planets [V1]": "https://i.ibb.co/9kPCFjb3/IMG-4188.png",
    "Detox [V4]": "https://i.ibb.co/6RkFj8pm/IMG-4189.png",
    "Detox [V5]": "https://i.ibb.co/xSd6hwSd/IMG-4198.jpg",
    "Compton": "https://i.ibb.co/Fp7tWm8/dr-dre-compton-vinyl-record-rapbay-cover-74961.jpg",
    "Detox [V6]": "https://i.ibb.co/ZzKBpkQ9/IMG-4203.png",
    "JESUS IS KING: The Dr. Dre Version": "https://i.ibb.co/QFS24gkV/IMG-4206.jpg",
    "Detox [V7]": "https://i.ibb.co/mr3y7dCk/IMG-4208.png",
    "Missionary": "https://i.ibb.co/pj6R4Qr6/IMG-4209.jpg",
    "LP4": "https://i.ibb.co/N6vkwn6X/IMG-4212.png",
    "Planets [V2]": "https://i.ibb.co/yct1HRHw/IMG-4213.jpg",
    "The Wash": "https://i.ibb.co/8DxZ3HLN/IMG-4167.jpg",
    // Era name aliases for tabs that use short names
    "100 Miles & Runnin'": "https://i.ibb.co/RktJV5fF/250px-NWA-100-Miles-And-Runnin.jpg",
    "The Aftermath": "https://i.ibb.co/1GvrGh7H/images.jpg",
    "Planets": "https://i.ibb.co/9kPCFjb3/IMG-4188.png",
  },

  ALBUM_RELEASE_DATES: {
    "N.W.A. And The Posse": "11/06/1987",
    "Straight Outta Compton": "01/25/1989",
    "100 Miles & Runnin'": "08/14/1990",
    "efiL4zaggiN": "05/28/1991",
    "The Chronic": "12/15/1992",
    "Helter Skelter": "??/??/????",
    "The Chronic II": "??/??/????",
    "2001": "11/16/1999",
    "The Wash": "11/20/2001",
    "Break Up To Make Up": "??/??/????",
    "N.W.A. Reunion": "??/??/????",
    "Detox [V1]": "??/??/????",
    "Detox [V2]": "??/??/????",
    "Detox [V3]": "??/??/????",
    "Planets [V1]": "??/??/????",
    "Detox [V4]": "??/??/????",
    "Detox [V5]": "??/??/????",
    "Compton": "08/07/2015",
    "Detox [V6]": "??/??/????",
    "JESUS IS KING: The Dr. Dre Version": "??/??/????",
    "Detox [V7]": "??/??/????",
    "Missionary": "??/??/????",
    "LP4": "??/??/????",
    "Planets [V2]": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    "N.W.A. And The Posse": "Compilation album credited to N.W.A. and the Posse, released in 1987 on Macola Records; N.W.A.'s first release and among Dr. Dre's earliest recorded work.",
    "Straight Outta Compton": "N.W.A.'s debut studio album, released January 25, 1989 on Ruthless Records; a landmark gangsta rap album co-produced by Dr. Dre.",
    "100 Miles & Runnin'": "N.W.A. EP released August 1990, the group's first release after Ice Cube's departure.",
    "efiL4zaggiN": "efiL4zaggiN (Niggaz4Life spelled backwards) is the second and final studio album by N.W.A., and the only N.W.A. album to not feature Ice Cube as a group member. The project is notable for its extremely dark sound, lyrics and subject matter such as rape and mutilation, teetering on horrorcore at some points. This is in stark contrast to other N.W.A. projects which are somewhat lighter in tone.",
    "The Chronic": "Dr. Dre's solo debut studio album, released December 15, 1992 on Death Row Records; established the G-funk sound and launched Snoop Dogg's career.",
    "Helter Skelter": "Helter Skelter was a scrapped collab album between Dr. Dre and Ice Cube, and was slated to release as the next Death Row Records album following Snoop Dogg's \"Doggystyle\" album. According to The D.O.C., Dre wanted to base the album off of post-apocalyptic themes, and asked The D.O.C. to read various novels on the apocalypse whilst writing verses on the album for him. Although the exact reason for scrapping the project is unknown, the final nail in the coffin was The D.O.C. leaving Death Row Records due to a dispute with Dre and reusing concepts and lyrics from tracks intended for Helter Skelter on his own album of the same name in January 1996. The album's lead single, Natural Born Killaz, was released on the Murder Was The Case soundtrack in 1994.",
    "The Chronic II": "Cover by imrobtyler. The title is not a typo. The Chronic II: A New World Odor (Poppa's Got A Brand New Funk) was the working title of Compton rapper/producer Dr. Dre's planned sophomore studio album. This version of the album was scrapped once Dre left Death Row.",
    "2001": "2001 (otherwise known as Chronic 2001 or simply The Chronic 2) is the sophomore studio album of Compton rapper/producer Dr. Dre.",
    "The Wash": "Soundtrack album for the film The Wash, starring Dr. Dre and Snoop Dogg, released November 20, 2001.",
    "Break Up To Make Up": "On August 8th 1997 during an interview with MTV Snoop Dogg had announced that he would be releasing his second collaboration album with Dr. Dre on July 4th 1998 titled \"Break Up To Make Up.\" Beyond a release date and the title track almost nothing is known about this album as it did not release and was never mentioned beyond this singular interview.",
    "N.W.A. Reunion": "In 1999, the members of N.W.A. (aside from Eazy-E & DJ Yella) would record the song \"Chin Check\" for the soundtrack of Ice Cube's movie 'Next Friday'. This song sparked the idea of an N.W.A. reunion album, which began being teased after the soundtrack's release. Snoop Dogg would take the place of Eazy-E in this reunion, which was Dre's idea according to MC Ren. A 2nd N.W.A. track called \"Hello\" would release on Ice Cube's album 'War & Peace Vol. 2 (The Peace Disc)', and would feature verses from Dre and MC Ren as well as ad-libs from Snoop Dogg. As time went by, nothing was heard from the album, and by 2003 \"Chin Check\" would be put on a re-issue of the N.W.A. Greatest Hits album whilst MC Ren said that nothing was going on with the reunion. The main title this album goes by is 'Not These Niggaz Again' which comes from a Dre line on Xzibit's song \"X\" that was later repeated on Eminem's song \"Bitch Please II\".",
    "Detox [V1]": "The first era of Detox. Off the heels from 2001 Dre took some time to help bring up Eminem and Xzibit's albums and work with other artists, of course while working on his then supposed to be third album, Detox. Dre himself would state that Detox would be a \"hip hop musical\" of sorts, conceptualized about a hitman. However, the concept was scrapped a couple years after. Not much material has leaked from this era but at the time Dre was promoting this as his final album before retiring (even claiming that the verse he recorded for Where I'm From would be his last verse ever). In 2004, Dre also mentioned he wanted to put out up to 12 singles for the album as well, however later that year he seems to have restarted development once again. Songs such as Want Me Back would leave a legacy for Dre.",
    "Detox [V2]": "Detox V2 was quite the busy time for Dre and was the start of the many delays that would happen to Detox. During this time Dre would start to branch out for working with artists and would change up the Detox sound. This was also the era when his working relationship with JAŸ-Z really came to a start. We don't have many leaks from this time but from what we know this was a promising iteration of Detox. This era also brings back The D.O.C. as one of the main team members, writing for both Dr. Dre and Snoop Dogg.",
    "Detox [V3]": "One of the more lesser heard from eras of Detox is the third iteration, it was mostly carried by Bishop Lamont & Hayes with Slim the Mobster only getting involved near the end of this version around 2007. Dre was noticeably quiet on the released music side with not much content involving his name coming out. This version of Detox would also start to introduce different producers into the sound such as Jake One and DJ Khalil along with working with other artists such as T.I. & Rain 910. Lastly, this era would also introduce Sly Pyper, Dre's most underrated Aftermath artist.",
    "Planets [V1]": "Dre started work in 2008 on a conceptual type album called Planets which would be a surround sound like instrumental album. This project was mentioned once and never again so who knows what happened to it.",
    "Detox [V4]": "The most wanted version of Detox. Coming out of \"Relapse\" sessions \"Detox\" is finally put into full focus by Dr. Dre, and the most extensive sessions are held through this period. The sound of the project switched throughout the 3 years this version was being developed, going from the classic 2000's Dr. Dre sound into a more experimental electronic sound by 2010-2011. Very late into this version, Kendrick Lamar started working with Dre for both Detox and his own solo project. Singles are released and the album comes the closest it ever did to releasing, but ultimately burns out and Dre steps back from working on his own music again in 2011.",
    "Detox [V5]": "Taking a step back from solo music Dre focuses heavily on ushering in a new era of Afermath artists while giving some side time to another version of Detox. From this stretch of time emerges Jon Connor, Kendrick Lamar and the formation of the ICU. Though this version of Detox didn't bear much fruit it morphed into what we now know as Compton. The album \"Thanks To My Patients For Your Patience\" was also being made, speculated just to be a bunch of bonus songs for the long wait for Detox, or a sister project.",
    "Compton": "Inspired by working on \"Straight Outta Compton\" and the memories of his early career, Dr. Dre works on \"Compton\", first intended as a tie-in soundtrack for the movie but evolving to take its place as his long-awaited third studio album.",
    "Detox [V6]": "Following the release of Compton, Dr. Dre enters a semi-retirement from solo music, mainly focusing on supporting new Aftermath signees and only sparatically working on music himself. However, Detox was still being made (being brought back after Compton released), but wasn't the main focus. In 2018, ESPN reporter Chris Haynes asked Dr. Dre is Detox would be coming out, and Dre's response to him was \"I'm working on a couple songs right now. We'll see\", meaning the title was still likely in use.",
    "JESUS IS KING: The Dr. Dre Version": "The release of JESUS IS KING was met with mixed reviews from fans and critics. Kanye then took to Twitter to announce that he was working on a new album with Dr. Dre. Initially conceived as a remix album, it eventually grew to incorporate mainly unreleased material. During the #WESTDAYEVER campaign, Kanye did on Twitter in 2020, it was supposed to release officially, but never did. It ended up being scrapped sometime in 2020, as stated by producer Dem Jointz. Kanye posted the cover in 2022, which is assumed to be for the album.",
    "Detox [V7]": "The seventh iteration of the ever delayed Detox, this era starts a new phase where Dre might be at some of his busiest. While working on Detox he was also juggling Casablanco, Missionary, Hot Water, JESUS IS KING: The Dr. Dre Version, working with Eminem and whatever other secret things he has his hands on.",
    "Missionary": "Collaborative album between Dr. Dre and Snoop Dogg, released November 2024 and produced entirely by Dre.",
    "LP4": "It's unknown what solo project Dre has been working on since 2022, however we know that the \"Detox\" name likely isn't being used anymore. Nothing much is known.",
    "Planets [V2]": "Later stage of the rumored Planets project; details on its contents remain scarce.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  // Explicit order avoids JS hoisting integer-like keys (e.g. "2001") to the front of Object.keys()
  ALBUM_ORDER: [
    "N.W.A. And The Posse",
    "Straight Outta Compton",
    "100 Miles & Runnin'",
    "efiL4zaggiN",
    "The Chronic",
    "Helter Skelter",
    "The Chronic II",
    "2001",
    "The Wash",
    "Break Up To Make Up",
    "N.W.A. Reunion",
    "Detox [V1]",
    "Detox [V2]",
    "Detox [V3]",
    "Planets [V1]",
    "Detox [V4]",
    "Detox [V5]",
    "Compton",
    "Detox [V6]",
    "JESUS IS KING: The Dr. Dre Version",
    "Detox [V7]",
    "Missionary",
    "LP4",
    "Planets [V2]",
  ],
  hasCompsTab: false,
  hasConcertsTab: false,
  hasSubAlbumsTab: false,
  productionSecond: true,

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By DREgold', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By DREgold': 'Leaks & Songs added by the owner of the site.',
  },
};
