import type { ArtistConfig } from './types';

export const drizzygoldConfig: ArtistConfig = {
  slug: 'drizzygold',
  SITE_NAME: 'DRIZZYGOLD',
  SITE_DESCRIPTION: 'The Best Drake Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/drizzygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'drizzygold_',
  HARDCODED_SHEET_ID: '1v55XAPLzw1iuWxH1OQKajCIYPhW2BXcLoV4mXDZ55DI',
  HARDCODED_SHEET_GID: '755606328',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: `https://docs.google.com/spreadsheets/d/1v55XAPLzw1iuWxH1OQKajCIYPhW2BXcLoV4mXDZ55DI/export?format=csv&gid=494030977`,
  accentColor: '#b8860b',
  artistLabel: 'Drake',
  cardLetter: 'OVO',
  logoUrl: '/logos/drizzygold.png',

  getArtistName(_eraName) { return 'Drake'; },

  CUSTOM_IMAGES: {
    "Before So Far Gone": "https://i.ibb.co/FbMLhG39/drake-throughout-the-years-2007-2024-v0-u4scurc0gu1d1.webp",
    "So Far Gone": "https://i.ibb.co/23MLhymR/Drake-So-Far-Gone-cover.png",
    "We Are Young Money": "https://i.ibb.co/Q7q6L50Z/Young-Money-We-Are-Young-Money.png",
    "Thank Me Later": "https://i.ibb.co/7xCrrG7L/Drake-Thank-Me-Later-cover.jpg",
    "It's Never Enough": "https://i.ibb.co/twCFkB4R/cd-ITSNEVERENOUGHfront.webp",
    "Take Care": "https://i.ibb.co/LdvpSkm6/Drake-Take-Care-cover.jpg",
    "Posthumous Aaliyah Project": "https://i.ibb.co/BHC6S0z5/Enough-Said-cover-art.jpg",
    "Nothing Was The Same": "https://i.ibb.co/DDngN5ZN/NWTS.jpg",
    "If You're Reading This It's Too Late": "https://i.ibb.co/XZM3C3D5/if-youre-reading-this-its-too-late.jpg",
    "What A Time To Be Alive": "https://i.ibb.co/sXd5zd7/WATTBA.jpg",
    "Wolves": "https://i.ibb.co/219R9QGq/wolves.jpg",
    "Views": "https://i.ibb.co/7tWvzVHN/Drake-Views-cover.jpg",
    "More Life": "https://i.ibb.co/jZZ8hPrL/Drake-More-Life-cover.jpg",
    "Scorpion [V1]": "https://i.ibb.co/Knx1J4c/scoripion-V1.jpg",
    "Scorpion [V2]": "https://i.ibb.co/pjRFZjHR/Scorpion-by-Drake.jpg",
    "What A Time To Be Alive 2": "https://i.ibb.co/W4wLnHH9/WATTBA2.webp",
    "Certified Lover Boy [V1]": "https://i.ibb.co/mmLBvYk/CLBV1.webp",
    "Certified Lover Boy [V2]": "https://i.ibb.co/jqyfXDF/Drake-Certified-Lover-Boy.png",
    "Honestly, Nevermind": "https://i.ibb.co/PBPhRy5/Honestly-Nevermind-Drake.png",
    "Her Loss": "https://i.ibb.co/nq3Mt2TS/Drake-and-21-Savage-Her-Loss.png",
    "For All The Dogs": "https://i.ibb.co/991mxf4v/Drake-For-All-The-Dogs.png",
    "Scary Hours 3": "https://i.ibb.co/m5xCZN1W/attachment-drake-scary-hours-3-cover.jpg",
    "100 GIGS": "https://i.ibb.co/4Zsk4MmL/Drake-100-Gigs.png",
    "$ome $exy $ongs 4 U": "https://i.ibb.co/G33GRf3v/SSSFU.jpg",
    "ICEMAN [V1]": "https://i.ibb.co/6R3dhyc4/Iceman-V1.webp",
    "ICEMAN [V2]": "https://i.ibb.co/Fb33KRt5/Iceman-V2.jpg",
    "Scorpion": "https://i.ibb.co/pjRFZjHR/Scorpion-by-Drake.jpg",
  },

  ALBUM_RELEASE_DATES: {
    "Before So Far Gone": "??/??/????",
    "So Far Gone": "02/13/2009",
    "We Are Young Money": "12/21/2009",
    "Thank Me Later": "06/15/2010",
    "It's Never Enough": "??/??/????",
    "Take Care": "11/15/2011",
    "Posthumous Aaliyah Project": "??/??/????",
    "Nothing Was The Same": "09/24/2013",
    "If You're Reading This It's Too Late": "02/13/2015",
    "What A Time To Be Alive": "09/20/2015",
    "Wolves": "??/??/????",
    "Views": "04/29/2016",
    "More Life": "03/18/2017",
    "Scorpion [V1]": "??/??/????",
    "Scorpion [V2]": "06/29/2018",
    "What A Time To Be Alive 2": "??/??/????",
    "Certified Lover Boy [V1]": "??/??/????",
    "Certified Lover Boy [V2]": "09/03/2021",
    "Honestly, Nevermind": "06/17/2022",
    "Her Loss": "11/04/2022",
    "For All The Dogs": "10/06/2023",
    "Scary Hours 3": "??/??/????",
    "100 GIGS": "??/??/????",
    "$ome $exy $ongs 4 U": "02/14/2025",
    "ICEMAN [V1]": "??/??/????",
    "ICEMAN [V2]": "??/??/????",
    "Unknown": "??/??/????",
  },

  HIDDEN_ALBUMS: ["Unknown", "Scary Hours 3"],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  loadingScreens: [
    { id: 'none', label: 'None', type: 'none' },
    { id: 'shuffle', label: 'Shuffle', type: 'none' },
    { id: 'takecare', label: 'Take Care', type: 'gif', url: 'https://i.ibb.co/pBtLbGHy/IMG-4149.gif' },
    { id: 'thankmelater', label: 'Thank Me Later', type: 'gif', url: 'https://i.ibb.co/wXCBygN/IMG-4148.gif' },
    { id: 'nwts', label: 'Nothing Was the Same', type: 'gif', url: 'https://i.ibb.co/fGPG3QVC/IMG-4147.gif' },
    { id: 'clb', label: 'Certified Lover Boy', type: 'gif', url: 'https://i.ibb.co/j279Kz5/CLB.gif' },
    { id: 'honestlynevermind', label: 'Honestly Nevermind', type: 'gif', url: 'https://i.ibb.co/0p3H4Tmy/IMG-4218.gif' },
    { id: 'iyrtitl', label: "If You're Reading This It's Too Late", type: 'gif', url: 'https://i.ibb.co/T9vx1kR/IYRTITL.gif' },
    { id: 'herloss', label: 'Her Loss', type: 'gif', url: 'https://i.ibb.co/yn42p7cQ/her-loss.gif' },
    { id: 'morelife', label: 'More Life', type: 'gif', url: 'https://i.ibb.co/bcmf1WZ/more-life.gif' },
    { id: 'scorpion', label: 'Scorpion', type: 'gif', url: 'https://i.ibb.co/vCKB4xZ1/Scorpion.gif' },
    { id: 'sofargone', label: 'So Far Gone', type: 'gif', url: 'https://i.ibb.co/H5J3vbN/sfg.gif' },
    { id: 'views', label: 'Views', type: 'gif', url: 'https://i.ibb.co/SwmyNq2Y/views.gif' },
  ],

  ERA_MAPPINGS: { "ICEMAN": "ICEMAN [V2]", "Scary Hours 3": "For All The Dogs" },
  hasCompsTab: false,
  hasConcertsTab: false,
  hasSubAlbumsTab: false,

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By DRIZZYgold', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By DRIZZYgold': 'Leaks & Songs added by the owner of the site.',
  },
};
