import type { ArtistConfig } from './types';

export const fiftygoldConfig: ArtistConfig = {
  slug: 'fiftygold',
  SITE_NAME: 'FIFTYGOLD',
  SITE_DESCRIPTION: 'The Best 50 Cent Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/fiftygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'fiftygold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#1d4ed8',
  artistLabel: '50 Cent',
  cardLetter: '50',
  logoUrl: '/logos/fiftygold.webp',
  artistPhotoUrl: '/artists/50cent.webp',

  getArtistName() {
    return '50 Cent';
  },

  CUSTOM_IMAGES: {
    'Before Power Of The Dollar': '/fiftygold/eras/before-power-of-the-dollar.jpg',
    'Power Of The Dollar': '/fiftygold/eras/power-of-the-dollar.jpg',
    "Get Rich Or Die Tryin'": '/fiftygold/eras/get-rich-or-die-tryin.jpg',
    '8 Mile Soundtrack': '/fiftygold/eras/8-mile-soundtrack.jpg',
    'Beg For Mercy': '/fiftygold/eras/beg-for-mercy.jpg',
    'The Massacre': '/fiftygold/eras/the-massacre.jpg',
    "Get Rich Or Die Tryin' OST": '/fiftygold/eras/get-rich-or-die-tryin-ost.jpg',
    'The Re-Up': '/fiftygold/eras/the-re-up.jpg',
    'Curtis': '/fiftygold/eras/curtis.jpg',
    'Terminate On Sight': '/fiftygold/eras/terminate-on-sight.jpg',
    'Before I Self Destruct': '/fiftygold/eras/before-i-self-destruct.jpg',
    'Black Magic': '/fiftygold/eras/black-magic.jpg',
    'Street King: Immortal [V1]': '/fiftygold/eras/street-king-immortal-v1.jpg',
    'Street King: Immortal [V2]': '/fiftygold/eras/street-king-immortal-v2.jpg',
    'Animal Ambition': '/fiftygold/eras/animal-ambition.jpg',
    'LP6': '/fiftygold/eras/lp6.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Before Power Of The Dollar': '??/??/????',
    'Power Of The Dollar': '09/12/2000',
    "Get Rich Or Die Tryin'": '02/06/2003',
    '8 Mile Soundtrack': '10/29/2002',
    'Beg For Mercy': '11/14/2003',
    'The Massacre': '03/03/2005',
    "Get Rich Or Die Tryin' OST": '11/08/2005',
    'The Re-Up': '??/??/????',
    'Curtis': '09/11/2007',
    'Terminate On Sight': '07/01/2008',
    'Before I Self Destruct': '11/09/2009',
    'Black Magic': '??/??/????',
    'Street King: Immortal [V1]': '??/??/????',
    'Street King: Immortal [V2]': '??/??/????',
    'Animal Ambition': '06/03/2014',
    'LP6': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Before Power Of The Dollar': 'Early scrapped recordings from 50 Cent\'s teenage years and early Columbia Records sessions, before Power Of The Dollar.',
    'Power Of The Dollar': "Power Of The Dollar is the unreleased original debut album by 50 Cent, it was meant to drop on July 4th, 2000 but was not released due to 50 Cent getting shot 9 times.",
    "Get Rich Or Die Tryin'": "Get Rich Or Die Trying is the first studio album by New York rapper 50 Cent, and is executive produced by Compton rapper/producer Dr. Dre and Detroit rapper Eminem.",
    '8 Mile Soundtrack': "A soundtrack that was made alongside the 2002 semi-autobiographical movie 8 Mile, starring Eminem.",
    'Beg For Mercy': "Beg for Mercy is the debut studio album by American rap group G-Unit, released through Interscope Records and 50 Cent's G-Unit Records. The album was released on November 14, 2003, nine months after 50 Cent's successful debut album Get Rich or Die Tryin'.",
    'The Massacre': "After 50 released his monstrous debut in 2003, demand was high for 50 content. He would help his fellow G-Unit members get off the ground before releasing The Massacre in 2005. According to 50, the album had a bit of a different direction at first, focusing more on imperfections and with more generally soft content on the album then release, at least for the singles. However, after giving some songs the The Game for \"The Documentary\", he changed his direction and got songs like \"Candy Shop\" and \"Just A Lil' Bit\" among others on the album. The album was supposed to come out in February 2005, however this was delayed to give Game's Documentary more breathing room. 50 was quite unhappy with this and leaked Disco Inferno early, along with Candy Shop months later.",
    "Get Rich Or Die Tryin' OST": "Get Rich or Die Tryin': Music from and Inspired by the Motion Picture is the soundtrack to the 2005 film of the same name, released on November 8, 2005, on Interscope Records and 50 Cent's G-Unit Records. It features artists on the G-Unit label such as 50 Cent (who also executive produced the album), Lloyd Banks, Young Buck, Tony Yayo, Olivia, and Mobb Deep.",
    'The Re-Up': "In early 2006, Eminem would sign Ca$his & Bobby Creekwater to Shady Records. The Re-Up was originally supposed to be a mixtape, until Eminem liked the material enough to want to turn it into a compilation so it could give Stat, Bobby & Ca$his a \"real boost\".",
    'Curtis': '50 Cent\'s third studio album, released September 11, 2007, amid a much-publicized sales competition against Kanye West\'s Graduation.',
    'Terminate On Sight': "T.O.S. (Terminate on Sight) is the second and final studio album by rap group G-Unit. It was the group's first album in five years since their previous album, Beg for Mercy. The title of the album was originally announced to be Shoot to Kill and then Lock & Load, with the eventual name being Terminate on Sight. The album was originally scheduled to be released on June 24, 2008, but was rescheduled to July 1.",
    'Before I Self Destruct': '50 Cent\'s fourth studio album, released November 9, 2009, accompanied by a direct-to-DVD film of the same name.',
    'Black Magic': "In a Contactmusic.com interview, Jackson said he was working on a Eurodance album, Black Magic, inspired by European nightclubs: \"First they played hip-hop which suddenly changed to uptempo songs, known as Eurodance\". He later said he had changed his next album to The Return of the Heartless Monster after writing different material when he returned home from the Invitation Tour in 2010, shelving Black Magic.",
    'Street King: Immortal [V1]': "50 Cent announced the album and it was stated to be a more uplifting and postive project compared to his previous gangster related albums. Unfortunately this album never got to see the light of day.",
    'Street King: Immortal [V2]': 'Later reworked version of Street King Immortal, which went through nearly a decade of delays before being officially scrapped in 2021.',
    'Animal Ambition': '50 Cent\'s fifth studio album, released June 3, 2014, put out independently after leaving Interscope.',
    'LP6': 'Working title for 50 Cent\'s long-rumored sixth studio album, which has yet to be released.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Before Power Of The Dollar',
    'Power Of The Dollar',
    "Get Rich Or Die Tryin'",
    '8 Mile Soundtrack',
    'Beg For Mercy',
    'The Massacre',
    "Get Rich Or Die Tryin' OST",
    'The Re-Up',
    'Curtis',
    'Terminate On Sight',
    'Before I Self Destruct',
    'Black Magic',
    'Street King: Immortal [V1]',
    'Street King: Immortal [V2]',
    'Animal Ambition',
    'LP6',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
  hasSubAlbumsTab: false,
};
