import type { ArtistConfig } from './types';

export const fiftygoldConfig: ArtistConfig = {
  slug: 'fiftygold',
  SITE_NAME: 'FIFTYGOLD',
  SITE_DESCRIPTION: 'The Best 50 Cent Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/fiftygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'fiftygold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#1d4ed8',
  artistLabel: '50 Cent',
  cardLetter: '50',
  logoUrl: '/logos/fiftygold.webp',
  artistPhotoUrl: '/artists/50cent.webp',

  getArtistName() {
    return '50 Cent';
  },

  CUSTOM_IMAGES: {
    'Before Power Of The Dollar': '/fiftygold/eras/before-power-of-the-dollar.jpg',
    'Power Of The Dollar': '/fiftygold/eras/power-of-the-dollar.jpg',
    "Get Rich Or Die Tryin'": '/fiftygold/eras/get-rich-or-die-tryin.jpg',
    '8 Mile Soundtrack': '/fiftygold/eras/8-mile-soundtrack.jpg',
    'Beg For Mercy': '/fiftygold/eras/beg-for-mercy.jpg',
    'The Massacre': '/fiftygold/eras/the-massacre.jpg',
    "Get Rich Or Die Tryin' OST": '/fiftygold/eras/get-rich-or-die-tryin-ost.jpg',
    'The Re-Up': '/fiftygold/eras/the-re-up.jpg',
    'Curtis': '/fiftygold/eras/curtis.jpg',
    'Terminate On Sight': '/fiftygold/eras/terminate-on-sight.jpg',
    'Before I Self Destruct': '/fiftygold/eras/before-i-self-destruct.jpg',
    'Black Magic': '/fiftygold/eras/black-magic.jpg',
    'Street King: Immortal [V1]': '/fiftygold/eras/street-king-immortal-v1.jpg',
    'Street King: Immortal [V2]': '/fiftygold/eras/street-king-immortal-v2.jpg',
    'Animal Ambition': '/fiftygold/eras/animal-ambition.jpg',
    'LP6': '/artists/50cent.webp',
  },

  ALBUM_RELEASE_DATES: {
    'Before Power Of The Dollar': '??/??/????',
    'Power Of The Dollar': '09/12/2000',
    "Get Rich Or Die Tryin'": '02/06/2003',
    '8 Mile Soundtrack': '10/29/2002',
    'Beg For Mercy': '11/14/2003',
    'The Massacre': '03/03/2005',
    "Get Rich Or Die Tryin' OST": '11/08/2005',
    'The Re-Up': '??/??/????',
    'Curtis': '09/11/2007',
    'Terminate On Sight': '07/01/2008',
    'Before I Self Destruct': '11/09/2009',
    'Black Magic': '??/??/????',
    'Street King: Immortal [V1]': '??/??/????',
    'Street King: Immortal [V2]': '??/??/????',
    'Animal Ambition': '06/03/2014',
    'LP6': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Before Power Of The Dollar',
    'Power Of The Dollar',
    "Get Rich Or Die Tryin'",
    '8 Mile Soundtrack',
    'Beg For Mercy',
    'The Massacre',
    "Get Rich Or Die Tryin' OST",
    'The Re-Up',
    'Curtis',
    'Terminate On Sight',
    'Before I Self Destruct',
    'Black Magic',
    'Street King: Immortal [V1]',
    'Street King: Immortal [V2]',
    'Animal Ambition',
    'LP6',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
