import type { ArtistConfig } from './types';

export const fiftygoldConfig: ArtistConfig = {
  slug: 'fiftygold',
  SITE_NAME: 'FIFTYGOLD',
  SITE_DESCRIPTION: 'The Best 50 Cent Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/fiftygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'fiftygold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#1d4ed8',
  artistLabel: '50 Cent',
  cardLetter: '50',
  logoUrl: '/logos/fiftygold.webp',
  artistPhotoUrl: '/artists/50cent.webp',

  getArtistName() {
    return '50 Cent';
  },

  CUSTOM_IMAGES: {
    'Before Power Of The Dollar': '/fiftygold/eras/before-power-of-the-dollar.jpg',
    'Power Of The Dollar': '/fiftygold/eras/power-of-the-dollar.jpg',
    "Get Rich Or Die Tryin'": '/fiftygold/eras/get-rich-or-die-tryin.jpg',
    '8 Mile Soundtrack': '/fiftygold/eras/8-mile-soundtrack.jpg',
    'Beg For Mercy': '/fiftygold/eras/beg-for-mercy.jpg',
    'The Massacre': '/fiftygold/eras/the-massacre.jpg',
    "Get Rich Or Die Tryin' OST": '/fiftygold/eras/get-rich-or-die-tryin-ost.jpg',
    'The Re-Up': '/fiftygold/eras/the-re-up.jpg',
    'Curtis': '/fiftygold/eras/curtis.jpg',
    'Terminate On Sight': '/fiftygold/eras/terminate-on-sight.jpg',
    'Before I Self Destruct': '/fiftygold/eras/before-i-self-destruct.jpg',
    'Black Magic': '/fiftygold/eras/black-magic.jpg',
    'Street King: Immortal [V1]': '/fiftygold/eras/street-king-immortal-v1.jpg',
    'Street King: Immortal [V2]': '/fiftygold/eras/street-king-immortal-v2.jpg',
    'Animal Ambition': '/fiftygold/eras/animal-ambition.jpg',
    'LP6': '/artists/50cent.webp',
  },

  ALBUM_RELEASE_DATES: {
    'Before Power Of The Dollar': '??/??/????',
    'Power Of The Dollar': '09/12/2000',
    "Get Rich Or Die Tryin'": '02/06/2003',
    '8 Mile Soundtrack': '10/29/2002',
    'Beg For Mercy': '11/14/2003',
    'The Massacre': '03/03/2005',
    "Get Rich Or Die Tryin' OST": '11/08/2005',
    'The Re-Up': '??/??/????',
    'Curtis': '09/11/2007',
    'Terminate On Sight': '07/01/2008',
    'Before I Self Destruct': '11/09/2009',
    'Black Magic': '??/??/????',
    'Street King: Immortal [V1]': '??/??/????',
    'Street King: Immortal [V2]': '??/??/????',
    'Animal Ambition': '06/03/2014',
    'LP6': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Before Power Of The Dollar': 'Early scrapped recordings from 50 Cent\'s teenage years and early Columbia Records sessions, before Power Of The Dollar.',
    'Power Of The Dollar': '50 Cent\'s shelved debut album, recorded for Columbia Records around 1999-2000. The single "How To Rob" caused controversy, and the album was scrapped after he was shot in 2000.',
    "Get Rich Or Die Tryin'": '50 Cent\'s official debut studio album, released February 6, 2003 on Shady/Aftermath/Interscope. Largely produced by Dr. Dre and Eminem, it became one of the best-selling hip-hop albums of the decade.',
    '8 Mile Soundtrack': 'Soundtrack to the 2002 film 8 Mile starring Eminem, featuring 50 Cent\'s song "Wanksta."',
    'Beg For Mercy': 'Debut studio album by G-Unit (50 Cent, Lloyd Banks, and Tony Yayo), released November 14, 2003.',
    'The Massacre': '50 Cent\'s second studio album, released March 3, 2005, spawning the hits "Candy Shop" and "Disco Inferno."',
    "Get Rich Or Die Tryin' OST": 'Soundtrack album for the 2005 semi-biographical film of the same name starring 50 Cent, released November 2005.',
    'The Re-Up': 'G-Unit compilation album featuring Mobb Deep, Young Buck, and other affiliates, released in December 2006.',
    'Curtis': '50 Cent\'s third studio album, released September 11, 2007, amid a much-publicized sales competition against Kanye West\'s Graduation.',
    'Terminate On Sight': 'Second and final G-Unit studio album, also known as T.O.S., released July 1, 2008.',
    'Before I Self Destruct': '50 Cent\'s fourth studio album, released November 9, 2009, accompanied by a direct-to-DVD film of the same name.',
    'Black Magic': 'Shelved 50 Cent album exploring dance and rock influences; recorded but ultimately never officially released.',
    'Street King: Immortal [V1]': 'Early version of Street King Immortal, 50 Cent\'s long-delayed sixth album first planned for release around 2011-2012.',
    'Street King: Immortal [V2]': 'Later reworked version of Street King Immortal, which went through nearly a decade of delays before being officially scrapped in 2021.',
    'Animal Ambition': '50 Cent\'s fifth studio album, released June 3, 2014, put out independently after leaving Interscope.',
    'LP6': 'Working title for 50 Cent\'s long-rumored sixth studio album, which has yet to be released.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Before Power Of The Dollar',
    'Power Of The Dollar',
    "Get Rich Or Die Tryin'",
    '8 Mile Soundtrack',
    'Beg For Mercy',
    'The Massacre',
    "Get Rich Or Die Tryin' OST",
    'The Re-Up',
    'Curtis',
    'Terminate On Sight',
    'Before I Self Destruct',
    'Black Magic',
    'Street King: Immortal [V1]',
    'Street King: Immortal [V2]',
    'Animal Ambition',
    'LP6',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
