import type { ArtistConfig } from './types';

export const futuregoldConfig: ArtistConfig = {
  slug: 'futuregold',
  SITE_NAME: 'FUTUREGOLD',
  SITE_DESCRIPTION: 'The Best Future Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/futuregold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'futuregold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#f97316',
  artistLabel: 'Future',
  cardLetter: 'F',
  logoUrl: '/logos/futuregold.webp',
  artistPhotoUrl: '/artists/future.webp',

  getArtistName() {
    return 'Future';
  },

  CUSTOM_IMAGES: {
    'Dirty Sprite': '/futuregold/eras/dirty-sprite.jpg',
    Pluto: '/futuregold/eras/pluto.jpg',
    'Fire Marshal': '/futuregold/eras/fire-marshal.jpg',
    Honest: '/futuregold/eras/honest.jpg',
    Monster: '/futuregold/eras/monster.jpg',
    'Beast Mode': '/futuregold/eras/beast-mode.jpg',
    'Dirty Sprite 2': '/futuregold/eras/dirty-sprite-2.jpg',
    'What a Time to Be Alive': '/futuregold/eras/what-a-time-to-be-alive.jpg',
    'Ape Shit': '/futuregold/eras/ape-shit.jpg',
    'Purple Reign': '/futuregold/eras/purple-reign.jpg',
    EVOL: '/futuregold/eras/evol.jpg',
    Future: '/futuregold/eras/future.jpg',
    HNDRXX: '/futuregold/eras/hndrxx.jpg',
    'Super Slimey': '/futuregold/eras/super-slimey.jpg',
    'Beast Mode 2': '/futuregold/eras/beast-mode-2.jpg',
    'WRLD ON DRUGS': '/futuregold/eras/wrld-on-drugs.jpg',
    'THE WIZRD': '/futuregold/eras/the-wizrd.jpg',
    'SAVE ME': '/futuregold/eras/save-me.jpg',
    'HIGH OFF LIFE': '/futuregold/eras/high-off-life.jpg',
    'PLUTO X BABY PLUTO': '/futuregold/eras/pluto-x-baby-pluto.jpg',
    'I NEVER LIKED YOU': '/futuregold/eras/i-never-liked-you.jpg',
    'WDTY & WSDTY': '/futuregold/eras/wdty-wsdty.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Dirty Sprite (Sessions)': '??/??/????',
    'Dirty Sprite': '01/11/2011',
    'Pluto (Sessions)': '??/??/????',
    Pluto: '04/17/2012',
    'Fire Marshal (Sessions)': '??/??/????',
    'Fire Marshal': '??/??/????',
    'Honest (Sessions)': '??/??/????',
    Honest: '04/22/2014',
    'Monster (Sessions)': '??/??/????',
    Monster: '10/27/2014',
    'Beast Mode (Sessions)': '??/??/????',
    'Beast Mode': '01/06/2015',
    'Dirty Sprite 2 (Sessions)': '??/??/????',
    'Dirty Sprite 2': '07/17/2015',
    'What a Time to Be Alive': '09/24/2015',
    'Ape Shit': '??/??/????',
    'Purple Reign': '03/01/2016',
    EVOL: '02/16/2016',
    Future: '02/17/2017',
    HNDRXX: '02/24/2017',
    'Super Slimey': '11/17/2017',
    'Beast Mode 2': '05/13/2018',
    'WRLD ON DRUGS': '07/06/2018',
    'THE WIZRD': '01/18/2019',
    'SAVE ME': '08/16/2019',
    'HIGH OFF LIFE': '05/15/2020',
    'PLUTO X BABY PLUTO': '02/05/2021',
    'I NEVER LIKED YOU': '04/29/2022',
    'WDTY & WSDTY': '03/22/2024',
    'MIXTAPE PLUTO': '11/15/2024',
    Ongoing: '??/??/????',
    Unknowns: '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Dirty Sprite (Sessions)': 'Unreleased studio sessions and loosies recorded around Future\'s Dirty Sprite mixtape era.',
    'Dirty Sprite': 'Dirty Sprite is one of Future\'s earliest mixtapes, released January 11, 2011.',
    'Pluto (Sessions)': 'Unreleased sessions and loosies recorded during the making of Future\'s debut album, Pluto.',
    Pluto: 'Pluto is Future\'s debut studio album, released April 17, 2012.',
    'Fire Marshal (Sessions)': 'Unreleased sessions and loosies from the Fire Marshall Future mixtape era.',
    'Fire Marshal': 'Fire Marshall Future is a mixtape released by Future in 2014.',
    'Honest (Sessions)': 'Unreleased sessions and loosies recorded during the making of Future\'s Honest album.',
    Honest: 'Honest is Future\'s second studio album, released April 22, 2014.',
    'Monster (Sessions)': 'Unreleased sessions and loosies from Future\'s Monster mixtape era.',
    Monster: 'Monster is a mixtape by Future, released October 27, 2014, part of his Future Hendrix mixtape run.',
    'Beast Mode (Sessions)': 'Unreleased sessions and loosies from Future\'s Beast Mode mixtape era.',
    'Beast Mode': 'Beast Mode is a collaborative mixtape between Future and producer Zaytoven, released January 6, 2015.',
    'Dirty Sprite 2 (Sessions)': 'Unreleased sessions and loosies recorded during the making of Future\'s Dirty Sprite 2 album.',
    'Dirty Sprite 2': 'Dirty Sprite 2 (DS2) is Future\'s third studio album, released July 17, 2015, and debuted at number one on the Billboard 200.',
    'What a Time to Be Alive': 'What a Time to Be Alive is a collaborative mixtape with Drake, released September 24, 2015.',
    'Ape Shit': 'Loosely-documented, unreleased project from Future\'s catalog that was never officially put out.',
    'Purple Reign': 'Purple Reign is a mixtape by Future, released March 1, 2016.',
    EVOL: 'EVOL is Future\'s fourth studio album, released February 16, 2016.',
    Future: 'Future is Future\'s self-titled fifth studio album, released February 17, 2017, debuting at number one on the Billboard 200.',
    HNDRXX: 'HNDRXX is Future\'s sixth studio album, released February 24, 2017, one week after Future, making him the first artist with consecutive number-one albums in back-to-back weeks.',
    'Super Slimey': 'Super Slimey is a collaborative mixtape with Young Thug, released November 17, 2017.',
    'Beast Mode 2': 'Beast Mode 2 is the sequel to Beast Mode, a collaborative mixtape with Zaytoven, released May 13, 2018.',
    'WRLD ON DRUGS': 'WRLD on Drugs is a collaborative album with Juice WRLD, released July 6, 2018.',
    'THE WIZRD': 'The Wizrd is Future\'s seventh studio album, released January 18, 2019, debuting at number one on the Billboard 200.',
    'SAVE ME': 'Save Me is an EP by Future, released August 16, 2019.',
    'HIGH OFF LIFE': 'High Off Life is Future\'s eighth studio album, released May 15, 2020.',
    'PLUTO X BABY PLUTO': 'Pluto x Baby Pluto is a collaborative album with Lil Uzi Vert, released February 5, 2021.',
    'I NEVER LIKED YOU': 'I Never Liked You is Future\'s ninth studio album, released April 29, 2022, debuting at number one on the Billboard 200.',
    'WDTY & WSDTY': 'We Don\'t Trust You and We Still Don\'t Trust You are two collaborative albums with Metro Boomin, released March 22 and April 12, 2024.',
    'MIXTAPE PLUTO': 'Mixtape Pluto is a project by Future, released November 15, 2024.',
    Ongoing: 'Songs without a confirmed era or still being worked on.',
    Unknowns: 'Miscellaneous material without a confirmed era.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Dirty Sprite (Sessions)',
    'Dirty Sprite',
    'Pluto (Sessions)',
    'Pluto',
    'Fire Marshal (Sessions)',
    'Fire Marshal',
    'Honest (Sessions)',
    'Honest',
    'Monster (Sessions)',
    'Monster',
    'Beast Mode (Sessions)',
    'Beast Mode',
    'Dirty Sprite 2 (Sessions)',
    'Dirty Sprite 2',
    'What a Time to Be Alive',
    'Ape Shit',
    'Purple Reign',
    'EVOL',
    'Future',
    'HNDRXX',
    'Super Slimey',
    'Beast Mode 2',
    'WRLD ON DRUGS',
    'THE WIZRD',
    'SAVE ME',
    'HIGH OFF LIFE',
    'PLUTO X BABY PLUTO',
    'I NEVER LIKED YOU',
    'WDTY & WSDTY',
    'MIXTAPE PLUTO',
    'Ongoing',
    'Unknowns',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
