import type { ArtistConfig } from './types';

export const futuregoldConfig: ArtistConfig = {
  slug: 'futuregold',
  SITE_NAME: 'FUTUREGOLD',
  SITE_DESCRIPTION: 'The Best Future Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/futuregold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'futuregold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#f97316',
  artistLabel: 'Future',
  cardLetter: 'F',
  logoUrl: '/logos/futuregold.webp',
  artistPhotoUrl: '/artists/future.webp',

  getArtistName() {
    return 'Future';
  },

  CUSTOM_IMAGES: {
    'Dirty Sprite': '/futuregold/eras/dirty-sprite.jpg',
    Pluto: '/futuregold/eras/pluto.jpg',
    'Fire Marshal': '/futuregold/eras/fire-marshal.jpg',
    Honest: '/futuregold/eras/honest.jpg',
    Monster: '/futuregold/eras/monster.jpg',
    'Beast Mode': '/futuregold/eras/beast-mode.jpg',
    'Dirty Sprite 2': '/futuregold/eras/dirty-sprite-2.jpg',
    'What a Time to Be Alive': '/futuregold/eras/what-a-time-to-be-alive.jpg',
    'Ape Shit': '/futuregold/eras/ape-shit.jpg',
    'Purple Reign': '/futuregold/eras/purple-reign.jpg',
    EVOL: '/futuregold/eras/evol.jpg',
    Future: '/futuregold/eras/future.jpg',
    HNDRXX: '/futuregold/eras/hndrxx.jpg',
    'Super Slimey': '/futuregold/eras/super-slimey.jpg',
    'Beast Mode 2': '/futuregold/eras/beast-mode-2.jpg',
    'WRLD ON DRUGS': '/futuregold/eras/wrld-on-drugs.jpg',
    'THE WIZRD': '/futuregold/eras/the-wizrd.jpg',
    'SAVE ME': '/futuregold/eras/save-me.jpg',
    'HIGH OFF LIFE': '/futuregold/eras/high-off-life.jpg',
    'PLUTO X BABY PLUTO': '/futuregold/eras/pluto-x-baby-pluto.jpg',
    'I NEVER LIKED YOU': '/futuregold/eras/i-never-liked-you.jpg',
    'WDTY & WSDTY': '/futuregold/eras/wdty-wsdty.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Dirty Sprite (Sessions)': '??/??/????',
    'Dirty Sprite': '01/11/2011',
    'Pluto (Sessions)': '??/??/????',
    Pluto: '04/17/2012',
    'Fire Marshal (Sessions)': '??/??/????',
    'Fire Marshal': '??/??/????',
    'Honest (Sessions)': '??/??/????',
    Honest: '04/22/2014',
    'Monster (Sessions)': '??/??/????',
    Monster: '10/27/2014',
    'Beast Mode (Sessions)': '??/??/????',
    'Beast Mode': '01/06/2015',
    'Dirty Sprite 2 (Sessions)': '??/??/????',
    'Dirty Sprite 2': '07/17/2015',
    'What a Time to Be Alive': '09/24/2015',
    'Ape Shit': '??/??/????',
    'Purple Reign': '03/01/2016',
    EVOL: '02/16/2016',
    Future: '02/17/2017',
    HNDRXX: '02/24/2017',
    'Super Slimey': '11/17/2017',
    'Beast Mode 2': '05/13/2018',
    'WRLD ON DRUGS': '07/06/2018',
    'THE WIZRD': '01/18/2019',
    'SAVE ME': '08/16/2019',
    'HIGH OFF LIFE': '05/15/2020',
    'PLUTO X BABY PLUTO': '02/05/2021',
    'I NEVER LIKED YOU': '04/29/2022',
    'WDTY & WSDTY': '03/22/2024',
    'MIXTAPE PLUTO': '11/15/2024',
    Ongoing: '??/??/????',
    Unknowns: '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Dirty Sprite (Sessions)',
    'Dirty Sprite',
    'Pluto (Sessions)',
    'Pluto',
    'Fire Marshal (Sessions)',
    'Fire Marshal',
    'Honest (Sessions)',
    'Honest',
    'Monster (Sessions)',
    'Monster',
    'Beast Mode (Sessions)',
    'Beast Mode',
    'Dirty Sprite 2 (Sessions)',
    'Dirty Sprite 2',
    'What a Time to Be Alive',
    'Ape Shit',
    'Purple Reign',
    'EVOL',
    'Future',
    'HNDRXX',
    'Super Slimey',
    'Beast Mode 2',
    'WRLD ON DRUGS',
    'THE WIZRD',
    'SAVE ME',
    'HIGH OFF LIFE',
    'PLUTO X BABY PLUTO',
    'I NEVER LIKED YOU',
    'WDTY & WSDTY',
    'MIXTAPE PLUTO',
    'Ongoing',
    'Unknowns',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
