import type { ArtistConfig } from './types';

export const futuregoldConfig: ArtistConfig = {
  slug: 'futuregold',
  SITE_NAME: 'FUTUREGOLD',
  SITE_DESCRIPTION: 'The Best Future Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/futuregold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'futuregold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1OGAthACjwPcq3vHIVTAoaT8blFXjyBLtVcP0m5u80-U/export?format=csv&gid=1932564138',
  accentColor: '#f97316',
  artistLabel: 'Future',
  cardLetter: 'F',
  logoUrl: '/logos/futuregold.webp',
  artistPhotoUrl: '/artists/future.jpeg',

  getArtistName() {
    return 'Future';
  },

  CUSTOM_IMAGES: {
    'Dirty Sprite': '/futuregold/eras/dirty-sprite.jpg',
    'Astronaut Status': '/futuregold/eras/astronaut-status.jpg',
    Pluto: '/futuregold/eras/pluto.jpg',
    'F.B.G. The Movie': '/futuregold/eras/f-b-g-the-movie.jpg',
    'Black Woodstock': '/futuregold/eras/black-woodstock.jpg',
    'Super Future / Fire Marshal Future': '/futuregold/eras/fire-marshal.jpg',
    'No Sleep': '/futuregold/eras/no-sleep.jpg',
    Honest: '/futuregold/eras/honest.jpg',
    Monster: '/futuregold/eras/monster.jpg',
    'Beast Mode': '/futuregold/eras/beast-mode.jpg',
    '56 Nights': '/futuregold/eras/56-nights.jpg',
    'Ape Sh!t': '/futuregold/eras/ape-shit.jpg',
    'Monster 2 [V1]': '/futuregold/eras/monster-2-v1.jpg',
    DS2: '/futuregold/eras/dirty-sprite-2.jpg',
    'What A Time To Be Alive': '/futuregold/eras/what-a-time-to-be-alive.jpg',
    'Purple Reign': '/futuregold/eras/purple-reign.jpg',
    EVOL: '/futuregold/eras/evol.jpg',
    'HOMIE from the FUTURE': '/futuregold/eras/homie-from-the-future.jpg',
    'Project E.T.': '/futuregold/eras/project-e-t.jpg',
    'Beast Mode \'16': '/futuregold/eras/beast-mode-16.jpg',
    '4Ever Or Never': '/futuregold/eras/4ever-or-never.jpg',
    FUTURE: '/futuregold/eras/future.jpg',
    HNDRXX: '/futuregold/eras/hndrxx.jpg',
    'SUPER SLIMEY': '/futuregold/eras/super-slimey.jpg',
    KOLORBLIND: '/futuregold/eras/kolorblind.jpg',
    SUPERFLY: '/futuregold/eras/superfly.jpg',
    'BEASTMODE 2': '/futuregold/eras/beast-mode-2.jpg',
    'WRLD On Drugs': '/futuregold/eras/wrld-on-drugs.jpg',
    'What A Time 2 Be Alive': '/futuregold/eras/what-a-time-2-be-alive.jpg',
    'The WIZRD': '/futuregold/eras/the-wizrd.jpg',
    'SAVE ME': '/futuregold/eras/save-me.jpg',
    'F.B.G. The Album': '/futuregold/eras/f-b-g-the-album.jpg',
    'High Off Life': '/futuregold/eras/high-off-life.jpg',
    'Pluto x Baby Pluto': '/futuregold/eras/pluto-x-baby-pluto.jpg',
    'Monster 2 [V2]': '/futuregold/eras/monster-2-v2.jpg',
    'Donda 2': '/futuregold/eras/donda-2.jpg',
    'I NEVER LIKED YOU': '/futuregold/eras/i-never-liked-you.jpg',
    'Lil Durk Collab': '/futuregold/eras/lil-durk-collab.jpg',
    'WE DON\'T TRUST YOU': '/futuregold/eras/we-dont-trust-you.jpg',
    'WE STILL DON\'T TRUST YOU': '/futuregold/eras/we-still-dont-trust-you.jpg',
    'MIXTAPE PLUTO': '/futuregold/eras/mixtape-pluto.jpg',
    'Edd, Ed n Eddy': '/futuregold/eras/edd-ed-n-eddy.jpg',
    'The Real Me': '/futuregold/eras/the-real-me.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Dirty Sprite': '01/11/2011',
    'Astronaut Status': '01/12/2012',
    Pluto: '04/17/2012',
    'F.B.G. The Movie': '??/??/2012',
    'Black Woodstock': '04/20/2013',
    'Super Future / Fire Marshal Future': '??/??/2012',
    'No Sleep': '??/??/2013',
    Honest: '04/22/2014',
    Monster: '10/28/2014',
    'Beast Mode': '01/06/2015',
    '56 Nights': '03/20/2015',
    'Ape Sh!t': '??/??/????',
    'Monster 2 [V1]': '??/??/2015',
    DS2: '07/17/2015',
    'What A Time To Be Alive': '09/20/2015',
    'Purple Reign': '01/17/2016',
    EVOL: '02/05/2016',
    'HOMIE from the FUTURE': '??/??/2016',
    'Project E.T.': '06/24/2016',
    'Beast Mode \'16': '??/??/2016',
    '4Ever Or Never': '??/??/2016',
    FUTURE: '02/17/2017',
    HNDRXX: '02/24/2017',
    'SUPER SLIMEY': '10/13/2017',
    KOLORBLIND: '03/30/2018',
    SUPERFLY: '06/08/2018',
    'BEASTMODE 2': '07/04/2018',
    'WRLD On Drugs': '10/19/2018',
    'What A Time 2 Be Alive': '??/??/????',
    'The WIZRD': '01/18/2019',
    'SAVE ME': '06/07/2019',
    'F.B.G. The Album': '??/??/2019',
    'High Off Life': '05/15/2020',
    'Pluto x Baby Pluto': '11/13/2020',
    'Monster 2 [V2]': '??/??/2021',
    'Donda 2': '02/22/2022',
    'I NEVER LIKED YOU': '04/29/2022',
    'Lil Durk Collab': '??/??/????',
    'WE DON\'T TRUST YOU': '03/22/2024',
    'WE STILL DON\'T TRUST YOU': '04/12/2024',
    'MIXTAPE PLUTO': '09/20/2024',
    'Edd, Ed n Eddy': '??/??/????',
    'The Real Me': '??/??/????',
    Unknown: '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Dirty Sprite': 'Early Future loosies and mixtape-era cuts from the Dirty Sprite run.',
    'Astronaut Status': 'Astronaut Status (Da Astronaut Kid) — Future\'s 2012 mixtape era.',
    Pluto: 'Pluto is Future\'s debut studio album, released April 17, 2012.',
    'F.B.G. The Movie': 'F.B.G: The Movie — a collaboration with Freeband Gang & DJ Drama.',
    'Black Woodstock': 'Black Woodstock: The Soundtrack — a collaboration with DJ ESCO.',
    'Super Future / Fire Marshal Future': 'Super Future / Fire Marshal Future mixtape era.',
    'No Sleep': 'No Sleep — a collaboration with Freeband Gang & DJ ESCO.',
    Honest: 'Honest is Future\'s second studio album, released April 22, 2014.',
    Monster: 'Monster is a mixtape by Future, released October 28, 2014.',
    'Beast Mode': 'Beast Mode is a collaborative mixtape with Zaytoven, released January 6, 2015.',
    '56 Nights': '56 Nights is a mixtape hosted by DJ ESCO, released March 20, 2015.',
    'Ape Sh!t': 'Ape Sh!t — an unreleased project from Future\'s catalog.',
    'Monster 2 [V1]': 'Monster 2 [V1] — an unreleased sequel, executively produced by Metro Boomin.',
    DS2: 'DS2 (Dirty Sprite 2) is Future\'s third studio album, released July 17, 2015.',
    'What A Time To Be Alive': 'What A Time To Be Alive is a collaborative mixtape with Drake, released September 20, 2015.',
    'Purple Reign': 'Purple Reign is a mixtape by Future, released January 17, 2016.',
    EVOL: 'EVOL is Future\'s fourth studio album, released February 5, 2016.',
    'HOMIE from the FUTURE': 'HOMIE from the FUTURE — a collaboration with Rich Homie Quan.',
    'Project E.T.': 'Project E.T. (Esco Terrestrial) — a collaboration with DJ ESCO, released June 24, 2016.',
    'Beast Mode \'16': 'Beast Mode \'16 — an unreleased collaboration with Zaytoven.',
    '4Ever Or Never': '4Ever Or Never — an unreleased collaboration with Freeband Gang.',
    FUTURE: 'FUTURE is Future\'s self-titled fifth studio album, released February 17, 2017.',
    HNDRXX: 'HNDRXX is Future\'s sixth studio album, released February 24, 2017.',
    'SUPER SLIMEY': 'Super Slimey is a collaborative mixtape with Young Thug, released October 13, 2017.',
    KOLORBLIND: 'KOLORBLIND — a collaboration with DJ ESCO, released March 30, 2018.',
    SUPERFLY: 'SUPERFLY — Future\'s soundtrack for the 2018 film, released June 8, 2018.',
    'BEASTMODE 2': 'Beast Mode 2 is a collaborative mixtape with Zaytoven, released July 4, 2018.',
    'WRLD On Drugs': 'WRLD on Drugs is a collaborative album with Juice WRLD, released October 19, 2018.',
    'What A Time 2 Be Alive': 'What A Time 2 Be Alive — an unreleased sequel collaboration with Drake.',
    'The WIZRD': 'The WIZRD is Future\'s seventh studio album, released January 18, 2019.',
    'SAVE ME': 'Save Me is an EP by Future, released June 7, 2019.',
    'F.B.G. The Album': 'F.B.G. The Album — an unreleased collaboration with Freeband Gang.',
    'High Off Life': 'High Off Life (Life Is Good) is Future\'s eighth studio album, released May 15, 2020.',
    'Pluto x Baby Pluto': 'Pluto x Baby Pluto is a collaborative album with Lil Uzi Vert, released November 13, 2020.',
    'Monster 2 [V2]': 'Monster 2 [V2] — an unreleased sequel, executively produced by Metro Boomin.',
    'Donda 2': 'Donda 2 — Kanye West\'s album executively produced by Future, released February 22, 2022.',
    'I NEVER LIKED YOU': 'I Never Liked You is Future\'s ninth studio album, released April 29, 2022.',
    'Lil Durk Collab': 'Unreleased collaborative material between Future and Lil Durk.',
    'WE DON\'T TRUST YOU': 'We Don\'t Trust You is a collaborative album with Metro Boomin, released March 22, 2024.',
    'WE STILL DON\'T TRUST YOU': 'We Still Don\'t Trust You is a collaborative album with Metro Boomin, released April 12, 2024.',
    'MIXTAPE PLUTO': 'Mixtape Pluto is a project by Future, released September 20, 2024.',
    'Edd, Ed n Eddy': 'Edd, Ed n Eddy — an unreleased collaboration with Young Thug & Lil Baby.',
    'The Real Me': 'The Real Me — Future\'s most recent era.',
    Unknown: 'Miscellaneous material without a confirmed era.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_DISCLAIMERS: {
    'Donda 2': {
      text: 'Due to copyright issues, the Future tracker cannot provide songs from this era. If you want to hear songs from this era, check out the Kanye tracker',
      linkText: 'here',
      linkUrl: 'https://unvaulted.cc/yzygold/album/donda-2',
    },
  },
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Dirty Sprite',
    'Astronaut Status',
    'Pluto',
    'F.B.G. The Movie',
    'Black Woodstock',
    'Super Future / Fire Marshal Future',
    'No Sleep',
    'Honest',
    'Monster',
    'Beast Mode',
    '56 Nights',
    'Ape Sh!t',
    'Monster 2 [V1]',
    'DS2',
    'What A Time To Be Alive',
    'Purple Reign',
    'EVOL',
    'HOMIE from the FUTURE',
    'Project E.T.',
    'Beast Mode \'16',
    '4Ever Or Never',
    'FUTURE',
    'HNDRXX',
    'SUPER SLIMEY',
    'KOLORBLIND',
    'SUPERFLY',
    'BEASTMODE 2',
    'WRLD On Drugs',
    'What A Time 2 Be Alive',
    'The WIZRD',
    'SAVE ME',
    'F.B.G. The Album',
    'High Off Life',
    'Pluto x Baby Pluto',
    'Monster 2 [V2]',
    'Donda 2',
    'I NEVER LIKED YOU',
    'Lil Durk Collab',
    'WE DON\'T TRUST YOU',
    'WE STILL DON\'T TRUST YOU',
    'MIXTAPE PLUTO',
    'Edd, Ed n Eddy',
    'The Real Me',
    'Unknown',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
  hasMiscTab: false,
  hasSubAlbumsTab: false,
};
