import type { ArtistConfig } from './types';

export const gorillazgoldConfig: ArtistConfig = {
  slug: 'gorillazgold',
  SITE_NAME: 'GORILLAZGOLD',
  SITE_DESCRIPTION: 'The Best Gorillaz Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/gorillazgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'gorillazgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#14b8a6',
  artistLabel: 'Gorillaz',
  cardLetter: 'GZ',
  logoUrl: '/logos/gorillazgold.webp',
  artistPhotoUrl: '/artists/gorillaz.webp',

  getArtistName() {
    return 'Gorillaz';
  },

  CUSTOM_IMAGES: {
    'Gorillaz': '/gorillazgold/eras/gorillaz.jpg',
    'G-Sides': '/gorillazgold/eras/g-sides.jpg',
    'Laika Come Home': '/gorillazgold/eras/g-sides.jpg',
    'Demon Days': '/gorillazgold/eras/demon-days.jpg',
    'D-Sides': '/gorillazgold/eras/d-sides.jpg',
    'Carousel': '/gorillazgold/eras/demon-days.jpg',
    'Monkey - Journey To The West': '/gorillazgold/eras/monkey-journey-to-the-west.jpg',
    'Plastic Beach': '/gorillazgold/eras/plastic-beach.jpg',
    'The Fall': '/gorillazgold/eras/the-fall.jpg',
    'HUMANZ': '/gorillazgold/eras/humanz.jpg',
    'The Now Now': '/gorillazgold/eras/the-now-now.jpg',
    'Song Machine, Season One: Strange Timez': '/gorillazgold/eras/song-machine-season-one.jpg',
    'Meanwhile': '/gorillazgold/eras/meanwhile.jpg',
    'Cracker Island': '/gorillazgold/eras/cracker-island.jpg',
    'The Mountain': '/gorillazgold/eras/the-mountain.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Gorillaz': '03/26/2001',
    'G-Sides': '12/12/2001',
    'Laika Come Home': '11/18/2002',
    'Demon Days': '05/11/2005',
    'D-Sides': '11/19/2007',
    'Carousel': '??/??/????',
    'Monkey - Journey To The West': '01/01/2008',
    'Plastic Beach': '03/08/2010',
    'The Fall': '12/25/2010',
    'HUMANZ': '04/28/2017',
    'The Now Now': '06/29/2018',
    'Song Machine, Season One: Strange Timez': '10/23/2020',
    'Meanwhile': '03/26/2021',
    'Cracker Island': '02/24/2023',
    'The Mountain': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Gorillaz': 'Gorillaz\' self-titled debut studio album, released March 26, 2001.',
    'G-Sides': 'B-sides and remix compilation released December 12, 2001, as a companion to the debut album.',
    'Laika Come Home': 'Remix album by Spacemonkeyz vs Gorillaz, released November 18, 2002, reworking tracks from the debut album in dub and reggae styles.',
    'Demon Days': 'Gorillaz\' second studio album, released May 11, 2005, produced by Danger Mouse.',
    'D-Sides': 'B-sides and rarities compilation released November 19, 2007, as a companion to Demon Days.',
    'Carousel': 'Scrapped third studio album, recorded 2008-2009 as an ambitious multimedia project before being abandoned in favor of Plastic Beach. Some material, including "Stylo" and "Broken," was repurposed for that album.',
    'Monkey - Journey To The West': 'Music composed by Damon Albarn for the Chinese opera Monkey: Journey to the West, a collaboration with Jamie Hewlett that premiered in 2007.',
    'Plastic Beach': 'Gorillaz\' third studio album, released March 8, 2010, featuring an eclectic cast of guest musicians.',
    'The Fall': 'Fourth studio album, largely recorded on an iPad during the Plastic Beach tour and released as a free Christmas gift to fans on December 25, 2010.',
    'HUMANZ': 'Fifth studio album, released April 28, 2017, featuring an extensive list of guest vocalists.',
    'The Now Now': 'Sixth studio album, released June 29, 2018, a more stripped-back record with fewer guest features than HUMANZ.',
    'Song Machine, Season One: Strange Timez': 'Seventh studio album, released October 23, 2020, compiled from episodic singles released throughout the year as part of the Song Machine web series.',
    'Meanwhile': 'Standalone EP released March 26, 2021, tied to the Gorillaz augmented reality app.',
    'Cracker Island': 'Eighth studio album, released February 24, 2023, featuring collaborations with Thundercat, Stevie Nicks, and Bad Bunny among others.',
    'The Mountain': 'Ninth studio album, exploring themes of death, grief, and the afterlife with heavy Indian classical instrumentation.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Gorillaz',
    'G-Sides',
    'Laika Come Home',
    'Demon Days',
    'D-Sides',
    'Carousel',
    'Monkey - Journey To The West',
    'Plastic Beach',
    'The Fall',
    'HUMANZ',
    'The Now Now',
    'Song Machine, Season One: Strange Timez',
    'Meanwhile',
    'Cracker Island',
    'The Mountain',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
};
