import type { ArtistConfig } from './types';

export const gorillazgoldConfig: ArtistConfig = {
  slug: 'gorillazgold',
  SITE_NAME: 'GORILLAZGOLD',
  SITE_DESCRIPTION: 'The Best Gorillaz Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/gorillazgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'gorillazgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#14b8a6',
  artistLabel: 'Gorillaz',
  cardLetter: 'GZ',
  logoUrl: '/logos/gorillazgold.webp',
  artistPhotoUrl: '/artists/gorillaz.webp',

  getArtistName() {
    return 'Gorillaz';
  },

  CUSTOM_IMAGES: {
    'Gorillaz': '/gorillazgold/eras/gorillaz.jpg',
    'G-Sides': '/gorillazgold/eras/g-sides.jpg',
    'Laika Come Home': '/gorillazgold/eras/g-sides.jpg',
    'Demon Days': '/gorillazgold/eras/demon-days.jpg',
    'D-Sides': '/gorillazgold/eras/d-sides.jpg',
    'Carousel': '/gorillazgold/eras/demon-days.jpg',
    'Monkey - Journey To The West': '/gorillazgold/eras/monkey-journey-to-the-west.jpg',
    'Plastic Beach': '/gorillazgold/eras/plastic-beach.jpg',
    'The Fall': '/gorillazgold/eras/the-fall.jpg',
    'HUMANZ': '/gorillazgold/eras/humanz.jpg',
    'The Now Now': '/gorillazgold/eras/the-now-now.jpg',
    'Song Machine, Season One: Strange Timez': '/gorillazgold/eras/song-machine-season-one.jpg',
    'Meanwhile': '/gorillazgold/eras/meanwhile.jpg',
    'Cracker Island': '/gorillazgold/eras/cracker-island.jpg',
    'The Mountain': '/gorillazgold/eras/the-mountain.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Gorillaz': '03/26/2001',
    'G-Sides': '12/12/2001',
    'Laika Come Home': '11/18/2002',
    'Demon Days': '05/11/2005',
    'D-Sides': '11/19/2007',
    'Carousel': '??/??/????',
    'Monkey - Journey To The West': '01/01/2008',
    'Plastic Beach': '03/08/2010',
    'The Fall': '12/25/2010',
    'HUMANZ': '04/28/2017',
    'The Now Now': '06/29/2018',
    'Song Machine, Season One: Strange Timez': '10/23/2020',
    'Meanwhile': '03/26/2021',
    'Cracker Island': '02/24/2023',
    'The Mountain': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Gorillaz': 'The first album by Gorillaz following the Tomorrow Comes Today EP. The album was made in collaboration with Deltron 3030 members Dan the Automator (also of Handsome Boy Modelling School, Lovage, etc.) and Kid Koala, with Del the Funky Homosapien featuring on "Clint Eastwood" and "Rock the House".',
    'G-Sides': 'B-sides and remix compilation released December 12, 2001, as a companion to the debut album.',
    'Laika Come Home': 'Remix album by Spacemonkeyz vs Gorillaz, released November 18, 2002, reworking tracks from the debut album in dub and reggae styles.',
    'Demon Days': 'With the goal of proving Gorillaz wasn’t a gimmick, Demon Days featured a noticeable shift in sound from the dub-influenced underground hip-hop of Gorillaz to a more political rock, pop, choral and hip-hop route brought on by string arrangements, drum-sequencing, and lyrics crticizing the Afghanistan War and life post-911. Co-produced by then-newcomer Danger Mouse, Demon Days is also the first Gorillaz album to heavily feature other artists and rely on collaboration, a future mainstay for all Gorillaz projects.',
    'D-Sides': 'B-sides and rarities compilation released November 19, 2007, as a companion to Demon Days.',
    'Carousel': 'Announced in 2008 as the third Gorillaz album, Carousel was to be a multi-media orchestral art-rock project contained in 15 stories. Thematically, Carousel would revolve around the mystical aspects of Britain and the progression of life all taking place on a 100-mile pier. Carousel was scrapped by EMI who refused to fund the project while Damon and Jamie struggled to structure the project. Damon and Jamie would then carry over elements from Carousel to another Gorillaz project, Plastic Beach.',
    'Monkey - Journey To The West': '"Monkey - Journey To The West" is an opera that is a stage adaptation of the Chinese novel "Journey To The West," made in collaboration with Chinese actor and director Chen Shi-Zheng in 2005. Damon and Hewlett have both referred to Monkey: Journey To The West as a Gorillaz project. Originally, they intended for the soundtrack to be released as a Gorillaz project, under the Gorillaz name, but were unable to do so for legal reasons.',
    'Plastic Beach': 'Conceived initially as three separate projects: Carousel, Plastic Beach and Dee, The Opera. The third Gorillaz album took on a more environmental focus from Damon observing the amounts of plastic on the sands of a beach. Plastic Beach is infamous for going over the band\'s budget, and its scrapped content, leading to the 2018 #FreeTheSea campaign calling for the release of the 200+ unreleased songs recorded during the making of Phase 3.',
    'The Fall': '"The Fall" is the fourth album by Gorillaz, infamous for being concieved on tour, on an iPad. It was first released as a download for members of the Gorillaz fan club on December 25th, 2010, followed by a wider physical release on April 19th, 2011 by Parlophone Records.',
    'HUMANZ': 'After reuniting at a party, Damon and Jamie would begin work on a Gorillaz comeback album in 2015 titled Transformerz. After producer The Twilite Tone became involved in 2016, Transformerz would be renamed to Humanz, with a new concept imagining a party at the end of the world caused by (the then-hypothetical of) Donald Trump winning the 2016 US presidential election.',
    'The Now Now': 'Recorded during the Humanz Tour with the intention of having more Damon-centric songs to play at concerts after the reaction to his absence on the majority of Humanz. The Now Now is a largely funk-inspired album written from the perspective of 2-D, with the change in sound being accredited in-universe to the temporary substitution of Murdoc to Ace from The Powerpuff Girls as the band\'s bassist.',
    'Song Machine, Season One: Strange Timez': 'Setting out to not make an album, Damon, Jamie, and longtime collaborator and newly credited Gorillaz member Remi Kabaka Jr began work on releasing singles accompanied by music videos near-monthly throughout 2020 in a series titled Song Machine. However, after the rise of the COVID-19 pandemic in March, more songs would be created through Zoom and emails, leading to the first season of Song Machine being expanded into an album released as Song Machine, Season One: Strange Timez.',
    'Meanwhile': 'The existence of new Gorillaz material after Song Machine, Season One: Strange Timez would be revealed by Damon in an interview with NME describing it as "carnival-themed". Damon would later reveal in an interview with Mark Ronson that a new Gorillaz EP would be released to compliment that year\'s Notting Hill Carnival. Meanwhile was also released in celebration as a part of the 20th anniversary of Gorillaz, showcasing a modern take on the sounds explored 20 years ago on Gorillaz.',
    'Cracker Island': 'Originally announced as the second season of Song Machine in October 2020; Jamie, through the Gorillaz Unofficial 2020 Plastic Beach Fanzine, would reveal that the project following Song Machine would take on a narrative-heavy structure, describing it as a "more in-depth kinda epic story with the characters and music. Not just an album, but bigger." Cracker Island would topically revolve around cults and the Los Angeles lifestyle, where the album was recorded in 9-11 days with album collaborator Greg Kurstin.',
    'The Mountain': 'Vaguely hinted at in their 2023 Coachella interview, the ninth Gorillaz album will be recorded somewhere they\'d "never been before", likely Mumbai as teased in recent social media posts. Several tracks from the album were played at a mystery show on September 3rd, 2025. It is very likely this new album is in some way a spiritual successor to Plastic Beach, having several unused tracks from the era repurposed.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Gorillaz',
    'G-Sides',
    'Laika Come Home',
    'Demon Days',
    'D-Sides',
    'Carousel',
    'Monkey - Journey To The West',
    'Plastic Beach',
    'The Fall',
    'HUMANZ',
    'The Now Now',
    'Song Machine, Season One: Strange Timez',
    'Meanwhile',
    'Cracker Island',
    'The Mountain',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
};
