import type { ArtistConfig } from './types';

// Gunna tracker. Data served from committed CSV snapshots under
// public/gunnagold/data/*.csv, transformed from the source Google-Sheet exports by
// scripts/build-bigupdate-csvs.py. An era only appears in the Music grid if its
// name is a key in ALBUM_RELEASE_DATES.
export const gunnagoldConfig: ArtistConfig = {
  slug: 'gunnagold',
  SITE_NAME: 'GUNNAGOLD',
  SITE_DESCRIPTION: 'The Best Gunna Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/gunnagold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'gunnagold_',

  sheetUrl: 'https://docs.google.com/spreadsheets/d/1P_BA-CIy05lDl9j1H06awxNqvXYJcD-KeBPVdgTO7Eo/edit?gid=1630289126#1630289126',

  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',

  accentColor: '#c026d3',
  artistLabel: 'Gunna',
  cardLetter: 'G',
  logoUrl: '',
  artistPhotoUrl: '/artists/gunnagold.jpg',

  getArtistName() {
    return 'Gunna';
  },

  CUSTOM_IMAGES: {
    'SPC Entourage':                     '/gunnagold/eras/spc-entourage.png',
    'Family 1st':                        '/gunnagold/eras/family-1st.jpg',
    'Hard Body':                         '/gunnagold/eras/hard-body.jpg',
    "Money Can't Buy Dreams [V1]":       '/gunnagold/eras/money-cant-buy-dreams-v1.png',
    'The Nextdoor Neighbors':            '/gunnagold/eras/the-nextdoor-neighbors.jpg',
    "Money Can't Buy Dreams [V2]":       '/gunnagold/eras/money-cant-buy-dreams-v2.jpg',
    'Drip Season':                       '/gunnagold/eras/drip-season.jpg',
    'Drip Season 2':                     '/gunnagold/eras/drip-season-2.jpg',
    'Designer Drip':                     '/gunnagold/eras/designer-drip.jpg',
    'Drip or Drown':                     '/gunnagold/eras/drip-or-drown.jpg',
    'Collaboration with UnoTheActivist': '/gunnagold/eras/collaboration-with-unotheactivist.jpg',
    'Drip Season 3':                     '/gunnagold/eras/drip-season-3.jpg',
    'Drip Harder':                       '/gunnagold/eras/drip-harder.jpg',
    'Drip or Drown 2':                   '/gunnagold/eras/drip-or-drown-2.jpg',
    'Collaboration with Young Thug':     '/gunnagold/eras/collaboration-with-young-thug.jpg',
    'WUNNA':                             '/gunnagold/eras/wunna.jpg',
    'WUNNA (Deluxe)':                    '/gunnagold/eras/wunna-deluxe.jpg',
    'SUPER SLIMEY: SURFER EDITION':      '/gunnagold/eras/super-slimey-surfer-edition.jpg',
    'Drip Harder 2':                     '/gunnagold/eras/drip-harder-2.jpg',
    'Slime Language 2':                  '/gunnagold/eras/slime-language-2.jpg',
    'DS4EVER':                           '/gunnagold/eras/ds4ever.jpg',
    'Untitled (2022)':                   '/gunnagold/eras/untitled-2022.jpg',
    'a Gift & a Curse':                  '/gunnagold/eras/a-gift-a-curse.jpg',
    'One of Wun':                        '/gunnagold/eras/one-of-wun.jpg',
    'Collaboration with Offset':         '/gunnagold/eras/collaboration-with-offset.png',
    'The Last Wun':                      '/gunnagold/eras/the-last-wun.jpg',
    'Ongoing':                           '/gunnagold/eras/ongoing.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'SPC Entourage': '??/??/????',
    'Family 1st': '??/??/????',
    'Hard Body': '??/??/????',
    'Money Can\'t Buy Dreams [V1]': '??/??/????',
    'The Nextdoor Neighbors': '??/??/????',
    'Money Can\'t Buy Dreams [V2]': '??/??/????',
    'Drip Season': '??/??/????',
    'Drip Season 2': '??/??/????',
    'Designer Drip': '??/??/????',
    'Drip or Drown': '??/??/????',
    'Collaboration with UnoTheActivist': '??/??/????',
    'Drip Season 3': '??/??/????',
    'Drip Harder': '??/??/????',
    'Drip or Drown 2': '??/??/????',
    'Collaboration with Young Thug': '??/??/????',
    'WUNNA': '??/??/????',
    'WUNNA (Deluxe)': '??/??/????',
    'SUPER SLIMEY: SURFER EDITION': '??/??/????',
    'Super Slimey: Surfer Edition': '??/??/????',
    'Drip Harder 2': '??/??/????',
    'Slime Language 2': '??/??/????',
    'DS4EVER': '??/??/????',
    'Untitled (2022)': '??/??/????',
    'a Gift & a Curse': '??/??/????',
    'One of Wun': '??/??/????',
    'Collaboration with Offset': '??/??/????',
    'The Last Wun': '??/??/????',
    'Ongoing': '??/??/????'
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  ALBUM_ORDER: [
    'SPC Entourage',
    'Family 1st',
    'Hard Body',
    'Money Can\'t Buy Dreams [V1]',
    'The Nextdoor Neighbors',
    'Money Can\'t Buy Dreams [V2]',
    'Drip Season',
    'Drip Season 2',
    'Designer Drip',
    'Drip or Drown',
    'Collaboration with UnoTheActivist',
    'Drip Season 3',
    'Drip Harder',
    'Drip or Drown 2',
    'Collaboration with Young Thug',
    'WUNNA',
    'WUNNA (Deluxe)',
    'SUPER SLIMEY: SURFER EDITION',
    'Super Slimey: Surfer Edition',
    'Drip Harder 2',
    'Slime Language 2',
    'DS4EVER',
    'Untitled (2022)',
    'a Gift & a Curse',
    'One of Wun',
    'Collaboration with Offset',
    'The Last Wun',
    'Ongoing'
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},
  hasSubAlbumsTab: false, // no sub-albums data for this tracker
  hasAlbumCopiesTab: true,
};
