import type { ArtistConfig } from './types';

export const jayzgoldConfig: ArtistConfig = {
  slug: 'jayzgold',
  SITE_NAME: 'JAYZGOLD',
  SITE_DESCRIPTION: 'The Best Jay-Z Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/jayzgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'jayzgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#1a1a1a',
  artistLabel: 'Jay-Z',
  cardLetter: 'J',
  logoUrl: '/logos/jayzgold.webp',
  artistPhotoUrl: '/artists/jayz.webp',

  getArtistName() {
    return 'Jay-Z';
  },

  CUSTOM_IMAGES: {
    'Streets Is Watching': '/jayzgold/eras/4-44.jpg',
    'The Best Of Both Worlds': '/jayzgold/eras/the-best-of-both-worlds.jpg',
    'Unfinished Business': '/jayzgold/eras/unfinished-business.jpg',
    'The Black Album': '/jayzgold/eras/the-black-album.jpg',
    'Preasonable Doubt': '/jayzgold/eras/reasonable-doubt.jpg',
    'Reasonable Doubt': '/jayzgold/eras/reasonable-doubt.jpg',
    'In My Lifetime, Vol 1': '/jayzgold/eras/in-my-lifetime-vol-1.jpg',
    'Vol 1': '/jayzgold/eras/in-my-lifetime-vol-1.jpg',
    'Vol 2, Hard Knock Life': '/jayzgold/eras/vol-2-hard-knock-life.jpg',
    'Vol 2': '/jayzgold/eras/vol-2-hard-knock-life.jpg',
    'Vol. 3... Life and Times of S. Carter': '/jayzgold/eras/vol-3-life-and-times-of-s-carter.jpg',
    'Vol 3': '/jayzgold/eras/vol-3-life-and-times-of-s-carter.jpg',
    'The Dynasty: Roc La Familia': '/jayzgold/eras/the-dynasty-roc-la-familia.jpg',
    'The Blueprint': '/jayzgold/eras/the-blueprint.jpg',
    'The Вlueprint²': '/jayzgold/eras/the-blueprint-2.jpg',
    'The Blueprint 2': '/jayzgold/eras/the-blueprint-2.jpg',
    'Blueprint 2.1': '/jayzgold/eras/the-blueprint-2.jpg',
    'Kingdom Come': '/jayzgold/eras/kingdom-come.jpg',
    'American Gangster': '/jayzgold/eras/american-gangster.jpg',
    'The Βlueprint 3': '/jayzgold/eras/the-blueprint-3.jpg',
    'The Blueprint 3': '/jayzgold/eras/the-blueprint-3.jpg',
    'Watch The Throne': '/jayzgold/eras/watch-the-throne.jpg',
    'Magna Carta.. Holy Grail': '/jayzgold/eras/magna-carta-holy-grail.jpg',
    '4:44': '/jayzgold/eras/4-44.jpg',
    'EVERYTHING IS LOVE': '/jayzgold/eras/everything-is-love.jpg',
    'Everything Is Love': '/jayzgold/eras/everything-is-love.jpg',
    'LP14': '/artists/jayz.webp',
  },

  ALBUM_RELEASE_DATES: {
    'Streets Is Watching': '05/12/1998',
    'The Best Of Both Worlds': '03/26/2002',
    'Unfinished Business': '10/29/2002',
    'The Black Album': '11/14/2003',
    'Preasonable Doubt': '??/??/????',
    'Reasonable Doubt': '06/25/1996',
    'In My Lifetime, Vol 1': '11/04/1997',
    'Vol 1': '11/04/1997',
    'Vol 2, Hard Knock Life': '09/29/1998',
    'Vol 2': '09/29/1998',
    'Vol. 3... Life and Times of S. Carter': '12/28/1999',
    'Vol 3': '12/28/1999',
    'The Dynasty: Roc La Familia': '10/31/2000',
    'The Blueprint': '09/11/2001',
    'The Вlueprint²': '11/12/2002',
    'The Blueprint 2': '11/12/2002',
    'Blueprint 2.1': '12/09/2003',
    'Kingdom Come': '11/21/2006',
    'American Gangster': '11/06/2007',
    'The Βlueprint 3': '09/08/2009',
    'The Blueprint 3': '09/08/2009',
    'Watch The Throne': '08/08/2011',
    'Magna Carta.. Holy Grail': '07/04/2013',
    '4:44': '06/30/2017',
    'EVERYTHING IS LOVE': '06/16/2018',
    'Everything Is Love': '06/16/2018',
    'LP14': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Preasonable Doubt': 'JAY-Z made his early appearances on tracks by Jaz-O, Big Daddy Kane, and others in the late 1980s and early 1990s. He was involved in a rap feud with LL Cool J during this time. JAY-Z\'s big break came with the 1994 song "Show and Prove" on Big Daddy Kane\'s album "Daddy\'s Home". He also appeared on tracks by Big L, Mic Geronimo, and others in the mid-1990s. In 1995, JAY-Z released his first official rap single, "In My Lifetime", along with a music video.',
    'Reasonable Doubt': 'After being rejected by major labels, Jay-Z started selling burned CDs out of his car. He teamed up with Damon "Dame" Dash and Kareem "Biggs" Burke to create Roc-A-Fella Records, an independent label in 1995. After striking a distribution deal with Priority, Jay-Z released his 1996 debut album Reasonable Doubt with beats from acclaimed producers such as DJ Premier and Super DJ Clark Kent and an appearance by The Notorious B.I.G. The album reached number 23 on the Billboard 200, and was generally favored by critics.',
    'In My Lifetime, Vol 1': 'JAY-Z\'s second album, "In My Lifetime, Vol. 1", was released just over a year after his debut, "Reasonable Doubt". Despite being more successful in terms of sales, it received mixed reviews from critics. The album took a more commercial approach, and was criticized for being too radio-friendly. Jay released six singles from the album, compared to four on his debut. The album was influenced by the passing of his friend The Notorious B.I.G. and Jay has since said that he didn\'t have as much fun making it as he did with his debut.',
    'Vol 1': 'Alternate era name for In My Lifetime, Vol. 1, Jay-Z\'s second studio album, released November 4, 1997.',
    'Vol 2, Hard Knock Life': 'JAY-Z\'s third studio album, Vol. 2... Hard Knock Life, was released in September 1998. The album spawned his biggest hit, "Hard Knock Life (Ghetto Anthem)", which sold over 5 million copies by 2000. The album\'s production features a mix of new and old collaborators, including DJ Premier, Swizz Beatz, Timbaland, and Irv Gotti. The album\'s sound is a return to Jay\'s earlier style, with a focus on lyrics and storytelling. The album\'s lead single, "Can I Get A...", was a major hit and helped the album debut at number one on the US Billboard 200 chart.',
    'Vol 2': 'Alternate era name for Vol. 2... Hard Knock Life, Jay-Z\'s third studio album, released September 29, 1998.',
    'Vol. 3... Life and Times of S. Carter': 'JAY-Z\'s fourth studio album, the final in his Vol. series, was released on December 28, 1999. The album featured a more commercial sound, with production from Timbaland and Swizz Beatz, and marked Jay\'s departure from his Mafioso theme. The album was surrounded by controversy, including a leak three months before release and a subsequent altercation with Word Association that led to Jay\'s probation. The album has different track listings in the US and internationally, with some tracks omitted from international releases.',
    'Vol 3': 'Alternate era name for Vol. 3... Life and Times of S. Carter, Jay-Z\'s fourth studio album, released December 28, 1999.',
    'The Dynasty: Roc La Familia': 'The Dynasty: Roc La Familia is often regarded as Jay Z\'s 5th solo album, although it was initially considered a Roc-A-Fella posse album with Jay Z as a guest rapper. Featuring tracks from most Roc-A-Fella artists, the album helped launch the careers of Just Blaze, Kanye West, Bink!, and Beanie Sigel. The album showcases Jay Z\'s personal rhymes, including "Where Have You Been" and "This Can\'t Be Life", which deal with the loss of his father and the struggles of drug addiction.',
    'The Blueprint': 'JAY-Z\'s sixth studio album, "The Blueprint", was released on September 11, 2001. The album was recorded in New York City\'s Manhattan Center Studios and Baseline Studios, with production handled by Kanye West, Just Blaze, Bink, Timbaland, Trackmasters, and Eminem. The album features soul-based sampling and is notable for the breakouts of Kanye West and Just Blaze as major producers. At the time of the album\'s release, JAY-Z was awaiting two criminal trials and was one of the most dissed artists in hip hop, with many rappers including Nas, Prodigy, and Jadakiss targeting him with insults.',
    'The Best Of Both Worlds': 'The Best of Both Worlds is the first collaborative album between Jay Z and R. Kelly, released in 2002 to middling reviews. The duo was formed via mutual relationships both had with the Trackmasters, and they first linked up on “Fiesta (Remix)”. Although the album did go on to sell over a million copies in the US, certifying it platinum, its release was tainted by the R. Kelly underage sex accusations. No videos were released from the project due to this, and a planned tour was scrapped due to the poor publicity surrounding R. Kelly. The album was announced via a star-studded press conference, with P Diddler in attendance and Jay saying, “It’s bigger than music, it’s like Martin and Malcolm coming together.”',
    'Unfinished Business': 'After Jay and Kelly reconnected at the Fade to Black show, in late 2003, a decision was made for them to continue the work of Best of Both Worlds, and use up the leftover songs they had from those sessions. Released October 26, 2004, this record wasn’t plagued by the problems of the first, and a video for first single “Big Chips” was released prior to the album’s release. They toured on the back of the release, titling it the Best of Both Worlds Tour, an unmitigated disaster which saw Kelly leave halfway through, and Jay continue on presenting a solo show “with friends.”.',
    'The Вlueprint²': '"The Blueprint²: The Gift & The Curse" is JAY-Z\'s explicit retelling of his life as a hip-hop superstar, detailing both the highs and lows of his career. Despite being certified Triple Platinum and selling 545,000 copies in its first week, the album is now considered a misstep in his discography. The success of singles "‘03 Bonnie and Clyde" and "Excuse Me Miss" likely boosted sales. The double-disc format was initially suggested by Young Guru, who wanted JAY-Z to join the ranks of Biggie and 2Pac with a critically acclaimed and commercially successful double album.',
    'The Blueprint 2': 'Alternate era name for The Blueprint²: The Gift & The Curse, Jay-Z\'s seventh studio album, released November 12, 2002.',
    'Blueprint 2.1': 'Blueprint 2.1 is a condensed single-disc reissue of The Blueprint², released December 9, 2003.',
    'The Black Album': 'JAY-Z\'s eighth studio album, The Black Album, was released on November 14, 2003. The album was touted as his final release, with retirement being a recurring theme throughout the songs. He originally wanted to collaborate with DJ Premier, but ultimately worked with 10 different producers, including Kanye West, who produced two tracks. The album debuted at #1 on the Billboard 200 and has been certified triple Platinum with sales of over 3.5 million. A documentary, Fade to Black, was also produced to capture the recording of the album and JAY-Z\'s retirement tour.',
    'Kingdom Come': 'Released on November 21st, 2006, Kingdom Come was JAY-Z’s comeback album following his three-year hiatus after the release of The Black Album in 2003. It generally has lukewarm reviews, the album was admittedly rushed, because L.A. Reid wanted the album out by the end of 2006 because Def Jam had no major releases that year, plus other albums suffered illegal downloading. Jay said: “I’m like, ‘We’re not ready. I have some songs but it’s not done and he’s in Africa.’ They’re like ‘If this shit doesn’t come out, people are getting fired. I can’t pay my bills, this record has to come out at this time.’',
    'American Gangster': 'After watching an early screening of "American Gangster" starring Denzel Washington, Jay Z was inspired to create a companion album. The film sparked memories and emotions, and he began writing and recording on the spot. The album, released in November 2007, received widespread critical acclaim, earning an 83 on Metacritic and selling 425,000 copies in its first week. The album, which features singles like "Blue Magic" and "Roc Boys", is considered one of Jay Z\'s best works. The production was handled by Sean Combs, The Neptunes, and Jermaine Dupri, with guest verses from Lil Wayne, Nas, and Beanie Sigel.',
    'The Βlueprint 3': 'The Blueprint 3 is the eleventh studio album by American rapper JAY-Z, released September 8, 2009, on Roc Nation and Roc-A-Fella. It is the third album in the Blueprint series, preceded by The Blueprint (2001) and The Blueprint2: The Gift & The Curse (2002). Production for the album took place during 2008 to 2009 at several recording studios and was handled by Kanye West, No I.D., The Neptunes, Jeff Bhasker, Swizz Beatz, Timbaland and more. The album also features guest appearances by Kanye West, Rihanna, Drake, Kid Cudi, Young Jeezy, J. Cole and Alicia Keys among others.',
    'The Blueprint 3': 'Alternate era name for The Blueprint 3, Jay-Z\'s eleventh studio album, released September 8, 2009.',
    'Watch The Throne': 'Considered one of the most legendary collab albums of all time, Watch the Throne puts together two of the most legendary figures in music history for a full studio album. Kanye teams up with his big brother, JAY-Z, for an album, focused primarily on luxury, black excellence, and the American dream. The album\'s production also reflects that, and having been recorded by two future billionaires primarily in New York City\'s Tribeca Grand Hotel, how could it not?',
    'Magna Carta.. Holy Grail': '"Magna Carta... Holy Grail" is the 12th studio album by JAY-Z, released on July 8, 2013. The album broke multiple records on Spotify, including most streams per day and biggest first week for an album. The album features collaborations with Justin Timberlake, Nas, Rick Ross, Frank Ocean, and Beyoncé, and was produced by Timbaland and others. The album was made available for free digital download to Samsung customers and was released for retail sale. It was certified 2x Platinum by the RIAA in September 2013 and won the "Best Rap/Sung Collaboration" Grammy Award in 2014.',
    '4:44': 'In June 2017, JAY-Z\'s album "4:44" was promoted with posters and ads in New York City, Los Angeles, and online. A teaser ad aired during the NBA Finals, featuring actors Mahershala Ali, Lupita Nyong\'o, and Danny Glover. The album was released exclusively on Tidal and Sprint on June 30, 2017, as part of a partnership between the two companies. The album received widespread critical acclaim for its emotional and personal content. It debuted at number one on the Billboard 200 chart and was certified Platinum by the RIAA. The album spawned two singles and several music videos, and received a Grammy Award nomination for Album of the Year.',
    'EVERYTHING IS LOVE': 'EVERYTHING IS LOVE is the debut collaborative album by THE CARTERS, which consists of power couple Beyoncé and JAY-Z. Like much of the couple’s discography, the album was periodically exclusively available on the streaming service TIDAL, which is primarily owned by JAY-Z and Beyoncé (among other notable artists). It was later added to all streaming services on June 18, 2018. EVERYTHING IS LOVE was released with no prior promotion, similar to Bey’s eponymous BEYONCÉ in 2013 and LEMONADE in 2016',
    'Everything Is Love': 'Alternate era name for Everything Is Love, the collaborative album with Beyoncé released as The Carters on June 16, 2018.',
    'LP14': 'Placeholder name for Jay-Z\'s rumored, unreleased fourteenth studio album.',
    'Streets Is Watching': 'Streets Is Watching is a 1998 direct-to-video film and companion soundtrack compilation released on Roc-A-Fella/Def Jam.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Preasonable Doubt',
    'Reasonable Doubt',
    'In My Lifetime, Vol 1',
    'Vol 1',
    'Vol 2, Hard Knock Life',
    'Vol 2',
    'Vol. 3... Life and Times of S. Carter',
    'Vol 3',
    'The Dynasty: Roc La Familia',
    'The Blueprint',
    'The Best Of Both Worlds',
    'Unfinished Business',
    'The Вlueprint²',
    'The Blueprint 2',
    'Blueprint 2.1',
    'The Black Album',
    'Kingdom Come',
    'American Gangster',
    'The Βlueprint 3',
    'The Blueprint 3',
    'Watch The Throne',
    'Magna Carta.. Holy Grail',
    '4:44',
    'EVERYTHING IS LOVE',
    'Everything Is Love',
    'LP14',
    'Streets Is Watching',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
