import type { ArtistConfig } from './types';

export const jayzgoldConfig: ArtistConfig = {
  slug: 'jayzgold',
  SITE_NAME: 'JAYZGOLD',
  SITE_DESCRIPTION: 'The Best Jay-Z Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/jayzgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'jayzgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#1a1a1a',
  artistLabel: 'Jay-Z',
  cardLetter: 'J',
  logoUrl: '/logos/jayzgold.webp',
  artistPhotoUrl: '/artists/jayz.webp',

  getArtistName() {
    return 'Jay-Z';
  },

  CUSTOM_IMAGES: {
    'Streets Is Watching': '/jayzgold/eras/4-44.jpg',
    'The Best Of Both Worlds': '/jayzgold/eras/the-best-of-both-worlds.jpg',
    'Unfinished Business': '/jayzgold/eras/unfinished-business.jpg',
    'The Black Album': '/jayzgold/eras/the-black-album.jpg',
    'Preasonable Doubt': '/jayzgold/eras/reasonable-doubt.jpg',
    'Reasonable Doubt': '/jayzgold/eras/reasonable-doubt.jpg',
    'In My Lifetime, Vol 1': '/jayzgold/eras/in-my-lifetime-vol-1.jpg',
    'Vol 1': '/jayzgold/eras/in-my-lifetime-vol-1.jpg',
    'Vol 2, Hard Knock Life': '/jayzgold/eras/vol-2-hard-knock-life.jpg',
    'Vol 2': '/jayzgold/eras/vol-2-hard-knock-life.jpg',
    'Vol. 3... Life and Times of S. Carter': '/jayzgold/eras/vol-3-life-and-times-of-s-carter.jpg',
    'Vol 3': '/jayzgold/eras/vol-3-life-and-times-of-s-carter.jpg',
    'The Dynasty: Roc La Familia': '/jayzgold/eras/the-dynasty-roc-la-familia.jpg',
    'The Blueprint': '/jayzgold/eras/the-blueprint.jpg',
    'The Вlueprint²': '/jayzgold/eras/the-blueprint-2.jpg',
    'The Blueprint 2': '/jayzgold/eras/the-blueprint-2.jpg',
    'Blueprint 2.1': '/jayzgold/eras/the-blueprint-2.jpg',
    'Kingdom Come': '/jayzgold/eras/kingdom-come.jpg',
    'American Gangster': '/jayzgold/eras/american-gangster.jpg',
    'The Βlueprint 3': '/jayzgold/eras/the-blueprint-3.jpg',
    'The Blueprint 3': '/jayzgold/eras/the-blueprint-3.jpg',
    'Watch The Throne': '/jayzgold/eras/watch-the-throne.jpg',
    'Magna Carta.. Holy Grail': '/jayzgold/eras/magna-carta-holy-grail.jpg',
    '4:44': '/jayzgold/eras/4-44.jpg',
    'EVERYTHING IS LOVE': '/jayzgold/eras/everything-is-love.jpg',
    'Everything Is Love': '/jayzgold/eras/everything-is-love.jpg',
    'LP14': '/artists/jayz.webp',
  },

  ALBUM_RELEASE_DATES: {
    'Streets Is Watching': '05/12/1998',
    'The Best Of Both Worlds': '03/26/2002',
    'Unfinished Business': '10/29/2002',
    'The Black Album': '11/14/2003',
    'Preasonable Doubt': '??/??/????',
    'Reasonable Doubt': '06/25/1996',
    'In My Lifetime, Vol 1': '11/04/1997',
    'Vol 1': '11/04/1997',
    'Vol 2, Hard Knock Life': '09/29/1998',
    'Vol 2': '09/29/1998',
    'Vol. 3... Life and Times of S. Carter': '12/28/1999',
    'Vol 3': '12/28/1999',
    'The Dynasty: Roc La Familia': '10/31/2000',
    'The Blueprint': '09/11/2001',
    'The Вlueprint²': '11/12/2002',
    'The Blueprint 2': '11/12/2002',
    'Blueprint 2.1': '12/09/2003',
    'Kingdom Come': '11/21/2006',
    'American Gangster': '11/06/2007',
    'The Βlueprint 3': '09/08/2009',
    'The Blueprint 3': '09/08/2009',
    'Watch The Throne': '08/08/2011',
    'Magna Carta.. Holy Grail': '07/04/2013',
    '4:44': '06/30/2017',
    'EVERYTHING IS LOVE': '06/16/2018',
    'Everything Is Love': '06/16/2018',
    'LP14': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Preasonable Doubt': 'Scrapped early Jay-Z project predating Reasonable Doubt, made up of unreleased material recorded before his 1996 debut.',
    'Reasonable Doubt': 'Reasonable Doubt is Jay-Z\'s debut studio album, released June 25, 1996. Widely regarded as one of the greatest hip-hop albums of all time.',
    'In My Lifetime, Vol 1': 'In My Lifetime, Vol. 1 is Jay-Z\'s second studio album, released November 4, 1997.',
    'Vol 1': 'Alternate era name for In My Lifetime, Vol. 1, Jay-Z\'s second studio album, released November 4, 1997.',
    'Vol 2, Hard Knock Life': 'Vol. 2... Hard Knock Life is Jay-Z\'s third studio album, released September 29, 1998, featuring the hit single "Hard Knock Life (Ghetto Anthem)."',
    'Vol 2': 'Alternate era name for Vol. 2... Hard Knock Life, Jay-Z\'s third studio album, released September 29, 1998.',
    'Vol. 3... Life and Times of S. Carter': 'Vol. 3... Life and Times of S. Carter is Jay-Z\'s fourth studio album, released December 28, 1999.',
    'Vol 3': 'Alternate era name for Vol. 3... Life and Times of S. Carter, Jay-Z\'s fourth studio album, released December 28, 1999.',
    'The Dynasty: Roc La Familia': 'The Dynasty: Roc La Familia is Jay-Z\'s fifth studio album, released October 31, 2000, showcasing several Roc-A-Fella artists.',
    'The Blueprint': 'The Blueprint is Jay-Z\'s sixth studio album, released September 11, 2001, widely acclaimed for its soul-sampled production from Kanye West and Just Blaze.',
    'The Best Of Both Worlds': 'The Best of Both Worlds is a collaborative album with R. Kelly, released March 26, 2002.',
    'Unfinished Business': 'Unfinished Business is the second collaborative album with R. Kelly, released October 29, 2002.',
    'The Вlueprint²': 'The Blueprint²: The Gift & The Curse is Jay-Z\'s seventh studio album, a double disc released November 12, 2002.',
    'The Blueprint 2': 'Alternate era name for The Blueprint²: The Gift & The Curse, Jay-Z\'s seventh studio album, released November 12, 2002.',
    'Blueprint 2.1': 'Blueprint 2.1 is a condensed single-disc reissue of The Blueprint², released December 9, 2003.',
    'The Black Album': 'The Black Album is Jay-Z\'s eighth studio album, released November 14, 2003, originally billed as his retirement album.',
    'Kingdom Come': 'Kingdom Come is Jay-Z\'s ninth studio album, released November 21, 2006, marking his comeback after a brief retirement.',
    'American Gangster': 'American Gangster is Jay-Z\'s tenth studio album, released November 6, 2007, a concept album inspired by the film of the same name.',
    'The Βlueprint 3': 'The Blueprint 3 is Jay-Z\'s eleventh studio album, released September 8, 2009.',
    'The Blueprint 3': 'Alternate era name for The Blueprint 3, Jay-Z\'s eleventh studio album, released September 8, 2009.',
    'Watch The Throne': 'Watch the Throne is a collaborative album with Kanye West, released August 8, 2011.',
    'Magna Carta.. Holy Grail': 'Magna Carta... Holy Grail is Jay-Z\'s twelfth studio album, released July 4, 2013.',
    '4:44': '4:44 is Jay-Z\'s thirteenth studio album, released June 30, 2017, produced entirely by No I.D.',
    'EVERYTHING IS LOVE': 'Everything Is Love is a collaborative album with Beyoncé, released as The Carters on June 16, 2018.',
    'Everything Is Love': 'Alternate era name for Everything Is Love, the collaborative album with Beyoncé released as The Carters on June 16, 2018.',
    'LP14': 'Placeholder name for Jay-Z\'s rumored, unreleased fourteenth studio album.',
    'Streets Is Watching': 'Streets Is Watching is a 1998 direct-to-video film and companion soundtrack compilation released on Roc-A-Fella/Def Jam.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Preasonable Doubt',
    'Reasonable Doubt',
    'In My Lifetime, Vol 1',
    'Vol 1',
    'Vol 2, Hard Knock Life',
    'Vol 2',
    'Vol. 3... Life and Times of S. Carter',
    'Vol 3',
    'The Dynasty: Roc La Familia',
    'The Blueprint',
    'The Best Of Both Worlds',
    'Unfinished Business',
    'The Вlueprint²',
    'The Blueprint 2',
    'Blueprint 2.1',
    'The Black Album',
    'Kingdom Come',
    'American Gangster',
    'The Βlueprint 3',
    'The Blueprint 3',
    'Watch The Throne',
    'Magna Carta.. Holy Grail',
    '4:44',
    'EVERYTHING IS LOVE',
    'Everything Is Love',
    'LP14',
    'Streets Is Watching',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
