import type { ArtistConfig } from './types';

export const jojigoldConfig: ArtistConfig = {
  slug: 'jojigold',
  SITE_NAME: 'JOJIGOLD',
  SITE_DESCRIPTION: 'The Best Joji Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/jojigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'jojigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1FPlWbXnx94y5FODJ2qniLf0BzViNSAmj6Xdfw1ZNwQ4/export?format=csv&gid=583378522',
  accentColor: '#9f1239',
  artistLabel: 'Joji',
  cardLetter: 'J',
  logoUrl: '/logos/jojigold.webp',
  artistPhotoUrl: '/artists/joji.jpeg',

  getArtistName() {
    return 'Joji';
  },

  CUSTOM_IMAGES: {
    'George Miller': '/jojigold/eras/george-miller.jpg',
    'Chloe Burbank Volume 1 [V2]': '/jojigold/eras/chloe-burbank-volume-1.jpg',
    'Lost Instruments': '/jojigold/eras/lost-instruments.jpg',
    'In Tongues': '/jojigold/eras/in-tongues.jpg',
    'In Tongues (Deluxe)': '/jojigold/eras/in-tongues.jpg',
    'Green Echo': '/jojigold/eras/green-echo.jpg',
    'Head In The Clouds': '/jojigold/eras/head-in-the-clouds.jpg',
    'BALLADS 1': '/jojigold/eras/ballads-1.jpg',
    'Head In The Clouds II': '/jojigold/eras/head-in-the-clouds-ii.jpg',
    'Nectar': '/jojigold/eras/nectar.jpg',
    'SMITHEREENS': '/jojigold/eras/smithereens.jpg',
    'Piss In The Wind': '/jojigold/eras/piss-in-the-wind.jpg',
    'Piss In The Wind (Deluxe)': '/jojigold/eras/piss-in-the-wind.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'George Miller': '??/??/????',
    'TEMPURA BOYZ': '??/??/????',
    'MC Rukuss': '??/??/????',
    'Before Joji': '??/??/????',
    'JOJI [V1]': '??/??/????',
    'Chloe Burbank Volume 1 [V2]': '??/??/????',
    'Lost Instruments': '10/27/2017',
    'In Tongues': '11/03/2017',
    'In Tongues (Deluxe)': '02/14/2018',
    'Green Echo': '??/??/????',
    'Head In The Clouds': '07/20/2018',
    'BALLADS 1': '10/26/2018',
    'Head In The Clouds II': '10/11/2019',
    'Nectar': '07/10/2020',
    'The Extravaganza': '??/??/????',
    'SMITHEREENS': '06/10/2022',
    'PLUMMCORP': '??/??/????',
    'Piss In The Wind': '02/06/2026',
    'Piss In The Wind (Deluxe)': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'George Miller': "Early comedic persona and YouTube name George Miller used before adopting the Joji music persona.",
    'TEMPURA BOYZ': 'Early comedy rap duo project George Miller was part of on YouTube, prior to becoming Joji.',
    'MC Rukuss': 'Another early comedic rap alias used by George Miller on YouTube before the Joji persona.',
    'Before Joji': 'Catch-all for material made before George Miller adopted the Joji music persona.',
    'JOJI [V1]': 'Early working sessions and scrapped material from the beginning of the Joji era.',
    'Chloe Burbank Volume 1 [V2]': "Chloe Burbank, Vol. 1 is Joji's debut mixtape, released independently in March 2017.",
    'Lost Instruments': 'Instrumental collection released October 27, 2017, made up of beats and unused production.',
    'In Tongues': "In Tongues is Joji's debut EP, released November 3, 2017 via 88rising and 12Tone Music.",
    'In Tongues (Deluxe)': 'Deluxe reissue of In Tongues, released February 14, 2018 with additional tracks.',
    'Green Echo': 'Rare, little-documented Joji-era release.',
    'Head In The Clouds': "Head In The Clouds is Joji's debut studio album, released July 20, 2018.",
    'BALLADS 1': "BALLADS 1 is Joji's second studio album, released October 26, 2018, featuring the hit single \"SLOW DANCING IN THE DARK.\"",
    'Head In The Clouds II': '88rising label compilation album released October 11, 2019, featuring Joji alongside other 88rising artists.',
    'Nectar': "Nectar is Joji's third studio album, released July 10, 2020.",
    'The Extravaganza': 'Material associated with a Joji-era tour or promotional campaign.',
    'SMITHEREENS': "SMITHEREENS is Joji's fourth studio album, released June 10, 2022.",
    'PLUMMCORP': "Name associated with Joji's creative outlet/brand, used for miscellaneous related material.",
    'Piss In The Wind': "Joji's newest project, expected to release around early 2026.",
    'Piss In The Wind (Deluxe)': 'Planned deluxe edition of Piss In The Wind.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'George Miller',
    'TEMPURA BOYZ',
    'MC Rukuss',
    'Before Joji',
    'JOJI [V1]',
    'Chloe Burbank Volume 1 [V2]',
    'Lost Instruments',
    'In Tongues',
    'In Tongues (Deluxe)',
    'Green Echo',
    'Head In The Clouds',
    'BALLADS 1',
    'Head In The Clouds II',
    'Nectar',
    'The Extravaganza',
    'SMITHEREENS',
    'PLUMMCORP',
    'Piss In The Wind',
    'Piss In The Wind (Deluxe)',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: true,
  hasSubAlbumsTab: false,
};
