import type { ArtistConfig } from './types';

export const jojigoldConfig: ArtistConfig = {
  slug: 'jojigold',
  SITE_NAME: 'JOJIGOLD',
  SITE_DESCRIPTION: 'The Best Joji Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/jojigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'jojigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1FPlWbXnx94y5FODJ2qniLf0BzViNSAmj6Xdfw1ZNwQ4/export?format=csv&gid=583378522',
  accentColor: '#9f1239',
  artistLabel: 'Joji',
  cardLetter: 'J',
  logoUrl: '/logos/jojigold.webp',
  artistPhotoUrl: '/artists/joji.jpg',

  getArtistName() {
    return 'Joji';
  },

  CUSTOM_IMAGES: {
    'George Miller': '/jojigold/eras/george-miller.jpg',
    'Chloe Burbank Volume 1 [V2]': '/jojigold/eras/chloe-burbank-volume-1.jpg',
    'Lost Instruments': '/jojigold/eras/lost-instruments.jpg',
    'In Tongues': '/jojigold/eras/in-tongues.jpg',
    'In Tongues (Deluxe)': '/jojigold/eras/in-tongues.jpg',
    'Green Echo': '/jojigold/eras/green-echo.jpg',
    'Head In The Clouds': '/jojigold/eras/head-in-the-clouds.jpg',
    'BALLADS 1': '/jojigold/eras/ballads-1.jpg',
    'Head In The Clouds II': '/jojigold/eras/head-in-the-clouds-ii.jpg',
    'Nectar': '/jojigold/eras/nectar.jpg',
    'SMITHEREENS': '/jojigold/eras/smithereens.jpg',
    'Piss In The Wind': '/jojigold/eras/piss-in-the-wind.jpg',
    'Piss In The Wind (Deluxe)': '/jojigold/eras/piss-in-the-wind.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'George Miller': '??/??/????',
    'TEMPURA BOYZ': '??/??/????',
    'MC Rukuss': '??/??/????',
    'Before Joji': '??/??/????',
    'JOJI [V1]': '??/??/????',
    'Chloe Burbank Volume 1 [V2]': '??/??/????',
    'Lost Instruments': '10/27/2017',
    'In Tongues': '11/03/2017',
    'In Tongues (Deluxe)': '02/14/2018',
    'Green Echo': '??/??/????',
    'Head In The Clouds': '07/20/2018',
    'BALLADS 1': '10/26/2018',
    'Head In The Clouds II': '10/11/2019',
    'Nectar': '07/10/2020',
    'The Extravaganza': '??/??/????',
    'SMITHEREENS': '06/10/2022',
    'PLUMMCORP': '??/??/????',
    'Piss In The Wind': '02/06/2026',
    'Piss In The Wind (Deluxe)': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'George Miller',
    'TEMPURA BOYZ',
    'MC Rukuss',
    'Before Joji',
    'JOJI [V1]',
    'Chloe Burbank Volume 1 [V2]',
    'Lost Instruments',
    'In Tongues',
    'In Tongues (Deluxe)',
    'Green Echo',
    'Head In The Clouds',
    'BALLADS 1',
    'Head In The Clouds II',
    'Nectar',
    'The Extravaganza',
    'SMITHEREENS',
    'PLUMMCORP',
    'Piss In The Wind',
    'Piss In The Wind (Deluxe)',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: true,
  hasSubAlbumsTab: false,
};
