import type { ArtistConfig } from './types';

const SHEET_ID = '1tD3ytt5wPx4zfcefXi5ATeYhIiDaugWjMS46nZrP568';

export const juicegoldConfig: ArtistConfig = {
  slug: 'juicegold',
  SITE_NAME: 'JUICEgold',
  SITE_DESCRIPTION: 'The Best Juice WRLD Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/juicegold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'juicegold_',
  HARDCODED_SHEET_ID: SHEET_ID,
  HARDCODED_SHEET_GID: '0',
  SHEET_URL_UNRELEASED: `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=0`,
  SHEET_URL_RECENT: `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=1558109614`,

  accentColor: '#e53e3e',
  artistLabel: 'Juice WRLD',
  cardLetter: 'JCE',
  logoUrl: '/logos/juicegold.png',
  artistPhotoUrl: '/artists/juice.webp',

  getArtistName(_eraName) { return 'Juice WRLD'; },

  CUSTOM_IMAGES: {
    '999': '',
    'A Forgotten Love Story': '',
    'Goodbye & Good Riddance': 'https://upload.wikimedia.org/wikipedia/en/6/6f/Juice_Wrld_Goodbye_Good_Riddance.jpg',
    'Goodbye & Good Riddance [V1]': 'https://upload.wikimedia.org/wikipedia/en/6/6f/Juice_Wrld_Goodbye_Good_Riddance.jpg',
    'Goodbye & Good Riddance [V2]': 'https://upload.wikimedia.org/wikipedia/en/6/6f/Juice_Wrld_Goodbye_Good_Riddance.jpg',
    'Death Race for Love': 'https://upload.wikimedia.org/wikipedia/en/5/57/Juice_WRLD_Death_Race_for_Love_album_cover.jpg',
    'Death Race for Love [V1]': 'https://upload.wikimedia.org/wikipedia/en/5/57/Juice_WRLD_Death_Race_for_Love_album_cover.jpg',
    'Death Race for Love [V2]': 'https://upload.wikimedia.org/wikipedia/en/5/57/Juice_WRLD_Death_Race_for_Love_album_cover.jpg',
    'Legends Never Die': 'https://upload.wikimedia.org/wikipedia/en/f/ff/Juice_Wrld_-_Legends_Never_Die.png',
    'Legends Never Die [V1]': 'https://upload.wikimedia.org/wikipedia/en/f/ff/Juice_Wrld_-_Legends_Never_Die.png',
    'Legends Never Die [V2]': 'https://upload.wikimedia.org/wikipedia/en/f/ff/Juice_Wrld_-_Legends_Never_Die.png',
    'Fighting Demons': 'https://upload.wikimedia.org/wikipedia/en/6/6d/Juice_WRLD_-_Fighting_Demons.png',
    'Fighting Demons [V1]': 'https://upload.wikimedia.org/wikipedia/en/6/6d/Juice_WRLD_-_Fighting_Demons.png',
    'The Party Never Ends': '',
    'Unreleased': '',
    'Unknown': '',
    'Ongoing': '',
  },

  ALBUM_RELEASE_DATES: {
    '999': '??/??/2017',
    'A Forgotten Love Story': '??/??/2017',
    'Goodbye & Good Riddance [V1]': '??/??/2018',
    'Goodbye & Good Riddance [V2]': '??/??/2018',
    'Goodbye & Good Riddance': '05/23/2018',
    'Death Race for Love [V1]': '??/??/2019',
    'Death Race for Love [V2]': '??/??/2019',
    'Death Race for Love': '03/08/2019',
    'Legends Never Die [V1]': '??/??/2020',
    'Legends Never Die [V2]': '??/??/2020',
    'Legends Never Die': '07/10/2020',
    'Fighting Demons [V1]': '??/??/2021',
    'Fighting Demons': '12/10/2021',
    'The Party Never Ends': '??/??/2022',
    'Unreleased': '??/??/????',
    'Unknown': '??/??/????',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: ['Unknown'],

  ALBUM_DESCRIPTIONS: {
    '999': 'Juice WRLD\'s earliest era — loosies and early recordings from before his major label deal.',
    'A Forgotten Love Story': 'Early unreleased project from Juice WRLD\'s pre-debut period.',
    'Goodbye & Good Riddance': 'Juice WRLD\'s debut studio album, released May 23, 2018 on Grade A Productions / Interscope.',
    'Goodbye & Good Riddance [V1]': 'First working sessions for Goodbye & Good Riddance.',
    'Goodbye & Good Riddance [V2]': 'Later sessions for Goodbye & Good Riddance.',
    'Death Race for Love': 'Juice WRLD\'s second studio album, released March 8, 2019. Debuted at #1 on the Billboard 200.',
    'Death Race for Love [V1]': 'First working sessions for Death Race for Love.',
    'Death Race for Love [V2]': 'Second working sessions for Death Race for Love.',
    'Legends Never Die': 'First posthumous album, released July 10, 2020 — eight months after Juice WRLD\'s passing.',
    'Legends Never Die [V1]': 'First working sessions for Legends Never Die.',
    'Legends Never Die [V2]': 'Second working sessions for Legends Never Die.',
    'Fighting Demons': 'Second posthumous album, released December 10, 2021.',
    'Fighting Demons [V1]': 'Working sessions for Fighting Demons.',
    'The Party Never Ends': 'Third posthumous album and unreleased material from 2022 onwards.',
    'Unreleased': 'Unreleased songs without a confirmed era.',
    'Unknown': 'Songs without a confirmed era or source.',
    'Ongoing': 'Ongoing posthumous projects and material.',
  },

  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},

  ERA_MAPPINGS: {
    '999*': '999',
    'A Forgotten Love Story*': 'A Forgotten Love Story',
    'Goodbye & Good Riddance [V1]*': 'Goodbye & Good Riddance [V1]',
    'Goodbye & Good Riddance [V2]*': 'Goodbye & Good Riddance [V2]',
    'Goodbye & Good Riddance*': 'Goodbye & Good Riddance',
    'GAGR*': 'Goodbye & Good Riddance',
    'Death Race for Love [V1]*': 'Death Race for Love [V1]',
    'Death Race for Love [V2]*': 'Death Race for Love [V2]',
    'Death Race for Love*': 'Death Race for Love',
    'DRFL*': 'Death Race for Love',
    'Legends Never Die [V1]*': 'Legends Never Die [V1]',
    'Legends Never Die [V2]*': 'Legends Never Die [V2]',
    'Legends Never Die*': 'Legends Never Die',
    'LND*': 'Legends Never Die',
    'Fighting Demons [V1]*': 'Fighting Demons [V1]',
    'Fighting Demons*': 'Fighting Demons',
    'The Party Never Ends*': 'The Party Never Ends',
    'TPNE*': 'The Party Never Ends',
    'Unreleased*': 'Unreleased',
    'Unknown*': 'Unknown',
    'Ongoing*': 'Ongoing',
  },

  hasRecentTab: true,
  hasCompsTab: false,
  hasConcertsTab: false,

  TAG_MAP: {
    '⭐': 'Best Of',
    '🏆': 'Grails',
    '🥇': 'Wanted',
    '🏅': 'Wanted',
    '✨': 'Notable',
    '💚': 'By JUICEgold',
    '🗑️': 'Worst Of',
    '🗑': 'Worst Of',
    '🚮': 'Unwanted',
    '🤖': 'AI',
    '⁉️': 'Lost Media',
    '⁉': 'Lost Media',
    '❓': 'Unknown',
    '⭐️': 'Best Of',
  },

  ERA_THEMES: {
    'Goodbye & Good Riddance': {},
    'Death Race for Love': {},
    'Legends Never Die': {},
    'Fighting Demons': {},
    'The Party Never Ends': {},
  },

  TAG_TOOLTIP_MAP: {
    'Best Of': 'Some of the best leaks on the tracker.',
    'Grails': 'The most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as much as Grails.',
    'Notable': 'Notable songs worth highlighting.',
    'Worst Of': 'Some of the worst leaks on the tracker.',
    'Unwanted': 'Songs we don\'t want to see leak in full.',
    'AI': 'Track contains AI vocals.',
    'Lost Media': 'Currently lost, or no link to the media is known.',
    'By JUICEgold': 'Leaks & songs added by the owner of the site.',
    'Unknown': 'Availability or status is unknown.',
  },
};
