import type { ArtistConfig } from './types';

export const kdotgoldConfig: ArtistConfig = {
  slug: 'kdotgold',
  SITE_NAME: 'KDOTgold',
  SITE_DESCRIPTION: 'The Best Kendrick Lamar Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/kdotgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'kdotgold_',
  HARDCODED_SHEET_ID: '1i4OQglDHiiqMDthqfUFPutGmpZzK7n63LaoWApqhQXI',
  HARDCODED_SHEET_GID: '1169728352',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: `https://docs.google.com/spreadsheets/d/1i4OQglDHiiqMDthqfUFPutGmpZzK7n63LaoWApqhQXI/gviz/tq?tqx=out:csv&sheet=🆕 Recent`,
  accentColor: '#1e3a5f',
  artistLabel: 'Kendrick Lamar',
  cardLetter: 'KDT',
  logoUrl: '/logos/kdotgold.png',
  artistPhotoUrl: '/artists/kendrick.webp',

  getArtistName(_eraName) { return 'Kendrick Lamar'; },

  CUSTOM_IMAGES: {
    "Y.H.N.I.C.": "https://i.ibb.co/RBDrKXS/Y-N-I-C.jpg",
    "Training Day": "https://i.ibb.co/4McYcND/Training-Day.jpg",
    "C4": "https://i.ibb.co/FWCG4C5/C4.jpg",
    "No Sleep 'Til NYC": "https://i.ibb.co/d4kX6Bng/AHOq17-EI6-C3-GUai6he-Tl-RIs0-nz-P1iq5-Ax9n-1t37q-K4pxku-A997-UIn-TY0mav8-YXe-Ewuf-H0e-CTZf72ylm-FEe.jpg",
    "The Kendrick Lamar EP": "https://i.ibb.co/8XC0LcQ/Kendrick-Lamar-EP.jpg",
    "Overly Dedicated": "https://i.ibb.co/VW7gryWb/download.jpg",
    "Collaboration with J. Cole": "https://i.ibb.co/vCs6Jb0v/Image.png",
    "Section.80": "https://i.ibb.co/ZRtB0zpk/Section-80.jpg",
    "good kid, m.A.A.d city": "https://i.ibb.co/3YvW46Lb/good-kid-m-A-A-d-city.jpg",
    "Tu Pimp A Caterpillar": "https://i.ibb.co/29SK0P3/Image-2.png",
    "Tu Pimp A Caterpillar [V1]": "https://i.ibb.co/29SK0P3/Image-2.png",
    "To Pimp A Butterfly": "https://i.ibb.co/C5GdgrwX/To-Pimp-A-Butterfly.jpg",
    "To Pimp A Butterfly [V2]": "https://i.ibb.co/C5GdgrwX/To-Pimp-A-Butterfly.jpg",
    "untitled unmastered.": "https://i.ibb.co/32KtvFr/untitled-unmastered.jpg",
    "DAMN.": "https://i.ibb.co/r2SMpmg3/DAMN.jpg",
    "Black Panther: The Album": "https://i.ibb.co/rGRm8Z0v/Image.jpg",
    "Look Woman": "https://i.ibb.co/pBJCSK9k/Image-3.png",
    "Everybody Sensitive": "https://i.ibb.co/fYgL3mJV/Image-4.png",
    "Everybody Sensitive [V1]": "https://i.ibb.co/fYgL3mJV/Image-4.png",
    "Mr. Morale [V2]": "https://i.ibb.co/9kkJvWQm/Image-2.jpg",
    "Mr. Morale [V3]": "https://i.ibb.co/4Rxjb4yC/Mr-Morale-The-Big-Steppers.jpg",
    "Mr. Morale & The Big Steppers": "https://i.ibb.co/4Rxjb4yC/Mr-Morale-The-Big-Steppers.jpg",
    "GNX": "https://i.ibb.co/VpNknRNt/GNX.jpg",
    "Drake vs. Kendrick Lamar": "https://i.ibb.co/1frf2JRC/9b2nomrjr91d1.jpg",
    "Rap Album": "https://i.ibb.co/6Qxb2yS/Image-5.png",
    "Compton Cowboys": "https://i.ibb.co/7JgDpKSQ/Image-6.png",
  },

  ALBUM_RELEASE_DATES: {
    "Y.H.N.I.C.": "??/??/2003",
    "Training Day": "??/??/2005",
    "No Sleep 'Til NYC": "11/13/2007",
    "C4": "01/30/2009",
    "The Kendrick Lamar EP": "??/??/2009",
    "Overly Dedicated": "09/14/2010",
    "Section.80": "07/02/2011",
    "Collaboration with J. Cole": "??/??/????",
    "good kid, m.A.A.d city": "10/22/2012",
    "Tu Pimp A Caterpillar [V1]": "??/??/2014",
    "To Pimp A Butterfly": "03/15/2015",
    "untitled unmastered.": "03/04/2016",
    "DAMN.": "04/14/2017",
    "Black Panther: The Album": "02/09/2018",
    "Look Woman": "??/??/????",
    "Everybody Sensitive [V1]": "??/??/????",
    "Mr. Morale [V2]": "??/??/????",
    "Mr. Morale [V3]": "??/??/????",
    "Mr. Morale & The Big Steppers": "05/13/2022",
    "Drake vs. Kendrick Lamar": "??/??/2024",
    "GNX": "11/22/2024",
    "Rap Album": "??/??/????",
    "Compton Cowboys": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ART_ONLY_ALBUMS: ['Y.H.N.I.C.', 'Mr. Morale & The Big Steppers'],
  ALBUM_DESCRIPTIONS: {
    "Y.H.N.I.C.": "K-Dot's earliest known mixtape, recorded and circulated around 2003 when Kendrick was a teenager.",
    "Training Day": "Early K-Dot mixtape released in 2005.",
    "No Sleep 'Til NYC": "K-Dot mixtape released in November 2007.",
    "C4": "K-Dot mixtape released January 30, 2009.",
    "The Kendrick Lamar EP": "Kendrick's first release under his own name rather than the K-Dot alias, self-released independently in 2009.",
    "Overly Dedicated": "Mixtape released September 14, 2010 via Top Dawg Entertainment; the project that first brought Kendrick wider recognition.",
    "Collaboration with J. Cole": "Catch-all era for loose, unreleased collaborative recordings between Kendrick Lamar and J. Cole; a full joint album between the two has never materialized.",
    "Section.80": "Kendrick's official debut studio album, released independently via Top Dawg Entertainment on July 2, 2011.",
    "good kid, m.A.A.d city": "Kendrick's major-label debut studio album, released October 22, 2012 via Aftermath/Interscope; a concept album about growing up in Compton.",
    "Tu Pimp A Caterpillar [V1]": "Early working stage of what would become To Pimp A Butterfly, dating to around 2013-2014.",
    "To Pimp A Butterfly": "Kendrick's third studio album, released March 15, 2015; a jazz- and funk-influenced record widely considered one of the best albums of its era.",
    "untitled unmastered.": "Compilation of demos and outtakes from the To Pimp A Butterfly sessions, released March 4, 2016.",
    "DAMN.": "Kendrick's fourth studio album, released April 14, 2017; won the Pulitzer Prize for Music in 2018.",
    "Black Panther: The Album": "Soundtrack and companion album to the film Black Panther, curated and produced by Kendrick Lamar and Top Dawg Entertainment, released February 9, 2018.",
    "Look Woman": "Shelved album project recorded around 2018-2019, prior to the sessions that became Mr. Morale & The Big Steppers.",
    "Everybody Sensitive [V1]": "Early working title and version of the album sessions that eventually became Mr. Morale & The Big Steppers.",
    "Mr. Morale [V2]": "Later working-title stage of the same album sessions, before the project's release as Mr. Morale & The Big Steppers.",
    "Mr. Morale [V3]": "Further-along working-title stage of the same album sessions, shortly before its final release as Mr. Morale & The Big Steppers.",
    "Mr. Morale & The Big Steppers": "Kendrick's fifth studio album, a double album released May 13, 2022.",
    "Drake vs. Kendrick Lamar": "Catch-all era for the 2024 rap feud between Kendrick Lamar and Drake, covering diss tracks like \"Euphoria,\" \"6:16 in LA,\" and \"Not Like Us.\"",
    "GNX": "Kendrick's sixth studio album, a surprise release on November 22, 2024.",
    "Rap Album": "Catch-all/placeholder era for unreleased material believed to be from Kendrick's next studio album.",
    "Compton Cowboys": "Shelved project title tied to material recorded around 2023, around the same time as the GNX sessions.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  hasCompsTab: false,
  hasConcertsTab: false,
  hasSubAlbumsTab: false,

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By KDOTgold', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By KDOTgold': 'Leaks & Songs added by the owner of the site.',
  },
};
