import type { ArtistConfig } from './types';

export const kdotgoldConfig: ArtistConfig = {
  slug: 'kdotgold',
  hasAlbumCopiesTab: true,
  SITE_NAME: 'KDOTgold',
  SITE_DESCRIPTION: 'The Best Kendrick Lamar Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/kdotgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'kdotgold_',
  HARDCODED_SHEET_ID: '1i4OQglDHiiqMDthqfUFPutGmpZzK7n63LaoWApqhQXI',
  HARDCODED_SHEET_GID: '1169728352',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: `https://docs.google.com/spreadsheets/d/1i4OQglDHiiqMDthqfUFPutGmpZzK7n63LaoWApqhQXI/gviz/tq?tqx=out:csv&sheet=🆕 Recent`,
  accentColor: '#1e3a5f',
  artistLabel: 'Kendrick Lamar',
  cardLetter: 'KDT',
  logoUrl: '/logos/kdotgold.png',
  artistPhotoUrl: '/artists/kendrick.webp',

  getArtistName(_eraName) { return 'Kendrick Lamar'; },

  CUSTOM_IMAGES: {
    "Y.H.N.I.C.": "https://i.ibb.co/RBDrKXS/Y-N-I-C.jpg",
    "Training Day": "https://i.ibb.co/4McYcND/Training-Day.jpg",
    "C4": "https://i.ibb.co/FWCG4C5/C4.jpg",
    "No Sleep 'Til NYC": "https://i.ibb.co/d4kX6Bng/AHOq17-EI6-C3-GUai6he-Tl-RIs0-nz-P1iq5-Ax9n-1t37q-K4pxku-A997-UIn-TY0mav8-YXe-Ewuf-H0e-CTZf72ylm-FEe.jpg",
    "The Kendrick Lamar EP": "https://i.ibb.co/8XC0LcQ/Kendrick-Lamar-EP.jpg",
    "Overly Dedicated": "https://i.ibb.co/VW7gryWb/download.jpg",
    "Collaboration with J. Cole": "https://i.ibb.co/vCs6Jb0v/Image.png",
    "Section.80": "https://i.ibb.co/ZRtB0zpk/Section-80.jpg",
    "good kid, m.A.A.d city": "https://i.ibb.co/3YvW46Lb/good-kid-m-A-A-d-city.jpg",
    "Tu Pimp A Caterpillar": "https://i.ibb.co/29SK0P3/Image-2.png",
    "Tu Pimp A Caterpillar [V1]": "https://i.ibb.co/29SK0P3/Image-2.png",
    "To Pimp A Butterfly": "https://i.ibb.co/C5GdgrwX/To-Pimp-A-Butterfly.jpg",
    "To Pimp A Butterfly [V2]": "https://i.ibb.co/C5GdgrwX/To-Pimp-A-Butterfly.jpg",
    "untitled unmastered.": "https://i.ibb.co/32KtvFr/untitled-unmastered.jpg",
    "DAMN.": "https://i.ibb.co/r2SMpmg3/DAMN.jpg",
    "Black Panther: The Album": "https://i.ibb.co/rGRm8Z0v/Image.jpg",
    "Look Woman": "https://i.ibb.co/pBJCSK9k/Image-3.png",
    "Everybody Sensitive": "https://i.ibb.co/fYgL3mJV/Image-4.png",
    "Everybody Sensitive [V1]": "https://i.ibb.co/fYgL3mJV/Image-4.png",
    "Mr. Morale [V2]": "https://i.ibb.co/9kkJvWQm/Image-2.jpg",
    "Mr. Morale [V3]": "https://i.ibb.co/4Rxjb4yC/Mr-Morale-The-Big-Steppers.jpg",
    "Mr. Morale & The Big Steppers": "https://i.ibb.co/4Rxjb4yC/Mr-Morale-The-Big-Steppers.jpg",
    "GNX": "https://i.ibb.co/VpNknRNt/GNX.jpg",
    "Drake vs. Kendrick Lamar": "https://i.ibb.co/1frf2JRC/9b2nomrjr91d1.jpg",
    "Rap Album": "https://i.ibb.co/6Qxb2yS/Image-5.png",
    "Compton Cowboys": "https://i.ibb.co/7JgDpKSQ/Image-6.png",
  },

  ALBUM_RELEASE_DATES: {
    "Y.H.N.I.C.": "??/??/2003",
    "Training Day": "??/??/2005",
    "No Sleep 'Til NYC": "11/13/2007",
    "C4": "01/30/2009",
    "The Kendrick Lamar EP": "??/??/2009",
    "Overly Dedicated": "09/14/2010",
    "Section.80": "07/02/2011",
    "Collaboration with J. Cole": "??/??/????",
    "good kid, m.A.A.d city": "10/22/2012",
    "Tu Pimp A Caterpillar [V1]": "??/??/2014",
    "To Pimp A Butterfly": "03/15/2015",
    "untitled unmastered.": "03/04/2016",
    "DAMN.": "04/14/2017",
    "Black Panther: The Album": "02/09/2018",
    "Look Woman": "??/??/????",
    "Everybody Sensitive [V1]": "??/??/????",
    "Mr. Morale [V2]": "??/??/????",
    "Mr. Morale [V3]": "??/??/????",
    "Mr. Morale & The Big Steppers": "05/13/2022",
    "Drake vs. Kendrick Lamar": "??/??/2024",
    "GNX": "11/22/2024",
    "Rap Album": "??/??/????",
    "Compton Cowboys": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ART_ONLY_ALBUMS: ['Y.H.N.I.C.', 'Mr. Morale & The Big Steppers'],
  ALBUM_DESCRIPTIONS: {
    "Y.H.N.I.C.": "K-Dot's earliest known mixtape, recorded and circulated around 2003 when Kendrick was a teenager.",
    "Training Day": "Training Day is Kendrick Lamar’s second mixtape, but formally considered by himself his debut mixtape, he was 18 at the time and went under the name “K-Dot.” In this mixtape, Kendrick raps to many old-school​ beats as well as some new ones, like The Notorious B.I.G’s “Who Shot Ya” and André 3000’s “Prototype.” It also features an interview with DJ Dave, one of the primary beat producers for this tape.",
    "No Sleep 'Til NYC": "No Sleep 'Til NYC is the third mixtape by Kendrick Lamar and his first collaborative mixtape with Jay Rock. It was released on November 13th, 2007. The mixtape contains 26 tracks and features Ab-Soul and Punch on a handful of tracks. The mixtape features a lot of productions from DJs such as DJ Big Mike the Rule, DJ Envy, DJ Skee and DJ Warrior. Like on Training Day, both Kendrick and Jay Rock rap on many old-school​ beats such as \"Electric Relaxation\", \"It Ain't Hard To Tell\" and \"Dead Presidents II\".",
    "C4": "C4 is the fourth mixtape by American rapper Kendrick Lamar, then known as \"K.Dot\". It was released on January 30, 2009 through Top Dawg Entertainment (TDE). The mixtape contains 17 tracks and includes guest appearances from Lamar's TDE label-mates Ab-Soul, Punch, Jay Rock, ScHoolboy Q, and BO. The mixtape was heavily inspired by fellow American rapper Lil Wayne’s 2008 critically acclaimed album, Tha Carter III (C3), being mostly composed of freestyles over instrumentals from Wayne’s album in addition to a couple of original tracks.",
    "The Kendrick Lamar EP": "Kendrick Lamar is an EP by American rapper Kendrick Lamar that was released as a free digital download on December 31, 2009 by Top Dawg Entertainment. It is his first project to be released under his birth name, previously releasing music under the moniker K.Dot, from 2006 to mid 2009. Executive produced by DudeDawg, dee:jay:dave and Sounwave.",
    "Overly Dedicated": "Overly Dedicated—sometimes stylized O(verly) D(edicated)—is Kendrick Lamar’s fifth solo mixtape, released on September 14, 2010 via Top Dawg Entertainment. The cover art features different artists and musicians that have passed away, most of them from drug overdoses. These artists include: Michael Jackson, Pimp C, Ol' Dirty Bastard, Jimi Hendrix, Jim Morrison, Kurt Cobain, Sacer, Eric Snow, Dashiell “Dash” Snow, Robert Johnson and Bruce Lee.",
    "Collaboration with J. Cole": "In late 2010, Kendrick and J. Cole decided to work on a collab project. They were able to finish a couple of songs, with a couple beats laying around waiting to be used. It's been delayed since, possibly, 2013. The idea of the album coming into fruition is still possible, but as of right now neither Cole or Kendrick are focused on it. Kendrick put his focus on \"To Pimp A Butterfly\" and J. Cole put his focus on \"2014 Forest Hills Drive\". Although they would team up again for the \"Black Friday\" tracks teasing an album, no collab was released.",
    "Section.80": "Section.80 is Kendrick Lamar’s first full-length project, released on July 2, 2011, via Top Dawg Entertainment; although the project was marketed and distributed like a studio album, Lamar has consistently referred to it as a mixtape. The title, Section.80, is a combination of Section 8 Housing and the decade that Kendrick was born in—the 1980s. “The Spiteful Chant” was notably removed from streaming services in August 2019. (While the issue was never discovered, it’s presumed to be because of sample clearance issues.)",
    "good kid, m.A.A.d city": "good kid, m.A.A.d city is Kendrick Lamar’s major label debut, released on October 22, 2012 through Top Dawg Entertainment, Aftermath Entertainment and Interscope Records. Subtitled “A Short Film by Kendrick Lamar,” this concept album depicts a day in the life of a 17-year-old Lamar as he rides around Compton in his mom’s minivan. The first twelve tracks make up the standard edition of the album, and there are a variety of different deluxe editions including various bonus tracks. The album was re-released on March 19, 2013 with a bonus remix of “Bitch, Don’t Kill My Vibe” featuring JAŸ-Z.",
    "Tu Pimp A Caterpillar [V1]": "From 2012 to 2014, Kendrick worked on his next album titled \"Tu Pimp A Caterpillar\" in reference to the rapper Tupac. Work was proceeding like normal until Kendrick took a trip to South Africa in February 2014 to perform. When he visited, it moved him so much to the point where he completely scrapped the songs from this project for a more ambitious project. That project would turn into \"To Pimp A Butterfly\".",
    "To Pimp A Butterfly": "To Pimp a Butterfly is Kendrick Lamar’s second major label studio album, and third full-length project. It was released via Top Dawg Entertainment, Aftermath Entertainment, and Interscope Records. It followed his critically-acclaimed 2012 debut, good kid, m.A.A.d city. The album was very well-received upon release, eventually earning 11 Grammy nominations, and it has gone on to be hailed as one of the greatest hip-hop albums of all time. In contrast to Lamar’s previous projects, TPAB took more heavily from jazz, soul, and funk influences, with such contributors as Thundercat, Terrace Martin, Kamasi Washington, and Flying Lotus providing instrumentation and production.",
    "untitled unmastered.": "Compilation of demos and outtakes from the To Pimp A Butterfly sessions, released March 4, 2016.",
    "DAMN.": "DAMN., Kendrick Lamar’s fourth studio album, was expected to be released on April 7, 2017, after he rapped these lines on “The Heart Part 4”: \"Y'all got ‘til April the 7th to get y'all shit together\". However, when the pre-order was released, it was announced that it would appear on Good Friday—April 14, 2017. This is Kendrick’s first full-length project since 2015’s To Pimp A Butterfly. In between the albums, Kendrick released the 8-track EP untitled unmastered.",
    "Black Panther: The Album": "Black Panther: The Album is a compilation of music from and inspired by the 2018 Marvel film Black Panther. The compilation was released on February 9, 2018 (one week before the release of the film) through Top Dawg Entertainment, Aftermath Entertainment and Interscope Records. “All The Stars”, “Opps” and “Pray For Me” all make appearances in the film itself, while the rest are inspired by the movie. The soundtrack is executive produced by Kendrick Lamar and TDE CEO Anthony “Top Dawg” Tiffith.",
    "Look Woman": "During the early stages of Everybody Sensitive, Kendrick worked on a side project titled Look Woman, uncommonly titled Look Woman, Amen!. There was a tracklist made for the project and only a bit of work was put into it before being scrapped altogether to focus on Mr. Morale. There are two versions of the album that were considered, one of a relationship focusing on women and another as a \"horror film\". The remaining songs were given to other artists like Beyoncé and Rihanna.",
    "Everybody Sensitive [V1]": "After Black Panther: The Album, Kendrick works on his next album with much anticipation, titled Everybody Sensitive. He planned for the album to be more personal. Things were going smoothly with a 2019 release date in mind but Kendrick was not able to finish the album by then, continuing his work into 2020. It's assumed that Kendrick would've used pgLang's YouTube channel as a way to promote his and Baby Keem's next album due to the now deleted \"Visual Mission Statement\" video. Three known tracklists of the album exists, two from 2018 and a finalized version in 2019, which include notes from Kendrick about the concept, sound, producers, and samples.",
    "Mr. Morale [V2]": "Despite Kendrick's own delays and worldwide COVID lockdowns, he continued to work on the album at a steady pace. Songs received major reworks and by May, a 2020 version of the album was finished in the process of being mixed and mastered. However, Kendrick's team would delay finishing the rest of the album after May 5th since they agreed that COVID was going to delay future plans anyway. Kendrick worked on the album again around July-August 2020 to record the \"N95\" Music Video and the tap dancing, but the original sounds of the album started changing by late 2021.",
    "Mr. Morale [V3]": "Mr. Morale & The Big Steppers is the fifth studio album by American rapper Kendrick Lamar, released on May 13, 2022, by PGLang, Top Dawg Entertainment (TDE), Aftermath Entertainment, and Interscope Records. The double album is Lamar's first studio album release since DAMN. (2017), his first album release under his creative collective PGLang, and his final project with TDE (under which he released four albums and was one of their flagship artists).",
    "Mr. Morale & The Big Steppers": "Kendrick's fifth studio album, a double album released May 13, 2022.",
    "Drake vs. Kendrick Lamar": "Catch-all era for the 2024 rap feud between Kendrick Lamar and Drake, covering diss tracks like \"Euphoria,\" \"6:16 in LA,\" and \"Not Like Us.\"",
    "GNX": "GNX is the sixth studio album by American rapper Kendrick Lamar. It was released as a surprise album through PGLang and Interscope Records on November 22, 2024. Titled after the Buick Regal model, and a follow-up to Mr. Morale & the Big Steppers (2022) and his feud with Canadian rapper Drake, GNX is Lamar's first album after his departure from longtime labels Top Dawg Entertainment and Aftermath Entertainment.",
    "Rap Album": "Rumored rap album that was planned to drop April - May of 2024, told by a trustworthy insider. It's likely that everything Kendrick made pre-beef was meant for this project. This project was most likely turned into a deluxe for GNX like SOS Deluxe: LANA and did fully exist at some point, but for some reason it never dropped and is likely scrapped.",
    "Compton Cowboys": "Rumored conceptual album that was planned to drop April - May of 2024, told by a trustworthy insider. Compton Cowboys was the working title of the album in 2023. The sound of the album is said to be similar to \"I Feel Something\". Another rumor would surface that the sound/tone of the album is going through phases similar to Mr. Morale. It's likely to have been in some finished state at some point in time. There are rumors of him being in the mixing stages for new music and starting his rollout with billboards but that should be taken with a grain of salt.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  hasCompsTab: false,
  hasConcertsTab: false,
  hasSubAlbumsTab: false,

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By KDOTgold', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By KDOTgold': 'Leaks & Songs added by the owner of the site.',
  },
};
