import type { ArtistConfig } from './types';

export const lonelygoldConfig: ArtistConfig = {
  slug: 'lonelygold',
  SITE_NAME: 'LONELYGOLD',
  SITE_DESCRIPTION: 'The Best Destroy Lonely Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/lonelygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'lonelygold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1J16EyxHqZD4m0VZ6g6SoY_1GC21TU7P2kk9FeteSKvE/export?format=csv&gid=1413127973',
  accentColor: '#7209b7',
  artistLabel: 'Destroy Lonely',
  cardLetter: 'DL',
  logoUrl: '/logos/lonelygold.webp',
  artistPhotoUrl: '/artists/destroylonely.webp',

  getArtistName() {
    return 'Destroy Lonely';
  },

  CUSTOM_IMAGES: {
    'Pre-2016': '/lonelygold/eras/pre-2016.jpg',
    '2016': '/lonelygold/eras/2016.jpg',
    '2017-2018': '/lonelygold/eras/2017-2018.png',
    'NezzusDestroyed': '/lonelygold/eras/nezzusdestroyed.png',
    'NezzusDestroyed 2': '/lonelygold/eras/nezzusdestroyed-2.jpg',
    '2019': '/lonelygold/eras/2019.jpg',
    '2020': '/lonelygold/eras/2020.png',
    'NO STYLIST [V1]': '/lonelygold/eras/no-stylist-v1.jpg',
    'NO STYLIST [V2]': '/lonelygold/eras/no-stylist-v2.jpg',
    'NO STYLIST [V3]': '/lonelygold/eras/no-stylist-v3.png',
    '00Twinz [V1]': '/lonelygold/eras/00twinz-v1.jpg',
    'If Looks Could Kill': '/lonelygold/eras/if-looks-could-kill.png',
    'LOVE LASTS FOREVER [V1]': '/lonelygold/eras/love-lasts-forever-v1.jpg',
    '00CACTUS': '/lonelygold/eras/00cactus.jpg',
    'LOVE LASTS FOREVER [V2]': '/lonelygold/eras/love-lasts-forever-v2.png',
    '</3³': '/lonelygold/eras/3.png',
    '00Twinz [V2]': '/lonelygold/eras/00twinz-v2.jpg',
    'Drop Dead Gorgeous': '/lonelygold/eras/drop-dead-gorgeous.png',
    'Underworld.': '/lonelygold/eras/underworld.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Jori Xeric': '??/??/????',
    'Tundra Boy Lonely': '??/??/????',
    'Destroy': '??/??/????',
    'NezzusDestroyed': '02/04/2018',
    'NezzusDestroyed 2': '??/??/????',
    'Darkhorse': '03/12/2019',
    'Sometimes U Lose..': '??/??/????',
    'Forever, ILY': '??/??/????',
    'Underworld.': '??/??/????',
    'LORD': '??/??/????',
    'ECSTASY': '??/??/????',
    'addicted to money': '??/??/????',
    '</3': '??/??/????',
    'Top Floor Vampires': '??/??/????',
    'Overseas': '??/??/????',
    'XO': '??/??/????',
    'NO STYLIST [V1]': '??/??/????',
    'NO STYLIST [V2]': '??/??/????',
    'NO STYLIST [V3]': '03/15/2024',
    'If Looks Could Kill': '03/14/2025',
    'LOVE LASTS FOREVER [V1]': '??/??/????',
    'LOVE LASTS FOREVER [V2]': '??/??/????',
    'see u soon </3': '??/??/????',
    '</3³': '??/??/????',
    'Opium Twins [V1]': '??/??/????',
    'Opium Twins [V2]': '??/??/????',
    '00CACTUS': '??/??/????',
    'Drop Dead Gorgeous': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Jori Xeric': 'Early mixtape released under one of Destroy Lonely\'s pre-fame aliases.',
    'Tundra Boy Lonely': 'Early mixtape from Destroy Lonely\'s pre-fame catalog.',
    'Destroy': 'Early mixtape from Destroy Lonely\'s pre-fame catalog.',
    'NezzusDestroyed': 'Destroy Lonely met two of his best friends, Texaco and Nezzus, who would produce many of his early works and continue to work with him on later projects at school. Immediately upon meeting Nezzus, they began recording their first project, "NezzusDestroyed."',
    'NezzusDestroyed 2': 'Not much is really known about this project. Fenderbender was the lead single for it, and a few songs were uploaded that were likely meant for the tape, but other then that most of the info about it is unknown. It\'s unknown exactly when the idea was scrapped, but it was likely scrapped in around late 2018 or very early 2019. The cover used for this era is the official cover for Fenderbender',
    'Darkhorse': 'Early mixtape from Destroy Lonely\'s pre-fame catalog, released March 12, 2019.',
    'Sometimes U Lose..': 'Early project from Destroy Lonely\'s pre-fame catalog.',
    'Forever, ILY': 'Early project from Destroy Lonely\'s pre-fame catalog.',
    'Underworld.': 'Early project from Destroy Lonely\'s catalog, predating his rise with the Opium collective.',
    'LORD': 'Early project from Destroy Lonely\'s pre-fame catalog.',
    'ECSTASY': 'Early project from Destroy Lonely\'s pre-fame catalog.',
    'addicted to money': 'Early project from Destroy Lonely\'s pre-fame catalog.',
    '</3': 'Early project from Destroy Lonely\'s pre-fame catalog.',
    'Top Floor Vampires': 'Early project from Destroy Lonely\'s catalog.',
    'Overseas': 'Early project from Destroy Lonely\'s catalog.',
    'XO': 'Early project from Destroy Lonely\'s catalog.',
    'NO STYLIST [V1]': 'Immediately following the release of Underworld, Lone announced on Twitter that he was already working on new music. "After underworld imma give yall a mini project called no stylist nd imma give yall niggas swag nd let yall play wit it den disappear". Instead of being a mini project, No Stylist turned out to be Lone\'s first full length album, eventually releasing two and a half years after this initial announcement. On the 3rd of April Lone posted again on Twitter saying the project is almost done. A month later however, in May, Lone did an interview with Breativity in which he mentioned that the project had turned into an album and that it will be hosted on Texaco Cam\'s SoundCloud. He continued to tease No Stylist throughout June, stating on Twitter that Clayco was the executive producer, and he even dropped a 4-track EP titled \'LORD\' during this month as well. Finally in the beginning of July, Lone announced in a tweet that No Stylist will drop when he hits 10k on IG. Obviously, that was a lie and he deleted this later. Throughout July and August Lone continued to release singles while keeping quiet about the status of No Stylist. Around this time Lone started to work with hitechstef, a SoundCloud host who would host/release Lone\'s songs on his pages in a similar fashion to Texaco Cam, all the way up until July of 2022 (with permission from Lone of course). \'addicted to money\', a 5-track EP entirely recorded in 2019, dropped on hitechstef\'s SoundCloud in the beginning of August. In September, Lone dropped </3, a 10-track mixtape and his biggest project to date, with \'Miley Cyrus\' as the lead single being released the week prior. Lone reiterated on Twitter that this collection of songs was separate from No Stylist. The deluxe, </3², shortly followed, releasing at the end of October with six additional tracks. December 1st saw the release of \'overseas\', another EP hosted on hitechstef\'s SoundCloud. Overall, 2020 was the busiest year for Lonely to date, featuring a steady stream of singles and projects, including his mixtape Broken Hearts, as he worked on No Stylist in the background. On December 31st, Lone teased No Stylist once again in a deleted tweet, simply writing \'album mode\'. However, Broken Hearts caught the attention of fellow Atlanta rapper Playboi Carti, who was trying to make his own record label and sign smaller artists from the area, and in January 2021, Lone would sign to Playboi Carti\'s record label OPIUM & begin to change his sound and style. The cover for this era is fanmade.',
    'NO STYLIST [V2]': 'In January 2021, Lone would be signed to Playboi Carti\'s record label OPIUM. This caused a small change in sound and direction for the project, and Lone would start linking up with various producers such as Lil 88, Richie Souf, F1lTHY & most importantly Clayco, who took over executive production at this time. This was the point where Lone began to stop dropping EPs as consistently as he was in the previous years, and instead focus more on the NO STYLIST project, dropping only 1 EP in 2021 (XO) and even scrapping 2 EPs that he wanted to drop (Dark Lord & Ultra). On August 3rd, Lone would have a landmark studio session, recording many songs, which prompted him to decide to rework the album, which he announced the next day on August 4th, stating "for my loved ones who care ive restarted my album to ensure quality".',
    'NO STYLIST [V3]': 'After continuous tweets mentioning the project, Lonely would finally tease a release date of October 1, 2021, in a now deleted tweet. Despite this, NO STYLIST failed to see a release on that date. After leaving the mixtape’s status entirely in the dark, it was surprise released on August 12, 2022 (we found out it was dropping due to a timezone drop), eight months after the last mention with absolutely no promotion, even receiving a cosign from Lil Uzi Vert.',
    'If Looks Could Kill': 'Destroy Lonely first teased the project on September 15, 2022, in a now-deleted Twitter post, stating: "next album > “if looks could kill…” The rollout for the album would seem to officially start on April 25, 2023, when fans noticed a “billboard” in New York City with just the words “If Looks Could Kill” written in red on a mirror. The board would also show a QR code on the bottom right, leading fans to his website, revealing a countdown ending for May 5th, the supposed release for the album. On April 27, 2023, the tracklist of the album would somehow get leaked to fans and revealed 26 songs, 25 solo songs and 1 bonus track with Ken Carson. On May 5th, the album would finally release. When the album first released, it initially received lots of hate from fans. Many did not like it, as it was somewhat different from Lones previous music. However, when fall 2023 began to roll around and the albums deluxe (Directors Cut) dropped, many fans changed their opinions on the album and started to like it more. This is likely because the overall theme & vibe of the album was more halloween/fall, while the album dropped right before summertime. Nowadays, many praise this album & consider it one of his better works.',
    'LOVE LASTS FOREVER [V1]': 'After the release of his debut studio album \'If Looks Could Kill\', Lone began working on his next studio album, the title of which was at the time unknown. An apparent tracklist for the album was posted to Lones (now ex) girlfriend on August 17th, 2023 with 13 tracks being visible and small portions of 7 song titles showing. The name of the album became public when Lone took to Tumblr to confirm the albums name, simply posting the words "Love Last Forever". The songs recorded during these mid 2023-early 2024 sessions were similar in sound to If Looks Could Kill, often more melodic. However, in early 2024, Lone began frequently working with producer \'Lil 88\' to rework the sound of the album and drift away from the melodically evolved If Looks Could Kill sound, and more towards a Atlanta Trap sound. Some of the songs recorded during this era ended up making their way to the various deluxes for the release version of LOVE LASTS FOREVER. The cover for this era is fanmade.',
    'LOVE LASTS FOREVER [V2]': 'During March, Lil 88 became heavily involved in the production of the album, shifting the entire sound of the album with lone recording over 40 songs in March 2024 alone showcasing the new sound. His beats are known for their loud 808s and aggressive and repetitive drum patterns, which was a stark contrast to the LLF V1 sound. Many fans hated this change, and in the end, LLF ended up having mostly V2 songs, leaving fans wishing he dropped the album before Lil 88 became involved. This version of the album was meant to drop in April 2024, however, it ended up getting scrapped (likely because of Lone & Ayisha\'s breakup). Lone also attempted a rollout in May, but randomly went silent for unknown reasons. Then again in June 2024, even dropping a lead single, however Ayisha Mia accused Lone of domestic violence right before the last Friday of the month, leading him to scrap it again. In August 2024, Lone would take to Twitter to drop the album cover art and announce the release date of August 30th. This made fans very happy, and he began rolling out the album, teasing various new snippets, however, sellers who had LLF V2 era songs in their possession took this as their time to panic sell the songs before the release of the album, leading to LOVE HURTS & DOUBT IT being groupbought just a week before release. Most of the album (except for 2 songs) ended up leaking for free the night of release. On August 30th, the album finally dropped to very mixed reception from fans (most people thought it was ass). After all the backlash during the week of release, Lone released 12 bonus tracks on various deluxes for the album, which, save for a few, were devoid of production from Lil 88, and included several highly anticipated snippets that weren\'t included on the album. It started with \'LOVE LASTS FOREVER V2\' releasing Sep 3 on his website as a 5$ digital download, containing 5 bonus tracks added at the end of the album. \'LOVE LASTS FOREVER V2.5\' followed the day after with another 5 bonus tracks, also for 5$. Lone posted the tracklist of all 10 of these bonus songs on Sep 2, with a song called \'You Dont even Know\' being part of the list. Nobody knew it at the time, but this was the community grail \'Posted\', and it ended up being replaced for unknown reasons with \'MEET THE BOSS\', which ironically features heavy production from Lil 88. These two album versions that were exclusive to his website were leading up to the release of an updated version of the album on streaming, promised on Friday (Sep 5), with 3 extra tracks and slight tracklist changes. Two of the tracks promised were the two biggest grails at the time, PRETTIEST ONE (known as \'No Rest\' before release) and HOLDING IT DOWN. However, the producer \'star boy\', who actually had very little involvement with the song, refused to clear \'HOLDING IT DOWN\' for release stating that he\'s "not clearing nothing ungodly for no amount of money". LOVE LASTS FOREVER: PRESENTED BY BLAKAMERIKA ended up releasing with only two extra songs, \'PRETTIEST ONE\' and \'GET RIGHT\'. Lone acknowledged the dissapointment in a tweet - "dats rite 2 :/". Finally, on September 20, \'LOVE LASTS FOREVER V2.5\' was released on all platforms, with all 10 of the website-exclusive bonus tracks for free. This was the last LLF-related release. In the end, 33 different tracks were released throughout the many deluxes of LLF that dropped, including a CD-exclusive track featuring Don Toliver. The mix of v1 and v2 era songs left fans feeling mixed about the album, wishing it was more consistent, with most thinking that this is one of Lone\'s weaker projects. Lone lied multiple times about the release date of the album, claiming on twitter that it would come out in April, and then in June. All of these controversies along with the expectation that this would be similar to ILCK (based off of the v1 snippets) led to a lot of disappointment and hate for the project.',
    'see u soon </3': 'Scrapped project from Destroy Lonely\'s catalog.',
    '</3³': 'Shortly after the release of LLF, Lone hinted in a deleted tweet that Love Hurts is the title of his next project, and that he would take a break to work on his production and writing skills. In December 2024, after his performance at Rolling Loud Miami, an interviewer asked him what he has planned next. "I got a mixtape coming out top of the motherfucking year we not doing no album this time, we dropping real raw, real feelings, we back on that original shit.." In retrospect, we know he was talking about Broken Hearts 3, the sequel to his 2020 mixtape Broken Hearts and it\'s deluxe tape, Broken Hearts 2. Two months later, on March 23rd, he confirmed that he was working on BH3 and a collab tape with Ken Carson in a tweet. "i heard we going </3^3 but maybe later ..." In a short interview with @viewsfrance before a show, Lone previewed some songs considered for the tape and spoke more about how the mixtape will sound, in comparison to BH1 and BH2. "It\'s gonna be the same vibe and same producers, but, I\'ve grown, so I\'ma show yall that." Later, on June 5th, Lone surprise dropped an EP to Twitter and SoundCloud with four BH3 era tracks and a highly anticipated 2022 grail with Ken Carson. The next month in July, Lone said on Twitter that he\'s turned the album in. Later on in the month, \'not the mayor\' was dropped as a music video on July 30 (Lone\'s birthday). The lead single to the mixtape, \'jumanji\', quickly followed, releasing on Sep 11, with Lone confirming the same day that the mixtape will come out on 9/19/25. The tape released to critical acclaim and love from fans. Two months after the mixtape\'s release in November, Lone did an interview with Complex in which he gave some insight into how the project was made. "It only took me like six months to make the final version that yall heard, theres been seven versions of the album. I started making it on tour last year, when I did LLF, and I just finished it probably like a week before it (BH3) came out."',
    'Opium Twins [V1]': 'In 2022, after the release of his album \'X\', Ken Carson responded to a fan asking "ken when is the opium twins tape coming" with "any_day_now" before going silent about the tape again. According to King Bob, the tape was actually set to drop in January 2023 and was almost guaranteeingly finished, however, Interscope Records put the tape on hold for unknown reasons. From then on, the tape was mentioned a few times by Ken in mid 2023, where he always stated that the album was \'not coming anytime soon\' because by this time Lone was focusing on the first version of LOVE LASTS FOREVER & Ken was focusing on A Great Chaos. By the start of 2024, Ken & pretty much went completely silent about the tape, with Ken starting to focus on More Chaos & Lone focusing on the rework of his album LOVE LASTS FOREVER & his collab tape with Don Toliver (which ended up getting scrapped by their respective record labels too). The cover for this era is fanmade. Song placements in this era may be shakey due to recording dates being unclear & overall a lack of info surrounding this era. For the sake of simplicity on this tracker, it\'s assumed that songs recorded for this project were made from around mid 2022-mid 2023.',
    'Opium Twins [V2]': 'After the sudden halt on any word around the original version of Opium Twins from 2023, most fans assumed the album was scrapped, especially since at this point in time there was 0 news from insiders around the album. Ken & Lone continued to drop their respective albums (with features from eachother on each album) and focus on their own careers, leaving no hope for the project. However, on a random sunday, after all the silence on the tape, with most fans believing it would never come, Lone took to twitter on March 23rd, 2025 to announce that he would be dropping two projects: Broken Hearts 3 and a collaboration with Ken Carson. The cover for this era is fanmade.',
    '00CACTUS': 'In March 2024, after Lone & Ayisha\'s breakup, Lone began to rework his solo album LOVE LASTS FOREVER and work with new artists, one of these being Don Toliver. Lone & Don would begin recording songs together and decide that they would drop a collab EP. The real title is unknown, but according to older info leaks, it was likely titled \'00CACTUS\' and may have been meant to release alongside the rumored Playboi Carti & Travis Scott collab album of the same name. The project would end up being scrapped by Atlantic Records not too long after it was conceived due to \'poor streaming projections\', but in reality it was likely due to the ongoing beef that Don had with Ken Carson. This was most likely solidified as beef also likely began between Lone and Don due to an outburst from Ayisha on Twitter/X in the immediate aftermath of Lone\'s domestic violence court date in June 2024, wherein she claimed "[Lone] called [Don] a faggot and that he dance like one and [Don\'s] voice is gay". The cover art for this era is an edited version of the 00CACTUS ComplexCon promotional art.',
    'Drop Dead Gorgeous': 'On September 19th, 2025, after the release of his highly anticipated Broken Hearts 3, Lone took to Tumblr to announce his next album would be titled \'Drop Dead Gorgeous\'. Lone would begin previewing various snippets as time goes on, showcasing this to be a much more experimental era with snippets such as \'Paranormal\' while also collaborating with artists way out of his style, for example Giselle.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Jori Xeric',
    'Tundra Boy Lonely',
    'Destroy',
    'NezzusDestroyed',
    'NezzusDestroyed 2',
    'Darkhorse',
    'Sometimes U Lose..',
    'Forever, ILY',
    'Underworld.',
    'LORD',
    'ECSTASY',
    'addicted to money',
    '</3',
    'Top Floor Vampires',
    'Overseas',
    'XO',
    'NO STYLIST [V1]',
    'NO STYLIST [V2]',
    'NO STYLIST [V3]',
    'If Looks Could Kill',
    'LOVE LASTS FOREVER [V1]',
    'LOVE LASTS FOREVER [V2]',
    'see u soon </3',
    '</3³',
    'Opium Twins [V1]',
    'Opium Twins [V2]',
    '00CACTUS',
    'Drop Dead Gorgeous',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
  hasMiscTab: false,
  hasSubAlbumsTab: false,
};
