import type { ArtistConfig } from './types';

export const lonelygoldConfig: ArtistConfig = {
  slug: 'lonelygold',
  SITE_NAME: 'LONELYGOLD',
  SITE_DESCRIPTION: 'The Best Destroy Lonely Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/lonelygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'lonelygold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#7209b7',
  artistLabel: 'Destroy Lonely',
  cardLetter: 'DL',
  logoUrl: '/logos/lonelygold.webp',
  artistPhotoUrl: '/artists/destroylonely.jpg',

  getArtistName() {
    return 'Destroy Lonely';
  },

  CUSTOM_IMAGES: {
    'If Looks Could Kill': '/lonelygold/eras/if-looks-could-kill.jpg',
    'NO STYLIST [V3]': '/lonelygold/eras/no-stylist-v3.jpg',
    'Underworld.': '/lonelygold/eras/underworld.jpg',
    '00CACTUS': '/lonelygold/eras/00cactus.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Jori Xeric': '??/??/????',
    'Tundra Boy Lonely': '??/??/????',
    'Destroy': '??/??/????',
    'NezzusDestroyed': '02/04/2018',
    'NezzusDestroyed 2': '??/??/????',
    'Darkhorse': '03/12/2019',
    'Sometimes U Lose..': '??/??/????',
    'Forever, ILY': '??/??/????',
    'Underworld.': '??/??/????',
    'LORD': '??/??/????',
    'ECSTASY': '??/??/????',
    'addicted to money': '??/??/????',
    '</3': '??/??/????',
    'Top Floor Vampires': '??/??/????',
    'Overseas': '??/??/????',
    'XO': '??/??/????',
    'NO STYLIST [V1]': '??/??/????',
    'NO STYLIST [V2]': '??/??/????',
    'NO STYLIST [V3]': '03/15/2024',
    'If Looks Could Kill': '03/14/2025',
    'LOVE LASTS FOREVER [V1]': '??/??/????',
    'LOVE LASTS FOREVER [V2]': '??/??/????',
    'see u soon </3': '??/??/????',
    '</3³': '??/??/????',
    'Opium Twins [V1]': '??/??/????',
    'Opium Twins [V2]': '??/??/????',
    '00CACTUS': '??/??/????',
    'Drop Dead Gorgeous': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Jori Xeric',
    'Tundra Boy Lonely',
    'Destroy',
    'NezzusDestroyed',
    'NezzusDestroyed 2',
    'Darkhorse',
    'Sometimes U Lose..',
    'Forever, ILY',
    'Underworld.',
    'LORD',
    'ECSTASY',
    'addicted to money',
    '</3',
    'Top Floor Vampires',
    'Overseas',
    'XO',
    'NO STYLIST [V1]',
    'NO STYLIST [V2]',
    'NO STYLIST [V3]',
    'If Looks Could Kill',
    'LOVE LASTS FOREVER [V1]',
    'LOVE LASTS FOREVER [V2]',
    'see u soon </3',
    '</3³',
    'Opium Twins [V1]',
    'Opium Twins [V2]',
    '00CACTUS',
    'Drop Dead Gorgeous',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
