import type { ArtistConfig } from './types';

export const luckigoldConfig: ArtistConfig = {
  slug: 'luckigold',
  SITE_NAME: 'LUCKIGOLD',
  SITE_DESCRIPTION: 'The Best Lucki Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/luckigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'luckigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1zoRNpy7Lvr-JzPqtQLLWRVVDbgKygpBaDf4cC-Lt6k4/export?format=csv&gid=1422898255',
  accentColor: '#6f42c1',
  artistLabel: 'Lucki',
  cardLetter: 'LKI',
  logoUrl: '/logos/luckigold.png',
  artistPhotoUrl: '/artists/lucki.webp',

  getArtistName(_eraName) { return 'Lucki'; },

  CUSTOM_IMAGES: {
    'Body High': '',
    'X': '',
    'Freewave': '',
    'Lucki Eck$': '',
    'Freewave 2': '',
    'Watch My Back': '',
    'DAYS B4 II EP': '',
    'Freewave 3': '',
    'Days B4 III': '',
    'Almost There': '',
    'FLAWLESS LIKE ME [V1]': '',
    'WAKE UP LUCKI': '',
    'SON OF SAM': '',
    'FLAWLESS LIKE ME [V2]': '',
    'Alternative Trap': '',
    's*x m*ney dr*gs': '',
    'GEMINI!': '',
    'dr*gs r bad [V1]': '',
    'Dr*gs R Bad [V2]': '',
  },

  ALBUM_RELEASE_DATES: {
    'Body High': '??/??/2014',
    'X': '??/??/????',
    'Freewave': '08/14/2015',
    'Lucki Eck$': '??/??/????',
    'Freewave 2': '08/18/2016',
    'Watch My Back': '05/05/2017',
    'DAYS B4 II EP': '04/12/2018',
    'Freewave 3': '02/15/2019',
    'Days B4 III': '10/25/2019',
    'Almost There': '05/29/2020',
    'FLAWLESS LIKE ME [V1]': '??/??/????',
    'WAKE UP LUCKI': '12/03/2021',
    'SON OF SAM': '08/17/2022',
    'FLAWLESS LIKE ME [V2]': '09/23/2022',
    'Alternative Trap': '??/??/????',
    's*x m*ney dr*gs': '07/07/2023',
    'GEMINI!': '06/14/2024',
    'dr*gs r bad [V1]': '??/??/????',
    'Dr*gs R Bad [V2]': '05/15/2026',
  },

  HIDDEN_ALBUMS: ['Body High', 'X', 'Freewave'],
  ALBUM_DESCRIPTIONS: {
    'Body High': 'LUCKI\'s earliest era, featuring music videos released around 2014 before his "Lucki Eck$" tape era.',
    'X': 'An early era featuring the "Birdgang", "Lowlife", and "None Other" music videos, released between 2015 and 2017.',
    'Freewave': 'The original installment of the Freewave series, released August 14, 2015, preceding Freewave 2.',
    'Lucki Eck$': 'Lucki performing under his original "Lucki Eck$" moniker, before changing his name to LUCKI in January 2016.',
    'Freewave 2': 'Released August 18, 2016 as the second installment of the Freewave series.',
    'Watch My Back': 'Released May 5, 2017, also referred to as "Almighty So 2".',
    'DAYS B4 II EP': 'Released April 12, 2018. An early version of this project circulated under the title "Better Days" (BD).',
    'Freewave 3': 'Released February 15, 2019, the third installment of the Freewave series.',
    'Days B4 III': 'Released October 25, 2019. Also referred to as "Days B4 Flawless".',
    'Almost There': 'Released May 29, 2020.',
    'FLAWLESS LIKE ME [V1]': 'The original version of FLAWLESS LIKE ME worked on with BrentRambo following Almost There, before LUCKI shifted to the WAKE UP LUCKI project with F1LTHY.',
    'WAKE UP LUCKI': 'A collaborative project with producer F1LTHY, released December 3, 2021.',
    'SON OF SAM': 'An era marked by the official music video for "DOUBLE CHECK", released August 17, 2022.',
    'FLAWLESS LIKE ME [V2]': 'The released version of FLAWLESS LIKE ME, put out September 23, 2022.',
    'Alternative Trap': 'An era featuring the "Untouchable Lucki", "Everything Out$ide", "Love It", and "Count On Me" music videos, released between January and September 2023.',
    's*x m*ney dr*gs': 'Released July 7, 2023.',
    'GEMINI!': 'Released June 14, 2024.',
    'dr*gs r bad [V1]': 'Also referred to as "GEMIN! Deluxe". The original version of Dr*gs R Bad, with many songs from its sessions leaking around May 2025 before the project shifted into Dr*gs R Bad [V2].',
    'Dr*gs R Bad [V2]': 'LUCKI\'s most recent project, released May 15, 2026.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    'Watch My Back*': 'Watch My Back',
    'DAYS B4 II EP*': 'DAYS B4 II EP',
  },
  ALBUM_ORDER: [
    'Body High',
    'X',
    'Freewave',
    'Lucki Eck$',
    'Freewave 2',
    'Watch My Back',
    'DAYS B4 II EP',
    'Freewave 3',
    'Days B4 III',
    'Almost There',
    'FLAWLESS LIKE ME [V1]',
    'WAKE UP LUCKI',
    'SON OF SAM',
    'FLAWLESS LIKE ME [V2]',
    'Alternative Trap',
    's*x m*ney dr*gs',
    'GEMINI!',
    'dr*gs r bad [V1]',
    'Dr*gs R Bad [V2]',
  ],

  hasCompsTab: false,
  hasConcertsTab: false,
  hasRecentTab: true,

  TAG_MAP: {
    '⭐': 'Best Of', '⭐️': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By LUCKIGOLD', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {
    'Body High': {},
    'X': {},
    'Freewave': {},
    'Lucki Eck$': {},
    'Freewave 2': {},
    'Watch My Back': {},
    'DAYS B4 II EP': {},
    'Freewave 3': {},
    'Days B4 III': {},
    'Almost There': {},
    'FLAWLESS LIKE ME [V1]': {},
    'WAKE UP LUCKI': {},
    'SON OF SAM': {},
    'FLAWLESS LIKE ME [V2]': {},
    'Alternative Trap': {},
    's*x m*ney dr*gs': {},
    'GEMINI!': {},
    'dr*gs r bad [V1]': {},
    'Dr*gs R Bad [V2]': {},
  },
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By LUCKIGOLD': 'Leaks & Songs added by the owner of the site.',
  },
};
