import type { ArtistConfig } from './types';

export const luckigoldConfig: ArtistConfig = {
  slug: 'luckigold',
  SITE_NAME: 'LUCKIGOLD',
  SITE_DESCRIPTION: 'The Best Lucki Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/luckigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'luckigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#6f42c1',
  artistLabel: 'Lucki',
  cardLetter: 'LKI',
  logoUrl: '/logos/luckigold.png',
  artistPhotoUrl: '/artists/lucki.webp',

  getArtistName(_eraName) { return 'Lucki'; },

  CUSTOM_IMAGES: {
    'Alivebutdead': '',
    'Body High': '',
    'Watch My Back': '',
    'Days B4 III': '',
    'III': '',
    'Freewave': '',
    'Freewave 2': '',
    'Almost There': '',
    'Flawless Like Me': '',
    'Freewave 3': '',
    'Wake Up Lucki': '',
    'Ongoing': '',
  },

  ALBUM_RELEASE_DATES: {
    'Alivebutdead': '??/??/2013',
    'Body High': '??/??/2014',
    'Watch My Back': '??/??/2016',
    'Days B4 III': '??/??/2017',
    'III': '??/??/2018',
    'Freewave': '??/??/2018',
    'Freewave 2': '??/??/2019',
    'Almost There': '??/??/2020',
    'Flawless Like Me': '??/??/2020',
    'Freewave 3': '??/??/2022',
    'Wake Up Lucki': '??/??/2022',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  hasCompsTab: false,
  hasConcertsTab: false,
  hasRecentTab: true,

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By LUCKIGOLD', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By LUCKIGOLD': 'Leaks & Songs added by the owner of the site.',
  },
};
