import type { ArtistConfig } from './types';

export const macgoldConfig: ArtistConfig = {
  slug: 'macgold',
  SITE_NAME: 'MACGOLD',
  SITE_DESCRIPTION: 'The Best Mac Miller Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/macgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'macgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#ca8a04',
  artistLabel: 'Mac Miller',
  cardLetter: 'M',
  logoUrl: '',
  artistPhotoUrl: '/artists/macmiller.jpg',

  getArtistName() {
    return 'Mac Miller';
  },

  CUSTOM_IMAGES: {
    "But My Mackin' Ain't Easy": '/macgold/eras/but-my-mackin-aint-easy.jpg',
    'Welcome To Hip-Hop': '/macgold/eras/welcome-to-hip-hop.jpg',
    'How High': '/macgold/eras/the-jukebox.jpg',
    'The Jukebox: Prelude to Class Clown': '/macgold/eras/the-jukebox.jpg',
    'The Class Clown': '/macgold/eras/the-jukebox.jpg',
    'The High Life': '/macgold/eras/the-high-life.jpg',
    'K.I.D.S.': '/macgold/eras/kids.jpg',
    'Best Day Ever': '/macgold/eras/best-day-ever.jpg',
    'On and On and Beyond': '/macgold/eras/best-day-ever.jpg',
    '92 Till Infinity': '/macgold/eras/92-til-infinity.jpg',
    'I Love Life, Thank You': '/macgold/eras/i-love-life-thank-you.jpg',
    'Blue Slide Park': '/macgold/eras/blue-slide-park.jpg',
    'Macadelic': '/macgold/eras/macadelic.jpg',
    'Pink Slime': '/macgold/eras/pink-slime.jpg',
    'You': '/macgold/eras/macadelic.jpg',
    'Run-On Sentences, Vol. 1': '/macgold/eras/macadelic.jpg',
    'Watching Movies With The Sound Off': '/artists/macmiller.jpg',
    'Stolen Youth': '/artists/macmiller.jpg',
    'Delusional Thomas': '/artists/macmiller.jpg',
    'Live From Space': '/artists/macmiller.jpg',
    'Balloonerism': '/macgold/eras/balloonerism.jpg',
    'Children Of Forever': '/macgold/eras/balloonerism.jpg',
    'Faces': '/macgold/eras/faces.jpg',
    'Maclib': '/macgold/eras/faces.jpg',
    'Attorneys EP': '/macgold/eras/faces.jpg',
    'Good Morning': '/macgold/eras/faces.jpg',
    'GO:OD AM': '/macgold/eras/good-am.jpg',
    "Run-On Sentences, Vol. 2": '/macgold/eras/good-am.jpg',
    'The Divine Feminine': '/macgold/eras/the-divine-feminine.jpg',
    'Swimming': '/macgold/eras/swimming.jpg',
    'Swimming / Circles [V1]': '/macgold/eras/swimming.jpg',
    'Swimming / Circles [V2]': '/macgold/eras/swimming.jpg',
    'Swimming / Circles [V3]': '/macgold/eras/swimming.jpg',
    'Circles': '/macgold/eras/swimming.jpg',
    'Circles [V1]': '/macgold/eras/swimming.jpg',
    'Spotify Singles': '/artists/macmiller.jpg',
    'Posthumous Releases': '/artists/macmiller.jpg',
    'Unknown': '/artists/macmiller.jpg',
  },

  ALBUM_RELEASE_DATES: {
    "But My Mackin' Ain't Easy": '11/01/2007',
    'Welcome To Hip-Hop': '??/??/????',
    'How High': '10/27/2008',
    'The Jukebox: Prelude to Class Clown': '06/26/2009',
    'The Class Clown': '??/??/????',
    'The High Life': '11/13/2009',
    'K.I.D.S.': '08/13/2010',
    'Best Day Ever': '03/11/2011',
    'On and On and Beyond': '07/01/2011',
    '92 Till Infinity': '??/??/????',
    'I Love Life, Thank You': '08/15/2011',
    'Blue Slide Park': '11/08/2011',
    'Macadelic': '03/23/2012',
    'Pink Slime': '??/??/????',
    'You': '??/??/????',
    'Run-On Sentences, Vol. 1': '07/01/2015',
    'Watching Movies With The Sound Off': '06/18/2013',
    'Stolen Youth': '02/12/2013',
    'Delusional Thomas': '10/22/2013',
    'Live From Space': '08/06/2013',
    'Balloonerism': '01/17/2025',
    'Children Of Forever': '??/??/????',
    'Faces': '05/11/2014',
    'Maclib': '??/??/????',
    'Attorneys EP': '??/??/????',
    'Good Morning': '??/??/????',
    'GO:OD AM': '09/18/2015',
    "Run-On Sentences, Vol. 2": '12/23/2015',
    'The Divine Feminine': '09/16/2016',
    'Swimming': '08/03/2018',
    'Swimming / Circles [V1]': '??/??/????',
    'Swimming / Circles [V2]': '??/??/????',
    'Swimming / Circles [V3]': '??/??/????',
    'Circles': '01/17/2020',
    'Circles [V1]': '??/??/????',
    'Spotify Singles': '??/??/????',
    'Posthumous Releases': '??/??/????',
    'Unknown': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    "But My Mackin' Ain't Easy": "Mac Miller's debut mixtape, released in 2007 under the name Easy Mac when he was 15 years old.",
    'Welcome To Hip-Hop': "Little-documented early project from Mac Miller's pre-fame teenage years.",
    'How High': 'Mixtape by The Ill Spoken, a short-lived Pittsburgh rap duo formed by Mac Miller (as Easy Mac) and Beedie in 2008.',
    'The Jukebox: Prelude to Class Clown': 'Mixtape released in 2009, his first after adopting the Mac Miller name, teasing a planned follow-up called Class Clown.',
    'The Class Clown': 'Planned follow-up project teased alongside The Jukebox: Prelude to Class Clown that was ultimately scrapped in that form.',
    'The High Life': "Mixtape released November 13, 2009, one of Mac Miller's early releases under his new stage name.",
    'K.I.D.S.': "Mac Miller's breakthrough mixtape, released August 13, 2010, that built his early fanbase.",
    'Best Day Ever': 'Mixtape released March 11, 2011, widely regarded as one of the best of Mac Miller\'s early career.',
    'On and On and Beyond': "Mac Miller's debut EP, released March 2011, pairing two new songs with tracks from The High Life and Best Day Ever.",
    '92 Till Infinity': 'Planned collaborative project with DJ Jazzy Jeff over old-school breakbeats, announced in 2011 but never officially released.',
    'I Love Life, Thank You': "Mac Miller's sixth mixtape, released October 14, 2011, as part of his \"Road 2 a Million Fans\" campaign after reaching one million Twitter followers.",
    'Blue Slide Park': "Mac Miller's debut studio album, released November 8, 2011. It became the first independently distributed debut album to top the Billboard 200 since 1995.",
    'Macadelic': 'Mixtape released March 23, 2012, marking a shift toward more psychedelic production and themes.',
    'Pink Slime': 'Collaborative EP announced with Pharrell Williams in 2012 and teased for years, but never officially released.',
    'You': "Little-documented loosie/scrapped-era material from around Mac Miller's Macadelic period.",
    'Run-On Sentences, Vol. 1': "Instrumental mixtape released December 29, 2015, under Mac Miller's producer alias Larry Fisherman.",
    'Watching Movies With The Sound Off': "Mac Miller's second studio album, released June 18, 2013.",
    'Stolen Youth': 'Collaborative mixtape with Vince Staples, entirely produced by Mac Miller under his Larry Fisherman alias, released June 20, 2013.',
    'Delusional Thomas': "Mixtape released October 22, 2013, under Mac Miller's pitched-up alter ego, Delusional Thomas.",
    'Live From Space': 'Live album recorded during the Blue Slide Park tour, released August 6, 2013.',
    'Balloonerism': "Mac Miller's seventh studio album and second posthumous release. Recorded in 2014 around the Faces era and released January 17, 2025.",
    'Children Of Forever': "Little-documented unreleased project title from Mac Miller's catalog.",
    'Faces': 'Dark, drug-themed mixtape released May 11, 2014, widely considered one of his best projects.',
    'Maclib': 'Collaborative project with producer Madlib. Madlib announced the project as completed in 2023, but it remains unreleased.',
    'Attorneys EP': "Little-documented scrapped project from Mac Miller's catalog.",
    'Good Morning': "Little-documented scrapped project or loosie collection from Mac Miller's catalog.",
    'GO:OD AM': "Mac Miller's third studio album, released September 18, 2015, his first release after signing to Warner Bros.",
    "Run-On Sentences, Vol. 2": 'Follow-up instrumental release under the Larry Fisherman alias, released December 23, 2015.',
    'The Divine Feminine': "Mac Miller's fourth studio album, released September 16, 2016, a concept album about love largely produced by Frank Dukes.",
    'Swimming': "Mac Miller's fifth studio album, released August 3, 2018, just five weeks before his death.",
    'Swimming / Circles [V1]': 'Early working sessions from when Swimming and Circles were being developed together as a joint double album.',
    'Swimming / Circles [V2]': 'Later working sessions from the joint Swimming/Circles album development.',
    'Swimming / Circles [V3]': 'Final working sessions before Swimming and Circles were split into two separate albums.',
    'Circles': "Mac Miller's sixth studio album, a posthumous companion to Swimming completed by producer Jon Brion and released January 17, 2020.",
    'Circles [V1]': 'Early or alternate working version of the Circles album sessions.',
    'Spotify Singles': "Recordings from Mac Miller's session for Spotify's Spotify Singles series.",
    'Posthumous Releases': "Catch-all era for tracks released after Mac Miller's death that aren't tied to a specific studio album.",
    'Unknown': 'Miscellaneous material without a confirmed era.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    "But My Mackin' Ain't Easy",
    'Welcome To Hip-Hop',
    'How High',
    'The Jukebox: Prelude to Class Clown',
    'The Class Clown',
    'The High Life',
    'K.I.D.S.',
    'Best Day Ever',
    'On and On and Beyond',
    '92 Till Infinity',
    'I Love Life, Thank You',
    'Blue Slide Park',
    'Macadelic',
    'Pink Slime',
    'You',
    'Run-On Sentences, Vol. 1',
    'Watching Movies With The Sound Off',
    'Stolen Youth',
    'Delusional Thomas',
    'Live From Space',
    'Balloonerism',
    'Children Of Forever',
    'Faces',
    'Maclib',
    'Attorneys EP',
    'Good Morning',
    'GO:OD AM',
    "Run-On Sentences, Vol. 2",
    'The Divine Feminine',
    'Swimming',
    'Swimming / Circles [V1]',
    'Swimming / Circles [V2]',
    'Swimming / Circles [V3]',
    'Circles',
    'Circles [V1]',
    'Spotify Singles',
    'Posthumous Releases',
    'Unknown',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
};
