import type { ArtistConfig } from './types';

export const macgoldConfig: ArtistConfig = {
  slug: 'macgold',
  SITE_NAME: 'MACGOLD',
  SITE_DESCRIPTION: 'The Best Mac Miller Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/macgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'macgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#ca8a04',
  artistLabel: 'Mac Miller',
  cardLetter: 'M',
  logoUrl: '',
  artistPhotoUrl: '/artists/macmiller.jpg',

  getArtistName() {
    return 'Mac Miller';
  },

  CUSTOM_IMAGES: {
    "But My Mackin' Ain't Easy": '/macgold/eras/but-my-mackin-aint-easy.jpg',
    'Welcome To Hip-Hop': '/macgold/eras/welcome-to-hip-hop.jpg',
    'How High': '/macgold/eras/the-jukebox.jpg',
    'The Jukebox: Prelude to Class Clown': '/macgold/eras/the-jukebox.jpg',
    'The Class Clown': '/macgold/eras/the-jukebox.jpg',
    'The High Life': '/macgold/eras/the-high-life.jpg',
    'K.I.D.S.': '/macgold/eras/kids.jpg',
    'Best Day Ever': '/macgold/eras/best-day-ever.jpg',
    'On and On and Beyond': '/macgold/eras/best-day-ever.jpg',
    '92 Till Infinity': '/macgold/eras/92-til-infinity.jpg',
    'I Love Life, Thank You': '/macgold/eras/i-love-life-thank-you.jpg',
    'Blue Slide Park': '/macgold/eras/blue-slide-park.jpg',
    'Macadelic': '/macgold/eras/macadelic.jpg',
    'Pink Slime': '/macgold/eras/pink-slime.jpg',
    'You': '/macgold/eras/macadelic.jpg',
    'Run-On Sentences, Vol. 1': '/macgold/eras/macadelic.jpg',
    'Watching Movies With The Sound Off': '/artists/macmiller.jpg',
    'Stolen Youth': '/artists/macmiller.jpg',
    'Delusional Thomas': '/artists/macmiller.jpg',
    'Live From Space': '/artists/macmiller.jpg',
    'Balloonerism': '/macgold/eras/balloonerism.jpg',
    'Children Of Forever': '/macgold/eras/balloonerism.jpg',
    'Faces': '/macgold/eras/faces.jpg',
    'Maclib': '/macgold/eras/faces.jpg',
    'Attorneys EP': '/macgold/eras/faces.jpg',
    'Good Morning': '/macgold/eras/faces.jpg',
    'GO:OD AM': '/macgold/eras/good-am.jpg',
    "Run-On Sentences, Vol. 2": '/macgold/eras/good-am.jpg',
    'The Divine Feminine': '/macgold/eras/the-divine-feminine.jpg',
    'Swimming': '/macgold/eras/swimming.jpg',
    'Swimming / Circles [V1]': '/macgold/eras/swimming.jpg',
    'Swimming / Circles [V2]': '/macgold/eras/swimming.jpg',
    'Swimming / Circles [V3]': '/macgold/eras/swimming.jpg',
    'Circles': '/macgold/eras/swimming.jpg',
    'Circles [V1]': '/macgold/eras/swimming.jpg',
    'Spotify Singles': '/artists/macmiller.jpg',
    'Posthumous Releases': '/artists/macmiller.jpg',
    'Unknown': '/artists/macmiller.jpg',
  },

  ALBUM_RELEASE_DATES: {
    "But My Mackin' Ain't Easy": '11/01/2007',
    'Welcome To Hip-Hop': '??/??/????',
    'How High': '10/27/2008',
    'The Jukebox: Prelude to Class Clown': '06/26/2009',
    'The Class Clown': '??/??/????',
    'The High Life': '11/13/2009',
    'K.I.D.S.': '08/13/2010',
    'Best Day Ever': '03/11/2011',
    'On and On and Beyond': '07/01/2011',
    '92 Till Infinity': '??/??/????',
    'I Love Life, Thank You': '08/15/2011',
    'Blue Slide Park': '11/08/2011',
    'Macadelic': '03/23/2012',
    'Pink Slime': '??/??/????',
    'You': '??/??/????',
    'Run-On Sentences, Vol. 1': '07/01/2015',
    'Watching Movies With The Sound Off': '06/18/2013',
    'Stolen Youth': '02/12/2013',
    'Delusional Thomas': '10/22/2013',
    'Live From Space': '08/06/2013',
    'Balloonerism': '01/17/2025',
    'Children Of Forever': '??/??/????',
    'Faces': '05/11/2014',
    'Maclib': '??/??/????',
    'Attorneys EP': '??/??/????',
    'Good Morning': '??/??/????',
    'GO:OD AM': '09/18/2015',
    "Run-On Sentences, Vol. 2": '12/23/2015',
    'The Divine Feminine': '09/16/2016',
    'Swimming': '08/03/2018',
    'Swimming / Circles [V1]': '??/??/????',
    'Swimming / Circles [V2]': '??/??/????',
    'Swimming / Circles [V3]': '??/??/????',
    'Circles': '01/17/2020',
    'Circles [V1]': '??/??/????',
    'Spotify Singles': '??/??/????',
    'Posthumous Releases': '??/??/????',
    'Unknown': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    "But My Mackin' Ain't Easy",
    'Welcome To Hip-Hop',
    'How High',
    'The Jukebox: Prelude to Class Clown',
    'The Class Clown',
    'The High Life',
    'K.I.D.S.',
    'Best Day Ever',
    'On and On and Beyond',
    '92 Till Infinity',
    'I Love Life, Thank You',
    'Blue Slide Park',
    'Macadelic',
    'Pink Slime',
    'You',
    'Run-On Sentences, Vol. 1',
    'Watching Movies With The Sound Off',
    'Stolen Youth',
    'Delusional Thomas',
    'Live From Space',
    'Balloonerism',
    'Children Of Forever',
    'Faces',
    'Maclib',
    'Attorneys EP',
    'Good Morning',
    'GO:OD AM',
    "Run-On Sentences, Vol. 2",
    'The Divine Feminine',
    'Swimming',
    'Swimming / Circles [V1]',
    'Swimming / Circles [V2]',
    'Swimming / Circles [V3]',
    'Circles',
    'Circles [V1]',
    'Spotify Singles',
    'Posthumous Releases',
    'Unknown',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
};
