import type { ArtistConfig } from './types';

export const mfgoldConfig: ArtistConfig = {
  slug: 'mfgold',
  SITE_NAME: 'MFGOLD',
  SITE_DESCRIPTION: 'The Best MF DOOM Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/mfgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'mfgold_',
  HARDCODED_SHEET_ID: '1zEbzMVXFXzuY4wLdPvdQA23lb3RwCSOKqWtHsllXNk8',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1zEbzMVXFXzuY4wLdPvdQA23lb3RwCSOKqWtHsllXNk8/export?format=csv&gid=1476766908',
  accentColor: '#16a34a',
  artistLabel: 'MF DOOM',
  sheetCreator: 'madvilliany, HeyImTy',
  cardLetter: 'DOOM',
  logoUrl: '/logos/mfgold.png',
  artistPhotoUrl: '/artists/mfdoom.jpg',

  getArtistName() {
    return 'MF DOOM';
  },

  CUSTOM_IMAGES: {
    'By All Means Necessary': '/mfgold/eras/by-all-means-necessary.jpg',
    'Mr. Hood': '/mfgold/eras/mr-hood.jpg',
    'BL_CK B_ST_RDS': '/mfgold/eras/bl-ck-b-st-rds.jpg',
    'Mental Illness': '/mfgold/eras/mental-illness.jpg',
    'Operation: Doomsday': '/mfgold/eras/operation-doomsday.jpg',
    '1999 - 2003': '/mfgold/eras/1999-2003.jpg',
    'Vaudeville Villain': '/mfgold/eras/vaudeville-villain.jpg',
    'Take Me To Your Leader': '/mfgold/eras/take-me-to-your-leader.jpg',
    'Venomous Villain': '/mfgold/eras/venomous-villain.jpg',
    'Madvillainy': '/mfgold/eras/madvillainy.jpg',
    'MM..FOOD': '/mfgold/eras/mm-food.jpg',
    'The Mouse And The Mask': '/mfgold/eras/the-mouse-and-the-mask.jpg',
    '2006 - 2008': '/mfgold/eras/2006-2008.jpg',
    'Dilla-DOOM': '/mfgold/eras/dilla-doom.jpg',
    'Madvillainy 2': '/mfgold/eras/madvillainy-2.jpg',
    'Special Herbs, Vols. 9 & 0': '/mfgold/eras/special-herbs-vols-9-0.jpg',
    'BORN LIKE THIS': '/mfgold/eras/born-like-this.jpg',
    'Swift & Changeable': '/mfgold/eras/swift-changeable.jpg',
    'Key to the Kuffs': '/mfgold/eras/key-to-the-kuffs.jpg',
    'DOOMYORKES': '/mfgold/eras/doomyorkes.jpg',
    'NehruvianDOOM': '/mfgold/eras/nehruviandoom.jpg',
    '2015 - 2017': '/mfgold/eras/2015-2017.jpg',
    'Special Herbs 10': '/mfgold/eras/special-herbs-10.jpg',
    'The Missing Notebook Rhymes': '/mfgold/eras/the-missing-notebook-rhymes.jpg',
    'WestSide Doom': '/mfgold/eras/westside-doom.jpg',
    'Czarface Meets Metal Face': '/mfgold/eras/czarface-meets-metal-face.jpg',
    'Flylo-DOOM': '/mfgold/eras/flylo-doom.jpg',
    'Super What?': '/mfgold/eras/super-what.jpg',
    'Post Super What?': '/mfgold/eras/post-super-what.jpg',
    'Unknown': '/artists/mfdoom.jpg',
    'Ongoing': '/artists/mfdoom.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'By All Means Necessary': '??/??/????',
    'Mr. Hood': '05/06/1991',
    'BL_CK B_ST_RDS': '??/??/2001',
    'Mental Illness': '??/??/????',
    'Operation: Doomsday': '10/19/1999',
    '1999 - 2003': '??/??/????',
    'Vaudeville Villain': '09/16/2003',
    'Take Me To Your Leader': '06/17/2003',
    'Venomous Villain': '??/??/2004',
    'Madvillainy': '03/23/2004',
    'MM..FOOD': '03/30/2004',
    'The Mouse And The Mask': '10/10/2005',
    '2006 - 2008': '??/??/????',
    'Dilla-DOOM': '??/??/????',
    'Madvillainy 2': '??/??/????',
    'Special Herbs, Vols. 9 & 0': '??/??/????',
    'BORN LIKE THIS': '03/17/2009',
    'Swift & Changeable': '??/??/????',
    'Key to the Kuffs': '06/05/2012',
    'DOOMYORKES': '??/??/????',
    'NehruvianDOOM': '12/09/2014',
    '2015 - 2017': '??/??/????',
    'Special Herbs 10': '??/??/????',
    'The Missing Notebook Rhymes': '??/??/????',
    'WestSide Doom': '??/??/????',
    'Czarface Meets Metal Face': '02/16/2018',
    'Flylo-DOOM': '??/??/????',
    'Super What?': '??/??/????',
    'Post Super What?': '??/??/????',
    'Unknown': '??/??/????',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'By All Means Necessary': 'Scrapped early project reportedly predating Mr. Hood; little concrete information about it has surfaced.',
    'Mr. Hood': 'KMD\'s debut studio album, released in 1991 on Elektra Records, featuring a young Zev Love X (later MF DOOM) alongside his brother Subroc.',
    'BL_CK B_ST_RDS': 'KMD\'s second album, recorded in 1993 and shelved by Elektra over its cover art; released independently in 2001 as Black Bastards.',
    'Mental Illness': 'Scrapped project title from the period between KMD\'s collapse and Dumile\'s emergence as MF DOOM; little concrete information has surfaced.',
    'Operation: Doomsday': 'MF DOOM\'s solo debut album, released in 1999 on Fondle \'Em Records, introducing his supervillain persona.',
    '1999 - 2003': 'Catch-all era for loose MF DOOM leaks and loosies recorded between 1999 and 2003.',
    'Vaudeville Villain': 'Collaborative album released under the Viktor Vaughn alias in September 2003 on Sound-Ink Records.',
    'Take Me To Your Leader': 'Collaborative album released under the King Geedorah alias in 2003 via Big Dada, mixing guest verses with DOOM-produced instrumentals.',
    'Venomous Villain': 'Shelved sequel to Vaudeville Villain as Viktor Vaughn (VV:2); largely completed but never officially released, circulating instead as leaks and bootlegs.',
    'Madvillainy': 'Collaborative album with producer Madlib released as Madvillain in March 2004 on Stones Throw Records; widely regarded as one of the greatest hip-hop albums ever made.',
    'MM..FOOD': 'MF DOOM\'s solo studio album, released March 2004 on Rhymesayers Entertainment, built around a food-themed lyrical concept.',
    'The Mouse And The Mask': 'Collaborative album with producer Danger Mouse released as DANGERDOOM in October 2005 on Epitaph Records, built around Adult Swim characters.',
    '2006 - 2008': 'Catch-all era for loose MF DOOM leaks and loosies recorded between 2006 and 2008.',
    'Dilla-DOOM': 'Fan-designated name for loose collaborative material between MF DOOM and producer J Dilla; never compiled into an official release, partly due to Dilla\'s death in 2006.',
    'Madvillainy 2': 'Long-rumored sequel to Madvillainy by DOOM and Madlib; individual tracks have leaked over the years, but the album itself was never completed or released.',
    'Special Herbs, Vols. 9 & 0': 'Ninth and tenth (numbered "0") volumes of DOOM\'s instrumental Special Herbs series, released under the Metal Fingers alias.',
    'BORN LIKE THIS': 'MF DOOM\'s solo studio album, released March 2009 on Lex Records; his last full solo album released during his lifetime.',
    'Swift & Changeable': 'Rumored unreleased mixtape or project from DOOM\'s catalog; some tracks have been speculatively tied to it, but little has been confirmed.',
    'Key to the Kuffs': 'Collaborative album with producer Jneiro Jarel released as JJ DOOM in June 2012 on Lex Records, made while DOOM was based in London.',
    'DOOMYORKES': 'Rumored, scrapped collaborative project associated with MF DOOM; details on its contents remain scarce.',
    'NehruvianDOOM': 'Collaborative album with rapper Bishop Nehru, released December 2014, produced entirely by MF DOOM.',
    '2015 - 2017': 'Catch-all era for loose MF DOOM leaks and loosies recorded between 2015 and 2017.',
    'Special Herbs 10': 'Long-rumored, never-released tenth volume of DOOM\'s instrumental Special Herbs series.',
    'The Missing Notebook Rhymes': 'Scrapped or rumored project tied to lost DOOM notebooks and verses; little concrete information has surfaced.',
    'WestSide Doom': 'Rumored collaborative project between MF DOOM and Westside Gunn; teased but never officially released.',
    'Czarface Meets Metal Face': 'Collaborative album between Czarface (Inspectah Deck, 7L & Esoteric) and MF DOOM, released February 2018 on Get On Down.',
    'Flylo-DOOM': 'Fan-designated name for loose collaborative material between MF DOOM and producer Flying Lotus; never compiled into an official release.',
    'Super What?': 'Rumored project MF DOOM was reportedly working on later in his career; never officially released.',
    'Post Super What?': 'Catch-all era for MF DOOM material believed to have been recorded after the Super What? sessions.',
    'Unknown': 'Catch-all for songs whose era or recording period could not be determined.',
    'Ongoing': 'Catch-all for recent leaks not yet assigned to a specific era.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'By All Means Necessary', 'Mr. Hood', 'BL_CK B_ST_RDS', 'Mental Illness',
    'Operation: Doomsday', '1999 - 2003', 'Vaudeville Villain', 'Take Me To Your Leader', 'Venomous Villain', 'Madvillainy', 'MM..FOOD',
    'The Mouse And The Mask', '2006 - 2008', 'Dilla-DOOM', 'Madvillainy 2', 'Special Herbs, Vols. 9 & 0',
    'BORN LIKE THIS', 'Swift & Changeable', 'Key to the Kuffs', 'DOOMYORKES', 'NehruvianDOOM',
    '2015 - 2017', 'Special Herbs 10', 'The Missing Notebook Rhymes', 'WestSide Doom', 'Czarface Meets Metal Face',
    'Flylo-DOOM', 'Super What?', 'Post Super What?', 'Unknown', 'Ongoing',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
  hasTracklistsTab: false,
  hasSubAlbumsTab: false,
};
