import type { ArtistConfig } from './types';

export const mfgoldConfig: ArtistConfig = {
  slug: 'mfgold',
  SITE_NAME: 'MFGOLD',
  SITE_DESCRIPTION: 'The Best MF DOOM Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/mfgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'mfgold_',
  HARDCODED_SHEET_ID: '1zEbzMVXFXzuY4wLdPvdQA23lb3RwCSOKqWtHsllXNk8',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1zEbzMVXFXzuY4wLdPvdQA23lb3RwCSOKqWtHsllXNk8/export?format=csv&gid=1476766908',
  accentColor: '#16a34a',
  artistLabel: 'MF DOOM',
  cardLetter: 'DOOM',
  logoUrl: '/logos/mfgold.png',
  artistPhotoUrl: '/artists/mfdoom.jpg',

  getArtistName() {
    return 'MF DOOM';
  },

  CUSTOM_IMAGES: {
    'By All Means Necessary': '/mfgold/eras/by-all-means-necessary.jpg',
    'Mr. Hood': '/mfgold/eras/mr-hood.jpg',
    'BL_CK B_ST_RDS': '/mfgold/eras/bl-ck-b-st-rds.jpg',
    'Mental Illness': '/mfgold/eras/mental-illness.jpg',
    'Operation: Doomsday': '/mfgold/eras/operation-doomsday.jpg',
    '1999 - 2003': '/mfgold/eras/1999-2003.jpg',
    'Vaudeville Villain': '/mfgold/eras/vaudeville-villain.jpg',
    'Take Me To Your Leader': '/mfgold/eras/take-me-to-your-leader.jpg',
    'Venomous Villain': '/mfgold/eras/venomous-villain.jpg',
    'Madvillainy': '/mfgold/eras/madvillainy.jpg',
    'MM..FOOD': '/mfgold/eras/mm-food.jpg',
    'The Mouse And The Mask': '/mfgold/eras/the-mouse-and-the-mask.jpg',
    '2006 - 2008': '/mfgold/eras/2006-2008.jpg',
    'Dilla-DOOM': '/mfgold/eras/dilla-doom.jpg',
    'Madvillainy 2': '/mfgold/eras/madvillainy-2.jpg',
    'Special Herbs, Vols. 9 & 0': '/mfgold/eras/special-herbs-vols-9-0.jpg',
    'BORN LIKE THIS': '/mfgold/eras/born-like-this.jpg',
    'Swift & Changeable': '/mfgold/eras/swift-changeable.jpg',
    'Key to the Kuffs': '/mfgold/eras/key-to-the-kuffs.jpg',
    'DOOMYORKES': '/mfgold/eras/doomyorkes.jpg',
    'NehruvianDOOM': '/mfgold/eras/nehruviandoom.jpg',
    '2015 - 2017': '/mfgold/eras/2015-2017.jpg',
    'Special Herbs 10': '/mfgold/eras/special-herbs-10.jpg',
    'The Missing Notebook Rhymes': '/mfgold/eras/the-missing-notebook-rhymes.jpg',
    'WestSide Doom': '/mfgold/eras/westside-doom.jpg',
    'Czarface Meets Metal Face': '/mfgold/eras/czarface-meets-metal-face.jpg',
    'Flylo-DOOM': '/mfgold/eras/flylo-doom.jpg',
    'Super What?': '/mfgold/eras/super-what.jpg',
    'Post Super What?': '/mfgold/eras/post-super-what.jpg',
    'Unknown': '/artists/mfdoom.jpg',
    'Ongoing': '/artists/mfdoom.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'By All Means Necessary': '??/??/????',
    'Mr. Hood': '05/06/1991',
    'BL_CK B_ST_RDS': '??/??/2001',
    'Mental Illness': '??/??/????',
    'Operation: Doomsday': '10/19/1999',
    '1999 - 2003': '??/??/????',
    'Vaudeville Villain': '09/16/2003',
    'Take Me To Your Leader': '06/17/2003',
    'Venomous Villain': '??/??/2004',
    'Madvillainy': '03/23/2004',
    'MM..FOOD': '03/30/2004',
    'The Mouse And The Mask': '10/10/2005',
    '2006 - 2008': '??/??/????',
    'Dilla-DOOM': '??/??/????',
    'Madvillainy 2': '??/??/????',
    'Special Herbs, Vols. 9 & 0': '??/??/????',
    'BORN LIKE THIS': '03/17/2009',
    'Swift & Changeable': '??/??/????',
    'Key to the Kuffs': '06/05/2012',
    'DOOMYORKES': '??/??/????',
    'NehruvianDOOM': '12/09/2014',
    '2015 - 2017': '??/??/????',
    'Special Herbs 10': '??/??/????',
    'The Missing Notebook Rhymes': '??/??/????',
    'WestSide Doom': '??/??/????',
    'Czarface Meets Metal Face': '02/16/2018',
    'Flylo-DOOM': '??/??/????',
    'Super What?': '??/??/????',
    'Post Super What?': '??/??/????',
    'Unknown': '??/??/????',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'By All Means Necessary', 'Mr. Hood', 'BL_CK B_ST_RDS', 'Mental Illness',
    'Operation: Doomsday', '1999 - 2003', 'Vaudeville Villain', 'Take Me To Your Leader', 'Venomous Villain', 'Madvillainy', 'MM..FOOD',
    'The Mouse And The Mask', '2006 - 2008', 'Dilla-DOOM', 'Madvillainy 2', 'Special Herbs, Vols. 9 & 0',
    'BORN LIKE THIS', 'Swift & Changeable', 'Key to the Kuffs', 'DOOMYORKES', 'NehruvianDOOM',
    '2015 - 2017', 'Special Herbs 10', 'The Missing Notebook Rhymes', 'WestSide Doom', 'Czarface Meets Metal Face',
    'Flylo-DOOM', 'Super What?', 'Post Super What?', 'Unknown', 'Ongoing',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
  hasTracklistsTab: false,
  hasSubAlbumsTab: false,
};
