import type { ArtistConfig } from './types';

export const mjgoldConfig: ArtistConfig = {
  slug: 'mjgold',
  SITE_NAME: 'MJGOLD',
  SITE_DESCRIPTION: 'The Best Michael Jackson Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/mjgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'mjgold_',
  HARDCODED_SHEET_ID: '1i59TKrIZ1OvFFPJFuOMw1VXlvyzaVOH0Wb0vVJp9BTw',
  HARDCODED_SHEET_GID: '1792554832',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1i59TKrIZ1OvFFPJFuOMw1VXlvyzaVOH0Wb0vVJp9BTw/export?format=csv&gid=180906153',
  accentColor: '#facc15',
  artistLabel: 'Michael Jackson',
  cardLetter: 'MJ',
  logoUrl: '/logos/mjgold.jpg',
  artistPhotoUrl: '/artists/michaeljackson.jpg',

  getArtistName() {
    return 'Michael Jackson';
  },

  CUSTOM_IMAGES: {
    'Got To Be There': '/mjgold/eras/got-to-be-there.jpg',
    'Ben': '/mjgold/eras/ben.jpg',
    'Music & Me': '/mjgold/eras/music-and-me.jpg',
    'Forever, Michael': '/mjgold/eras/forever-michael.jpg',
    'Off The Wall': '/mjgold/eras/off-the-wall.jpg',
    'Thriller': '/mjgold/eras/thriller.jpg',
    'Bad': '/mjgold/eras/bad.jpg',
    'Bad 25': '/mjgold/eras/bad-25.jpg',
    'Dangerous': '/mjgold/eras/dangerous.jpg',
    'HIStory: Past, Present, And Future: Book I': '/mjgold/eras/history.jpg',
    'Blood On The Dance Floor: HIStory In The Mix': '/mjgold/eras/blood-on-the-dance-floor.jpg',
    'Invincible': '/mjgold/eras/invincible.jpg',
    'The Ultimate Collection': '/mjgold/eras/ultimate-collection.jpg',
    'Post-Invincible': '/mjgold/eras/post-invincible.jpg',
    'Thriller 25': '/mjgold/eras/thriller-25.jpg',
    'This Is It': '/mjgold/eras/this-is-it.jpg',
    'Final sessions': '/mjgold/eras/final-sessions.jpg',
    'Michael': '/mjgold/eras/michael.jpg',
    'XSCAPE': '/mjgold/eras/xscape.jpg',
    'Thriller 40': '/mjgold/eras/thriller-40.jpg',
    'Ongoing': '/mjgold/eras/ongoing.jpg',
    'Unclassified': '/mjgold/eras/unclassified.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Got To Be There': '01/24/1972',
    'Ben': '08/04/1972',
    'Music & Me': '04/13/1973',
    'Forever, Michael': '01/16/1975',
    'Off The Wall': '08/10/1979',
    'Thriller': '11/29/1982',
    'Bad': '08/31/1987',
    'Bad 25': '09/18/2012',
    'Dangerous': '11/21/1991',
    'HIStory: Past, Present, And Future: Book I': '06/20/1995',
    'Blood On The Dance Floor: HIStory In The Mix': '05/20/1997',
    'Invincible': '10/30/2001',
    'The Ultimate Collection': '11/16/2004',
    'Post-Invincible': '??/??/????',
    'Thriller 25': '02/08/2008',
    'This Is It': '10/27/2009',
    'Final sessions': '??/??/????',
    'Michael': '12/10/2010',
    'XSCAPE': '05/09/2014',
    'Thriller 40': '10/20/2022',
    'Ongoing': '??/??/????',
    'Unclassified': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Got To Be There', 'Ben', 'Music & Me', 'Forever, Michael',
    'Off The Wall', 'Thriller', 'Bad', 'Dangerous',
    'HIStory: Past, Present, And Future: Book I', 'Blood On The Dance Floor: HIStory In The Mix',
    'Invincible', 'The Ultimate Collection', 'Post-Invincible', 'Thriller 25', 'This Is It',
    'Final sessions', 'Michael', 'Bad 25', 'XSCAPE', 'Thriller 40', 'Ongoing', 'Unclassified',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
  hasMiscTab: false,
  hasSubAlbumsTab: false,
};
