import type { ArtistConfig } from './types';

export const rihannagoldConfig: ArtistConfig = {
  slug: 'rihannagold',
  SITE_NAME: 'RIHANNAGOLD',
  SITE_DESCRIPTION: 'The Best Rihanna Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/rihannagold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'rihannagold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#dc2626',
  artistLabel: 'Rihanna',
  cardLetter: 'RIH',
  logoUrl: '/logos/rihannagold.webp',
  artistPhotoUrl: '/artists/rihanna.webp',

  getArtistName() {
    return 'Rihanna';
  },

  CUSTOM_IMAGES: {
    'Music Of The Sun': '/artists/rihanna.webp',
    'A Girl Like Me': '/rihannagold/eras/a-girl-like-me.jpg',
    'Good Girl Gone Bad': '/rihannagold/eras/good-girl-gone-bad.jpg',
    'Rated R': '/rihannagold/eras/rated-r.jpg',
    'Loud': '/rihannagold/eras/loud.jpg',
    'Talk That Talk': '/rihannagold/eras/talk-that-talk.jpg',
    'Unapologetic': '/rihannagold/eras/unapologetic.jpg',
    'ANTI': '/rihannagold/eras/anti.jpg',
    'R9*': '/artists/rihanna.webp',
    'Ongoing': '/artists/rihanna.webp',
  },

  ALBUM_RELEASE_DATES: {
    'Music Of The Sun': '08/29/2005',
    'A Girl Like Me': '04/10/2006',
    'Good Girl Gone Bad': '05/31/2007',
    'Rated R': '11/23/2009',
    'Loud': '11/12/2010',
    'Talk That Talk': '11/18/2011',
    'Unapologetic': '11/19/2012',
    'ANTI': '01/28/2016',
    'R9*': '??/??/????',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'Music Of The Sun': "Rihanna's debut studio album, released August 29, 2005.",
    'A Girl Like Me': "Rihanna's second studio album, released April 10, 2006.",
    'Good Girl Gone Bad': "Rihanna's third studio album, released May 31, 2007, and her commercial breakthrough, led by the single \"Umbrella.\"",
    'Rated R': "Rihanna's fourth studio album, released November 23, 2009, with a darker, more introspective tone.",
    'Loud': "Rihanna's fifth studio album, released November 12, 2010, featuring singles like \"Only Girl (In The World)\" and \"S&M.\"",
    'Talk That Talk': "Rihanna's sixth studio album, released November 18, 2011, featuring the hit single \"We Found Love.\"",
    'Unapologetic': "Rihanna's seventh studio album, released November 19, 2012, her first album to debut at number one on the Billboard 200.",
    'ANTI': "Rihanna's eighth studio album, released January 28, 2016, marking a more experimental, R&B-leaning direction.",
    'R9*': "Fan term for Rihanna's long-in-development ninth studio album, teased for years but not yet officially released.",
    'Ongoing': 'Songs without a confirmed era or currently being worked on.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'Music Of The Sun',
    'A Girl Like Me',
    'Good Girl Gone Bad',
    'Rated R',
    'Loud',
    'Talk That Talk',
    'Unapologetic',
    'ANTI',
    'R9*',
    'Ongoing',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
