import type { ArtistConfig } from './types';

export const shadygoldConfig: ArtistConfig = {
  slug: 'shadygold',
  SITE_NAME: 'SHADYGOLD',
  SITE_DESCRIPTION: 'The Best Eminem Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/shadygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'shadygold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#e53e3e',
  artistLabel: 'Eminem',
  cardLetter: 'SHY',
  logoUrl: '/logos/shadygold.png',
  artistPhotoUrl: '/artists/eminem.webp',

  getArtistName(eraName) {
    if (!eraName) return 'Eminem';
    const d12Eras = ["Devil's Night", "D12 World", "Unknown Album", "Return Of The Dozen Vol. 2", "Shady XV", "The Re-Up"];
    if (d12Eras.some(e => eraName.startsWith(e))) return 'D12';
    const soulIntentEras = ["Soul Intent"];
    if (soulIntentEras.includes(eraName)) return 'Soul Intent';
    const earlyEras = ["Marshall & Ronnie Tapes", "New Jacks", "Steppin' On To The Scene", "Pre-Still In The Bassmint / The M&M Solo Tape", "Still In The Bassmint / The M&M Solo Tape"];
    if (earlyEras.some(e => eraName.startsWith(e.split('\n')[0]))) return 'M&M';
    return 'Eminem';
  },

  CUSTOM_IMAGES: {
    "Marshall & Ronnie Tapes": "https://i.ibb.co/LDGYkV4/eminem-early.jpg",
    "Infinite": "https://upload.wikimedia.org/wikipedia/en/5/5c/Eminem_-_Infinite.jpg",
    "Slim Shady EP": "https://upload.wikimedia.org/wikipedia/en/3/39/Slim_Shady_EP_cover.jpg",
    "The Slim Shady LP": "https://upload.wikimedia.org/wikipedia/en/3/35/Eminem_-_The_Slim_Shady_LP_CD_cover.jpg",
    "The Marshall Mathers LP": "https://upload.wikimedia.org/wikipedia/en/a/ae/The_Marshall_Mathers_LP.jpg",
    "The Eminem Show": "https://upload.wikimedia.org/wikipedia/en/3/35/Eminem_-_The_Eminem_Show.jpg",
    "Encore": "https://upload.wikimedia.org/wikipedia/en/4/4e/Eminem-encore.jpg",
    "Relapse": "https://upload.wikimedia.org/wikipedia/en/4/43/Eminem_-_Relapse.jpg",
    "Recovery": "https://upload.wikimedia.org/wikipedia/en/7/77/Eminem_-_Recovery.jpg",
    "The Marshall Mathers LP 2": "https://upload.wikimedia.org/wikipedia/en/8/87/The_Marshall_Mathers_LP_2.png",
    "Revival": "https://upload.wikimedia.org/wikipedia/en/2/2c/Eminem_-_Revival.png",
    "Kamikaze": "https://upload.wikimedia.org/wikipedia/en/8/8f/Eminem_-_Kamikaze.png",
    "Music To Be Murdered By": "https://upload.wikimedia.org/wikipedia/en/5/5c/Eminem_-_Music_to_Be_Murdered_By.png",
    "Music To Be Murdered By: Side B": "https://upload.wikimedia.org/wikipedia/en/e/e3/Music_to_Be_Murdered_By_-_Side_B.png",
    "The Death of Slim Shady (Coup de Grâce)": "https://upload.wikimedia.org/wikipedia/en/b/be/The_Death_of_Slim_Shady_%28Coup_de_Gr%C3%A2ce%29.png",
    "Curtain Call 2": "https://upload.wikimedia.org/wikipedia/en/0/0c/Eminem_-_Curtain_Call_2.png",
    "8 Mile Soundtrack": "https://upload.wikimedia.org/wikipedia/en/3/3e/8_Mile_Soundtrack.jpg",
    "Devil's Night": "https://upload.wikimedia.org/wikipedia/en/b/bd/D12_Devil%27s_Night.jpg",
    "D12 World": "https://upload.wikimedia.org/wikipedia/en/0/02/D12World.jpg",
    "Shady XV": "https://upload.wikimedia.org/wikipedia/en/8/84/Shady_XV.jpg",
    "Hell: The Sequel": "https://upload.wikimedia.org/wikipedia/en/6/62/Hell_The_Sequel.jpg",
  },

  ALBUM_RELEASE_DATES: {
    "Marshall & Ronnie Tapes": "??/??/1984",
    "New Jacks": "??/??/1988",
    "Steppin' On To The Scene": "??/??/1990",
    "Pre-Still In The Bassmint / The M&M Solo Tape": "??/??/1990",
    "Still In The Bassmint / \nThe M&M Solo Tape": "??/??/1992",
    "Soul Intent": "??/??/1993",
    "Infinite": "11/12/1996",
    "Slim Shady EP": "12/??/1997",
    "The Slim Shady LP": "02/23/1999",
    "The Marshall Mathers LP": "05/23/2000",
    "Devil's Night": "06/19/2001",
    "The Eminem Show": "05/26/2002",
    "8 Mile Soundtrack": "10/29/2002",
    "D12 World": "04/27/2004",
    "Encore": "11/12/2004",
    "Curtain Call": "12/06/2005",
    "Unknown Album": "??/??/????",
    "The Re-Up": "12/05/2006",
    "Album 6": "??/??/????",
    "King Mathers": "??/??/????",
    "Relapse": "05/15/2009",
    "Relapse 2": "??/??/????",
    "Recovery": "06/18/2010",
    "Hell: The Sequel": "06/14/2011",
    "Return Of The Dozen Vol. 2": "??/??/????",
    "The Marshall Mathers LP 2": "11/05/2013",
    "Shady XV": "11/24/2014",
    "Southpaw Soundtrack": "07/17/2015",
    "Revival": "12/15/2017",
    "Kamikaze": "08/31/2018",
    "Music To Be Murdered By": "01/17/2020",
    "Music To Be Murdered By: Side B": "12/18/2020",
    "Curtain Call 2": "12/02/2022",
    "The Death of Slim Shady (Coup de Grâce)": "07/12/2024",
    "STANS: The Official Soundtrack": "??/??/????",
    "LP13": "??/??/????",
    "Unknown": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {
    "Marshall & Ronnie Tapes": 3, "New Jacks": 7, "Steppin' On To The Scene": 11,
    "Pre-Still In The Bassmint / The M&M Solo Tape": 15, "Soul Intent": 45,
    "Infinite": 19, "Slim Shady EP": 12, "The Slim Shady LP": 74,
    "The Marshall Mathers LP": 67, "Devil's Night": 27, "The Eminem Show": 57,
    "8 Mile Soundtrack": 17, "D12 World": 21, "Encore": 90, "Curtain Call": 53,
    "Unknown Album": 17, "The Re-Up": 15, "Album 6": 56, "King Mathers": 92,
    "Relapse": 82, "Relapse 2": 58, "Recovery": 52, "Hell: The Sequel": 14,
    "Return Of The Dozen Vol. 2": 27, "The Marshall Mathers LP 2": 120, "Shady XV": 21,
    "Southpaw Soundtrack": 28, "Revival": 37, "Kamikaze": 22, "Music To Be Murdered By": 53,
    "Music To Be Murdered By: Side B": 30, "Curtain Call 2": 26,
    "The Death of Slim Shady (Coup de Grâce)": 26, "LP13": 9, "Unknown": 18,
  },
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    "Still In The Bassmint /\nThe M&M Solo Tape": "Still In The Bassmint / \nThe M&M Solo Tape",
  },

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By SHADYGOLD', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By SHADYGOLD': 'Leaks & Songs added by the owner of the site.',
  },
};
