import type { ArtistConfig } from './types';

export const shadygoldConfig: ArtistConfig = {
  slug: 'shadygold',
  hasGroupbuysTab: true,
  SITE_NAME: 'SHADYGOLD',
  SITE_DESCRIPTION: 'The Best Eminem Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/shadygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'shadygold_',
  HARDCODED_SHEET_ID: '1x9tTOOqH5WpKOoptdQzABSN_x8oZbMgzIGlGH9w1IKA',
  HARDCODED_SHEET_GID: '1792554832',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#e53e3e',
  artistLabel: 'Eminem',
  sheetCreator: 'JAYDAHEATER!, GrimR3xx, Emball, John Banana, Days Dissolve, G-Man Junior, Panda, Kaisersaurus, Franki8000, HighSpeedChase',
  cardLetter: 'SHY',
  logoUrl: '/logos/shadygold.png',
  artistPhotoUrl: '/artists/eminem.jpg',

  getArtistName(eraName) {
    if (!eraName) return 'Eminem';
    const d12Eras = ["Devil's Night", "D12 World", "Unknown Album", "Return Of The Dozen Vol. 2", "Shady XV", "The Re-Up"];
    if (d12Eras.some(e => eraName.startsWith(e))) return 'D12';
    const soulIntentEras = ["Soul Intent"];
    if (soulIntentEras.includes(eraName)) return 'Soul Intent';
    const earlyEras = ["Marshall & Ronnie Tapes", "New Jacks", "Steppin' On To The Scene", "Pre-Still In The Bassmint / The M&M Solo Tape", "Still In The Bassmint / The M&M Solo Tape"];
    if (earlyEras.some(e => eraName.startsWith(e.split('\n')[0]))) return 'M&M';
    return 'Eminem';
  },

  CUSTOM_IMAGES: {
    "Marshall & Ronnie Tapes": "https://i.ibb.co/LzPBCDk6/cell-Image-1792554832-0.jpg",
    "New Jacks": "https://i.ibb.co/XkSwbcRX/cell-Image-1792554832-1.jpg",
    "Steppin' On To The Scene": "https://i.ibb.co/3mkBNNgN/cell-Image-531726349-0.jpg",
    "Pre-Still In The Bassmint / The M&M Solo Tape": "https://i.ibb.co/3mkBNNgN/cell-Image-531726349-0.jpg",
    "Still In The Bassmint / \nThe M&M Solo Tape": "https://i.ibb.co/CphPwWgx/cell-Image-1792554832-4.jpg",
    "Soul Intent": "https://i.ibb.co/0VGbRpgn/cell-Image-909053212-1.jpg",
    "Infinite": "https://i.ibb.co/TqJ1G2Cc/cell-Image-909053212-2.jpg",
    "Slim Shady EP": "https://i.ibb.co/ycZjH9sh/cell-Image-909053212-4.jpg",
    "The Slim Shady LP": "https://i.ibb.co/3YB4LJnV/cell-Image-531726349-5.jpg",
    "The Marshall Mathers LP": "https://i.ibb.co/4RXDRgFm/cell-Image-531726349-6.jpg",
    "Devil's Night": "https://i.ibb.co/xKvHj9Sy/cell-Image-531726349-7.jpg",
    "The Eminem Show": "https://i.ibb.co/zVBvKdWb/cell-Image-531726349-8.jpg",
    "8 Mile Soundtrack": "https://i.ibb.co/Rp8sGSHB/cell-Image-531726349-9.jpg",
    "D12 World": "https://i.ibb.co/JjwxSh94/cell-Image-531726349-10.jpg",
    "Encore": "https://i.ibb.co/sJcmbMkL/cell-Image-531726349-11.jpg",
    "Curtain Call": "https://i.ibb.co/0j6n3KGT/cell-Image-531726349-12.jpg",
    "Unknown Album": "https://i.ibb.co/YMrqkWh/D12-Playlist-0.jpg",
    "The Re-Up": "https://i.ibb.co/N6LMgz1x/cell-Image-531726349-13.jpg",
    "Album 6": "https://i.ibb.co/B2CGcrx4/cell-Image-531726349-14.jpg",
    "King Mathers": "https://i.ibb.co/Jw128Wr6/cell-Image-531726349-15.png",
    "Relapse": "https://i.ibb.co/3Y839DGc/cell-Image-531726349-16.jpg",
    "Relapse 2": "https://i.ibb.co/tpJtYMKp/cell-Image-531726349-18.jpg",
    "Recovery": "https://i.ibb.co/PsJSqF3z/cell-Image-531726349-19.jpg",
    "Hell: The Sequel": "https://i.ibb.co/DHPPdMKp/cell-Image-531726349-20.jpg",
    "Return Of The Dozen Vol. 2": "https://i.ibb.co/F4mXVztX/cell-Image-531726349-21.jpg",
    "The Marshall Mathers LP 2": "https://i.ibb.co/f7mZxhY/cell-Image-531726349-22.jpg",
    "Shady XV": "https://i.ibb.co/5WKsNKVZ/cell-Image-531726349-23.jpg",
    "Southpaw Soundtrack": "https://i.ibb.co/vCQX49kd/cell-Image-531726349-24.jpg",
    "Revival": "https://i.ibb.co/ZPQzxVt/cell-Image-531726349-25.jpg",
    "Kamikaze": "https://i.ibb.co/JLfVKt1/cell-Image-531726349-26.jpg",
    "Music To Be Murdered By": "https://i.ibb.co/Wp2Hcfk7/cell-Image-531726349-27.jpg",
    "Music To Be Murdered By: Side B": "https://i.ibb.co/ZphBFsJx/cell-Image-531726349-28.jpg",
    "Curtain Call 2": "https://i.ibb.co/fzTD1LZY/cell-Image-531726349-29.png",
    "The Death of Slim Shady (Coup de Grâce)": "https://i.ibb.co/20S3ZzFH/cell-Image-531726349-30.jpg",
    "STANS: The Official Soundtrack": "https://i.ibb.co/5qxc054/cell-Image-909053212-243.jpg",
    "LP13": "https://i.ibb.co/SXhDjnLd/hq720.jpg",
    "Unknown": "https://i.ibb.co/XZPV7xD1/36079964425-7b3042d5e1-k.jpg",
  },

  ALBUM_RELEASE_DATES: {
    "Marshall & Ronnie Tapes": "??/??/1984",
    "New Jacks": "??/??/1988",
    "Steppin' On To The Scene": "??/??/1990",
    "Pre-Still In The Bassmint / The M&M Solo Tape": "??/??/1990",
    "Still In The Bassmint / \nThe M&M Solo Tape": "??/??/1992",
    "Soul Intent": "??/??/1993",
    "Infinite": "11/12/1996",
    "Slim Shady EP": "12/??/1997",
    "The Slim Shady LP": "02/23/1999",
    "The Marshall Mathers LP": "05/23/2000",
    "Devil's Night": "06/19/2001",
    "The Eminem Show": "05/26/2002",
    "8 Mile Soundtrack": "10/29/2002",
    "D12 World": "04/27/2004",
    "Encore": "11/12/2004",
    "Curtain Call": "12/06/2005",
    "Unknown Album": "??/??/????",
    "The Re-Up": "12/05/2006",
    "Album 6": "??/??/????",
    "King Mathers": "??/??/????",
    "Relapse": "05/15/2009",
    "Relapse 2": "??/??/????",
    "Recovery": "06/18/2010",
    "Hell: The Sequel": "06/14/2011",
    "Return Of The Dozen Vol. 2": "??/??/????",
    "The Marshall Mathers LP 2": "11/05/2013",
    "Shady XV": "11/24/2014",
    "Southpaw Soundtrack": "07/17/2015",
    "Revival": "12/15/2017",
    "Kamikaze": "08/31/2018",
    "Music To Be Murdered By": "01/17/2020",
    "Music To Be Murdered By: Side B": "12/18/2020",
    "Curtain Call 2": "12/02/2022",
    "The Death of Slim Shady (Coup de Grâce)": "07/12/2024",
    "STANS: The Official Soundtrack": "??/??/????",
    "LP13": "??/??/????",
    "Unknown": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    "Marshall & Ronnie Tapes": "Home recordings from Eminem's childhood with his uncle Ronnie Polkingharn, who first introduced him to hip-hop.",
    "New Jacks": "Early childhood freestyle recordings from Eminem's pre-teen years.",
    "Steppin' On To The Scene": "One of Eminem's earliest known demo tapes, recorded as a teenager in Detroit.",
    "Pre-Still In The Bassmint / The M&M Solo Tape": "Early demo sessions that preceded Still In The Bassmint / The M&M Solo Tape.",
    "Still In The Bassmint / \nThe M&M Solo Tape": "One of Eminem's earliest known solo demo tapes, recorded around 1992.",
    "Soul Intent": "Early Detroit rap group Eminem was part of alongside Proof, prior to forming D12.",
    "Infinite": "Infinite was Eminem's first studio album. According to Eminem, it sold maybe 20 copies and didn't get great feedback. A lot of people thought he sounded like Nas, which was a heavy influence for him at the time. A little after its release, Eminem attempted suicide by swallowing tylenol pills. Thankfully he lived and went on to work on the Slim Shady EP afterwards.",
    "Slim Shady EP": "After his failed suicide attempt, Eminem worked on the Slim Shady EP. It got some buzz in the underground and online sites couldn't keep it in stock. Following the Rap Olympics, Dean Geistlinger from Interscope, an assistant in Jimmy Iovine's office at that time would be given the demo by Eminem. The tape then would eventually find its way to Dr. Dre & Jimmy Iovine's hands, who loved it.",
    "The Slim Shady LP": "Dr. Dre eventually got to work with Eminem, they made 5 songs in their first sesison together (My Name Is, Role Model, Being Partners, When Hell Freezes Over & Night And Day), 3 of those would be release on The Slim Shady LP. This is usually considered to be Eminem's first studio album.",
    "The Marshall Mathers LP": "With the success of The Slim Shady LP, Eminem had to make another album. Originally titled \"Amsterdamn\", which was one of his favorite cities, this and a combination of being \"irked\" by Dutch journalists (which he'd write several songs about on his first trip) and the legal drugs it had to offer is what inspired the original title. The name would go from \"Amsterdamn\" to \"The Marshall Mathers LP\" after he made the song \"Marshall Mathers\". This is widley considered to be one of, if not, Eminem's best album, The Marshall Mathers LP sold 1.78 million copies in its first week, which made it one of the fastest-selling studio albums in the United States.",
    "Devil's Night": "After the success of The Slim Shady LP, Eminem kept his promise and brought D12 with him. Making their first appearences on MMLP (Amityville & Under The Influence respectively). They would name Devil's Night after a tradition in Detroit where the night before Halloween (October 30th), which had to do with vandelism and arson.",
    "The Eminem Show": "Work on The Eminem Show would start during the making of 8 Mile with the song \"Sing For The Moment\". Originally slated for a June 4th, 2002 release, but was pushed ahead after it got leaked weeks in advance. The song \"Stimulate\" was supposed to be in Say Goodbye To Hollywood's place.",
    "8 Mile Soundtrack": "A soundtrack that was made alongside the 2002 semi-autobiographical movie 8 Mile, starring Eminem.",
    "D12 World": "Originally titled \"Devil's Night Part II\", as mentioned by Bizarre on Census Bureau and on the outro to Cheers by Obie Trice. D12 World is the second and final studio album by D12.",
    "Encore": "From 2002-2004, Eminem was in the middle of some beef with Ja Rule & Benzino, making several diss tracks aimed at them, which were (for the most part) on the Invasion mixtape series hosted by DJ Green Lantern. Eminem would also sign Stat Quo in 2003. In November of 2003, a demo tape called \"Straight From The Lab\" would be leaked online in low quality by Nate's friend (not Nate as in Nate Dogg and not Joshua). This would cause Encore to be extensively reworked. Over time, Eminem's drug addiction got worse, contributing to the album's inconsistency and leading to songs such as \"My 1st Single\" and \"Rain Man\". The song \"Like Toy Soldiers\" would also mark the end of his beef with Ja Rule & Benzino.",
    "Curtain Call": "After Encore's release, Eminem would start work on some new music. He would also embark on the Anger Management 3 Tour alongside Lil Jon & 50 Cent. However, the European leg of the tour would be cancelled because Eminem checked into rehab for sleep medication. He would leave rehab in October 2005 and write Beautiful, as well as wrap up Curtain Call and release it in December. It should be noted that this was originally intended as a full length studio album.",
    "Unknown Album": "In 2006, Proof would mention that a third D12 album was in the works. On April 11th, 2006, Proof got shot and killed at a night club in Detroit. This effectively killed the group in the process, but work on the third album would continue. In April 2007, Mr. Porter would mention that he was guiding the album since and waiting on Eminem to sign off on the album. Eventually, in July 2007, Mr. Porter mentioned he wasn't having fun doing the album anymore, since Eminem was busy with his own projects and everyone else was doing their own thing. The songs \"Where I'm From\" & \"Don't Hate\" could've been meant for this album.",
    "The Re-Up": "In early 2006, Eminem would sign Ca$his & Bobby Creekwater to Shady Records. The Re-Up was originally supposed to be a mixtape, until Eminem liked the material enough to want to turn it into a compilation so it could give Stat, Bobby & Ca$his a \"real boost\".",
    "Album 6": "Almost a week after Curtain Call was released, Eminem started working on his next album. He would sign Bobby Creekwater & Ca$his during this time period. After Proof's death, Eminem's drug addiction would get way worse. Not much is known about this era, however a few songs and a list of songs that were gonna be on the album are available. Some of these tracks were reworked for the mixtape commonly known as \"King Mathers\", but only 4 ended up released (heavily reworked however), those being My Darling, Careful What You Wish For, Beautiful & Elevator (There Used To Be A Saying). The album is also known to feature Akon (unknown what song he is on).",
    "King Mathers": "After Eminem scrapped \"Album 6\" in November of 2006, he would continue to work on more music for his next project, \"King Mathers\". Ca$his was the one who gave Eminem that album title, and Eminem gave Ca$his the album title \"Loose Cannon\". Other names during this time were thrown around, like \"The Empact\" in mid-2008 by Sha Money XL, and Ca$his on MySpace. On December 24th, 2007, Eminem overdosed on methadone and nearly died. His publicist would later say it was pneumonia, which was debunked later on. The first version of King Mathers was scrapped because of this. Eminem would also reconcile with Royce too, thanks to Ca$his. On April 20th, 2008, Eminem would become sober, and he would scrap King Mathers soon after in July 2008.",
    "Relapse": "After Eminem sobered up, he would basically learn how to rap again. He would make some warm up tracks like \"Detroit Basketball\" and \"Wee Wee\". Eventually, Eminem would team up with Dr. Dre, and they would work on Detox and Relapse. Originally intended for a December 2008 release date. Eminem mentioned that he made enough material during the sesions for three Relapse albums. He would also hint at a sequel and confirm it in interviews and the Steve Berman skit.",
    "Relapse 2": "Initially comprising of leftovers from Relapse, Eminem would work on Relapse 2. Eminem, Mr. Porter & Dr. Dre would fly out to Hawaii and work on Relapse 2. During these sessions Eminem would transition from using accents to using none at all. Dre would eventually leave to work on Detox. Eminem would return and work with Just Blaze. In October 2009, Eminem mentioned that Relapse 2 was done and just needed to be mixed. To hold the fans over, Eminem would re-release Relapse as \"Relapse: Refill\" with some bonus tracks. On April 14th, 2010, Eminem would tweet that \"There is no Relapse 2\".",
    "Recovery": "After the third version of Relapse 2 was turned down by the label, Eminem decided to scrap it, and instead evolve it into Recovery, making many new songs for it such as Love The Way You Lie, Seduction, and Not Afraid, whilst also taking his favorite songs from the Relapse 2 sessions such as On Fire, Cold Wind Blows, and So Bad and moving them onto Recovery as well. The recording sessions for this album were just a little under 7 months, however some of the material used dates back many more months, since they are from Relapse 2 sessions.",
    "Hell: The Sequel": "In late 2010, Eminem & Royce would start work on Hell: The Sequel. The album name comes from a song they made in 1999 named \"Bad Meets Evil\" where Eminem raps at the end \"see you in hell for the sequel\". Em & Royce had a falling out later on and wouldn't reconcile until mid-2008 with the help of Ca$his. During the recording sessions for this album, Koolo had got his hands on some of the songs as they were being made, and decided to leak demos for the songs \"Echo\" and \"Living Proof\" in November 2010. This caused those tracks to be pushed to the deluxe edition, and a song called \"Take From Me\" was made about the leaks. Royce was beefing with Koolo on Twitter during this time, so Koolo would also leak a snippet for the song \"Take From Me\", as a way to get back at Royce for \"disrespecting his mother\".",
    "Return Of The Dozen Vol. 2": "A mixtape D12 was originally going to release in 2009, but delayed it until 2011. Eminem was only on one song on the released version.",
    "The Marshall Mathers LP 2": "Eminem would team up with Rick Rubin to work on a sequel to MMLP. It would have a tie-in with Call Of Duty: Ghosts, and was available to preorder. Not only was the song \"Survival\" used as a single for it, but the song \"Don't Front\" was included. The track was included in the special edition of COD Ghosts & MMLP2.",
    "Shady XV": "A compilation released to celebrate 15 years of Shady Records. Disc 1 consisted of new material, and Disc 2 was older songs. It also contained a demo of Lose Yourself.",
    "Southpaw Soundtrack": "A soundtrack made for Southpaw. Eminem was supposed to star in the movie, but he turned it down.",
    "Revival": "After not releasing an album since 2013, Eminem made a return. Starting with the single titled \"Campaign Speech\", Starting the rollout for Revival. It was promoted using a cryptic marketing campaign for a fake pharmaceutical company, in late October 2017. This name ties into his continued use of drug references - Relapse (2009) and Recovery (2010) -in his album titles. When it released it was met with negative reception.",
    "Kamikaze": "On August 31, 2018, Eminem unexpectedly released his tenth studio album, Kamikaze. The follow-up to his December 2017 album Revival. Due to Revival's reception, Eminem was mad and made a whole album expressing his anger while dissing a lot of people.",
    "Music To Be Murdered By": "Music To Be Murdered By would be released as a surprise drop on January 17th, 2020, and is the eleventh studio by now. Following Kamikaze's reception, the album was inspired by Sir Alfred Hitchcock (1899–1980) One of the most influential and prominent directors and filmmakers of all time, who titled his 1958 music album, \"Music to Be Murdered By\".",
    "Music To Be Murdered By: Side B": "Less than a year after the release of the standard edition, Eminem would drop a deluxe version to MTBMB. This was originally intended to be a surprise release, but the cover art would end up leaking days before the release. The surprise release of the album contains a reference to Side B in the standard edition, specifically in \"You Gon' Learn\" A possible foreshadow, \"Thought my name was B-side 'cause they flipped over my tape\".",
    "Curtain Call 2": "Curtain Call 2 is the second greatest hits collection by Eminem. The project serves as the sequel to his December 2005 album, Curtain Call: The Hits. The album includes music from 2005 to 2022, with music included from albums like May 2009’s Relapse, June 2010’s Recovery, November 2013’s The Marshall Mathers LP2, and more. Featured a re-recorded version of Is This Love.",
    "The Death of Slim Shady (Coup de Grâce)": "Following a hiatus after the release of Music To Be Murdered By: Side B, Eminem began teasing a new album in early 2024. A teaser for the album released on April 26th, 2024 that featured a fake news report about the murder of Slim Shady. Following the single release of 'Houdini' and another album trailer with a callback to Popsomp Hills from the Relapse era, The Death Of Slim Shady (Coupe de Grace) released on July 12th, 2024.",
    "STANS: The Official Soundtrack": "Soundtrack accompanying the 2024 documentary Stans, which explores Eminem's fanbase.",
    "LP13": "Working title used for material believed to be intended for Eminem's next studio album.",
    "Unknown": "Catch-all for miscellaneous leaks and songs without a confirmed era.",
  },
  ALBUM_SONG_COUNTS: {
    "Marshall & Ronnie Tapes": 3, "New Jacks": 7, "Steppin' On To The Scene": 11,
    "Pre-Still In The Bassmint / The M&M Solo Tape": 15, "Soul Intent": 45,
    "Infinite": 19, "Slim Shady EP": 12, "The Slim Shady LP": 74,
    "The Marshall Mathers LP": 67, "Devil's Night": 27, "The Eminem Show": 57,
    "8 Mile Soundtrack": 17, "D12 World": 21, "Encore": 90, "Curtain Call": 53,
    "Unknown Album": 17, "The Re-Up": 15, "Album 6": 56, "King Mathers": 92,
    "Relapse": 82, "Relapse 2": 58, "Recovery": 52, "Hell: The Sequel": 14,
    "Return Of The Dozen Vol. 2": 27, "The Marshall Mathers LP 2": 120, "Shady XV": 21,
    "Southpaw Soundtrack": 28, "Revival": 37, "Kamikaze": 22, "Music To Be Murdered By": 53,
    "Music To Be Murdered By: Side B": 30, "Curtain Call 2": 26,
    "The Death of Slim Shady (Coup de Grâce)": 26, "LP13": 9, "Unknown": 18,
  },
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    "Still In The Bassmint /\nThe M&M Solo Tape": "Still In The Bassmint / \nThe M&M Solo Tape",
  },

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By SHADYGOLD', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By SHADYGOLD': 'Leaks & Songs added by the owner of the site.',
  },
};
