import type { ArtistConfig } from './types';

export const slimegoldConfig: ArtistConfig = {
  slug: 'slimegold',
  SITE_NAME: 'SLIMEGOLD',
  SITE_DESCRIPTION: 'The Best Young Thug Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/slimegold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'slimegold_',
  HARDCODED_SHEET_ID: '12zc2reK5y8XP6SQhv1ujQtiG9VpJy7yDWwDuE-S-wpc',
  HARDCODED_SHEET_GID: '0',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/12zc2reK5y8XP6SQhv1ujQtiG9VpJy7yDWwDuE-S-wpc/export?format=csv&gid=1507357362',
  accentColor: '#ec4899',
  artistLabel: 'Young Thug',
  cardLetter: 'THUG',
  logoUrl: '/logos/slimegold.png',
  artistPhotoUrl: '/artists/youngthug-v2.jpg',

  getArtistName() {
    return 'Young Thug';
  },

  CUSTOM_IMAGES: {
    'I Came From Nothing': '/slimegold/eras/i-came-from-nothing.jpg',
    '1017 Thug': '/slimegold/eras/1017-thug.jpg',
    'Black Portland': '/slimegold/eras/black-portland.jpg',
    'HiTunes [V1]': '/slimegold/eras/hitunes-v1.jpg',
    'Metro Thuggin': '/slimegold/eras/metro-thuggin.jpg',
    'Rich Gang: Tha Tour Pt. 1': '/slimegold/eras/rich-gang-tha-tour-pt-1.jpg',
    'Rich Gang: Tha Tour Pt. 2': '/slimegold/eras/rich-gang-tha-tour-pt-2.jpg',
    'Barter 6': '/slimegold/eras/barter-6.jpg',
    'Hy!£UN35 [V2]': '/slimegold/eras/hyun35-v2.jpg',
    'Slime Season': '/slimegold/eras/slime-season.jpg',
    'Slime Season 2': '/slimegold/eras/slime-season-2.jpg',
    'MigoThuggin': '/slimegold/eras/migothuggin.jpg',
    'ThuggaWapp': '/slimegold/eras/thuggawapp.jpg',
    "I'm Up": '/slimegold/eras/im-up.jpg',
    'Slime Season 3': '/slimegold/eras/slime-season-3.jpg',
    'HiTunes [V3]': '/slimegold/eras/hitunes-v3.jpg',
    'JEFFERY': '/slimegold/eras/jeffery.jpg',
    'BEAUTIFUL THUGGER GIRLS': '/slimegold/eras/beautiful-thugger-girls.jpg',
    'Young Martha': '/slimegold/eras/young-martha.jpg',
    'SUPER SLIMEY': '/slimegold/eras/super-slimey.jpg',
    'Collaboration with 808 Mafia': '/slimegold/eras/collaboration-with-808-mafia.jpg',
    'Hy!£UN35 [V4]': '/slimegold/eras/hyun35-v4.jpg',
    'Slime Language': '/slimegold/eras/slime-language.jpg',
    'Barter 7': '/slimegold/eras/barter-7.jpg',
    'Static': '/slimegold/eras/static.jpg',
    'Slime WRLD': '/slimegold/eras/slime-wrld.jpg',
    'So Much Fun': '/slimegold/eras/so-much-fun.jpg',
    'So Much Fun (Deluxe)': '/slimegold/eras/so-much-fun-deluxe.jpg',
    'SUPER SLIMEY: SURFER EDITION': '/slimegold/eras/super-slimey-surfer-edition.jpg',
    'Punk [V1]': '/slimegold/eras/punk-v1.jpg',
    'Slime Language 2': '/slimegold/eras/slime-language-2.jpg',
    'Punk [V2]': '/slimegold/eras/punk-v2.jpg',
    'Unknown (2022)': '/slimegold/eras/unknown-2022.jpg',
    'BUSINESS IS BUSINESS': '/slimegold/eras/business-is-business.jpg',
    'LOVE YOU LATER': '/slimegold/eras/love-you-later.jpg',
    'Edd, Ed n Eddy': '/slimegold/eras/slime-sea4on.jpg',
    'UY SCUTI': '/slimegold/eras/edd-ed-n-eddy.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'I Came From Nothing': '05/14/2010',
    '1017 Thug': '09/12/2012',
    'Black Portland': '01/21/2014',
    'HiTunes [V1]': '03/11/2013',
    'Metro Thuggin': '??/??/????',
    'Rich Gang: Tha Tour Pt. 1': '??/??/????',
    'Rich Gang: Tha Tour Pt. 2': '??/??/????',
    'Barter 6': '04/17/2015',
    'Hy!£UN35 [V2]': '??/??/????',
    'Slime Season': '04/18/2015',
    'Slime Season 2': '09/18/2015',
    'MigoThuggin': '12/18/2015',
    'ThuggaWapp': '??/??/????',
    "I'm Up": '11/03/2015',
    'Slime Season 3': '02/12/2016',
    'HiTunes [V3]': '??/??/????',
    'JEFFERY': '04/11/2016',
    'BEAUTIFUL THUGGER GIRLS': '10/21/2017',
    'Young Martha': '09/08/2017',
    'SUPER SLIMEY': '10/20/2017',
    'Collaboration with 808 Mafia': '??/??/????',
    'Hy!£UN35 [V4]': '??/??/????',
    'Slime Language': '04/27/2018',
    'Barter 7': '??/??/????',
    'Static': '??/??/????',
    'Slime WRLD': '??/??/????',
    'So Much Fun': '08/16/2019',
    'So Much Fun (Deluxe)': '08/23/2019',
    'SUPER SLIMEY: SURFER EDITION': '??/??/????',
    'Punk [V1]': '10/15/2021',
    'Slime Language 2': '05/08/2020',
    'Punk [V2]': '??/??/????',
    'Unknown (2022)': '10/22/2021',
    'BUSINESS IS BUSINESS': '06/23/2023',
    'LOVE YOU LATER': '??/??/????',
    'Slime Sea4on': '??/??/????',
    'Edd, Ed n Eddy': '??/??/????',
    'UY SCUTI': '01/02/2025',
    'Day Before Coachella': '10/17/2025',
    'GØŁDMØÜFDÖG': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'I Came From Nothing': "Across 2011 to 2012, Jeffery Lamar Williams, known as Young Thug, released three mixtapes in his I Came From Nothing series, with the first and third being hosted by DJ Swamp Izzo.",
    '1017 Thug': "1017 Thug is the first installment in Young Thug's 1017 Thug series, released on February 23, 2013. This is the mixtape that began to put Thug on the map.",
    'Black Portland': "Black Portland is a collaborative mixtape between Young Thug and Bloody Jay. The tape features experimental production and drowned-in-AutoTune vocals alongside traditional rapping. It was released on January 21, 2014, and was met with acclaim by outlets like Stereogum.",
    'HiTunes [V1]': "Thug first announced \"HiTunes\" on November 8, 2013. Promotion continued in February of 2014 while he dropped \"Stoner\" and its video, likely intended to be the first single. However, Thug was quiet about the project after this, likely due to him struggling to get out of his 1017 contract. Two sequels of \"1017 Thug\" released in 2014, but Thug didn't work on either and they were put together by Alex Tumay to satisfy his contract. Emanwhile, Thug did make reference to his \"album\" during this time, indicating \"HiTunes\" was still in progress. After joining 300 Entertainment, Lyor Cohen gave Thug a release plan that would see him first drop a commercial mixtape, followed by \"HiTunes\" being re-announced to ride that momentum. It's assumed at this point Thug shifted focus to finishing his collaboration with Rich Homie Quan and developing \"Barter 6\".",
    'Metro Thuggin': "Metro Thuggin was a collaborative project between Metro Boomin and Young Thug, primarily recorded between Septemmber 2013 and February 2014 and announced in March 2014 with the release of the lead single \"The Blanguage.\" They released \"Cash Talk\" three months later, but the project stalled after missing its originally announced Spring release, Thug focused on \"Tha Tour Pt. 1\" with Rich Gang and Metro on \"Rodeo\" with Travis Scott during latter 2014. In early 2015 they began teasing the album again, releasing 3 more singles in January and February and planning a Spring 2015 release. However, the project never released and several tracks were either released on \"Slime Season\" 1 & 2 or given to other artists in mid 2015. Metro later said that the album was shelved by 300 Entertainment.",
    'Rich Gang: Tha Tour Pt. 1': "\"Birdman Presents Rich Gang: Tha Tour Pt. 1\" is the classic Young Thug and Rich Homie Quan collaboration mixtape that massively boosted Thug’s career while simultaneously being Quan’s last popular project. After Thug & Quan’s friendship ended, Pt. 2 was considered scrapped, but most of the songs from it eventually leaked.",
    'Rich Gang: Tha Tour Pt. 2': "\"Tha Tour Pt. 2\" was supposed to be the sequel to the previous \"Tha Tour\" mixtape, announced in November 2014 and intended to release before the Rich Gang 2 album. Thug and Quan recorded a bit in late 2014, but leading into 2015 Thug seems to have been more focused on \"Barter 6\". In March 2015 Thug and Quan fell out after Thug publicly trashed him during an appearance on the \"Rodeo\" tour over him remaining neutral on Birdman and Lil Wayne's beef. Cover art is fan-made.",
    'Barter 6': "\"Barter 6\" is Young Thug’s debut solo mixtape under 300 Entertainment. The project was released on April 17, 2015 – the same date as Thug’s mom, Mama Duck’s, birthday. The mixtape was originally titled \"Tha Carter 6\" as a spiritual successor to his idol Lil Wayne’s Carter series, but 3 days before its release, Thug swapped the ‘C’ for a ‘B'. \"Barter 6\" was intended to build momentum for Thug to lead into the release of his first album, \"Hy!£UN35\", and the Day \"Barter 6\" released it was also announced.",
    'Hy!£UN35 [V2]': "The day \"Barter 6\" dropped, Lyor Cohen sent out an email saying \"Hy!£UN35\" would arrive on August 28. In July 2015, Thug reaffirmed that \"Hy!£UN35\" was still 'on the way,' after \"Slime Season\" failed to drop on its original release date of July 4, 2015. Young Thug later announced the “Hy!£UN35 Tour” on August 6, 2015 after dropping “Pacifier” as a single. However, August 28 passed, and there was no sign of the album nor tour. However, on September 9 and the next few days, Thugger announced on Instagram that the tour would begin in a week, and it lasted throughout October. Fanmade art.",
    'Slime Season': "Young Thug’s long-awaited \"Slime Season\" mixtape was originally set to be released on July 4, 2015, entirely produced by London On Da Track, but it was delayed until September 15. This is likely because of the 100-song leak of which Thugger was a victim in May 2015, which included most of the songs on this mixtape. London On Da Track hinted that Thugger’s label requested the changes that caused the mixtape to become a solo Thug project instead of a collaboration between the two of them, with a 75-day delay. Many of the songs on \"Slime Season\" 1 and 2 have been found to date back to 2014, suggesting much of the new music Thug was recording was instead planned for \"Hy!£UN35\".",
    'Slime Season 2': "\"Slime Season 2\" is the second installment of Young Thug's \"Slime Season\" mixtape series. Thugger came through once again, delivering the second installment of \"Slime Season\" on Halloween 2015 – less than two months after the first.",
    'MigoThuggin': "\"MigoThuggin\" was a collaborative mixtape between Migos and Young Thug that was originally set to be released on Halloween of 2015, then on Christmas. However, Migos member Offset said that the project was frozen by 300 Entertainment’s Lyor Cohen indefinitely.",
    'ThuggaWapp': "\"ThuggaWapp\" is a scrapped collaborative project between Young Thug and Fetty Wap. On December 3, 2015, Young Thug announced on Twitter: \"ThuggaXWapp STAY READY.... VERY SOON\" alongside a sketch of the potential cover art. On December 7, 2015, Thug told French programme Mon Entourage “I’m bringing out a mixtape with Fetty Wap,” and that “all of them are done it’s just like four songs left on one of them. But all of them are done.” Several leaked songs are dated January 12, 2016 when they were either bounced or sent through iMessage, the project was likely being put together at this point. However, the project never saw an official release.",
    "I'm Up": "\"I’m Up\" is a surprise mixtape by Young Thug which temporarily interrupted the \"Slime Season\" trilogy.",
    'Slime Season 3': "\"Slime Season 3\" is the third installment of Young Thug's \"Slime Season\" mixtape series. Thug originally announced that \"Slime Season 3\" would drop on February 5, 2016. It was instead delayed and replaced with the mixtape I’m Up. It released instead on March 25, 2016.",
    'HiTunes [V3]': "Young Thug also announced yet another \"Hy!£UN35\" tour in March 2016, which lasted through the month of May, but \"Hy!£UN35\" the album still hadn’t been released. The art used for the era is the Year Of The Thug logo.",
    'JEFFERY': "Young Thug’s third retail mixtape, released on August 26, 2016. \"JEFFERY\" signaled a triumphant rebrand of Thug, as he retired his former stage name and took the name of Jeffery. All of the album’s tracks are named after his idols and biggest inspirations. The album was originally known as \"No, My Name is JEFFERY\", and was first announced on July 9, 2016.",
    'BEAUTIFUL THUGGER GIRLS': "\"BEAUTIFUL THUGGER GIRLS\" is Young Thug’s fourth commercial mixtape, executively produced by Drake, Wheezy and London On Da Track. Originally titled \"Easy Breezy Beautiful Thugger Girls\", sometimes referred to as shortened E.B.B.T.G. As opposed to his heavy trap mixtapes of the past, this project blends together elements of rap, R&B, pop, and country. Thug first announced the project on April 26, 2017, through Twitter, describing it as a “singing album.” However, it was postponed for unknown reasons before its final release on June 16.",
    'Young Martha': "\"Young Martha\" is a collaborative EP by rapper Young Thug and DJ/Producer Carnage. It was initially announced by Carnage in December 2016, but was released on September 22, 2017, through 300 Entertainment, YSL and Heavyweight Records. The EP was produced by Carnage but also featured co-production from OG Parker, Felix Snow and Wheezy. The final track of the project, “Don’t Call Me”, premiered in July 2016, and was expected to be included on Carnage’s sophomore album, but instead featured on this EP.",
    'SUPER SLIMEY': "\"SUPER SLIMEY\" is a collaborative mixtape by Future and Young Thug, released on October 20, 2017. The project features the two Atlanta rappers flowing over trap production by 808 Mafia, Wheezy, London and more. There is only one feature on this project, and that’s from Offset, a member of the Migos group. The project began around mid 2016 after the two squashed their beef. After taking time away to finish their own albums, they recorded further in 2017 and finished up the project a bit more than a year after it began.",
    'Collaboration with 808 Mafia': "Young Thug was working on a collaborative project with Southside and TM88 of 808 Mafia around the time he was working on \"SUPER SLIMEY\" with Future. On December 7, 2017, Alex Tumay tweeted “This is gonna be thugs DS2”, teasing the Southside produced album containing heavier, modern trap beats. On December 29, 2017, TM88 tweeted that there is a \"a Slime x Sizzle x 88 project that’s completed\" in response to fans. He still planned on releasing in 2018, but scrapped it to work on other projects. The cover art for the era is fanmade by Zonark000.",
    'Hy!£UN35 [V4]': "\"Hy!£UN35\" was supposed to be Young Thug's debut album. Leaked documents from April 9, 2018 show plans of a 2018 rollout for the album. \"Hear No Evil\" was going to be the teaser for the new version of the album, with the album being set to release in June of 2018. There was going to be a documentary type video made for Thug to give more hype. It was set to be announced on May 11 alongside the cover art, but this did not happen and the rollout was cancelled. The cover art used for this era is from a leaked album photoshoot on April 6, 2018.",
    'Slime Language': "\"Slime Language\" was released on August 17, 2018, the day after Thug’s 27th birthday. The project is Thug’s first full-length offering since June 2017’s \"BEAUTIFUL THUGGER GIRLS\". With Slime Language, Thug continues post- \"Hear No Evil\" with his 2018 theme of honoring his deaf brother, Greg. The project’s artwork features the phrase “Young Stoner Life” spelled out in drawings of American Sign Language, and of course, the title \"Slime Language\" itself is literally a play on “sign language.”",
    'Barter 7': "\"Barter 7\" was likely the main solo project Thug worked on in 2018 after the \"Hy!£UN35\" rollout was cancelled and while he worked on \"Slime Language\" with YSL. \"Barter 7\" was first teased by Wheezy in 2017 in an Instagram post, but never officially announced as his next album. In August Thug learned he would soon be charged for 2017 drug and gun possession, and put together the EP \"On the Rvn\" to release when he was arrested. Following the release of \"On the Rvn\" Thug announced the project, tweeting \"🅱️🅰️RTER 7 in moments 😇\" and shared an image to his Instagram which seemed to be an outtake from the \"Barter 6\" photoshoot. However, on January 25, 2019, he confirmed in an Instagram live that \"Lil Wayne trying to sue [him] for that,\" meaning the project was scrapped.",
    'Static': "\"Static\" is a scrapped collaborative project by Trae tha Truth, Young Thug and Gunna. Trae announced the project on Instagram on September 4, 2018, claiming it would release during October, but nothing ever surfaced. On October 30, 2018, Trae took to Facebook to explain that, even though the album was already finished, he was forced to delay its release. There has been no release date announced since.",
    'Slime WRLD': "Young Thug confirmed he was working on a project with Juice WRLD in an interview with BigBoyTV released on August 21, 2019. It was first teased in 2018. \"He don't just wanna put out [an album] out, we're doing a sketch, we're doing a 45-minute movie with this album\". Unfortunately, the project was scrapped after Juice's death in December 2019. The \"Slime WRLD\" name has never been confirmed, but is popular with fans and has been repeated by members of both teams. According to a leaker, no tracklist ever existed. The cover art used for this era is fanmade.",
    'So Much Fun': "\"So Much Fun\", initially titled \"GØŁDMØÜFDÖG\", is Young Thug’s long-awaited debut studio album and thirteenth solo release, following his September 2018 EP \"On the Rvn\". The album boasts features from Lil Uzi Vert, Travis Scott, Future, J. Cole, Juice WRLD, 21 Savage, Gunna, and Lil Baby, among others.",
    'So Much Fun (Deluxe)': "Thug first announced a deluxe edition of \"So Much Fun\" via social media on December 18, 2019, hinting at two features: \"Deluxe out Friday… FT. *r**** ***t* ****a\". Fans quickly deciphered that the two names were Travis Scott and Gunna, who appeared together on \"Hot (Remix)\" and “Diamonds” and “Hop Off a Jet,” respectively. There were also two new solo tracks, “Die Today” and “Millions.”",
    'SUPER SLIMEY: SURFER EDITION': "\"SUPER SLIMEY: SURFER EDITION\" is the scrapped sequel to Future and Young Thug's 2017 collaborative project \"SUPER SLIMEY\", which would've seen Gunna and Lil Baby join the duo. The project was first announced with a teaser of \"Jewel Baby\", but the project seemingly was stalled by the COVID-19 pandemic. There were teases in 2021 to drop after the release of \"Slime Language 2\", however this never happened and following Thug's RICO arrest and falling out with Gunna the project was dead. The cover art used for this era is fanmade.",
    'Punk [V1]': "Young Thug originally intended to drop his second album, \"Punk\", in late 2019, soon after the release of \"So Much Fun\". In contrast to his debut which he described as 'lighthearted,' \"Punk\" would be more personal and introspective. He also said that the album would reflect “real rap.” After releasing the deluxe to \"So Much Fun\", he announced that Punk would drop in February of 2020. However, he did not end up dropping the album and eventually began working on \"Slime Language 2\" and \"Slime & B\" with Chris Brown, before later finishing the album in 2021. The cover art used for this era is a scrapped cover for the final album.",
    'Slime Language 2': "Slime Language 2 is the second Young Stoner Life compilation album, succeeding the original 2018 project. This time, Gunna was upgraded to a headlining artist on the album alongside Thug, reflecting his increased importance to the label and status rivaling Thug's. The album was first announced by Gunna in an interview May 22, 2020, and Thug confirmed it was coming July 29. The album was initially set to release August 16, and then Black Friday, but missed both dates.",
    'Punk [V2]': "\"Punk\" is Young Thug’s sophomore studio album and fourteenth official solo release. After not dropping in early 2020, Thug continues to work on solo music simultaneously with \"Slime Language 2\". On July 25, 2021 at Rolling Loud Miami, Young Thug debuted a new promotional single from the album, titled “Tick Tock.” This performance was then followed up with an NPR Tiny Desk home concert two days later, on July 27, 2021, where Thug performed four then-unreleased songs (including the aforementioned “Tick Tock”) and teased an October 15 release date for the album, as seen on the back of Thug’s t-shirt.",
    'Unknown (2022)': "On April 19, 2022, Thugger first teased the release of his third studio album after he shared an image of the artwork on his Instagram, indicating a 2022 release as he captioned: \"These past few weeks gave me so much to talk bout.. y’all ready??\" No title was ever confirmed, and although the cover led many to believe the project would be a fourth \"Slime Season\", insiders have claimed this was not the case. On May 9, Thug was arrested in Atlanta on gang-related charges, which halted any new music work. He was later charged in a 56-count RICO indictment which to him being locked up and unable to work on new music until he was released in late 2024.",
    'BUSINESS IS BUSINESS': "BUSINESS IS BUSINESS is Young Thug’s third studio album and fifteenth official solo release, following his October 2021, chart-topping, Punk. Due to Thug being incarcerated at the time of the album’s release, Metro Boomin, the album’s executive producer, compiled an album full of leaked tracks such as “Gucci Grocery Bag” and “Abracadabra,” older tracks such as “Want Me Dead” - which was recorded in 2017 - and other unreleased and old songs.",
    'LOVE YOU LATER': "A week after the release of \"BUSINESS IS BUSINESS\", a 'singing album' titled \"Love You Later\" was meant to drop. This was rumoured at the time and some songs supposedly meant for it were played at the \"BUSINESS IS BUSINESS\" listening party, but full confirmation including the title wouldn't surface until jail calls discussing the project leaked in August 2025. The has been rumored to have been scrapped due to the label only wanting to release trap music from Thug, but it may also have been in part due to \"BUSINESS IS BUSINESS\" underperforming.",
    'Slime Sea4on': "In 2024 London On Da Track began to work on some older Young Thug records in preparation for an album late into the year. This plan was likely scrapped following Young Thug's freedom on October 31, 2024, but London continued working with Thug and appeared heavily on UY SCUTI. Most of London's edits used AI isolated stems because he didn't have access to the original files.",
    'Edd, Ed n Eddy': "Soon after being released from prison Thug began recording heavily with Future and Lil Baby, as well as Wheezy. The first piece of new Thug music to be released was a collaboration between the three on Lil Baby's album. Shortly after \"UY SCUTI\" droppped leaker Pop revealed the three had been working on a full album called \"Edd, Ed n Eddy\", but the project was likely cancelled due to Future and Thug's falling out. The project may also have initially been called \"Super Slimey 2\", based on a studio pic with future and Wheezy where the title was seen. The cover isn't official, just what Pop shared to tease the project.",
    'UY SCUTI': "On October 31, 2024, Young Thug was finally free. UY Scuti was announced in early 2025 and was originally meant to release on May 9th, however this date was pushed back to 'before summer smash' which also didn't happen. After months of radio silence, various jail calls from Young Thug would leak, where he was dissing pretty much the entire industry. Suddenly, on September 12th, Thug would surprise drop 'Miss My Dogs' on Instagram & announce that UY SCUTI would be releasing on September 19th. However, fellow artist Destroy Lonely planned to release his album on this day, so he delayed it one week. Finally, on September 26th, 2025, UY SCUTI released",
    'Day Before Coachella': "Thug first started teasing a new album shortly after the release of \"UY SCUTI\". Shortly after being announced for Coachella 2026 he officially announced the album as \"DBC\", soon revealed to mean \"Day Before Coachella\". The album was presumed to release shortly before or after Coachella, but it didn't and presumably was scrapped. It's currently unclear what the concept or sound of the project was, although Thug did hint at a \"singing\" album after \"UY SCUTI\".",
    'GØŁDMØÜFDÖG': "\"GØŁDMØÜFDÖG\" was originally the title for \"So Much Fun\", but like \"HyTunes\" it is seemingly a title Thug is fond of and he revived it in 2026 for his forthcoming sixth studio album after scrapping \"Day Before Coachella\". In a visual for \"Shouters\" (also a 2019-era song Thug brought back) tattoos and grills are seen sporting the title. After mixed reception to \"UY SCUTI\", Thug is presumably hoping to recapture the feeling of what was his most successful period for his music.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    'Hy!£UN35 [V3]': 'HiTunes [V3]',
    'Collaboration with Juice WRLD': 'Slime WRLD',
  },
  ALBUM_ORDER: [
    'I Came From Nothing', '1017 Thug', 'Black Portland', 'HiTunes [V1]', 'Metro Thuggin',
    'Rich Gang: Tha Tour Pt. 1', 'Rich Gang: Tha Tour Pt. 2', 'Barter 6', 'Hy!£UN35 [V2]',
    'Slime Season', 'Slime Season 2', 'MigoThuggin', 'ThuggaWapp', "I'm Up", 'Slime Season 3',
    'HiTunes [V3]', 'JEFFERY', 'BEAUTIFUL THUGGER GIRLS', 'Young Martha', 'SUPER SLIMEY',
    'Collaboration with 808 Mafia', 'Hy!£UN35 [V4]', 'Slime Language', 'Barter 7', 'Static',
    'Slime WRLD', 'So Much Fun', 'So Much Fun (Deluxe)', 'SUPER SLIMEY: SURFER EDITION',
    'Punk [V1]', 'Slime Language 2', 'Punk [V2]', 'Unknown (2022)', 'BUSINESS IS BUSINESS',
    'LOVE YOU LATER', 'Slime Sea4on', 'Edd, Ed n Eddy', 'UY SCUTI', 'Day Before Coachella', 'GØŁDMØÜFDÖG',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
  hasMiscTab: false,
  hasSubAlbumsTab: false,
};
