import type { ArtistConfig } from './types';

export const slimegoldConfig: ArtistConfig = {
  slug: 'slimegold',
  SITE_NAME: 'SLIMEGOLD',
  SITE_DESCRIPTION: 'The Best Young Thug Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/slimegold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'slimegold_',
  HARDCODED_SHEET_ID: '12zc2reK5y8XP6SQhv1ujQtiG9VpJy7yDWwDuE-S-wpc',
  HARDCODED_SHEET_GID: '0',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/12zc2reK5y8XP6SQhv1ujQtiG9VpJy7yDWwDuE-S-wpc/export?format=csv&gid=1507357362',
  accentColor: '#ec4899',
  artistLabel: 'Young Thug',
  cardLetter: 'THUG',
  logoUrl: '/logos/slimegold.png',
  artistPhotoUrl: '/artists/youngthug.jpg',

  getArtistName() {
    return 'Young Thug';
  },

  CUSTOM_IMAGES: {
    'I Came From Nothing': '/slimegold/eras/i-came-from-nothing.jpg',
    '1017 Thug': '/slimegold/eras/1017-thug.jpg',
    'Black Portland': '/slimegold/eras/black-portland.jpg',
    'HiTunes [V1]': '/slimegold/eras/hitunes-v1.jpg',
    'Metro Thuggin': '/slimegold/eras/metro-thuggin.jpg',
    'Rich Gang: Tha Tour Pt. 1': '/slimegold/eras/rich-gang-tha-tour-pt-1.jpg',
    'Rich Gang: Tha Tour Pt. 2': '/slimegold/eras/rich-gang-tha-tour-pt-2.jpg',
    'Barter 6': '/slimegold/eras/barter-6.jpg',
    'Hy!£UN35 [V2]': '/slimegold/eras/hyun35-v2.jpg',
    'Slime Season': '/slimegold/eras/slime-season.jpg',
    'Slime Season 2': '/slimegold/eras/slime-season-2.jpg',
    'MigoThuggin': '/slimegold/eras/migothuggin.jpg',
    'ThuggaWapp': '/slimegold/eras/thuggawapp.jpg',
    "I'm Up": '/slimegold/eras/im-up.jpg',
    'Slime Season 3': '/slimegold/eras/slime-season-3.jpg',
    'HiTunes [V3]': '/slimegold/eras/hitunes-v3.jpg',
    'JEFFERY': '/slimegold/eras/jeffery.jpg',
    'BEAUTIFUL THUGGER GIRLS': '/slimegold/eras/beautiful-thugger-girls.jpg',
    'Young Martha': '/slimegold/eras/young-martha.jpg',
    'SUPER SLIMEY': '/slimegold/eras/super-slimey.jpg',
    'Collaboration with 808 Mafia': '/slimegold/eras/collaboration-with-808-mafia.jpg',
    'Hy!£UN35 [V4]': '/slimegold/eras/hyun35-v4.jpg',
    'Slime Language': '/slimegold/eras/slime-language.jpg',
    'Barter 7': '/slimegold/eras/barter-7.jpg',
    'Static': '/slimegold/eras/static.jpg',
    'Slime WRLD': '/slimegold/eras/slime-wrld.jpg',
    'So Much Fun': '/slimegold/eras/so-much-fun.jpg',
    'So Much Fun (Deluxe)': '/slimegold/eras/so-much-fun-deluxe.jpg',
    'SUPER SLIMEY: SURFER EDITION': '/slimegold/eras/super-slimey-surfer-edition.jpg',
    'Punk [V1]': '/slimegold/eras/punk-v1.jpg',
    'Slime Language 2': '/slimegold/eras/slime-language-2.jpg',
    'Punk [V2]': '/slimegold/eras/punk-v2.jpg',
    'Unknown (2022)': '/slimegold/eras/unknown-2022.jpg',
    'BUSINESS IS BUSINESS': '/slimegold/eras/business-is-business.jpg',
    'LOVE YOU LATER': '/slimegold/eras/love-you-later.jpg',
    'Edd, Ed n Eddy': '/slimegold/eras/slime-sea4on.jpg',
    'UY SCUTI': '/slimegold/eras/edd-ed-n-eddy.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'I Came From Nothing': '05/14/2010',
    '1017 Thug': '09/12/2012',
    'Black Portland': '01/21/2014',
    'HiTunes [V1]': '03/11/2013',
    'Metro Thuggin': '??/??/????',
    'Rich Gang: Tha Tour Pt. 1': '??/??/????',
    'Rich Gang: Tha Tour Pt. 2': '??/??/????',
    'Barter 6': '04/17/2015',
    'Hy!£UN35 [V2]': '??/??/????',
    'Slime Season': '04/18/2015',
    'Slime Season 2': '09/18/2015',
    'MigoThuggin': '12/18/2015',
    'ThuggaWapp': '??/??/????',
    "I'm Up": '11/03/2015',
    'Slime Season 3': '02/12/2016',
    'HiTunes [V3]': '??/??/????',
    'JEFFERY': '04/11/2016',
    'BEAUTIFUL THUGGER GIRLS': '10/21/2017',
    'Young Martha': '09/08/2017',
    'SUPER SLIMEY': '10/20/2017',
    'Collaboration with 808 Mafia': '??/??/????',
    'Hy!£UN35 [V4]': '??/??/????',
    'Slime Language': '04/27/2018',
    'Barter 7': '??/??/????',
    'Static': '??/??/????',
    'Slime WRLD': '??/??/????',
    'So Much Fun': '08/16/2019',
    'So Much Fun (Deluxe)': '08/23/2019',
    'SUPER SLIMEY: SURFER EDITION': '??/??/????',
    'Punk [V1]': '10/15/2021',
    'Slime Language 2': '05/08/2020',
    'Punk [V2]': '??/??/????',
    'Unknown (2022)': '10/22/2021',
    'BUSINESS IS BUSINESS': '06/23/2023',
    'LOVE YOU LATER': '??/??/????',
    'Slime Sea4on': '??/??/????',
    'Edd, Ed n Eddy': '??/??/????',
    'UY SCUTI': '01/02/2025',
    'Day Before Coachella': '10/17/2025',
    'GØŁDMØÜFDÖG': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'I Came From Nothing': 'Young Thug\'s earliest known mixtape, self-released in 2010 near the start of his career.',
    '1017 Thug': 'Young Thug\'s breakout mixtape, produced largely by London On Da Track and released under Gucci Mane\'s 1017 Brick Squad in 2013.',
    'Black Portland': 'Collaborative mixtape with Bloody Jay, released January 21, 2014.',
    'HiTunes [V1]': 'Earliest working version of the Hy!£UN35 mixtape, an early scrapped project from Young Thug\'s come-up.',
    'Metro Thuggin': 'Scrapped collaborative project between Young Thug and producer Metro Boomin from around 2014-2015.',
    'Rich Gang: Tha Tour Pt. 1': 'First installment of the Rich Gang mixtape series with Young Thug and Rich Homie Quan, hosted by DJ Holiday.',
    'Rich Gang: Tha Tour Pt. 2': 'Planned sequel to Tha Tour Pt. 1 with Rich Homie Quan that was never officially released.',
    'Barter 6': 'Young Thug\'s major-label mixtape, released April 17, 2015. Originally announced as "Carter 6" before a dispute with Lil Wayne forced the name change.',
    'Hy!£UN35 [V2]': 'Second working version of the Hy!£UN35 mixtape sessions.',
    'Slime Season': 'Mixtape released in 2015, the first entry in the Slime Season series.',
    'Slime Season 2': 'Second mixtape in the Slime Season series, released in 2015.',
    'MigoThuggin': 'Scrapped collaborative project between Young Thug and Migos from late 2015.',
    'ThuggaWapp': 'Scrapped collaborative project between Young Thug and Fetty Wap.',
    "I'm Up": 'Mixtape released November 3, 2015, hosted by DJ Carnage.',
    'Slime Season 3': 'Third mixtape in the Slime Season series, released February 12, 2016.',
    'HiTunes [V3]': 'Later working version of the Hy!£UN35 mixtape sessions, ultimately abandoned before the project became JEFFERY.',
    'JEFFERY': 'Young Thug\'s mixtape released April 11, 2016, notable for its cover art and songs each named after a public figure who inspired Thug.',
    'BEAUTIFUL THUGGER GIRLS': 'Young Thug\'s debut studio album, released October 21, 2017, blending rap with country and pop influences.',
    'Young Martha': 'Collaborative EP with producer Carnage, released September 8, 2017.',
    'SUPER SLIMEY': 'Collaborative mixtape with Future, released October 20, 2017.',
    'Collaboration with 808 Mafia': 'Scrapped collaborative project between Young Thug and the 808 Mafia production team.',
    'Hy!£UN35 [V4]': 'Final working version of the Hy!£UN35 mixtape before the project was ultimately shelved.',
    'Slime Language': 'Compilation mixtape released April 27, 2018, featuring Young Thug\'s YSL Records roster.',
    'Barter 7': 'Planned follow-up to Barter 6 that was never officially released.',
    'Static': 'Scrapped mixtape by Trae Tha Truth intended to feature Young Thug and Gunna, never released.',
    'Slime WRLD': 'Scrapped collaborative project between Young Thug and Juice WRLD.',
    'So Much Fun': 'Young Thug\'s second studio album, released August 16, 2019, his first to debut at number one on the Billboard 200.',
    'So Much Fun (Deluxe)': 'Deluxe edition of So Much Fun, released August 23, 2019 with additional tracks.',
    'SUPER SLIMEY: SURFER EDITION': 'Planned follow-up or deluxe edition to SUPER SLIMEY with Future that was never released.',
    'Punk [V1]': 'Young Thug\'s third studio album, Punk, released October 15, 2021.',
    'Slime Language 2': 'Compilation mixtape released May 8, 2020, again featuring Young Thug\'s YSL Records roster.',
    'Punk [V2]': 'Alternate versions and leftover sessions from the Punk album recordings that didn\'t make the final tracklist.',
    'Unknown (2022)': 'Catch-all for songs recorded in or around 2022 without a confirmed era.',
    'BUSINESS IS BUSINESS': 'Young Thug\'s fourth studio album, released June 23, 2023.',
    'LOVE YOU LATER': 'Planned Young Thug project worked on before his RICO arrest; considered for release but never officially put out.',
    'Slime Sea4on': 'Planned follow-up to the Slime Season mixtape series that has yet to be released.',
    'Edd, Ed n Eddy': 'Scrapped song/project title from 2025 sessions, likely tied to collaborations with Future and Lil Baby.',
    'UY SCUTI': 'Young Thug\'s fifth studio album, released January 2, 2025.',
    'Day Before Coachella': 'Bucket for a batch of loosies and collaborations that surfaced around October 2025.',
    'GØŁDMØÜFDÖG': 'Working title for an unreleased collaborative project associated with producer Fred again.., first teased via a song previewed at a Dior fashion show.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    'Hy!£UN35 [V3]': 'HiTunes [V3]',
    'Collaboration with Juice WRLD': 'Slime WRLD',
  },
  ALBUM_ORDER: [
    'I Came From Nothing', '1017 Thug', 'Black Portland', 'HiTunes [V1]', 'Metro Thuggin',
    'Rich Gang: Tha Tour Pt. 1', 'Rich Gang: Tha Tour Pt. 2', 'Barter 6', 'Hy!£UN35 [V2]',
    'Slime Season', 'Slime Season 2', 'MigoThuggin', 'ThuggaWapp', "I'm Up", 'Slime Season 3',
    'HiTunes [V3]', 'JEFFERY', 'BEAUTIFUL THUGGER GIRLS', 'Young Martha', 'SUPER SLIMEY',
    'Collaboration with 808 Mafia', 'Hy!£UN35 [V4]', 'Slime Language', 'Barter 7', 'Static',
    'Slime WRLD', 'So Much Fun', 'So Much Fun (Deluxe)', 'SUPER SLIMEY: SURFER EDITION',
    'Punk [V1]', 'Slime Language 2', 'Punk [V2]', 'Unknown (2022)', 'BUSINESS IS BUSINESS',
    'LOVE YOU LATER', 'Slime Sea4on', 'Edd, Ed n Eddy', 'UY SCUTI', 'Day Before Coachella', 'GØŁDMØÜFDÖG',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
  hasMiscTab: false,
  hasSubAlbumsTab: false,
};
