import type { ArtistConfig } from './types';

export const slimegoldConfig: ArtistConfig = {
  slug: 'slimegold',
  SITE_NAME: 'SLIMEGOLD',
  SITE_DESCRIPTION: 'The Best Young Thug Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/slimegold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'slimegold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#ec4899',
  artistLabel: 'Young Thug',
  cardLetter: 'THUG',
  logoUrl: '/logos/slimegold.png',
  artistPhotoUrl: '/artists/youngthug.jpg',

  getArtistName() {
    return 'Young Thug';
  },

  CUSTOM_IMAGES: {
    'I Came From Nothing': '/slimegold/eras/i-came-from-nothing.jpg',
    '1017 Thug': '/slimegold/eras/1017-thug.jpg',
    'Black Portland': '/slimegold/eras/black-portland.jpg',
    'HiTunes [V1]': '/slimegold/eras/hitunes-v1.jpg',
    'Metro Thuggin': '/slimegold/eras/metro-thuggin.jpg',
    'Rich Gang: Tha Tour Pt. 1': '/slimegold/eras/rich-gang-tha-tour-pt-1.jpg',
    'Rich Gang: Tha Tour Pt. 2': '/slimegold/eras/rich-gang-tha-tour-pt-2.jpg',
    'Barter 6': '/slimegold/eras/barter-6.jpg',
    'Hy!£UN35 [V2]': '/slimegold/eras/hyun35-v2.jpg',
    'Slime Season': '/slimegold/eras/slime-season.jpg',
    'Slime Season 2': '/slimegold/eras/slime-season-2.jpg',
    'MigoThuggin': '/slimegold/eras/migothuggin.jpg',
    'ThuggaWapp': '/slimegold/eras/thuggawapp.jpg',
    "I'm Up": '/slimegold/eras/im-up.jpg',
    'Slime Season 3': '/slimegold/eras/slime-season-3.jpg',
    'HiTunes [V3]': '/slimegold/eras/hitunes-v3.jpg',
    'JEFFERY': '/slimegold/eras/jeffery.jpg',
    'BEAUTIFUL THUGGER GIRLS': '/slimegold/eras/beautiful-thugger-girls.jpg',
    'Young Martha': '/slimegold/eras/young-martha.jpg',
    'SUPER SLIMEY': '/slimegold/eras/super-slimey.jpg',
    'Collaboration with 808 Mafia': '/slimegold/eras/collaboration-with-808-mafia.jpg',
    'Hy!£UN35 [V4]': '/slimegold/eras/hyun35-v4.jpg',
    'Slime Language': '/slimegold/eras/slime-language.jpg',
    'Barter 7': '/slimegold/eras/barter-7.jpg',
    'Static': '/slimegold/eras/static.jpg',
    'Slime WRLD': '/slimegold/eras/slime-wrld.jpg',
    'So Much Fun': '/slimegold/eras/so-much-fun.jpg',
    'So Much Fun (Deluxe)': '/slimegold/eras/so-much-fun-deluxe.jpg',
    'SUPER SLIMEY: SURFER EDITION': '/slimegold/eras/super-slimey-surfer-edition.jpg',
    'Punk [V1]': '/slimegold/eras/punk-v1.jpg',
    'Slime Language 2': '/slimegold/eras/slime-language-2.jpg',
    'Punk [V2]': '/slimegold/eras/punk-v2.jpg',
    'Unknown (2022)': '/slimegold/eras/unknown-2022.jpg',
    'BUSINESS IS BUSINESS': '/slimegold/eras/business-is-business.jpg',
    'LOVE YOU LATER': '/slimegold/eras/love-you-later.jpg',
    'Slime Sea4on': '/slimegold/eras/slime-sea4on.jpg',
    'Edd, Ed n Eddy': '/slimegold/eras/edd-ed-n-eddy.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'I Came From Nothing': '05/14/2010',
    '1017 Thug': '09/12/2012',
    'Black Portland': '01/21/2014',
    'HiTunes [V1]': '03/11/2013',
    'Metro Thuggin': '??/??/????',
    'Rich Gang: Tha Tour Pt. 1': '??/??/????',
    'Rich Gang: Tha Tour Pt. 2': '??/??/????',
    'Barter 6': '04/17/2015',
    'Hy!£UN35 [V2]': '??/??/????',
    'Slime Season': '04/18/2015',
    'Slime Season 2': '09/18/2015',
    'MigoThuggin': '12/18/2015',
    'ThuggaWapp': '??/??/????',
    "I'm Up": '11/03/2015',
    'Slime Season 3': '02/12/2016',
    'HiTunes [V3]': '??/??/????',
    'JEFFERY': '04/11/2016',
    'BEAUTIFUL THUGGER GIRLS': '10/21/2017',
    'Young Martha': '09/08/2017',
    'SUPER SLIMEY': '10/20/2017',
    'Collaboration with 808 Mafia': '??/??/????',
    'Hy!£UN35 [V4]': '??/??/????',
    'Slime Language': '04/27/2018',
    'Barter 7': '??/??/????',
    'Static': '??/??/????',
    'Slime WRLD': '??/??/????',
    'So Much Fun': '08/16/2019',
    'So Much Fun (Deluxe)': '08/23/2019',
    'SUPER SLIMEY: SURFER EDITION': '??/??/????',
    'Punk [V1]': '10/15/2021',
    'Slime Language 2': '05/08/2020',
    'Punk [V2]': '??/??/????',
    'Unknown (2022)': '10/22/2021',
    'BUSINESS IS BUSINESS': '06/23/2023',
    'LOVE YOU LATER': '??/??/????',
    'Slime Sea4on': '??/??/????',
    'Edd, Ed n Eddy': '??/??/????',
    'UY SCUTI': '01/02/2025',
    'Day Before Coachella': '10/17/2025',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'I Came From Nothing', '1017 Thug', 'Black Portland', 'HiTunes [V1]', 'Metro Thuggin',
    'Rich Gang: Tha Tour Pt. 1', 'Rich Gang: Tha Tour Pt. 2', 'Barter 6', 'Hy!£UN35 [V2]',
    'Slime Season', 'Slime Season 2', 'MigoThuggin', 'ThuggaWapp', "I'm Up", 'Slime Season 3',
    'HiTunes [V3]', 'JEFFERY', 'BEAUTIFUL THUGGER GIRLS', 'Young Martha', 'SUPER SLIMEY',
    'Collaboration with 808 Mafia', 'Hy!£UN35 [V4]', 'Slime Language', 'Barter 7', 'Static',
    'Slime WRLD', 'So Much Fun', 'So Much Fun (Deluxe)', 'SUPER SLIMEY: SURFER EDITION',
    'Punk [V1]', 'Slime Language 2', 'Punk [V2]', 'Unknown (2022)', 'BUSINESS IS BUSINESS',
    'LOVE YOU LATER', 'Slime Sea4on', 'Edd, Ed n Eddy', 'UY SCUTI', 'Day Before Coachella',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: false,
  hasVideosTab: false,
};
