import type { ArtistConfig } from './types';

export const smokegoldConfig: ArtistConfig = {
  slug: 'smokegold',
  SITE_NAME: 'SMOKEGOLD',
  SITE_DESCRIPTION: 'The Best Pop Smoke Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/smokegold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'smokegold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1-Kd8molYeR1WpmWR81DqmSCGng3g-AVmZfgd752kh3M/export?format=csv&gid=1507357362',
  accentColor: '#1a1a2e',
  artistLabel: 'Pop Smoke',
  cardLetter: 'P',
  logoUrl: '/logos/smokegold.webp',
  artistPhotoUrl: '/artists/popsmoke.webp',

  getArtistName() {
    return 'Pop Smoke';
  },

  CUSTOM_IMAGES: {
    'Meet The Woo 1': '/smokegold/eras/meet-the-woo-1.jpg',
    'Meet The Woo 2': '/smokegold/eras/meet-the-woo-2.jpg',
    'SFTSAFTM': '/smokegold/eras/sftsaftm.jpg',
    'SFTSAFTM (Deluxe)': '/smokegold/eras/sftsaftm.jpg',
    'Boogie': '/smokegold/eras/boogie.jpg',
    'Faith': '/smokegold/eras/faith.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'GQ': '??/??/????',
    'Meet The Woo 1': '07/26/2019',
    'Meet The Woo 2': '02/07/2020',
    'PS3': '??/??/????',
    'Collaboration with French Montana': '??/??/????',
    'Huncho Woo': '??/??/????',
    'SFTSAFTM': '07/03/2020',
    'SFTSAFTM (Deluxe)': '07/20/2020',
    'Boogie': '03/05/2021',
    'Faith': '07/16/2021',
    'Ongoing': '??/??/????',
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    'GQ': 'Bashar Barakah Jackson, most commonly known as Pop Smoke, was born on July 20, 1999. Some of his early aliases include "Poppa Stunnin," "GQ" and "Smoko Guwop," before finalizing with the name Pop Smoke. He started rapping in 2017 thanks to NYC rapper Jay Gwuapo. He was brought to the attention of Steven Victor with Victor Victor Worldwide with his popular songs "MPR" and "Flexin\'," as well as other then-unreleased songs that demonstrated talent in a variety of genres. He signed with Victor in April of 2019 and eventually dropped Meet The Woo, Vol. 1, his first mixtape, and the rest is history.',
    'Meet The Woo 1': 'Pop Smoke\'s debut mixtape, Meet The Woo, Vol. 1, was released on July 26, 2019, and marked a significant moment in the burgeoning New York drill scene. At the time, the 20-year-old rapper was just starting to make waves, garnering attention with his unique deep voice and aggressive delivery. Meet The Woo, Vol. 1 featured hard-hitting beats and gritty lyrics that showcased Pop Smoke\'s raw talent and potential. The mixtape quickly gained traction, with tracks like "Welcome to the Party" and "Dior" becoming viral hits and solidifying Pop Smoke\'s status as a rising star in the hip-hop world.',
    'Meet The Woo 2': 'Pop Smoke\'s second mixtape, Meet The Woo, Vol. 2, was released on February 7, 2020, just a few weeks before his untimely death. The mixtape was highly anticipated, following the success of his debut project and the growing buzz surrounding his unique style and energy. Meet The Woo, Vol. 2 featured collaborations with some of the biggest names in hip-hop, including Quavo, A Boogie wit da Hoodie, and Lil Tjay, among others. Despite its short release window, Meet The Woo, Vol. 2 was a commercial success, debuting at number seven on the Billboard 200 chart and further cementing Pop Smoke\'s status as a rising star in the rap world.',
    'PS3': 'Following the release of the deluxe to Meet The Woo, Vol. 2, Pop Smoke was then going to hone in on working on his debut album, which at the time did not have a confirmed title, for the summer of 2020. However, those plans were cut short when he was tragically killed in a robbery-gone-wrong on February 19, 2020 in Los Angeles, California, barely a week after the deluxe had come out. The untimely death shook the hip-hop world, and then put it into the hands of Victor Victor Worldwide to carry on his legacy and put out his debut album posthumously.',
    'Collaboration with French Montana': 'French Montana said in an interview that him and Pop recorded enough material for a collab project and intended on having one. They were seen in the studio August 2019, and later again in December 2019. As of now, the only officially released collabs between them that released were the tracks \'Double G\' & \'Stuck in the Jungle\', with the former ending up on French\'s 2020 mixtape \'CB5\', and the latter ending up on French\'s 2021 studio album \'They Got Amnesia\'.',
    'Huncho Woo': '\'Huncho Woo\' was a potential, now scrapped collaboration mixtape between Pop Smoke and Quavo that was being worked on during the making of \'Meet The Woo 2\' and considered to drop sometime in the future. Pop Smoke and Quavo had been working in the studio in several occasions, racking up to 9-10 songs together in the time that he was alive, including "Shake The Room". After the tragic passing of Pop Smoke, the potential of the project coming out disappeared, with some of the leftover tracks being used in \'Shoot For The Stars Aim For The Moon\', with others being rumored for the deluxe or being involved in the Migos\' \'Culture III\'.',
    'SFTSAFTM': 'Shoot For The Stars Aim For The Moon is the debut studio album by the late rapper Pop Smoke, which was released posthumously on July 3, 2020. The album was a critical and commercial success, debuting at number one on the Billboard 200 chart, and breaking several streaming records. The album featured collaborations with many high-profile artists, including Quavo, DaBaby, Lil Baby, Future, and 50 Cent (also executive-producer), among others. Shoot For The Stars Aim For The Moon showcased Pop Smoke\'s versatility as an artist, as he effortlessly switched between hard-hitting drill tracks and smoother melodic songs.',
    'SFTSAFTM (Deluxe)': 'The deluxe to Shoot For The Stars Aim For The Moon saw a release on July 20, 2020, just over two weeks after the album\'s release. The deluxe included 15 additional songs, including two remixes to songs released on the original album.',
    'Boogie': 'Boogie: The Original Motion Picture Soundtrack is the soundtrack to the 2021 film Boogie. Released by Republic Records on March 5, 2021, the soundtrack consisted of 14 tracks, mostly hip hop and pop tracks. It also featured three original songs written and performed by Pop Smoke, who also starred in the film in his first and only film appearance before his death in February 2020. His song "AP" was the lead single that preceded the soundtrack.',
    'Faith': 'Faith is the second posthumous studio album by the late rapper Pop Smoke, released on July 16, 2021. The album was highly anticipated, as fans were eager to hear more from the artist after the success of his debut posthumous album, Shoot For The Stars Aim For The Moon. Faith features guest appearances from a variety of artists, including Kanye West, Chris Brown, Dua Lipa, Pusha T, and Pharrell Williams, among others. However, the album faced heavy criticism and backlash over the commercialization of Pop Smoke\'s posthumous music and the manner in which it was handled.',
    'Ongoing': 'After the release of Faith, it is unknown what plans his label has in terms of his music, however it is unlikely that another album or project will release in his name. Numerous tracks have had the possibility and have been teased to release, whether as singles or features. Pop Smoke\'s former manager Rico Beats hinted in an interview that Pop\'s family is in charge of his music, and are potentially working on things moving forward.',
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  ALBUM_ORDER: [
    'GQ',
    'Meet The Woo 1',
    'Meet The Woo 2',
    'PS3',
    'Collaboration with French Montana',
    'Huncho Woo',
    'SFTSAFTM',
    'SFTSAFTM (Deluxe)',
    'Boogie',
    'Faith',
    'Ongoing',
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},

  hasArtTab: true,
  hasVideosTab: false,
  hasSubAlbumsTab: false,
};
