import type { ArtistConfig } from './types';

export const twizzygoldConfig: ArtistConfig = {
  slug: 'twizzygold',
  SITE_NAME: 'TWIZZYgold',
  SITE_DESCRIPTION: 'The Best YEAT Tracker In The World!',
  SITE_URL: 'https://vaultgold.net/twizzygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'twizzygold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1FUzAZyTCgFTVxQ--qbCAS2bUk4dsAw6ASxwjURPHbyI/export?format=csv&gid=1823522157',
  accentColor: '#a8e63d',
  artistLabel: 'YEAT',
  cardLetter: 'YT',
  logoUrl: '/logos/twizzygold.png',

  getArtistName(_eraName) { return 'YEAT'; },

  CUSTOM_IMAGES: {
    "Lyfëstyle [V1]": "https://i.ibb.co/dwf1KRDy/IMG-4302.jpg",
    "Different Creature": "https://i.ibb.co/tTn9BsGb/IMG-4286.jpg",
    "I'm So Me": "https://i.ibb.co/5hnKXXGj/IMG-4287.png",
    "Wake Up Call": "https://i.ibb.co/svksyfyS/10136.jpg",
    "Up 2 Më [V1]": "https://i.ibb.co/4nZ4zxH3/IMG-4293.png",
    "Up 2 Më [V3]": "https://i.ibb.co/chfqnj78/IMG-4295.jpg",
    "Alivë": "https://i.ibb.co/C5LY8MJ6/IMG-4291.jpg",
    "Hold Ön": "https://i.ibb.co/qY3JFb5K/IMG-4290.jpg",
    "2093": "https://i.ibb.co/6JN3hgX0/IMG-4304.jpg",
    "A DANGEROUS LYFE [V1]": "https://i.ibb.co/gMyTcrCz/IMG-4307.png",
    "ADL [V2]": "https://i.ibb.co/pjh4214p/IMG-4308.jpg",
    "ADL [V3]": "https://i.ibb.co/4w2qT0ZR/IMG-4310.jpg",
    "ADL": "",
    "ADL (Deluxe)": "",
    "AftërLyfe": "https://i.ibb.co/x8Gpb6tp/IMG-4300.jpg",
    "AftërLyfe (Deluxe)": "https://i.ibb.co/RTRpg56X/IMG-4301.jpg",
    "2 Alivë": "https://i.ibb.co/Mxv2Ygcz/IMG-4296.jpg",
    "2 Alivë (Geëk Pack)": "https://i.ibb.co/8LMB89mq/IMG-4298.jpg",
    "DANGEROUS SUMMER": "https://i.ibb.co/Ld23CYNw/IMG-4309.png",
    "Deep Blue $trips": "https://i.ibb.co/TM5wmpFS/IMG-4283.jpg",
    "LYFESTYLE [V2]": "https://i.ibb.co/7xQ0THSH/IMG-4305.jpg",
    "LYFESTYLE": "https://i.ibb.co/nMLBSDmN/IMG-4306.jpg",
    "LYFESTYLE DIGITAL DELUXE": "https://i.ibb.co/nMLBSDmN/IMG-4306.jpg",
    "Lyfë": "https://i.ibb.co/0psgwBxz/IMG-4299.jpg",
    "Trëndi": "https://i.ibb.co/Lh8607MY/IMG-4294.jpg",
    "4L": "https://i.ibb.co/1YzbvR0P/IMG-4292.jpg",
    "4L with us": "https://i.ibb.co/1YzbvR0P/IMG-4292.jpg",
    "1500": "https://i.ibb.co/0jcJs7GP/IMG-4280.jpg",
    "Collaboration with SwagHollywood": "https://i.ibb.co/pvnJL3QB/IMG-4281.jpg",
    "Up 2 Më": "https://i.ibb.co/4nZ4zxH3/IMG-4293.png",
    "We Us": "https://i.ibb.co/VFSL8zy/IMG-4288.jpg",
    "DC2": "https://i.ibb.co/yms50zkH/IMG-4289.jpg",
    "Elegance": "https://i.ibb.co/PG0H1RSR/IMG-4285.jpg",
    "Super Sonic": "https://i.ibb.co/JwZm3cK5/IMG-4282.jpg",
    "Super geëky": "https://i.ibb.co/Xr2zn5xW/IMG-4297.jpg",
    "Ongoing": "https://i.ibb.co/CKtWDp3W/IMG-4311.png",
  },

  ALBUM_RELEASE_DATES: {
    "Deep Blue $trips": "??/??/2018",
    "Wake Up Call": "??/??/2019",
    "Elegance": "??/??/????",
    "Different Creature": "??/??/2021",
    "I'm So Me": "??/??/2021",
    "We Us": "??/??/2020",
    "DC2": "??/??/????",
    "Hold Ön": "??/??/2020",
    "Alivë": "03/25/2022",
    "4L": "??/??/2021",
    "Up 2 Më [V1]": "??/??/2021",
    "Trëndi": "??/??/2021",
    "Up 2 Më [V3]": "??/??/2022",
    "Up 2 Më": "??/??/2021",
    "2 Alivë": "04/19/2024",
    "2 Alivë (Geëk Pack)": "??/??/2024",
    "Lyfë": "??/??/????",
    "AftërLyfe": "09/29/2023",
    "AftërLyfe (Deluxe)": "??/??/2023",
    "Lyfëstyle [V1]": "??/??/????",
    "2093": "08/26/2022",
    "LYFESTYLE [V2]": "??/??/????",
    "LYFESTYLE": "??/??/2025",
    "LYFESTYLE DIGITAL DELUXE": "??/??/2025",
    "A DANGEROUS LYFE [V1]": "??/??/2022",
    "ADL [V2]": "??/??/2022",
    "DANGEROUS SUMMER": "??/??/2024",
    "ADL [V3]": "??/??/2022",
    "ADL": "03/17/2023",
    "ADL (Deluxe)": "??/??/2023",
    "Ongoing": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},
  hasCompsTab: false,
  hasConcertsTab: false,

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By TWIZZYgold', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By TWIZZYgold': 'Leaks & Songs added by the owner of the site.',
  },
};
