import type { ArtistConfig } from './types';

export const twizzygoldConfig: ArtistConfig = {
  slug: 'twizzygold',
  SITE_NAME: 'TWIZZYgold',
  SITE_DESCRIPTION: 'The Best YEAT Tracker In The World!',
  SITE_URL: 'https://vaultgold.net/twizzygold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'twizzygold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#00ff88',
  artistLabel: 'YEAT',
  cardLetter: 'YT',
  logoUrl: '',

  getArtistName(_eraName) { return 'YEAT'; },

  CUSTOM_IMAGES: {
    "Lyfëstyle [V1]": "",
    "Different Creature": "",
    "I'm So Me": "",
    "Wake Up Call": "",
    "Up 2 Më [V1]": "",
    "Up 2 Më [V3]": "",
    "Alivë": "",
    "Hold Ön": "",
    "2093": "",
    "A DANGEROUS LYFE [V1]": "",
    "ADL [V2]": "",
    "ADL [V3]": "",
    "ADL": "",
    "ADL (Deluxe)": "",
    "AftërLyfe": "",
    "AftërLyfe (Deluxe)": "",
    "2 Alivë": "",
    "2 Alivë (Geëk Pack)": "",
    "DANGEROUS SUMMER": "",
    "Deep Blue $trips": "",
    "LYFESTYLE [V2]": "",
    "LYFESTYLE": "",
    "LYFESTYLE DIGITAL DELUXE": "",
    "Lyfë": "",
    "Trëndi": "",
    "4L": "",
    "Up 2 Më": "",
    "We Us": "",
    "DC2": "",
    "Elegance": "",
    "Super Sonic": "",
    "Super geëky": "",
    "Ongoing": "",
  },

  ALBUM_RELEASE_DATES: {
    "Lyfëstyle [V1]": "??/??/2020",
    "Different Creature": "??/??/2021",
    "I'm So Me": "??/??/2021",
    "Wake Up Call": "??/??/2021",
    "Up 2 Më [V1]": "??/??/2021",
    "Up 2 Më [V3]": "??/??/2022",
    "Alivë": "03/25/2022",
    "Hold Ön": "??/??/2022",
    "2093": "08/26/2022",
    "A DANGEROUS LYFE [V1]": "??/??/2022",
    "ADL [V2]": "??/??/2022",
    "ADL [V3]": "??/??/2022",
    "ADL": "03/17/2023",
    "ADL (Deluxe)": "??/??/2023",
    "AftërLyfe": "09/29/2023",
    "AftërLyfe (Deluxe)": "??/??/2023",
    "2 Alivë": "04/19/2024",
    "2 Alivë (Geëk Pack)": "??/??/2024",
    "DANGEROUS SUMMER": "??/??/2024",
    "Deep Blue $trips": "??/??/2024",
    "LYFESTYLE [V2]": "??/??/????",
    "LYFESTYLE": "??/??/2025",
    "LYFESTYLE DIGITAL DELUXE": "??/??/2025",
    "Lyfë": "??/??/????",
    "Trëndi": "??/??/????",
    "4L": "??/??/????",
    "Up 2 Më": "??/??/????",
    "We Us": "??/??/????",
    "DC2": "??/??/????",
    "Elegance": "??/??/????",
    "Ongoing": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By TWIZZYgold', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By TWIZZYgold': 'Leaks & Songs added by the owner of the site.',
  },
};
