import type { ArtistConfig } from './types';

// Ty Dolla $ign tracker. Data served from committed CSV snapshots under
// public/tydollagold/data/*.csv, transformed from the source Google-Sheet exports by
// scripts/build-bigupdate-csvs.py. An era only appears in the Music grid if its
// name is a key in ALBUM_RELEASE_DATES.
export const tydollagoldConfig: ArtistConfig = {
  slug: 'tydollagold',
  SITE_NAME: 'TYDOLLAGOLD',
  SITE_DESCRIPTION: 'The Best Ty Dolla $ign Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/tydollagold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'tydollagold_',

  sheetUrl: 'https://docs.google.com/spreadsheets/d/11Kk3Mi8iiFmXEFV8vzcmTrnjcMkfgImABCavXhC4D48/edit?gid=2000110692#2000110692',

  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',

  accentColor: '#9333ea',
  artistLabel: 'Ty Dolla $ign',
  cardLetter: 'T',
  logoUrl: '',
  artistPhotoUrl: '/artists/tydollagold.jpg',

  getArtistName() {
    return 'Ty Dolla $ign';
  },

  CUSTOM_IMAGES: {
    'Beach House':                    '/tydollagold/eras/beach-house.jpg',
    'Beach House 2':                  '/tydollagold/eras/beach-house-2.jpg',
    'Beach House EP':                 '/tydollagold/eras/beach-house-ep.jpg',
    '$ign Language':                  '/tydollagold/eras/ign-language.jpg',
    'Talk About it in the Morning':   '/tydollagold/eras/talk-about-it-in-the-morning.jpg',
    'Free TC':                        '/tydollagold/eras/free-tc.jpg',
    'Campaign [V1]':                  '/tydollagold/eras/campaign-v1.jpg',
    'Campaign [V2]':                  '/tydollagold/eras/campaign-v2.jpg',
    'Beach House 3':                  '/tydollagold/eras/beach-house-3.jpg',
    '$24:00 [V1]':                    '/tydollagold/eras/2400-v1.jpg',
    'MIH-TY':                         '/tydollagold/eras/mih-ty.jpg',
    'Dream House':                    '/tydollagold/eras/dream-house.jpg',
    'Kanye West - Yandhi':            '/tydollagold/eras/kanye-west-yandhi.jpg',
    'Collaboration with Skrillex':    '/tydollagold/eras/collaboration-with-skrillex.png',
    'Featuring Ty Dolla $ign':        '/tydollagold/eras/featuring-ty-dolla-ign.jpg',
    'Cheers to the Best Memories':    '/tydollagold/eras/cheers-to-the-best-memories.jpg',
    'Beach House 4 [V1]':             '/tydollagold/eras/beach-house-4-v1.jpg',
    '$24:00 [V2]':                    '/tydollagold/eras/2400-v2.jpg',
    'Collaboration with Mustard':     '/tydollagold/eras/collaboration-with-mustard.jpg',
    '$ign Language 2':                '/tydollagold/eras/ign-language-2.png',
    'Dance EP':                       '/tydollagold/eras/dance-ep.jpg',
    'Beach House 4 [V2]':             '/tydollagold/eras/beach-house-4-v2.jpg',
    'Airplane Mode 2 [V1]':           '/tydollagold/eras/airplane-mode-2-v1.jpg',
    '¥$':                             '/tydollagold/eras/ys.jpg',
    'VULTURES 1':                     '/tydollagold/eras/vultures-1.png',
    'VULTURES 2':                     '/tydollagold/eras/vultures-2.png',
    'VULTURES 3':                     '/tydollagold/eras/vultures-3.jpg',
    'TYCOON [V1]':                    '/tydollagold/eras/tycoon-v1.png',
    'TYCOON [V2]':                    '/tydollagold/eras/tycoon-v2.png',
    'AIRPLANE MODE 2 [V2]':           '/tydollagold/eras/airplane-mode-2-v2.jpg',
    'SUCIO SOUND SYSTEM':             '/tydollagold/eras/sucio-sound-system.jpg',
    'girl music vol. 1':              '/tydollagold/eras/girl-music-vol-1.jpg',
    'girl music vol 2: sex playlist': '/tydollagold/eras/girl-music-vol-2-sex-playlist.jpg',
    'Ongoing':                        '/tydollagold/eras/ongoing.png',
  },

  ALBUM_RELEASE_DATES: {
    'Beach House': '??/??/????',
    'Beach House 2': '??/??/????',
    'Beach House EP': '??/??/????',
    '$ign Language': '??/??/????',
    'Talk About it in the Morning': '??/??/????',
    'Free TC': '??/??/????',
    'Campaign [V1]': '??/??/????',
    'Campaign [V2]': '??/??/????',
    'Beach House 3': '??/??/????',
    '$24:00 [V1]': '??/??/????',
    'MIH-TY': '??/??/????',
    'Dream House': '??/??/????',
    'Kanye West - Yandhi': '??/??/????',
    'Yandhi': '??/??/????',
    'Collaboration with Skrillex': '??/??/????',
    'Skrillex Collaboration': '??/??/????',
    'Featuring Ty Dolla $ign': '??/??/????',
    'Cheers to the Best Memories': '??/??/????',
    'Beach House 4 [V1]': '??/??/????',
    '$24:00 [V2]': '??/??/????',
    'Collaboration with Mustard': '??/??/????',
    'Mustard Collaboration': '??/??/????',
    '$ign Language 2': '??/??/????',
    'Dance EP': '??/??/????',
    'Beach House 4 [V2]': '??/??/????',
    'Airplane Mode 2 [V1]': '??/??/????',
    '¥$': '??/??/????',
    'VULTURES 1': '??/??/????',
    'VULTURES 2': '??/??/????',
    'VULTURES 3': '??/??/????',
    'TYCOON [V1]': '??/??/????',
    'TYCOON [V2]': '??/??/????',
    'AIRPLANE MODE 2 [V2]': '??/??/????',
    'SUCIO SOUND SYSTEM': '??/??/????',
    'girl music vol. 1': '??/??/????',
    'girl music vol 2: sex playlist': '??/??/????',
    'girl music vol. 2: sex playlist': '??/??/????',
    'PURPLE MOON': '??/??/????',
    'Ongoing': '??/??/????'
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {},
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {},

  ALBUM_ORDER: [
    'Beach House',
    'Beach House 2',
    'Beach House EP',
    '$ign Language',
    'Talk About it in the Morning',
    'Free TC',
    'Campaign [V1]',
    'Campaign [V2]',
    'Beach House 3',
    '$24:00 [V1]',
    'MIH-TY',
    'Dream House',
    'Kanye West - Yandhi',
    'Yandhi',
    'Collaboration with Skrillex',
    'Skrillex Collaboration',
    'Featuring Ty Dolla $ign',
    'Cheers to the Best Memories',
    'Beach House 4 [V1]',
    '$24:00 [V2]',
    'Collaboration with Mustard',
    'Mustard Collaboration',
    '$ign Language 2',
    'Dance EP',
    'Beach House 4 [V2]',
    'Airplane Mode 2 [V1]',
    '¥$',
    'VULTURES 1',
    'VULTURES 2',
    'VULTURES 3',
    'TYCOON [V1]',
    'TYCOON [V2]',
    'AIRPLANE MODE 2 [V2]',
    'SUCIO SOUND SYSTEM',
    'girl music vol. 1',
    'girl music vol 2: sex playlist',
    'girl music vol. 2: sex playlist',
    'PURPLE MOON',
    'Ongoing'
  ],

  TAG_MAP: {},
  TAG_TOOLTIP_MAP: {},
  ERA_THEMES: {},
  hasSubAlbumsTab: false, // no sub-albums data for this tracker
  hasGroupbuysTab: true,
};
