import type { ArtistConfig } from './types';

export const uzigoldConfig: ArtistConfig = {
  slug: 'uzigold',
  SITE_NAME: 'UZIGOLD',
  SITE_DESCRIPTION: 'The Best Lil Uzi Vert Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/uzigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'uzigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1zqqdIds1iwnx4lh29iF1IlraeuqfGhxH9qLNlWOnryo/export?format=csv&gid=1339726772',
  accentColor: '#e8621a',
  artistLabel: 'Lil Uzi Vert',
  cardLetter: 'UZI',
  logoUrl: '/logos/uzigold.png',
  artistPhotoUrl: '/artists/uzi.webp',

  getArtistName(_eraName) { return 'Lil Uzi Vert'; },

  CUSTOM_IMAGES: {
    "Purple Thoughtz": "https://i.ibb.co/TMDzLKvd/IMG-4410.jpg",
    "Home Economic$": "https://i.ibb.co/8DbFtHtN/IMG-4411.jpg",
    "The Real Uzi": "https://i.ibb.co/cXwyJK3h/IMG-4412.jpg",
    "Luv Is Rage": "https://i.ibb.co/RGJtRdhC/IMG-4413.jpg",
    "Lil Uzi Vert vs. The World": "https://i.ibb.co/bYRG9P8/IMG-4414.jpg",
    "The Perfect LUV Tape": "https://i.ibb.co/mrj7hvDm/IMG-4415.jpg",
    "Luv Is Rage 2 [V1]": "https://i.ibb.co/xtw9QR1H/IMG-4416.jpg",
    "1017 vs. The World": "https://i.ibb.co/cXxqHt9m/IMG-4417.png",
    "Luv Is Rage 1.5": "https://i.ibb.co/Ps4DkzZ1/unknown.png",
    "2 Luv Is 2 Rage": "https://i.ibb.co/m5zykGDp/what-do-you-guys-think-of-2-luv-2-rage-soundcloud-exclusive-v0-jbroz1xhs48d1.jpg",
    "Luv Is Rage 2 [V2]": "https://i.ibb.co/ynwCST9Q/IMG-4418.png",
    "Too Fast": "https://i.ibb.co/Q4HSX8P/unknown.png",
    "Lil Uzi Vert vs. The World 2 [V1]": "https://i.ibb.co/gs1qVNq/IMG-4420.jpg",
    "16*29": "https://i.ibb.co/JFcRmg67/IMG-4421.jpg",
    "Tsunami Island": "https://i.ibb.co/hJgzfBR2/IMG-4422.jpg",
    "Eternal Atake [V1]": "https://i.ibb.co/kVPjGLYC/IMG-4423.jpg",
    "Eternal Atake [V2]": "https://i.ibb.co/Kp7sczsn/IMG-4424.png",
    "Eternal Atake [V3]": "https://i.ibb.co/V0GGPybx/IMG-4425.jpg",
    "Baby Pluto Era": "https://i.ibb.co/gL9XJ0pZ/IMG-4426.jpg",
    "Pluto x Baby Pluto": "https://i.ibb.co/j931WNnZ/IMG-4427.jpg",
    "Forever Young": "https://i.ibb.co/Jj7XpPKz/IMG-4428.png",
    "Pink Tape [V1]": "https://i.ibb.co/5hDDJZJh/IMG-4429.jpg",
    "Super gëëky": "https://i.ibb.co/tMdBKdtL/IMG-4430.jpg",
    "Pink Tape [V2]": "https://i.ibb.co/0jftPcpj/IMG-4431.jpg",
    "RED & WHITE": "https://i.ibb.co/67dstLP9/unknown.png",
    "METROOOO PINK": "https://i.ibb.co/mVbDzcRk/IMG-4453.png",
    "Pink Tape [V3]": "https://i.ibb.co/35NWKTXB/IMG-4432.png",
    "DPONTHEBEAT Vol 5": "https://i.ibb.co/DHWnt0fc/unknown.png",
    "Barter 16": "https://i.ibb.co/dwLFKySb/IMG-4433.jpg",
    "Luv Is Rage 3 [V2]": "https://i.ibb.co/Q7PpWsWj/IMG-4434.jpg",
    "Eternal Atake 2": "https://i.ibb.co/6J8RrQJq/IMG-4435.png",
    "ALL WHITE": "https://i.ibb.co/8DBMRfcH/IMG-4436.png",
    "W.H.2.U": "https://i.ibb.co/qLvbhgVF/IMG-4437.jpg",
    "LP 5": "https://i.ibb.co/KpzY7SwP/IMG-4438.jpg",
  },

  ALBUM_RELEASE_DATES: {
    "Purple Thoughtz": "??/??/2014",
    "Home Economic$": "??/??/2014",
    "The Real Uzi": "??/??/2014",
    "Luv Is Rage": "10/31/2015",
    "Lil Uzi Vert vs. The World": "07/22/2016",
    "The Perfect LUV Tape": "??/??/2017",
    "Luv Is Rage 2 [V1]": "??/??/2017",
    "1017 vs. The World": "??/??/2015",
    "Luv Is Rage 1.5": "??/??/2016",
    "2 Luv Is 2 Rage": "??/??/2016",
    "Luv Is Rage 2 [V2]": "08/25/2017",
    "Too Fast": "??/??/????",
    "Lil Uzi Vert vs. The World 2 [V1]": "??/??/2017",
    "16*29": "??/??/2017",
    "Tsunami Island": "??/??/????",
    "Eternal Atake [V1]": "??/??/2018",
    "Eternal Atake [V2]": "??/??/2019",
    "Eternal Atake [V3]": "03/06/2020",
    "Baby Pluto Era": "??/??/2020",
    "Pluto x Baby Pluto": "11/13/2020",
    "Forever Young": "??/??/2024",
    "Pink Tape [V1]": "??/??/2022",
    "Super gëëky": "??/??/????",
    "Pink Tape [V2]": "??/??/2023",
    "RED & WHITE": "??/??/2024",
    "METROOOO PINK": "??/??/2024",
    "Pink Tape [V3]": "06/30/2023",
    "DPONTHEBEAT Vol 5": "??/??/????",
    "Barter 16": "??/??/2016",
    "Luv Is Rage 3 [V2]": "??/??/2021",
    "Eternal Atake 2": "??/??/2022",
    "ALL WHITE": "??/??/2024",
    "W.H.2.U": "??/??/????",
    "LP 5": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    "Purple Thoughtz": "One of Lil Uzi Vert's earliest mixtapes, self-released in 2014 before he had a wide audience.",
    "Home Economic$": "Early 2014 mixtape from Lil Uzi Vert's pre-fame come-up.",
    "The Real Uzi": "Early 2014 project from Lil Uzi Vert's formative years, before his mainstream breakthrough.",
    "Luv Is Rage": "Luv Is Rage is Lil Uzi Vert's official debut mixtape, released October 31, 2015.",
    "Lil Uzi Vert vs. The World": "Lil Uzi Vert vs. The World is Lil Uzi Vert's second mixtape, released July 22, 2016, and the project that broke him into the mainstream.",
    "The Perfect LUV Tape": "The Perfect LuvTape is a mixtape released by Lil Uzi Vert in late 2016, following up on Lil Uzi Vert vs. The World.",
    "Luv Is Rage 2 [V1]": "Earlier version of the Luv Is Rage 2 sessions, before the album was reworked and finalized.",
    "1017 vs. The World": "A 2015 collaborative mixtape between Lil Uzi Vert and Gucci Mane's 1017 Brick Squad, from early in his career.",
    "Luv Is Rage 1.5": "A short 2016 release of four songs, including an early version of 'XO Tour Llif3', put out after Uzi lost his phone.",
    "2 Luv Is 2 Rage": "Scrapped set of songs recorded between 2015 and 2017 that never came together as a project, with several tracks later surfacing individually or on Luv Is Rage 2.",
    "Luv Is Rage 2 [V2]": "Luv Is Rage 2 is Lil Uzi Vert's debut studio album, released August 25, 2017, and includes the hit single 'XO Tour Llif3'.",
    "Too Fast": "Scrapped collaborative album between Lil Uzi Vert and NBA YoungBoy, reportedly recorded in a single day before being shelved.",
    "Lil Uzi Vert vs. The World 2 [V1]": "Early planned sequel to Lil Uzi Vert vs. The World, worked on in 2017 before being reworked into other projects.",
    "16*29": "Scrapped 2017 project from Lil Uzi Vert, worked on around the same time as Luv Is Rage 2 and The Perfect LuvTape.",
    "Tsunami Island": "Scrapped early recording sessions from Lil Uzi Vert, with most of the songs left untitled.",
    "Eternal Atake [V1]": "Earliest version of the Eternal Atake sessions, dating back to 2018, before the album went through multiple reworks.",
    "Eternal Atake [V2]": "Second version of the Eternal Atake sessions, worked on in 2019 as the album continued to evolve.",
    "Eternal Atake [V3]": "Eternal Atake is Lil Uzi Vert's second studio album, released March 6, 2020, built around his 'Baby Pluto' alter ego.",
    "Baby Pluto Era": "Recording sessions from 2020 tied to Lil Uzi Vert's 'Baby Pluto' persona, running alongside and after Eternal Atake.",
    "Pluto x Baby Pluto": "Pluto x Baby Pluto is a deluxe reissue of Eternal Atake, released November 13, 2020, with additional new tracks.",
    "Forever Young": "Scrapped Lil Uzi Vert project worked on around 2024.",
    "Pink Tape [V1]": "Early version of the sessions from 2022 that would eventually become Pink Tape.",
    "Super gëëky": "Collaborative sessions between Lil Uzi Vert and Yeat, with material later feeding into Pink Tape and other releases.",
    "Pink Tape [V2]": "Second version of the Pink Tape sessions, worked on in 2023 as the album continued to be reworked.",
    "RED & WHITE": "RED & WHITE is a 2024 Lil Uzi Vert release compiling previously SoundCloud-only songs for streaming.",
    "METROOOO PINK": "Scrapped joint tape sessions between Lil Uzi Vert and Metro Boomin, recorded in 2023.",
    "Pink Tape [V3]": "Pink Tape is Lil Uzi Vert's third studio album, released June 30, 2023.",
    "DPONTHEBEAT Vol 5": "A run of songs produced by DP Beats, released directly by the producer the same day each one leaked.",
    "Barter 16": "Scrapped Lil Uzi Vert project tied to the 'B16' era slang he used following Pink Tape.",
    "Luv Is Rage 3 [V2]": "Sessions for a planned third Luv Is Rage album, worked on around 2021.",
    "Eternal Atake 2": "Sessions for a planned sequel to Eternal Atake, worked on starting in 2022.",
    "ALL WHITE": "Scrapped Lil Uzi Vert project from 2024, with songs sometimes mistakenly attributed to other era sessions.",
    "W.H.2.U": "Unreleased mixtape teased heavily by Lil Uzi Vert and his affiliates, with a final title never confirmed.",
    "LP 5": "Placeholder name for Lil Uzi Vert's next studio album, currently in progress.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    '1017 Vs. The World': '1017 vs. The World',
    'LUV Is Rage 3 [V2]': 'Luv Is Rage 3 [V2]',
    'Super geeky': 'Super gëëky',
    'Super geëky': 'Super gëëky',
  },

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By UZIGOLD', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By UZIGOLD': 'Leaks & Songs added by the owner of the site.',
  },
};
