import type { ArtistConfig } from './types';

export const uzigoldConfig: ArtistConfig = {
  slug: 'uzigold',
  hasGroupbuysTab: true,
  SITE_NAME: 'UZIGOLD',
  SITE_DESCRIPTION: 'The Best Lil Uzi Vert Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/uzigold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'uzigold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/1zqqdIds1iwnx4lh29iF1IlraeuqfGhxH9qLNlWOnryo/export?format=csv&gid=1339726772',
  accentColor: '#e8621a',
  artistLabel: 'Lil Uzi Vert',
  cardLetter: 'UZI',
  logoUrl: '/logos/uzigold.png',
  artistPhotoUrl: '/artists/uzi.webp',

  getArtistName(_eraName) { return 'Lil Uzi Vert'; },

  CUSTOM_IMAGES: {
    "Purple Thoughtz": "https://i.ibb.co/TMDzLKvd/IMG-4410.jpg",
    "Home Economic$": "https://i.ibb.co/8DbFtHtN/IMG-4411.jpg",
    "The Real Uzi": "https://i.ibb.co/cXwyJK3h/IMG-4412.jpg",
    "Luv Is Rage": "https://i.ibb.co/RGJtRdhC/IMG-4413.jpg",
    "Lil Uzi Vert vs. The World": "https://i.ibb.co/bYRG9P8/IMG-4414.jpg",
    "The Perfect LUV Tape": "https://i.ibb.co/mrj7hvDm/IMG-4415.jpg",
    "Luv Is Rage 2 [V1]": "https://i.ibb.co/xtw9QR1H/IMG-4416.jpg",
    "1017 vs. The World": "https://i.ibb.co/cXxqHt9m/IMG-4417.png",
    "Luv Is Rage 1.5": "https://i.ibb.co/Ps4DkzZ1/unknown.png",
    "2 Luv Is 2 Rage": "https://i.ibb.co/m5zykGDp/what-do-you-guys-think-of-2-luv-2-rage-soundcloud-exclusive-v0-jbroz1xhs48d1.jpg",
    "Luv Is Rage 2 [V2]": "https://i.ibb.co/ynwCST9Q/IMG-4418.png",
    "Too Fast": "https://i.ibb.co/Q4HSX8P/unknown.png",
    "Lil Uzi Vert vs. The World 2 [V1]": "https://i.ibb.co/gs1qVNq/IMG-4420.jpg",
    "16*29": "https://i.ibb.co/JFcRmg67/IMG-4421.jpg",
    "Tsunami Island": "https://i.ibb.co/hJgzfBR2/IMG-4422.jpg",
    "Eternal Atake [V1]": "https://i.ibb.co/kVPjGLYC/IMG-4423.jpg",
    "Eternal Atake [V2]": "https://i.ibb.co/Kp7sczsn/IMG-4424.png",
    "Eternal Atake [V3]": "https://i.ibb.co/V0GGPybx/IMG-4425.jpg",
    "Baby Pluto Era": "https://i.ibb.co/gL9XJ0pZ/IMG-4426.jpg",
    "Pluto x Baby Pluto": "https://i.ibb.co/j931WNnZ/IMG-4427.jpg",
    "Forever Young": "https://i.ibb.co/Jj7XpPKz/IMG-4428.png",
    "Pink Tape [V1]": "https://i.ibb.co/5hDDJZJh/IMG-4429.jpg",
    "Super gëëky": "https://i.ibb.co/tMdBKdtL/IMG-4430.jpg",
    "Pink Tape [V2]": "https://i.ibb.co/0jftPcpj/IMG-4431.jpg",
    "RED & WHITE": "https://i.ibb.co/67dstLP9/unknown.png",
    "METROOOO PINK": "https://i.ibb.co/mVbDzcRk/IMG-4453.png",
    "Pink Tape [V3]": "https://i.ibb.co/35NWKTXB/IMG-4432.png",
    "DPONTHEBEAT Vol 5": "https://i.ibb.co/DHWnt0fc/unknown.png",
    "Barter 16": "https://i.ibb.co/dwLFKySb/IMG-4433.jpg",
    "Luv Is Rage 3 [V2]": "https://i.ibb.co/Q7PpWsWj/IMG-4434.jpg",
    "Eternal Atake 2": "https://i.ibb.co/6J8RrQJq/IMG-4435.png",
    "ALL WHITE": "https://i.ibb.co/8DBMRfcH/IMG-4436.png",
    "W.H.2.U": "https://i.ibb.co/qLvbhgVF/IMG-4437.jpg",
    "LP 5": "https://i.ibb.co/KpzY7SwP/IMG-4438.jpg",
  },

  ALBUM_RELEASE_DATES: {
    "Purple Thoughtz": "??/??/2014",
    "Home Economic$": "??/??/2014",
    "The Real Uzi": "??/??/2014",
    "Luv Is Rage": "10/31/2015",
    "Lil Uzi Vert vs. The World": "07/22/2016",
    "The Perfect LUV Tape": "??/??/2017",
    "Luv Is Rage 2 [V1]": "??/??/2017",
    "1017 vs. The World": "??/??/2015",
    "Luv Is Rage 1.5": "??/??/2016",
    "2 Luv Is 2 Rage": "??/??/2016",
    "Luv Is Rage 2 [V2]": "08/25/2017",
    "Too Fast": "??/??/????",
    "Lil Uzi Vert vs. The World 2 [V1]": "??/??/2017",
    "16*29": "??/??/2017",
    "Tsunami Island": "??/??/????",
    "Eternal Atake [V1]": "??/??/2018",
    "Eternal Atake [V2]": "??/??/2019",
    "Eternal Atake [V3]": "03/06/2020",
    "Baby Pluto Era": "??/??/2020",
    "Pluto x Baby Pluto": "11/13/2020",
    "Forever Young": "??/??/2024",
    "Pink Tape [V1]": "??/??/2022",
    "Super gëëky": "??/??/????",
    "Pink Tape [V2]": "??/??/2023",
    "RED & WHITE": "??/??/2024",
    "METROOOO PINK": "??/??/2024",
    "Pink Tape [V3]": "06/30/2023",
    "DPONTHEBEAT Vol 5": "??/??/????",
    "Barter 16": "??/??/2016",
    "Luv Is Rage 3 [V2]": "??/??/2021",
    "Eternal Atake 2": "??/??/2022",
    "ALL WHITE": "??/??/2024",
    "W.H.2.U": "??/??/????",
    "LP 5": "??/??/????",
  },

  HIDDEN_ALBUMS: [],
  ALBUM_DESCRIPTIONS: {
    "Purple Thoughtz": "Purple Thoughtz is the debut EP of Philedelphia rapper Lil Uzi Vert. The album was self-released onto Soundcloud on January 19, 2014. Coming out of their former rap group \"Steaktown\" and off one of their most popular songs titled Steaktown Anthem, Purple Thoughtz would serve as an introduction to Uzi's solo work as an artist prior to the release of their first mixtape.",
    "Home Economic$": "Scrapped mixtape with Reese LaFlare, some tracks would release before The Real Uzi but would continue to drop until 2016.",
    "The Real Uzi": "The debut mixtape by Lil Uzi Vert. The mixtape was released on August 5, 2014, and was hosted by Don Cannon. It shows a young, raw Lil Uzi, with an old favorite “Uzi.” This was released shortly after his Purple Thoughtz Vol. 1 EP, which was his first project.",
    "Luv Is Rage": "Luv Is Rage is Lil Uzi Vert’s second mixtape and his debut on Atlantic Records. It is also the first entry in the Luv Is Rage series. The mixtape boasts features from Young Thug and Wiz Khalifa while containing production from Don Cannon, Maaly Raw, DP Beats, FKi, Slade Da Monsta, Sonny Digital and many more.",
    "Lil Uzi Vert vs. The World": "A surprise mixtape from Lil Uzi Vert, released on April 15th 2016. Uzi had hinted at a mixtape on his Instagram, but it wasn’t clear that he was planning on releasing it so soon. Although there are no features, the project does not lack production as seen with Maaly Raw, Don Cannon, Metro Boomin and WondaGurl producing multiple tracks from this time.",
    "The Perfect LUV Tape": "The Perfect LUV Tape is Lil Uzi Vert’s second project of 2016, released on SoundCloud on July 31, 2016. Unlike Lil Uzi Vert Vs. The World, which had no features—Uzi is joined by hi-rollers Playboi Carti, Future and Offset of Migos, and prestigious producer Zaytoven to make his hits on The Perfect LUV Tape. The mixtape was released on Uzi’s 22nd birthday. The project also features strong production from Maaly Raw, Don Cannon and DP Beats.",
    "Luv Is Rage 2 [V1]": "The original version of Luv Is Rage 2, which was completed in 2016. Because of this, the project was ready to release in late 2016 or very early 2017, but ended up getting delayed. The change was because of Uzi travelling to Hawaii in January of 2017 where he started to play with a darker theme for the album. This likely made him realize how it could be better to rework the album, since this 2016 version was way too similar to The Perfect LUV Tape in terms of sound so he scrapped it in favor of developing the new gritty and dark version from 2017. The cover for this era is made by @mattmeiners_ (The creator of the official Luv Is Rage 2 Cover Art)",
    "1017 vs. The World": "A collaborative extended play by American rappers Lil Uzi Vert and Gucci Mane. It was released through Generation Now and GUWOP on November 23, 2016. The EP features production from Honorable C.N.O.T.E., D. Rich, Mannie Fresh, Zaytoven, DP Beats and GLOhan Beats. The project was planned to release fully on streaming, but didn't due to sample clearance issues and has stayed on Soundcloud since.",
    "Luv Is Rage 1.5": "A short 2016 release of four songs, including an early version of 'XO Tour Llif3', put out after Uzi lost his phone.",
    "2 Luv Is 2 Rage": "Scrapped set of songs recorded between 2015 and 2017 that never came together as a project, with several tracks later surfacing individually or on Luv Is Rage 2.",
    "Luv Is Rage 2 [V2]": "The debut studio album by the American rapper and singer Lil Uzi Vert, released on August 25, 2017, through Generation Now and Atlantic Records. The project contains heavy production from Don Cannon, Maaly Raw, Pi'erre Bourne and DP Beats. This album was highly anticipated since before Lil Uzi tweeted on December 13, 2016 regarding the release, but has been waited on since November of 2016. To much surprise, Uzi decided to leave out one of the songs that was most highly anticipated “Come This Way”, which was first previewed on his Instagram account, and performed in concerts, according to the producer, LyleLeDuff. LeDuff stated that he told him the fans wanted it but Uzi said he didn’t care. The release date was finally announced on August 25th, where Uzi tweeted out some leaks of snippets and his cover art/tracklist.",
    "Too Fast": "Not much is known about this project's details, and its fate. Only thing known is that both rappers worked on it (and 'finished' it too), on October 19, 2017. With some songs releasing as singles for YB's album. He even shared the album's cover art via his IG.",
    "Lil Uzi Vert vs. The World 2 [V1]": "Early planned sequel to Lil Uzi Vert vs. The World, worked on in 2017 before being reworked into other projects.",
    "16*29": "In September of 2017, Playboi Carti announced via Snapchat and Twitter that he would be collaborating with Lil Uzi Vert on a joint album titled 1629*. The following month, a tour for the album was announced by the two, but it was shortly canceled afterward when Uzi said he would not be going on tour with Carti because he \"needed to focus.\" The album would fall by the wayside until July of 2018, when Carti mentioned that he and Uzi had recorded \"like 100 songs.\" After that, all talk of the album pretty much subsided. It should be noted that many insiders have claimed that there was never a tracklist, cover art, or marketing plan put together. The cover for this era is fanmade.",
    "Tsunami Island": "On January 4th, 2018, Lil Uzi Vert would announce that a collaboration tape with Wheezy was 12 hours away from completion. Was said to have been made in one session on January 2nd. Originally 9 tracks long with 8 known and 1 unknown song . Uzi and Wheezy had the initial Tsunami Island session on Jan 2nd, then immediately went over to record with Carti in the same studio for the initial 16*29 sessions on Jan 3 and 4th (when he announced Tsunami Island). The cover for this era is fanmade.",
    "Eternal Atake [V1]": "On July 16, 2018, Uzi would announce his next album on his IG titled \"Eternal Atake\" - which means \"Forever Overtake\". The record was already conceptualized at the start of the year and Kesha Lee teased the concept back in February. He introduced a new theme for this project, which is visually (cover art) and thematically (songs) influenced by the logo of the Heaven’s Gate cult that infamously committed a mass suicide in 1997. Obviously, he received backlash and was threatened to be sued over the artwork for this creative decision. This era is a direct continuation from all work and ideas done during LUVvsTW 2 [V1]. Uzi hopped on more spacey and catchy beats during this era from producers such as Harper, Bugz Ronin, Forza, Oogie Mane, and others.",
    "Eternal Atake [V2]": "After label conflicts with Generation Now, Uzi delayed the album and sparked fan backlash. After DJ Drama claimed there was problems, Uzi fired back with a cryptic comment hinting at their dispute and launched the “FREE UZI” idea. He soon aligned with Roc Nation, giving him a way to keep recording while dealing with legal issues involving DJ Drama, Don Cannon, and GN. This marked the start of EA’s rework, previewed by the song “Free Uzi,” which shifted toward a trap‑focused sound and it's unique high pitched vocals in order to avoid copyright from Generation Now. Uzi continued developing East Coast–influenced flows and drew inspiration from New York styles while spending time with A Boogie wit da Hoodie. This era features production from Supah Mario, Brandon Finessin, Bugz Ronin, Oogie Mane and more. Ongoing label problems escalated when producer Forza was fired for leaking songs.",
    "Eternal Atake [V3]": "The final rollout for the album. Considered to start off with the single release of “Futsal Shuffle 2020” on December 12, 2019, marking a return to the spacey, futuristic themes of V1 blended with his newer 2019 trap flows alongside new production from Clibbo and returning producers. Throughout early January 2020, he teased Eternal Atake with promotional images, tweets and revealing more information. Uzi would confirm on February 1, 2020 that the album would feature 16 tracks. Uzi unexpectedly dropped the full album on March 6 (a week earlier than expected). A fan theorized that it's eighteen tracks aligned with his three alter egos—a theory Uzi confirmed—he immediately began teasing a deluxe edition, which released on March 13, 2020, featuring long‑sought songs from the LIR2 and LUVvsTW 2 (V1) eras along with newly updated tracks.",
    "Baby Pluto Era": "After Eternal Atake, Uzi faced backlash over his flows and track choices, pushing him toward a new sound built around sparkly beats mostly crafted with longtime friend Brandon Finessin. This time is often seen as the start of a decline in quality as he prioritized output and experimentation alongside hiring Benjamin Thomas, whom many blamed for Uzi's vocals sounding poorly mixed in the following years as his lead engineer after Kesha Lee quit to pursue her own music career. In April, Uzi began working with Working On Dying and Brandon on high‑pitched “baby voice” tracks, a style Playboi Carti was also using while they collaborated closely, dropping back‑to‑back singles (@ MEH and Sasuke) and staging a fake beef as part of Carti’s rollout; both were criticized for the unintelligible flow, leading Carti to rework Whole Lotta Red and Uzi to keep searching for a new sound. Because of this, Uzi started working on Pluto x Baby Pluto. This era is essentially a gap of experimental songs with a new sound from Uzi without a general project in mind.",
    "Pluto x Baby Pluto": "A collaborative project between Future and Uzi, which title comes from both of their alter egos; with Uzi tributing Future by once again using his \"Baby Pluto\" persona, that was previously introduced in Eternal Atake. The project features production from some more producers such as DJ ESCO, D. Hill, London on da Track and more. After Uzi recorded solo songs with no paticular direction in early 2020, they would release two singles together, \"Over Your Head\" and \"Patek\", which coincidentally was on Uzi's birthday. They would later release the trailer for the album (which used the scrapped intro, \"Astronauts\"), revealing the release date and so on from there. The album was released unexpectedly to some, with somewhat of a positive reception. Uzi would tease the deluxe, which ended up dropping just a week later.",
    "Forever Young": "Uzi responded to an IG comment asking him to return to his 2016–17 style by saying he would start that night, marking the beginning for Forever Young The concept had accelerated as he dyed his hair purple again and hosted multiple Instagram livestreams from December 17–23, previewing tons of new songs and snippets alongside announcing three projects planned for 2021: a SoundCloud mixtape, Forever Young, and Luv Is Rage 3, with new producers again such as Ty Luminocity and Pro Logic helping make a return to his old sound. Around this time he went viral for implanting a $24 million pink diamond in his forehead and for publicly confirming his relationship with JT. Uzi later tweeted The Real Uzi 2, confirming he was also working on a sequel to his 2014 tape. He officially announced The Pink Tape july but hadn't stopped working on Forever Young, as it remained active until it was finally scrapped in March 2022. The SoundCloud tape survived, and eventually released as Red & White in 2022, while Luv Is Rage 3 stayed in the idea stage until revisited in 2023. The Real Uzi 2 was notably worked on in the second half of this era and into Pink Tape. The art for this era is was done by jleovisions on TikTok, who was commissioned by Uzi.",
    "Pink Tape [V1]": "Uzi announced Pink Tape in July 2021, he shifted toward a melodic, experimental, and rage‑rap sound with huge production from Brandon Finessin alongside others such as Bugz Ronin and ShaunGoBrazy. Uzi previewed new songs at Rolling Loud Miami and briefly teased Forever Young for the last time. Inspired partly by Playboi Carti and their brief reunion, he developed the project into Delta Pink, performing tracks like “Rage” and “5, 4, 3, 2, 1,” making major public appearances, and releasing “Demon High” as its lead single. During this period he dealt with legal issues from a an incident in July, adopted new looks, explored Jersey‑club influences, appeared on Adin Ross’ streams, and introduced the “Astro Kat” persona. But by late December he abandoned the Delta Pink concept, shifted toward a more aggressive sound, went quiet on social media, and entered a key phase of court‑mandated rehabilitation—ultimately scrapping the first phase of the project..",
    "Super gëëky": "On December 12th, 2019, Yeat tweeted \"Me n uzi gone have a collab tape\". Yeat posted with Uzi to his Instagram on March 17, 2022 with the caption: \"16TR #p!nklyfe…. ###ë## #reallygeekedoutmybodykid #geeky????\", hinting that a collaborative tape between the artists could be on the way. BNYX® would confirm on March 25, 2022 that the two were working together for a project. On April 15, 2022, Yeat teased the project in a since-deleted tweet and IG story post, hinting that a collaborative project with Uzi was on the way: \"Super geeky tha tape… loading #kollab\". Throughout 2021 and 2022, Uzi and Yeat worked together very often, with even Uzi saying that they and Yeat had \"100 songs\" together, some of which are released and some which are expected to be on a collaboration project teased various times. Although the title is not confirmed, 'Super geeky' is the fan name for the Uzi x Yeat sessions as it was a listed as a name the last time. Not much has been said since 2022 for the project, and it is likely scrapped. The cover for this era is not official",
    "Pink Tape [V2]": "After the disaster for 2021's version of the project, Uzi decided to rework the album's sound and direction again with more unique sounding tracks. This time, he was influenced by the Philadelphia rap style; a more street influenced rap. During this time Uzi decided to finally drop a SoundCloud tape, and released the RED & WHITE EP. The reception for this EP was pretty mixed; people weren't so excited by Uzi's street style, but did appreciate his more spacey-experimental flow alongside the release of classic snippets. This made him rework the album once again, playing with more aesthetics and ideas. After Uzi failed to properly release BELIEVE ME on the RED & WHITE EP, Uzi was put into a 'timeout' by his own label for not properly releasing music, derailing immediate plans for a proper release for the Pink Tape in 2022. The cover art for this era is FANMADE (we should just use the R&W cover....)",
    "RED & WHITE": "RED & WHITE is a 2024 Lil Uzi Vert release compiling previously SoundCloud-only songs for streaming.",
    "METROOOO PINK": "In January of 2023, Metro and Uzi got back together in the studio after a long period of working seperately. The first confirmation of this tape's existence was a DM exchange from Uzi to Metro, asking for him to \"send the tape\". It was stated by someone in Uzi hub (aka. Grube), that the project was titled \"METROOOO PINK\", and was intended to relase sometime early in 2023; with it being scheduled to come out before the Pink Tape did. Ultimately, the tape got scrapped due to both artists being compromised with their repsective albums; Metro himself started working the soundtrack for the SPIDER-MAN: ACROSS THE SPIDER-VERSE movie, as well as two joint albums with Future. While Uzi dedicated himself to continue his sessions for the Pink Tape. @vaultofuzi would end up playing eight songs off the Tape on December 13, 2024, making the project publically known. The cover for this era is not actually intended for this project; comes from the promotional art for the SPIDER-MAN movie.",
    "Pink Tape [V3]": "The final version of the album was built together starting in the beginning of 2023, after Uzi decided to become more experimental for the project. This version of the project sees more rage and hard hitting production from Akachi, Only1Shredder, Bugz Ronin and more such as the Snow Strippers for remixing. Uzi would tease several more songs through IG live & live performances in 2023. Despite Uzi entering rehab in 2022, Uzi would be seen smoking cigarettes frequently (highlighted during the final rollout), and he would still continue to do promos for Telegram/Instagram marijuana 'businesses', and he continued on with this into his rock-type style. Several 2023 iterations of the project were made as Uzi began to finalize the tracklist and album into the \"experimental\" album that would release.",
    "DPONTHEBEAT Vol 5": "A run of songs produced by DP Beats, released directly by the producer the same day each one leaked.",
    "Barter 16": "Scrapped Lil Uzi Vert project tied to the 'B16' era slang he used following Pink Tape.",
    "Luv Is Rage 3 [V2]": "Uzi announced Luv Is Rage 3 will be his final album before retirement. Not much is currently known about the project, aside from Uzi saying it's sound was closer to the first two Luv Is Rage projects. Uzi later said that he wasn't retiring, basically confirmomg the idea of LIR3 to be cancelled/scrapped for his next album alongside EA2 being announcemed. Funnily enough, thanks to Uzi's ex-assistant's testimony from a lawsuit, she confirmed that Uzi started to work on a new project in February of 2024. This can only mean that it was until then when this iteration of Luv Is Rage 3 got scrapped.",
    "Eternal Atake 2": "Uzi first announced Eternal Atake 2 in an interview with someone who was asking what music the fans would hear next. His response was 'Eternal Atake 2', leading fans to believe a new successor to the 2020 album is on the way. Cover posted by Uzi on his IG. Based on public speculation and past Uzi posts, fans believed that this album was forced by the label and Uzi didn't want to release it; however, other insiders have noted that Uzi thought this was going to be a \"masterpiece\". Upon the project's release, however, it quickly became apparent this was easily his worst project yet, with only a few songs even qualifying as half-decent.",
    "ALL WHITE": "After the commercial failure of EA2, and the amount of backlash it received from the fans, Uzi started a new trend of his, by wearing all white clothes. Unfortunately, the majority of the fans didn't like either of the trends from this era and only a handful of snippets Uzi dropped. With many still complaining about Trilla's bad mixing on songs from this time, and some even claiming the songs to be \"unoriginal\", this made Uzi comment that he was \"testing the waters\" after quickly releasing two songs exclusively on YouTube. Uzi would once again go silent until he returned to the public eye, where he would completely scrap the \"ALL WHITE\" idea, alongside teasing a new \"Summer Tape\", and wearing different styles.",
    "W.H.2.U": "When asked about when was Uzi's new project releaseing, Don Cannon stated in an IG post that \"It'll drop when it drops 😎\". The original question was actually: \"Can you confirm Uzi is dropping The Perfect LUV Tape 2 this summer like people said\", and it was made on May 2, 2025. It's unknown if this was an actual project in the works, a placeholder name, or Don Cannon evading the question. Uzi would later start teasing 'W.H.2.U', and the fans started theorizing about it's meaning; some even pointed out that this was actually teased on the promotional material from Eternal Atake 2. He made some IG stories, teasing this project as a \"Summer Tape\", and some people even speculated the possibility of \"Lil Uzi Vert vs. The World 3\" being also in the works. @purple4matter on X (an insider of the music industry) claimed that Uzi was set to drop this project on August. But after he started sharing many snippets (pressumably as part of the rollout), he allegedly got into a conflict with his label, which made him either scrap it or delay it indefinetly. He then shifted his focus into working on building his own record label (XVI Records). The cover used for this era is FANMADE.",
    "LP 5": "Once W.H.2.U got scrapped in August, Uzi then started working on building his record label, XVI Records. Searching for talents to sign, and probably working on a tape with all the members. On September 4, he actually told iShowSpeed on his stream that he \"wasn't droppin' shit\"; at the time, everybody thought that he was being corny, and that he fumbled another chance of getting hype once again. We now know that he was in fact not planning on releasing his album any time soon, because he was grinding on his label on the low. We do know that he's been working on his own music too, with producer ZeeGoinXrazy claiming that they've been working with nostalgic beats and sounds and Uzi's manager, MeanXVI, having started 'recruiting' many of his best producers, like Maaly Raw, Don Cannon, WondaGurl, etc. Alongside him working with many underground artists, we also know he's once again gotten close with Carti & OPIUM. So despite Uzi being totally offline for the past months, there's a chance that he's working on something big this time. Whether it be his own fifth studio album, an EP or tape, or a collaborative project with his new label.",
  },
  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    '1017 Vs. The World': '1017 vs. The World',
    'LUV Is Rage 3 [V2]': 'Luv Is Rage 3 [V2]',
    'Super geeky': 'Super gëëky',
    'Super geëky': 'Super gëëky',
  },

  TAG_MAP: {
    '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
    '✨': 'Special', '💛': 'By UZIGOLD', '🗑️': 'Worst Of', '🗑': 'Worst Of',
    '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
  },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs worth highlighting.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By UZIGOLD': 'Leaks & Songs added by the owner of the site.',
  },
};
