import type { ArtistConfig } from './types';

const defaultTagMap = {
  '⭐': 'Best Of', '🏆': 'Grails', '🥇': 'Wanted', '🏅': 'Wanted',
  '✨': 'Special', '💛': 'By VAMPgold', '🗑️': 'Worst Of', '🗑': 'Worst Of',
  '🚮': 'Unwanted', '🤖': 'AI', '⁉️': 'Lost Media', '⁉': 'Lost Media', '❓': 'Unknown',
};

const defaultTagTooltips = {
  'Best Of': 'some of the best leaks hosted on the tracker.',
  'Grails': 'the most wanted songs that have not yet leaked in full.',
  'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
  'Special': 'special songs worth highlighting.',
  'Worst Of': 'some of the worst leaks hosted on the tracker.',
  'Unwanted': "Songs that we don't want to leak in full.",
  'AI': 'Track contains AI vocals.',
  'Lost Media': "Is currently lost, or we don't have a link to the media.",
};

export const vampgoldConfig: ArtistConfig = {
  slug: 'vampgold',
  SITE_NAME: 'VAMPgold',
  SITE_DESCRIPTION: 'The Best Playboi Carti Tracker In The World!',
  SITE_URL: 'https://vaultgold.net/vampgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'vampgold_',
  HARDCODED_SHEET_ID: '1Irtfvymu26CShYowLMMfD-rM0o9CJqE6-BBSlYsAaF4',
  HARDCODED_SHEET_GID: '0',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: `https://docs.google.com/spreadsheets/d/1Irtfvymu26CShYowLMMfD-rM0o9CJqE6-BBSlYsAaF4/export?format=csv&gid=1962169030`,
  accentColor: '#8b0000',
  artistLabel: 'Playboi Carti',
  cardLetter: 'VMP',
  logoUrl: '/logos/vampgold.png',

  getArtistName(_eraName) { return 'Playboi Carti'; },

  CUSTOM_IMAGES: {
    "Aviation Class": "https://i.ibb.co/R8WT57M/IMG-0678.png",
    "Killing Me Softly": "https://i.ibb.co/8g2jJc1b/tumblr-lkbw3l-Lx-Ad1qfnd2oo1-540.jpg",
    "Kream": "https://i.ibb.co/G4JF7f7N/tumblr-m76a2c-Bm-D51qfnd2oo1-500.jpg",
    "Young Mi$fit": "https://i.ibb.co/kVFwht33/tumblr-mdcd9s2-I9-G1qfnd2oo1-500.jpg",
    "Sen$ation": "https://i.ibb.co/CK8KMmYp/a3383006450-16.jpg",
    "Awful Records": "https://i.ibb.co/VW5xv70J/artworks-000116608046-icqf3o-t1080x1080.jpg",
    "Chucky Era": "https://i.ibb.co/TMhhgR5n/artworks-000125767641-af7vmm-t1080x1080.jpg",
    "Ca$h Carti Season": "https://i.ibb.co/pT7t9hB/IMG-4079.png",
    "Playboi Carti": "https://i.ibb.co/qFMJNmfm/1200x1200-000000-80-0-0.jpg",
    "16*29": "https://i.ibb.co/3mqLxnN6/0x1900-000000-80-0-0-DIF-2.jpg",
    "16*29 [V1]": "https://i.ibb.co/3mqLxnN6/0x1900-000000-80-0-0-DIF-2.jpg",
    "Die Lit": "https://i.ibb.co/spcmgX6J/die-lit-playboi-carti-hi-res-cover-133548411.jpg",
    "Whole Lotta Red [V1]": "https://i.ibb.co/6RQMsWx9/WHOLE-LOT-OF-RED.jpg",
    "WE DON'T DIAL 911": "https://i.ibb.co/ksjjq3vj/IMG-0674.jpg",
    "Whole Lotta Red [V2]": "https://i.ibb.co/Qjb9bD1V/IMG-0675.jpg",
    "Whole Lotta Red [V3]": "https://i.ibb.co/0pLvdrrd/IMG-0676.png",
    "Whole Lotta Red (Deluxe)": "https://i.imgur.com/U2x2OPH.png",
    "Whole Lotta Red [V4]": "https://i.ibb.co/BWs9m6z/IMG-0677.jpg",
    "Narcissist": "https://i.ibb.co/HL4LmCsJ/IMG-4068.png",
    "MUSIC [V1]": "https://i.ibb.co/PZDxHz50/484456766-1062141895957335-7903129463974570707-n.jpg",
    "MUSIC [V2]": "https://i.ibb.co/G3kGpbdB/6ac65b919ce5339d3f2707c03b8909ec-1000x1000x1.jpg",
    "MUSIC [V3]": "https://i.ibb.co/4Z3BndNL/1200x1200.jpg",
    "THC: The High Chronical$": "https://i.ibb.co/3Y04DsRv/6q1d-Uzi.png",
    "The High Chronical$": "https://i.ibb.co/3Y04DsRv/6q1d-Uzi.png",
    "death in tune": "https://i.ibb.co/VW5xv70J/artworks-000116608046-icqf3o-t1080x1080.jpg",
    "Cash Carti The Mixtape": "https://i.ibb.co/spDSTTBd/IMG-4071.jpg",
    "Digital Nas Collab": "https://i.ibb.co/cXJ34C8c/IMG-4072.jpg",
    "No Pressure": "https://i.ibb.co/4ngn6sz0/IMG-4076.png",
    "TrapMoneyBenny Collab": "https://i.ibb.co/Pzrdqnhz/IMG-4075.png",
    "Donda": "https://i.ibb.co/S4HZS9hp/Kanye-West-Donda-With-Child.png",
    "VULTURES": "https://i.ibb.co/b5CxHHPw/VULTURES-1.jpg",
    "CARTI YE": "https://i.ibb.co/VYzzYWNK/484831956-18026675570648887-6286441502178479497-n.jpg",
    "004KT": "https://i.ibb.co/6cQGqrqN/IMG-4074.jpg",
    "BABY BOI": "https://i.ibb.co/5WmWFQcJ/IMG-4073.jpg",
    "Sensation": "https://i.ibb.co/CK8KMmYp/a3383006450-16.jpg",
  },

  ALBUM_RELEASE_DATES: {
    "Aviation Class": "??/??/2010",
    "Killing Me Softly": "??/??/2011",
    "THC: The High Chronical$": "11/05/2011",
    "The High Chronical$": "11/05/2011",
    "$ir Cartier": "??/??/2012",
    "Kream": "??/??/2012",
    "death in tune": "??/??/2014",
    "Young Mi$fit": "??/??/2014",
    "Awful Records": "??/??/2014",
    "Chucky Era": "??/??/2014",
    "Cash Carti The Mixtape": "??/??/2015",
    "Sen$ation": "??/??/2015",
    "Ca$h Carti Season": "??/??/2016",
    "Digital Nas Collab": "??/??/2016",
    "Playboi Carti": "04/14/2017",
    "No Pressure": "??/??/2017",
    "16*29": "??/??/2017",
    "16*29 [V1]": "??/??/2017",
    "Die Lit": "05/11/2018",
    "Whole Lotta Red [V1]": "??/??/2018",
    "WE DON'T DIAL 911": "??/??/2019",
    "Whole Lotta Red [V2]": "??/??/2020",
    "Whole Lotta Red [V3]": "??/??/2020",
    "Whole Lotta Red (Deluxe)": "??/??/2021",
    "Whole Lotta Red [V4]": "12/25/2020",
    "Narcissist": "??/??/2021",
    "Donda": "??/??/2021",
    "Ye - DONDA": "??/??/2021",
    "MUSIC [V1]": "??/??/2022",
    "004KT": "??/??/2022",
    "MUSIC [V2]": "??/??/2023",
    "MUSIC [V3]": "??/??/2024",
    "VULTURES": "??/??/2024",
    "CARTI YE": "??/??/2025",
    "BABY BOI": "??/??/2024",
  },

  HIDDEN_ALBUMS: ["CARTI YE", "Ye - DONDA", "Donda", "VULTURES"],
  EXCLUDED_ALBUMS: ["TMB Collab", "004PF"],

  ALBUM_DESCRIPTIONS: {
    "Aviation Class": "Carti would first start working on music around 2009. His first musical appearance was the \"Jordan acting stupid\" video, going by the name \"JCee.\" He announced a mixtape called \"Aviation class\" on Sep 19, 2010 but released nothing except a couple of singles 5 months later.",
    "Killing Me Softly": "A project first teased by Carti on April 27, 2011. Later Carti left the project without mention until THC's release.",
    "Kream": "Project promoted by Carti in mid-2012, only one single was released for the project ($teeze). The project later morphed into Young Mi$fit.",
    "death in tune": "In 2014, Playboi Carti signed to Awful Records and started gaining popularity. During this era Carti used a red cover for his SoundCloud singles. The era ended with the release of death in tune EP.",
    "Cash Carti The Mixtape": "After death in tune, Carti's style shifted. He started collaborating more with MexikoDro and going deeper into the Plugg sound. The era ended January 2, 2016.",
    "Ca$h Carti Season": "Carti changed his style in early 2016 after meeting many famous rappers. This was his third era, the largest embodiment of Ca$h Carti, where he was at the peak of his flexing game.",
    "Digital Nas Collab": "Alongside work on Carti's third mixtape, Digital Nas and Carti worked on a collaboration project. The album never materialized aside from the song \"Run It\" being released by Digital Nas on SoundCloud in 2015.",
    "Playboi Carti": "Playboi Carti is the self-titled third mixtape from Playboi Carti, executively produced by A$AP Rocky, with heavy production from Pi'erre Bourne. It featured three singles: \"Lookin\", \"wokeuplikethis*\", and \"Magnolia.\"",
    "No Pressure": "Rich The Kid revealed on Reddit that he and Carti had \"a whole unreleased mixtape together.\" The project eventually got scrapped and songs were distributed to other artists.",
    "16*29": "In September 2017, Playboi Carti announced a joint album with Lil Uzi Vert titled 1629*. A tour was announced then cancelled. Carti mentioned recording \"like 100 songs\" with Uzi in July 2018, but the album subsided.",
    "TrapMoneyBenny Collab": "A collaborative project between Playboi Carti and TrapMoneyBenny. Details are sparse but sessions are known to have occurred.",
    "Die Lit": "Die Lit is Playboi Carti's debut studio album, executively produced by Pi'erre Bourne. Features Young Thug, Lil Uzi Vert, Travis Scott, Nicki Minaj, and Skepta. A hypnotic collection of catchy, effortless tracks.",
    "Whole Lotta Red [V1]": "The first iteration of Whole Lotta Red aimed for a similar sound to Die Lit, featuring Carti's now-famous \"Baby Voice\" prominently on songs like \"Pissy Pamper\" and \"Goku.\"",
    "WE DON'T DIAL 911": "Trippie Redd answered a fan asking for an EP with Carti \"sooner than later.\" The EP was likely worked on during 2019 but was later scrapped.",
    "Whole Lotta Red [V2]": "The second iteration of WLR pushed Carti's \"baby voice\" to new extremes. After mixed reactions to \"@ MEH,\" Carti reworked the project before its final release.",
    "Whole Lotta Red [V3]": "After the death of his friend Bigg Sosa, Carti took more time and abandoned his baby voice for an early version of his raspy voice.",
    "Whole Lotta Red (Deluxe)": "One day after WLR's release, Carti asked fans which songs they wanted on the deluxe. Two tracklist versions have been revealed by insiders but the project was ultimately shelved.",
    "Whole Lotta Red [V4]": "Carti shifted WLR into an aggressive ode to punk rock aesthetics. The album released on Christmas Day, 2020 with Ye as executive producer.",
    "Narcissist": "After shelving the WLR Deluxe, Carti entered his most mysterious era. He announced Narcissist for September 13, 2021, but it never dropped due to sample clearance issues.",
    "MUSIC [V1]": "The first phase of Carti's post-WLR sessions, working on his follow-up album.",
    "MUSIC [V2]": "The second phase of sessions for Carti's upcoming album.",
    "MUSIC [V3]": "The current and most recent phase of Carti's album sessions.",
  },

  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},
  ERA_MAPPINGS: {
    // Normalize song-row era names to match their header-row names
    "THC: The High Chronical$": "The High Chronical$",
    "THC: The High Chronicals": "The High Chronical$",
    "Ye - DONDA": "Donda",
  },
  hasCompsTab: false,
  hasConcertsTab: false,
  hasYeditsTab: false,
  hasSubAlbumsTab: false,
  TAG_MAP: { ...defaultTagMap, '💛': 'By VAMPgold' },
  ERA_THEMES: {},
  TAG_TOOLTIP_MAP: { ...defaultTagTooltips, 'By VAMPgold': 'Leaks & Songs added by the owner of the site.' },
};
