import type { ArtistConfig } from './types';

export const wolfgoldConfig: ArtistConfig = {
  slug: 'wolfgold',
  hasGroupbuysTab: true,
  hasAlbumCopiesTab: true,
  SITE_NAME: 'WOLFgold',
  SITE_DESCRIPTION: 'The Best Tyler, The Creator Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/wolfgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'wolfgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#f59e0b',
  artistLabel: 'Tyler, The Creator',
  cardLetter: 'WLF',
  logoUrl: '/logos/wolfgold.png',
  artistPhotoUrl: '/artists/tyler.jpg',

  getArtistName(eraName) {
    if (!eraName) return 'Tyler, The Creator';
    if (eraName === 'Ace') return 'Ace';
    return 'Tyler, The Creator';
  },

  CUSTOM_IMAGES: {
    'Ace': '/wolfgold/eras/ace.png',
    'my good beats': 'https://i.ibb.co/kgkqvknZ/images-q-tbn-ANd9-Gc-Qn-Ylu-RUl-YNIs-W9-J1-WSEhg-Kl-JBqtkd-NNU2-Raqja-Rbn-C6u-Tzhicdtg6-RNLH-s-10.jpg',
    'Dreams In 3-D': '/wolfgold/eras/dreams-in-3-d.png',
    'At Your Own Risk [V1]': '/wolfgold/eras/at-your-own-risk-v1.png',
    'Eargasm': '/wolfgold/eras/eargasm.png',
    'At Your Own Risk [V2]': '/wolfgold/eras/at-your-own-risk-v2.png',
    'Stereo-Type': '/wolfgold/eras/stereo-type.png',
    'The Recipe': '/wolfgold/eras/the-recipe.png',
    'Infinite Rhythms': '/wolfgold/eras/infinite-rhyhtms.png',
    'Unique Style': 'https://i.ibb.co/DfxJmxTs/8312d7bdf0fa37c6f8cce290b00f0f4c.jpg',
    'Poly/Mono': '/wolfgold/eras/poly-mono.png',
    'Radio Arcade': '/wolfgold/eras/radio-arcade.png',
    'Soundz On Acid': '/wolfgold/eras/soundz-on-acid.png',
    'Locked Away': '/wolfgold/eras/locked-away.jpg',
    'Personal Stash': '/wolfgold/eras/personal-stash.png',
    'Bodega': '/wolfgold/eras/bodega.jpg',
    'I Smell Panties': '/wolfgold/eras/i-smell-panties.png',
    'The Blair Bitch Project': '/wolfgold/eras/the-blair-bitch-project.png',
    'The Odd Future Tape Vol. 1': '/wolfgold/eras/the-of-tape-vol-1.png',
    'The OF Tape Vol. 1': '/wolfgold/eras/the-of-tape-vol-1.png',
    'PinkGoldSquarePixals': '/wolfgold/eras/pinkgold-squarepixals.png',
    'PinkGold SquarePixals': '/wolfgold/eras/pinkgold-squarepixals.png',
    'SuperDuperSteezMonster': '/wolfgold/eras/superduper-steezmonster.png',
    'SuperDuper SteezMonster': '/wolfgold/eras/superduper-steezmonster.png',
    'The Senioritis Tape': '/wolfgold/eras/the-senioritis-tape.png',
    'Ill Cab TV Thief': '/wolfgold/eras/ill-cab-tv-thief.png',
    'Dinosaur': '/wolfgold/eras/dinosaur.png',
    'The Au79': 'https://i.ibb.co/DDbWtNsW/sddefault.jpg',
    'Zombie Circus': '/wolfgold/eras/zombie-circus.jpg',
    'WOLF [V1]': '/wolfgold/eras/wolf-v1.png',
    'Bastard': '/wolfgold/eras/bastard.png',
    'Earl': '/wolfgold/eras/earl.png',
    'Radical': '/wolfgold/eras/radical.jpg',
    'Rolling Papers': '/wolfgold/eras/rolling-papers.jpg',
    'Goblin': '/wolfgold/eras/goblin.png',
    'Radical 2': 'https://i.ibb.co/4Bj3b2F/1-Odd-Future.jpg',
    'The Odd Future Tape Vol. 2': '/wolfgold/eras/the-of-tape-vol-2.png',
    'The OF Tape Vol. 2': '/wolfgold/eras/the-of-tape-vol-2.png',
    'Nilbog': '/wolfgold/eras/nilbog.jpg',
    'The Dead Sams': 'https://i.ibb.co/XZfrS4jb/e6d2d0ff7d3c576b9a3333aef2bbd581-lg.jpg',
    'WOLF [V2]': '/wolfgold/eras/wolf-v2.jpg',
    'WOLF [V3]': '/wolfgold/eras/wolf-v3.png',
    'The Jellies!': '/wolfgold/eras/the-jellies.png',
    'Cherry Bomb': '/wolfgold/eras/cherry-bomb.png',
    'Scum Fuck Flower Boy': '/wolfgold/eras/scum-fuck-flower-boy.png',
    'Flower Boy': '/wolfgold/eras/flower-boy.jpg',
    'WANG$AP': 'https://i.ibb.co/CsYKWkbB/1663276167-tyler-the-creator-asap-rocky-bromance-timeline-00.avif',
    "Music Inspired by Illumination & Dr. Seuss's The Grinch": '/wolfgold/eras/grinch-ep.jpg',
    'Grinch EP': '/wolfgold/eras/grinch-ep.jpg',
    'IGOR': '/wolfgold/eras/igor.png',
    'CALL ME WHEN YOU GET LOST': '/wolfgold/eras/call-me-if-you-get-lost-v1.png',
    'CALL ME IF YOU GET LOST [V1]': '/wolfgold/eras/call-me-if-you-get-lost-v1.png',
    'CALL ME IF YOU GET LOST [V2]': '/wolfgold/eras/call-me-if-you-get-lost-v2.png',
    'Louis Vuitton Show': 'https://i.ibb.co/dwLyLxc8/Tyler-The-Creator-Virgil-Abloh-fashion-show.jpg',
    'CHROMAKOPIA': '/wolfgold/eras/chromakopia.jpg',
    "DON'T TAP THE GLASS": '/wolfgold/eras/don-t-tap-the-glass.png',
    'Ongoing': '/wolfgold/eras/ongoing.png',
    'Unknown': 'https://i.ibb.co/9mp16ZJv/7zbfdm8b3npd1.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Ace': '??/??/2004',
    'my good beats': '??/??/2005',
    'Dreams In 3-D': '??/??/2006',
    'At Your Own Risk [V1]': '??/??/2007',
    'Eargasm': '??/??/2008',
    'At Your Own Risk [V2]': '??/??/2008',
    'Stereo-Type': '??/??/2008',
    'The Recipe': '??/??/2008',
    'Infinite Rhythms': '??/??/2009',
    'Unique Style': '??/??/2009',
    'Poly/Mono': '??/??/2009',
    'Radio Arcade': '??/??/2008',
    'Soundz On Acid': '??/??/2009',
    'Locked Away': '??/??/2009',
    'Personal Stash': '??/??/2009',
    'Bodega': '??/??/2010',
    'I Smell Panties': '??/??/2010',
    'The Blair Bitch Project': '??/??/2010',
    'The Odd Future Tape Vol. 1': '??/??/2010',
    'PinkGoldSquarePixals': '??/??/2010',
    'SuperDuperSteezMonster': '??/??/2011',
    'The Senioritis Tape': '??/??/2010',
    'Ill Cab TV Thief': '??/??/2011',
    'Dinosaur': '??/??/2009',
    'The Au79': '??/??/2011',
    'Zombie Circus': '??/??/2011',
    'WOLF [V1]': '??/??/2012',
    'Bastard': '12/25/2009',
    'Earl': '??/??/2011',
    'Radical': '??/??/2012',
    'Rolling Papers': '??/??/2011',
    'Goblin': '05/10/2011',
    'Awesome': '??/??/2012',
    'Radical 2': '??/??/2012',
    'The Odd Future Tape Vol. 2': '??/??/2012',
    'Nilbog': '??/??/2012',
    'The Dead Sams': '??/??/2012',
    'WOLF [V2]': '??/??/2012',
    'WOLF [V3]': '??/??/2012',
    'The Jellies!': '??/??/2014',
    'Cherry Bomb': '04/13/2015',
    'Scum Fuck Flower Boy': '07/21/2017',
    'Flower Boy': '07/21/2017',
    'WANG$AP': '??/??/2017',
    "Music Inspired by Illumination & Dr. Seuss's The Grinch": '??/??/2018',
    'IGOR': '05/17/2019',
    'CALL ME WHEN YOU GET LOST': '??/??/2020',
    'CALL ME IF YOU GET LOST': '06/25/2021',
    'CALL ME IF YOU GET LOST [V2]': '??/??/2020',
    'Louis Vuitton Show': '??/??/2024',
    'CHROMAKOPIA': '10/28/2024',
    "DON'T TAP THE GLASS": '07/18/2025',
    'Ongoing': '??/??/????',
    'Unknown': '??/??/????',
  },

  HIDDEN_ALBUMS: [],

  ALBUM_ORDER: [
    'Ace',
    'my good beats',
    'Dreams In 3-D',
    'At Your Own Risk [V1]',
    'Eargasm',
    'At Your Own Risk [V2]',
    'Stereo-Type',
    'The Recipe',
    'Infinite Rhythms',
    'Unique Style',
    'Poly/Mono',
    'Radio Arcade',
    'Soundz On Acid',
    'Locked Away',
    'Personal Stash',
    'Bodega',
    'I Smell Panties',
    'The Blair Bitch Project',
    'The Odd Future Tape Vol. 1',
    'PinkGoldSquarePixals',
    'SuperDuperSteezMonster',
    'The Senioritis Tape',
    'Ill Cab TV Thief',
    'Dinosaur',
    'The Au79',
    'Zombie Circus',
    'WOLF [V1]',
    'Bastard',
    'Earl',
    'Radical',
    'Rolling Papers',
    'Goblin',
    'Awesome',
    'Radical 2',
    'The Odd Future Tape Vol. 2',
    'Nilbog',
    'The Dead Sams',
    'WOLF [V2]',
    'WOLF [V3]',
    'The Jellies!',
    'Cherry Bomb',
    'Scum Fuck Flower Boy',
    'Flower Boy',
    'WANG$AP',
    "Music Inspired by Illumination & Dr. Seuss's The Grinch",
    'IGOR',
    'CALL ME WHEN YOU GET LOST',
    'CALL ME IF YOU GET LOST',
    'CALL ME IF YOU GET LOST [V2]',
    'Louis Vuitton Show',
    'CHROMAKOPIA',
    "DON'T TAP THE GLASS",
    'Ongoing',
    'Unknown',
  ],

  ALBUM_DESCRIPTIONS: {
    'Ace': "This is an umbrella era for any song that isn’t on any album, while Ace was either still uploading music to his MySpace, Hypebeast & imeem accounts, or just whenever Ace was last used.",
    'my good beats': "Compilation of beats Tyler made in 2004 that he wanted to repurpose for other projects, similar to \"Personal Stash\". Made under the name \"Tyler Okonma\", instead of Ace or Tyler, The Creator.",
    'Dreams In 3-D': 'Early scrapped MySpace-era project made in 2006, mostly instrumental.',
    'At Your Own Risk [V1]': "At Your Own Risk is another one of Tyler's earliest projects and was set to release on MySpace in 2008. This project contains a lot of reworked beats from Dreams In 3-D such as I Dream, Air Balloon, & Lounges X Blox. This was also mainly an instrumental album, with the only songs actually having vocals being Get Fresh and Speakerboxx. This project was likely shelved in favor of Stereo-Type sometime in 2007, but was later worked on later that year. Tyler ended up making a final instrumental copy of this album in 2008 that he burned onto CD's and gave to friends. Although he is never known to have recorded on this copy, the instrumental copy is known to be had.",
    'Eargasm': 'Scrapped MySpace-era project made around 2008.',
    'At Your Own Risk [V2]': "After At Your Own Risk was scrapped in early 2007, Tyler revived it in mid to late 2007. Every instrumental from the earlier copy got completely reworked into practically different tracks with the only similarities being the name. Planned to be recorded on and released around the same time Stereo-Type & Eargasm would've been in early to mid 2008.",
    'Stereo-Type': 'Mixtape set to release in 2008. Only instrumentals have leaked; the vocal copy is currently lost.',
    'The Recipe': 'Collaborative project with producer Burtono.',
    'Infinite Rhythms': "Earliest known project under the alias \"thrashpolo.\" Currently not much is known about it other than the fact it was worked on alongside \"Unique Style\", being worked on from Early 2007 - Late 2008.",
    'Unique Style': "The first known project Tyler has made under the alias \"thrashpolo\". Worked on from 2007 to 2009, and contains 16 instrumentals. This project has a cover, but is not leaked.",
    'Poly/Mono': 'Scrapped early instrumental project.',
    'Radio Arcade': 'Scrapped project made alongside Stereo-Type.',
    'Soundz On Acid': "Poly/Mono project worked on and off over the course of 2 years, unknown if it was meant for release or not.",
    'Locked Away': "Relatively obscure project made under the Ace alias, most likely consists of instrumentals only.",
    'Personal Stash': "Personal Stash was a playlist Tyler made that contained some of his favorite beats from around 2007 - 2010. It's unlikely that anything else tagged with this will surface again, as these are files taken directly from Tyler's personal emails.",
    'Bodega': "Relatively obscure project that was really only shared around with friends, quite a bit of this project was made at school. The songs on this project were tagged with many different artists, those being: Tyler, The Creator, Ace, Casey Veggies (CaseyV.), Skoolie300 (Skool Boy), brandUn DeShay, Trenard Moody (T Moody), & Mak Milli (K Mak). This project's last modified date is May 13th, 2008, but some songs were made later than that. This is one of three of Tyler's earliest projects that we have in full.",
    'I Smell Panties': "I Smell Panties is a joke collaboration between Tyler, Jasper Dolphin (Bon Bon) & HotBoy, two projects were planned but none released.",
    'The Blair Bitch Project': 'Scrapped early Odd Future-era project.',
    'The Odd Future Tape Vol. 1': "The Odd Future Tape is the debut mixtape from Odd Future, released on November 16, 2008.",
    'PinkGoldSquarePixals': "Album made under the Poly/Mono alias and was teased on Tyler's BlogSpot & on his MySpace alongside SuperDuperSteezMonster. Tyler talked on a Blogspot post about doing a \"Ghetto Tech Album, 808's And Sy.ths With Reverbs, Just Talking About Super Dumb Shit And Femals And Waffle, Shit That Can Get A Club Cracking.\"",
    'SuperDuperSteezMonster': "Album made under the Poly/Mono alias and was teased on Tyler's MySpace alongside PinkGoldSquarePixals.",
    'The Senioritis Tape': "The Senioritis Tape is a collaboration tape with Tyler & Odd Future that was planned to release when they graduated high school and was most likely scrapped soon after it was announced. Barely any information known about it other than it holding some OF Tape Vol. 1 instrumentals. It was announced on the Odd Future Blogspot on June 6th, 2009 and was supposed to be released on June 18th, 2009.",
    'Ill Cab TV Thief': "III Cab TV Thief is a project Tyler started in mid to late 2008, mostly comprised of instrumentals with the exception of \"Fuck Santa.\" Mentioned on April 8th, 2008. This project was worked alongside Dinosaur in early 2009, but later being scrapped and having some material moved over to Dinosaur.",
    'Dinosaur': "Dinosaur is a Tyler project that was set to release in March 2009 before being delayed, then scrapped in fall of the same year for Bastard. Tyler has stated on Twitter in 2010 that this project later became Bastard & that he still had a bunch of rough drafts from \"what it would have been.\"",
    'The Au79': "The Au79 was a Jazz instrumental album Tyler worked on from around 2008 to 2009, promotion was uploaded on his Vimeo account using the Untitled 63 beat.",
    'Zombie Circus': "Zombie Circus is a Tyler project that was started in late 2008, and worked on until mid 2009 when it was later scrapped, and some of the material got moved to WOLF. This album has been mentioned on a few of Tyler's songs. Tyler stated in an interview in 2013 that Zombie Circus would be releasing soon, but this interview has now been deleted. The base image for this era's album cover was later used on Bastard as an alternate cover.",
    'WOLF [V1]': "Original version of Wolf, dubbed \"WOLF 2010,\" that was worked on during Bastard and was meant to release alongside Goblin as a mixtape with both full songs and instrumentals. Eventually, the album was delayed for Tyler to focus on Goblin, but this was still being worked on. None of the songs from this iteration of the album are known to have made it onto the final version of Wolf. While yes, the era does span from 2008 - 2011, Supersonic [V2] is the ONLY \"WOLF [V1]\" tagged song that's 2008. This project started around January - February 2009 & was supposedly finished by November 11th, 2010.",
    'Bastard': 'Tyler\'s debut mixtape, released on Christmas Day 2009. A raw, introspective project that launched Odd Future\'s rise.',
    'Earl': "Earl is Earl Sweatshirt's debut mixtape, released on March 3rd, 2010. This era mainly contains a bunch of beats used on the project.",
    'Radical': "Radical is the second mixtape by Odd Future, released on May 7, 2010. This whole project consists of Odd Future members rapping over other people's instrumentals. Also notable for being the first time the EarlWolf name would be used.",
    'Rolling Papers': "Rolling Papers is Domo Genesis's debut mixtape, released on August 30th, 2010. This era mainly contains a bunch of beats used on the project.",
    'Goblin': 'Tyler\'s second studio album, released May 10, 2011 on XL Recordings. Features a therapy session concept and iconic tracks.',
    'Awesome': 'A scrapped Tyler, The Creator project from around 2012.',
    'Radical 2': "Radical 2 is a scrapped Odd Future project and the sequel to Radical, possibly named \"Awesome.\"",
    'The Odd Future Tape Vol. 2': "The OF Tape Vol. 2 is the debut album and second installation to the Odd Future Tape series, released on March 20th, 2012.",
    'Nilbog': "Nilbog is the name of a Tyler project that he did while he was healing from a foot injury he got at the House of Blues on July 16th, 2011, but also a bit before the release of Goblin. This album was not posted publically but screenshots were posted and immediately deleted, showing to have 37 tracks. First tracklist of Nilbog is length determined. Second tracklist is yet to be found.",
    'The Dead Sams': "The Dead Sams is a Tyler project that was first mentioned on Wolf and scrapped in late 2013, the concept for this project was conceived (or at least mentioned) in the Freeperm archive on June 7th, 2012. This project is said to sound like \"early Toro stuff and shitty N.E.R.D.,\" as well as \"all jazz chords but like garage rock.\" Also to be noted that The Dead Sams is the name of Tyler's \"dream band,\" in which they would do covers of songs.",
    'WOLF [V2]': "After the release of Goblin, Tyler would continue his work on WOLF, reusing some material from the original while making new pieces of work.",
    'WOLF [V3]': 'Third working version of the Wolf album sessions, leading into Tyler\'s third studio album, released April 2, 2013.',
    'The Jellies!': 'Scrapped project from the WOLF era.',
    'Cherry Bomb': 'Tyler\'s fourth studio album, released April 13, 2015. Known for its lo-fi, abrasive production.',
    'Scum Fuck Flower Boy': "Scum Fuck Flower Boy was first mentioned on October 9th, 2015 and would be worked on for the next two years until it's release as just \"Flower Boy\" on July 21st, 2017. Note that almost everything in this era except for a few things are snippets of rough drafts of songs that were ripped from Tyler's scumfuckflowerboy Instagram (I can't remember who added all the information about them but whoever did that, thank you).",
    'Flower Boy': "Flower Boy is Tyler's fifth studio album, leaked on July 10th, 2017 and released on July 21st, 2017.",
    'WANG$AP': "WANG$AP is the planned collaboration album between Tyler & A$AP Rocky that came out of the Flower Boy sessions, first mentioned Tyler's freeperm account on Feb 10, 2016 to be a \"9 song album\". The only official release from this album was Potato Salad, with it being considered scrapped in early 2019 after Tyler stated “i wish rocky would shut the fuck up and stop always saying what he's working on 40 years before its even a fleshed out idea.” and “that shit dont exist yall =)” in reference to WANG$AP. Tyler later revealed in 2025 that him and Rocky as a duo were originally meant to be called \"DON'T TAP THE GLASS\", a phrase which he would eventually reuse as the name of his ninth studio album.",
    "Music Inspired by Illumination & Dr. Seuss's The Grinch": "Music Inspired by Illumination & Dr. Seuss' The Grinch is Tyler's first extended play, released on November 16, 2018. Tyler commented that \"making christmas themed music, but not making it too xmasy was the goal [and] keeping 7 year olds in mind but also wanting the parents to listen also.\"",
    'IGOR': 'Tyler\'s sixth studio album, released May 17, 2019. Won the Grammy for Best Rap Album. A concept album about unrequited love.',
    'CALL ME WHEN YOU GET LOST': "Originally, CALL ME IF YOU GET LOST would've been a mixtape where he would rap over other people's beats, but he would later scrap this idea. This idea can be seen mostly with the throwaways in this era, but also in some songs on the album such as LUMBERJACK & SIR BAUDELAIRE. Tyler mentions in an interview that he started the album on December 25th, 2019 and initially thought the album was done in November 2020, but he would later rework the project. Was initially thought to be called HOUSE ON FIRE, but this was later disproven. DJ Drama would confirm on his podcast that the original name for the project was \"CALL ME WHEN YOU GET LOST\".",
    'CALL ME IF YOU GET LOST': 'Tyler\'s sixth studio album, released June 25, 2021 and narrated by DJ Drama in a Gangsta Grillz style.',
    'CALL ME IF YOU GET LOST [V2]': 'Later sessions leading toward the final album, released June 25, 2021 and narrated by DJ Drama in a Gangsta Grillz style.',
    'Louis Vuitton Show': "Umbrella-era for a collection of beats that Tyler used orchestrally for the Louis Vuitton Men's Fall-Winter Show in 2022. This show, held at Carreau du Temple in Paris, was one of the last shows put together by the late fashion designer and Louis Vuitton creative director Virgil Abloh. This show was scored by Tyler and was arranged by Arthur Verocai and it was Gustavo Dudamel who conducted the live performance by the Chineke! Orchestra. The Sunseeker isn't an official name.",
    'CHROMAKOPIA': 'Tyler\'s eighth studio album, released October 28, 2024. Explores themes of identity, legacy, and authenticity.',
    "DON'T TAP THE GLASS": 'Tyler\'s ninth studio album, released July 18, 2025.',
    'Ongoing': "After releasing DON'T TAP THE GLASS, Tyler has continued to make new music with the only currently known song being SAG HARBOR. A$AP Rocky claims that Tyler is soon to drop.",
    'Unknown': "Projects and songs that have little to no information on them go here. Hopefully, more will be known about these one day.",
  },

  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},

  ERA_MAPPINGS: {
    'Ace*': 'Ace',
    'Bastard*': 'Bastard',
    'Goblin*': 'Goblin',
    'Radical*': 'Radical',
    'Nilbog*': 'Nilbog',
    'WOLF [V1]*': 'WOLF [V1]',
    'WOLF [V2]*': 'WOLF [V2]',
    'WOLF [V3]*': 'WOLF [V3]',
    'Cherry Bomb*': 'Cherry Bomb',
    'Flower Boy*': 'Flower Boy',
    'Scum Fuck Flower Boy*': 'Scum Fuck Flower Boy',
    'IGOR*': 'IGOR',
    'CALL ME WHEN YOU GET LOST*': 'CALL ME WHEN YOU GET LOST',
    'CALL ME IF YOU GET LOST [V2]*': 'CALL ME IF YOU GET LOST [V2]',
    'At Your Own Risk [V1]*': 'At Your Own Risk [V1]',
    'At Your Own Risk [V2]*': 'At Your Own Risk [V2]',
    'CHROMAKOPIA*': 'CHROMAKOPIA',
  },

  hasCompsTab: false,
  hasConcertsTab: false,
  hasRecentTab: true,
  hasArtTab: false,
  hasVideosTab: false,

  TAG_MAP: {
    '⭐': 'Best Of',
    '🏆': 'Grails',
    '🥇': 'Wanted',
    '🏅': 'Wanted',
    '✨': 'Notable',
    '💛': 'By WOLFgold',
    '🗑️': 'Worst Of',
    '🗑': 'Worst Of',
    '🚮': 'Unwanted',
    '🤖': 'AI',
    '⁉️': 'Lost Media',
    '⁉': 'Lost Media',
    '❓': 'Unknown',
    '⭐️': 'Best Of',
  },

  ERA_THEMES: {
    'Bastard': {},
    'Goblin': {},
    'Cherry Bomb': {},
    'Flower Boy': {},
    'Scum Fuck Flower Boy': {},
    'IGOR': {},
    'CHROMAKOPIA': {},
  },

  TAG_TOOLTIP_MAP: {
    'Best Of': 'Some of the best leaks hosted on the tracker.',
    'Grails': 'The most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as much as Grails.',
    'Notable': 'Notable songs worth highlighting.',
    'Worst Of': 'Some of the worst leaks on the tracker.',
    'Unwanted': 'Songs we don\'t want to see leak in full.',
    'AI': 'Track contains AI vocals.',
    'Lost Media': 'Currently lost, or no link to the media is known.',
    'By WOLFgold': 'Leaks & songs added by the owner of the site.',
    'Unknown': 'Availability or status is unknown.',
  },
};
