import type { ArtistConfig } from './types';

export const wolfgoldConfig: ArtistConfig = {
  slug: 'wolfgold',
  SITE_NAME: 'WOLFgold',
  SITE_DESCRIPTION: 'The Best Tyler, The Creator Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/wolfgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'wolfgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#f59e0b',
  artistLabel: 'Tyler, The Creator',
  cardLetter: 'WLF',
  logoUrl: '/logos/wolfgold.png',
  artistPhotoUrl: '/artists/tyler.webp',

  getArtistName(eraName) {
    if (!eraName) return 'Tyler, The Creator';
    if (eraName === 'Ace') return 'Ace';
    return 'Tyler, The Creator';
  },

  CUSTOM_IMAGES: {
    'Ace': 'https://i.ibb.co/placeholder/ace.jpg',
    'Bastard': 'https://upload.wikimedia.org/wikipedia/en/6/6a/Tyler_the_Creator_-_Bastard.png',
    'Goblin': 'https://upload.wikimedia.org/wikipedia/en/4/45/Tyler_the_Creator_-_Goblin.jpg',
    'WOLF': 'https://upload.wikimedia.org/wikipedia/en/e/e7/Tyler_Wolf.jpg',
    'Cherry Bomb': 'https://upload.wikimedia.org/wikipedia/en/5/5d/Tyler_-_Cherry_Bomb.jpg',
    'Flower Boy': 'https://upload.wikimedia.org/wikipedia/en/1/14/Scum_Fuck_Flower_Boy_%28Official_Album_Cover%29_by_Tyler_the_Creator.jpg',
    'Scum Fuck Flower Boy': 'https://upload.wikimedia.org/wikipedia/en/1/14/Scum_Fuck_Flower_Boy_%28Official_Album_Cover%29_by_Tyler_the_Creator.jpg',
    'IGOR': 'https://upload.wikimedia.org/wikipedia/en/3/3c/IGOR_album_cover.jpg',
    'CALL ME IF YOU GET LOST': 'https://upload.wikimedia.org/wikipedia/en/e/e3/Tyler%2C_the_Creator_-_Call_Me_If_You_Get_Lost.png',
    'CALL ME IF YOU GET LOST [V1]': 'https://upload.wikimedia.org/wikipedia/en/e/e3/Tyler%2C_the_Creator_-_Call_Me_If_You_Get_Lost.png',
    'CALL ME IF YOU GET LOST [V2]': 'https://upload.wikimedia.org/wikipedia/en/e/e3/Tyler%2C_the_Creator_-_Call_Me_If_You_Get_Lost.png',
    'CHROMAKOPIA': 'https://upload.wikimedia.org/wikipedia/en/5/55/Tyler_the_Creator_-_Chromakopia.png',
    'Radical': '',
    'Nilbog': '',
    'Goblin [V2]': '',
    'WOLF [V1]': 'https://upload.wikimedia.org/wikipedia/en/e/e7/Tyler_Wolf.jpg',
    'WOLF [V2]': 'https://upload.wikimedia.org/wikipedia/en/e/e7/Tyler_Wolf.jpg',
    'WOLF [V3]': 'https://upload.wikimedia.org/wikipedia/en/e/e7/Tyler_Wolf.jpg',
    'At Your Own Risk [V1]': '',
    'At Your Own Risk [V2]': '',
    'At Your Own Risk': '',
    'Louis Vuitton Show': '',
    'Unknown': '',
    'Ongoing': '',
  },

  ALBUM_RELEASE_DATES: {
    'Ace': '??/??/2004',
    'Bastard': '12/25/2009',
    'Goblin': '05/10/2011',
    'Radical': '??/??/2012',
    'Nilbog': '??/??/2012',
    'WOLF [V1]': '??/??/2012',
    'WOLF [V2]': '??/??/2012',
    'WOLF [V3]': '??/??/2012',
    'WOLF': '04/02/2013',
    'Cherry Bomb': '04/13/2015',
    'Flower Boy': '07/21/2017',
    'Scum Fuck Flower Boy': '07/21/2017',
    'IGOR': '05/17/2019',
    'CALL ME IF YOU GET LOST [V1]': '??/??/2020',
    'CALL ME IF YOU GET LOST [V2]': '??/??/2020',
    'CALL ME IF YOU GET LOST': '06/25/2021',
    'At Your Own Risk [V1]': '??/??/2023',
    'At Your Own Risk [V2]': '??/??/2023',
    'At Your Own Risk': '??/??/2023',
    'Louis Vuitton Show': '??/??/2024',
    'CHROMAKOPIA': '10/28/2024',
    'Ongoing': '??/??/????',
    'Unknown': '??/??/????',
  },

  HIDDEN_ALBUMS: ['Unknown'],

  ALBUM_DESCRIPTIONS: {
    'Ace': 'Tyler\'s earliest era, producing beats under the name "Ace" and uploading to MySpace, Hypebeast, and imeem. Spans 2004–2012.',
    'Bastard': 'Tyler\'s debut mixtape, released on Christmas Day 2009. A raw, introspective project that launched Odd Future\'s rise.',
    'Goblin': 'Tyler\'s second studio album, released May 10, 2011 on XL Recordings. Features a therapy session concept and iconic tracks.',
    'Radical': 'Scrapped project that preceded Wolf. Contains some of Tyler\'s most sought-after unreleased material.',
    'Nilbog': 'Early scrapped album concept from around 2011–2012.',
    'WOLF [V1]': 'First working version of the Wolf album sessions.',
    'WOLF [V2]': 'Second working version of the Wolf album sessions.',
    'WOLF [V3]': 'Third working version of the Wolf album sessions.',
    'WOLF': 'Tyler\'s third studio album, released April 2, 2013. A sprawling concept album set at a youth camp.',
    'Cherry Bomb': 'Tyler\'s fourth studio album, released April 13, 2015. Known for its lo-fi, abrasive production.',
    'Flower Boy': 'Tyler\'s fifth studio album, released July 21, 2017. A breakthrough in critically acclaimed, more introspective music.',
    'Scum Fuck Flower Boy': 'Alternate title for Flower Boy used in some markets.',
    'IGOR': 'Tyler\'s sixth studio album, released May 17, 2019. Won the Grammy for Best Rap Album. A concept album about unrequited love.',
    'CALL ME IF YOU GET LOST [V1]': 'Early sessions for the Call Me If You Get Lost album.',
    'CALL ME IF YOU GET LOST [V2]': 'Later sessions leading toward the final album.',
    'CALL ME IF YOU GET LOST': 'Tyler\'s seventh studio album, released June 25, 2021. Narrated by DJ Drama in a Gangsta Grillz style.',
    'At Your Own Risk [V1]': 'First phase of the AYOR era sessions.',
    'At Your Own Risk [V2]': 'Second phase of the AYOR era sessions.',
    'At Your Own Risk': 'Sessions and material leading into CHROMAKOPIA.',
    'Louis Vuitton Show': 'Music made for Tyler\'s Louis Vuitton Men\'s Fall-Winter fashion show, also known as "The Sunseeker."',
    'CHROMAKOPIA': 'Tyler\'s eighth studio album, released October 28, 2024. Explores themes of identity, legacy, and authenticity.',
    'Ongoing': 'Songs without a confirmed era or still being worked on.',
    'Unknown': 'Miscellaneous material without a confirmed era.',
  },

  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},

  ERA_MAPPINGS: {
    'Ace*': 'Ace',
    'Bastard*': 'Bastard',
    'Goblin*': 'Goblin',
    'Radical*': 'Radical',
    'Nilbog*': 'Nilbog',
    'WOLF [V1]*': 'WOLF [V1]',
    'WOLF [V2]*': 'WOLF [V2]',
    'WOLF [V3]*': 'WOLF [V3]',
    'WOLF*': 'WOLF',
    'Cherry Bomb*': 'Cherry Bomb',
    'Flower Boy*': 'Flower Boy',
    'Scum Fuck Flower Boy*': 'Scum Fuck Flower Boy',
    'IGOR*': 'IGOR',
    'CALL ME IF YOU GET LOST [V1]*': 'CALL ME IF YOU GET LOST [V1]',
    'CALL ME IF YOU GET LOST [V2]*': 'CALL ME IF YOU GET LOST [V2]',
    'CALL ME IF YOU GET LOST*': 'CALL ME IF YOU GET LOST',
    'At Your Own Risk [V1]*': 'At Your Own Risk [V1]',
    'At Your Own Risk [V2]*': 'At Your Own Risk [V2]',
    'At Your Own Risk*': 'At Your Own Risk',
    'CHROMAKOPIA*': 'CHROMAKOPIA',
  },

  hasCompsTab: false,
  hasConcertsTab: false,
  hasRecentTab: true,

  TAG_MAP: {
    '⭐': 'Best Of',
    '🏆': 'Grails',
    '🥇': 'Wanted',
    '🏅': 'Wanted',
    '✨': 'Notable',
    '💛': 'By WOLFgold',
    '🗑️': 'Worst Of',
    '🗑': 'Worst Of',
    '🚮': 'Unwanted',
    '🤖': 'AI',
    '⁉️': 'Lost Media',
    '⁉': 'Lost Media',
    '❓': 'Unknown',
    '⭐️': 'Best Of',
  },

  ERA_THEMES: {
    'Bastard': {},
    'Goblin': {},
    'WOLF': {},
    'Cherry Bomb': {},
    'Flower Boy': {},
    'Scum Fuck Flower Boy': {},
    'IGOR': {},
    'CALL ME IF YOU GET LOST': {},
    'CHROMAKOPIA': {},
  },

  TAG_TOOLTIP_MAP: {
    'Best Of': 'Some of the best leaks hosted on the tracker.',
    'Grails': 'The most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as much as Grails.',
    'Notable': 'Notable songs worth highlighting.',
    'Worst Of': 'Some of the worst leaks on the tracker.',
    'Unwanted': 'Songs we don\'t want to see leak in full.',
    'AI': 'Track contains AI vocals.',
    'Lost Media': 'Currently lost, or no link to the media is known.',
    'By WOLFgold': 'Leaks & songs added by the owner of the site.',
    'Unknown': 'Availability or status is unknown.',
  },
};
