import type { ArtistConfig } from './types';

export const wolfgoldConfig: ArtistConfig = {
  slug: 'wolfgold',
  SITE_NAME: 'WOLFgold',
  SITE_DESCRIPTION: 'The Best Tyler, The Creator Tracker In The World!',
  SITE_URL: 'https://unvaulted.cc/wolfgold/',
  OG_IMAGE_URL: '',
  STORAGE_PREFIX: 'wolfgold_',
  HARDCODED_SHEET_ID: '',
  HARDCODED_SHEET_GID: '',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: '',
  accentColor: '#f59e0b',
  artistLabel: 'Tyler, The Creator',
  cardLetter: 'WLF',
  logoUrl: '/logos/wolfgold.png',
  artistPhotoUrl: '/artists/tyler.webp',

  getArtistName(eraName) {
    if (!eraName) return 'Tyler, The Creator';
    if (eraName === 'Ace') return 'Ace';
    return 'Tyler, The Creator';
  },

  CUSTOM_IMAGES: {
    'Ace': 'https://i.ibb.co/B5f4Fhdb/cell-Image-1205288305-0.png',
    'my good beats': 'https://i.ibb.co/kgkqvknZ/images-q-tbn-ANd9-Gc-Qn-Ylu-RUl-YNIs-W9-J1-WSEhg-Kl-JBqtkd-NNU2-Raqja-Rbn-C6u-Tzhicdtg6-RNLH-s-10.jpg',
    'Dreams In 3-D': 'https://i.ibb.co/dnV0563/cell-Image-1205288305-2.png',
    'At Your Own Risk [V1]': 'https://i.ibb.co/9HLJxTx4/cell-Image-1205288305-3.png',
    'Eargasm': 'https://i.ibb.co/fY6F5NN0/cell-Image-1205288305-10.png',
    'At Your Own Risk [V2]': 'https://i.ibb.co/bRYqzvZ8/cell-Image-1205288305-8.png',
    'Stereo-Type': 'https://i.ibb.co/W4j7qSky/cell-Image-1205288305-5.png',
    'The Recipe': 'https://i.ibb.co/q3Z9K33C/cell-Image-1205288305-7.png',
    'Infinite Rhythms': 'https://i.ibb.co/cS21cjvb/cell-Image-1205288305-11.png',
    'Unique Style': 'https://i.ibb.co/DfxJmxTs/8312d7bdf0fa37c6f8cce290b00f0f4c.jpg',
    'Poly/Mono': 'https://i.ibb.co/CsS5T3fP/cell-Image-1205288305-13.png',
    'Radio Arcade': 'https://i.ibb.co/P8zMx5K/cell-Image-1205288305-15.png',
    'Soundz On Acid': 'https://i.ibb.co/chWVVWvH/cell-Image-1205288305-16.png',
    'Locked Away': 'https://i.ibb.co/67hxv633/cell-Image-1205288305-17.jpg',
    'Personal Stash': 'https://i.ibb.co/vMKP0s8/cell-Image-1205288305-18.png',
    'Bodega': 'https://i.ibb.co/Fkp0RJHW/cell-Image-1205288305-19.jpg',
    'I Smell Panties': 'https://i.ibb.co/xKrtnqhG/cell-Image-1205288305-20.png',
    'The Blair Bitch Project': 'https://i.ibb.co/fGMmPpnW/cell-Image-1205288305-22.png',
    'The Odd Future Tape Vol. 1': 'https://i.ibb.co/VcdXtxHK/cell-Image-1205288305-23.png',
    'PinkGoldSquarePixals': 'https://i.ibb.co/6cws026f/cell-Image-1205288305-24.png',
    'SuperDuperSteezMonster': 'https://i.ibb.co/s9L1R2GK/cell-Image-1205288305-25.png',
    'The Senioritis Tape': 'https://i.ibb.co/QFZJ3Q9q/cell-Image-1205288305-26.png',
    'Ill Cab TV Thief': 'https://i.ibb.co/8gjDhjNb/cell-Image-1205288305-27.png',
    'Dinosaur': 'https://i.ibb.co/xRXJZmC/cell-Image-1205288305-28.png',
    'The Au79': 'https://i.ibb.co/DDbWtNsW/sddefault.jpg',
    'Zombie Circus': 'https://i.ibb.co/CKS5ppvd/cell-Image-1205288305-29.jpg',
    'WOLF [V1]': 'https://i.ibb.co/PvBsGX5M/cell-Image-1205288305-30.png',
    'Bastard': 'https://i.ibb.co/KjF4Cf0L/cell-Image-1205288305-32.png',
    'Earl': 'https://i.ibb.co/QvVnjW9h/cell-Image-1205288305-33.png',
    'Radical': 'https://i.ibb.co/N2LNHydb/cell-Image-1205288305-34.jpg',
    'Rolling Papers': 'https://i.ibb.co/27GcLzt7/cell-Image-1205288305-35.jpg',
    'Goblin': 'https://i.ibb.co/1YRzFNHG/cell-Image-1205288305-37.png',
    'Radical 2': 'https://i.ibb.co/4Bj3b2F/1-Odd-Future.jpg',
    'The Odd Future Tape Vol. 2': 'https://i.ibb.co/3G0HNz6/cell-Image-1205288305-38.png',
    'Nilbog': 'https://i.ibb.co/5hMWxqNL/cell-Image-1205288305-39.jpg',
    'The Dead Sams': 'https://i.ibb.co/XZfrS4jb/e6d2d0ff7d3c576b9a3333aef2bbd581-lg.jpg',
    'WOLF [V2]': 'https://i.ibb.co/PsVyF3YN/cell-Image-1205288305-40.jpg',
    'WOLF [V3]': 'https://i.ibb.co/ZRs7Qs2b/cell-Image-1205288305-42.png',
    'The Jellies!': 'https://i.ibb.co/rR9cFMPv/cell-Image-1205288305-43.png',
    'Cherry Bomb': 'https://i.ibb.co/zHbBjTFk/cell-Image-1205288305-45.png',
    'Scum Fuck Flower Boy': 'https://i.ibb.co/fzTzpdWH/cell-Image-1205288305-46.png',
    'Flower Boy': 'https://i.ibb.co/WpvmnysZ/cell-Image-1205288305-47.jpg',
    'WANG$AP': 'https://i.ibb.co/CsYKWkbB/1663276167-tyler-the-creator-asap-rocky-bromance-timeline-00.avif',
    "Music Inspired by Illumination & Dr. Seuss's The Grinch": 'https://i.ibb.co/jkvCyn0G/cell-Image-1205288305-48.jpg',
    'IGOR': 'https://i.ibb.co/84BS36Pq/cell-Image-1205288305-50.png',
    'CALL ME WHEN YOU GET LOST': 'https://i.ibb.co/PZ74gWb7/cell-Image-1205288305-51.png',
    'CALL ME IF YOU GET LOST [V2]': 'https://i.ibb.co/Vckq3Frr/cell-Image-1205288305-53.png',
    'Louis Vuitton Show': 'https://i.ibb.co/dwLyLxc8/Tyler-The-Creator-Virgil-Abloh-fashion-show.jpg',
    'CHROMAKOPIA': 'https://i.ibb.co/MDS2qHCs/cell-Image-1205288305-55.jpg',
    "DON'T TAP THE GLASS": 'https://i.ibb.co/5h1bGS6n/cell-Image-1205288305-57.png',
    'Ongoing': 'https://i.ibb.co/d4TFWcBT/cell-Image-1205288305-58.png',
    'Unknown': 'https://i.ibb.co/9mp16ZJv/7zbfdm8b3npd1.jpg',
  },

  ALBUM_RELEASE_DATES: {
    'Ace': '??/??/2004',
    'my good beats': '??/??/2005',
    'Dreams In 3-D': '??/??/2006',
    'At Your Own Risk [V1]': '??/??/2007',
    'Eargasm': '??/??/2008',
    'At Your Own Risk [V2]': '??/??/2008',
    'Stereo-Type': '??/??/2008',
    'The Recipe': '??/??/2008',
    'Infinite Rhythms': '??/??/2009',
    'Unique Style': '??/??/2009',
    'Poly/Mono': '??/??/2009',
    'Radio Arcade': '??/??/2008',
    'Soundz On Acid': '??/??/2009',
    'Locked Away': '??/??/2009',
    'Personal Stash': '??/??/2009',
    'Bodega': '??/??/2010',
    'I Smell Panties': '??/??/2010',
    'The Blair Bitch Project': '??/??/2010',
    'The Odd Future Tape Vol. 1': '??/??/2010',
    'PinkGoldSquarePixals': '??/??/2010',
    'SuperDuperSteezMonster': '??/??/2011',
    'The Senioritis Tape': '??/??/2010',
    'Ill Cab TV Thief': '??/??/2011',
    'Dinosaur': '??/??/2009',
    'The Au79': '??/??/2011',
    'Zombie Circus': '??/??/2011',
    'WOLF [V1]': '??/??/2012',
    'Bastard': '12/25/2009',
    'Earl': '??/??/2011',
    'Radical': '??/??/2012',
    'Rolling Papers': '??/??/2011',
    'Goblin': '05/10/2011',
    'Radical 2': '??/??/2012',
    'The Odd Future Tape Vol. 2': '??/??/2012',
    'Nilbog': '??/??/2012',
    'The Dead Sams': '??/??/2012',
    'WOLF [V2]': '??/??/2012',
    'WOLF [V3]': '??/??/2012',
    'The Jellies!': '??/??/2014',
    'Cherry Bomb': '04/13/2015',
    'Scum Fuck Flower Boy': '07/21/2017',
    'Flower Boy': '07/21/2017',
    'WANG$AP': '??/??/2017',
    "Music Inspired by Illumination & Dr. Seuss's The Grinch": '??/??/2018',
    'IGOR': '05/17/2019',
    'CALL ME WHEN YOU GET LOST': '??/??/2020',
    'CALL ME IF YOU GET LOST [V2]': '??/??/2020',
    'Louis Vuitton Show': '??/??/2024',
    'CHROMAKOPIA': '10/28/2024',
    "DON'T TAP THE GLASS": '07/18/2025',
    'Ongoing': '??/??/????',
    'Unknown': '??/??/????',
  },

  HIDDEN_ALBUMS: ['Unknown'],

  ALBUM_ORDER: [
    'Ace',
    'my good beats',
    'Dreams In 3-D',
    'At Your Own Risk [V1]',
    'Eargasm',
    'At Your Own Risk [V2]',
    'Stereo-Type',
    'The Recipe',
    'Infinite Rhythms',
    'Unique Style',
    'Poly/Mono',
    'Radio Arcade',
    'Soundz On Acid',
    'Locked Away',
    'Personal Stash',
    'Bodega',
    'I Smell Panties',
    'The Blair Bitch Project',
    'The Odd Future Tape Vol. 1',
    'PinkGoldSquarePixals',
    'SuperDuperSteezMonster',
    'The Senioritis Tape',
    'Ill Cab TV Thief',
    'Dinosaur',
    'The Au79',
    'Zombie Circus',
    'WOLF [V1]',
    'Bastard',
    'Earl',
    'Radical',
    'Rolling Papers',
    'Goblin',
    'Radical 2',
    'The Odd Future Tape Vol. 2',
    'Nilbog',
    'The Dead Sams',
    'WOLF [V2]',
    'WOLF [V3]',
    'The Jellies!',
    'Cherry Bomb',
    'Scum Fuck Flower Boy',
    'Flower Boy',
    'WANG$AP',
    "Music Inspired by Illumination & Dr. Seuss's The Grinch",
    'IGOR',
    'CALL ME WHEN YOU GET LOST',
    'CALL ME IF YOU GET LOST [V2]',
    'Louis Vuitton Show',
    'CHROMAKOPIA',
    "DON'T TAP THE GLASS",
    'Ongoing',
    'Unknown',
  ],

  ALBUM_DESCRIPTIONS: {
    'Ace': 'Tyler\'s earliest era, producing beats under the name "Ace" and uploading to MySpace, Hypebeast, and imeem. Spans 2004–2012.',
    'my good beats': 'Small batch of early instrumental beats from Tyler\'s "Ace" era.',
    'Dreams In 3-D': 'Early scrapped MySpace-era project made in 2006, mostly instrumental.',
    'At Your Own Risk [V1]': 'First version of At Your Own Risk, an early scrapped project set to release on MySpace, reworking beats from Dreams In 3-D.',
    'Eargasm': 'Scrapped MySpace-era project made around 2008.',
    'At Your Own Risk [V2]': 'Reworked second version of At Your Own Risk, picked back up in late 2007 with new instrumentals planned alongside Stereo-Type and Eargasm.',
    'Stereo-Type': 'Mixtape set to release in 2008. Only instrumentals have leaked; the vocal copy is currently lost.',
    'The Recipe': 'Collaborative project with producer Burtono.',
    'Infinite Rhythms': 'Scrapped early instrumental project.',
    'Unique Style': 'Scrapped early instrumental project.',
    'Poly/Mono': 'Scrapped early instrumental project.',
    'Radio Arcade': 'Scrapped project made alongside Stereo-Type.',
    'Soundz On Acid': 'Scrapped early instrumental project.',
    'Locked Away': 'Scrapped early instrumental project.',
    'Personal Stash': 'Scrapped early instrumental project.',
    'Bodega': 'Scrapped early instrumental project.',
    'I Smell Panties': 'Collaboration with Jasper Dolphin.',
    'The Blair Bitch Project': 'Scrapped early Odd Future-era project.',
    'The Odd Future Tape Vol. 1': 'Collaborative Odd Future compilation tape.',
    'PinkGoldSquarePixals': 'Scrapped early instrumental project.',
    'SuperDuperSteezMonster': 'Scrapped early project produced with Syd and StereoHype.',
    'The Senioritis Tape': 'Collaborative Odd Future-era tape.',
    'Ill Cab TV Thief': 'Scrapped early project.',
    'Dinosaur': 'Scrapped early project, also referred to as the Dinosaur EP, preceding Bastard.',
    'The Au79': 'Scrapped early instrumental project.',
    'Zombie Circus': 'Scrapped early project.',
    'WOLF [V1]': 'First working version of the Wolf album sessions.',
    'Bastard': 'Tyler\'s debut mixtape, released on Christmas Day 2009. A raw, introspective project that launched Odd Future\'s rise.',
    'Earl': 'Collaboration with Earl Sweatshirt.',
    'Radical': 'Scrapped project that preceded Wolf, made with Odd Future. Contains some of Tyler\'s most sought-after unreleased material.',
    'Rolling Papers': 'Collaboration with Domo Genesis.',
    'Goblin': 'Tyler\'s second studio album, released May 10, 2011 on XL Recordings. Features a therapy session concept and iconic tracks.',
    'Radical 2': 'Follow-up scrapped Odd Future collaboration project.',
    'The Odd Future Tape Vol. 2': 'Collaborative Odd Future compilation tape, the follow-up to Vol. 1.',
    'Nilbog': 'Early scrapped album concept from around 2011–2012.',
    'The Dead Sams': 'Scrapped early project.',
    'WOLF [V2]': 'Second working version of the Wolf album sessions.',
    'WOLF [V3]': 'Third working version of the Wolf album sessions, leading into Tyler\'s third studio album, released April 2, 2013.',
    'The Jellies!': 'Scrapped project from the WOLF era.',
    'Cherry Bomb': 'Tyler\'s fourth studio album, released April 13, 2015. Known for its lo-fi, abrasive production.',
    'Scum Fuck Flower Boy': 'Alternate title for Flower Boy used in some markets.',
    'Flower Boy': 'Tyler\'s fifth studio album, released July 21, 2017. A breakthrough in critically acclaimed, more introspective music.',
    'WANG$AP': 'Collaborative project with A$AP Rocky.',
    "Music Inspired by Illumination & Dr. Seuss's The Grinch": 'Soundtrack contributions for the 2018 animated film The Grinch.',
    'IGOR': 'Tyler\'s sixth studio album, released May 17, 2019. Won the Grammy for Best Rap Album. A concept album about unrequited love.',
    'CALL ME WHEN YOU GET LOST': 'Early sessions for the Call Me If You Get Lost album.',
    'CALL ME IF YOU GET LOST [V2]': 'Later sessions leading toward the final album, released June 25, 2021 and narrated by DJ Drama in a Gangsta Grillz style.',
    'Louis Vuitton Show': 'Music made for Tyler\'s Louis Vuitton Men\'s Fall-Winter fashion show, also known as "The Sunseeker."',
    'CHROMAKOPIA': 'Tyler\'s eighth studio album, released October 28, 2024. Explores themes of identity, legacy, and authenticity.',
    "DON'T TAP THE GLASS": 'Tyler\'s ninth studio album, released July 18, 2025.',
    'Ongoing': 'Songs without a confirmed era or still being worked on.',
    'Unknown': 'Miscellaneous material without a confirmed era.',
  },

  ALBUM_SONG_COUNTS: {},
  CUSTOM_ALBUM_INFO: {},

  ERA_MAPPINGS: {
    'Ace*': 'Ace',
    'Bastard*': 'Bastard',
    'Goblin*': 'Goblin',
    'Radical*': 'Radical',
    'Nilbog*': 'Nilbog',
    'WOLF [V1]*': 'WOLF [V1]',
    'WOLF [V2]*': 'WOLF [V2]',
    'WOLF [V3]*': 'WOLF [V3]',
    'Cherry Bomb*': 'Cherry Bomb',
    'Flower Boy*': 'Flower Boy',
    'Scum Fuck Flower Boy*': 'Scum Fuck Flower Boy',
    'IGOR*': 'IGOR',
    'CALL ME WHEN YOU GET LOST*': 'CALL ME WHEN YOU GET LOST',
    'CALL ME IF YOU GET LOST [V2]*': 'CALL ME IF YOU GET LOST [V2]',
    'At Your Own Risk [V1]*': 'At Your Own Risk [V1]',
    'At Your Own Risk [V2]*': 'At Your Own Risk [V2]',
    'CHROMAKOPIA*': 'CHROMAKOPIA',
  },

  hasCompsTab: false,
  hasConcertsTab: false,
  hasRecentTab: true,

  TAG_MAP: {
    '⭐': 'Best Of',
    '🏆': 'Grails',
    '🥇': 'Wanted',
    '🏅': 'Wanted',
    '✨': 'Notable',
    '💛': 'By WOLFgold',
    '🗑️': 'Worst Of',
    '🗑': 'Worst Of',
    '🚮': 'Unwanted',
    '🤖': 'AI',
    '⁉️': 'Lost Media',
    '⁉': 'Lost Media',
    '❓': 'Unknown',
    '⭐️': 'Best Of',
  },

  ERA_THEMES: {
    'Bastard': {},
    'Goblin': {},
    'Cherry Bomb': {},
    'Flower Boy': {},
    'Scum Fuck Flower Boy': {},
    'IGOR': {},
    'CHROMAKOPIA': {},
  },

  TAG_TOOLTIP_MAP: {
    'Best Of': 'Some of the best leaks hosted on the tracker.',
    'Grails': 'The most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as much as Grails.',
    'Notable': 'Notable songs worth highlighting.',
    'Worst Of': 'Some of the worst leaks on the tracker.',
    'Unwanted': 'Songs we don\'t want to see leak in full.',
    'AI': 'Track contains AI vocals.',
    'Lost Media': 'Currently lost, or no link to the media is known.',
    'By WOLFgold': 'Leaks & songs added by the owner of the site.',
    'Unknown': 'Availability or status is unknown.',
  },
};
