import type { ArtistConfig } from './types';

export const yzygoldConfig: ArtistConfig = {
  slug: 'yzygold',
  SITE_NAME: 'YƵYGOLD',
  SITE_DESCRIPTION: 'The Best YeTracker In The World!',
  SITE_URL: 'https://unvaulted.cc/yzygold/',
  OG_IMAGE_URL: 'https://i.ibb.co/LhXdRh7j/2026-03-23-T184041-712.png',
  STORAGE_PREFIX: 'yzygold_',
  HARDCODED_SHEET_ID: '12nGHPPh5dVTfLuBLVQYzC3QgPxKfvp-jgCoNccvEasM',
  HARDCODED_SHEET_GID: '1385926980',
  SHEET_URL_UNRELEASED: '',
  SHEET_URL_RECENT: 'https://docs.google.com/spreadsheets/d/12nGHPPh5dVTfLuBLVQYzC3QgPxKfvp-jgCoNccvEasM/export?format=csv&gid=1385926980',
  hasYeditsTab: true,
  hasCompsTab: false,
  accentColor: '#C9A224',
  artistLabel: 'Ye',
  cardLetter: 'YZY',
  logoUrl: '/logos/yzygold.png',
  artistPhotoUrl: '/artists/kanye.png',
  navLogoUrl: '/yzygold/logo.png',

  getArtistName(eraName) {
    if (!eraName) return 'Kanye West';
    const albumNames = Object.keys(this.ALBUM_RELEASE_DATES);
    const donda3Index = albumNames.indexOf('Donda [V3]');
    const eraIndex = albumNames.indexOf(eraName);
    if (donda3Index !== -1 && eraIndex !== -1 && eraIndex > donda3Index) return 'YE';
    return 'Kanye West';
  },

  CUSTOM_IMAGES: {
    "Before The College Dropout": "https://i.ibb.co/kpk9TzL/image-2026-05-04-074305465.png",
    "The College Dropout": "https://i.ibb.co/mrK8W4rL/image-2026-03-22-142639537.png",
    "Late Registration": "https://i.ibb.co/QvNMHS7f/image-2026-05-04-074325717.png",
    "Graduation": "https://i.ibb.co/gZmLyhpD/image-2026-05-04-074348808.png",
    "808s & Heartbreak": "https://i.ibb.co/gL1jHjxD/image-2026-05-04-074412180.png",
    "Good Ass Job": "https://i.ibb.co/zWDJvnF3/image-2026-05-04-074429956.png",
    "My Beautiful Dark Twisted Fantasy": "https://i.ibb.co/nMhS9cfq/image-2026-05-04-074450433.png",
    "Watch The Throne": "https://i.ibb.co/Gvh0rdt/ea89bace-a565-4fd7-aec2-de7f2a0341a2.jpg",
    "Thank God For Drugs": "https://i.ibb.co/G32JPb2w/image-2026-05-04-074528355.png",
    "Yeezus": "https://i.ibb.co/54tTPvy/YEEZUS-COVER-1-scaled.jpg",
    "Cruel Winter [V1]": "https://i.ibb.co/tPDQhJ3V/image-2026-05-04-074608802.png",
    "Yeezus 2": "https://i.ibb.co/gL2VPWGD/image-2026-05-04-074633664.png",
    "SWISH": "https://i.ibb.co/vvdd31rM/image-2026-05-04-074736182.png",
    "808s & Heartbreak: Live At The Hollywood Bowl": "https://i.ibb.co/gMW718Hb/i-made-the-808s-heartbreak-live-at-the-hollywood-bowl-on-v0-mz7y867oig3g1.webp",
    "ye": "https://i.ibb.co/4ffBbzd/0a170099-f725-41f6-88a9-c28ab2a6bdb8.jpg",
    "KIDS SEE GHOSTS": "https://i.ibb.co/xsRLz4k/28ef3e62-abba-4064-9dd7-44dd37803981.jpg",
    "KIDSSEEGHOSTS": "https://i.ibb.co/xsRLz4k/28ef3e62-abba-4064-9dd7-44dd37803981.jpg",
    "Good Ass Job (2018)": "https://i.ibb.co/Y4tB29pw/image-2026-05-04-075000044.png",
    "Yandhi [V1]": "https://api.pillows.su/api/get/45459f026801e8fbbbdf156e34d9daee",
    "Yandhi [V2]": "https://api.pillows.su/api/get/45459f026801e8fbbbdf156e34d9daee",
    "JESUS IS KING": "https://i.ibb.co/6cPT40L6/image-2026-05-04-075046079.png",
    "God's Country": "https://api.pillows.su/api/get/bf6a3725d457b7f79c3f8ada3e80b2cd",
    "JESUS IS KING: The Dr. Dre Version": "https://api.pillows.su/api/get/23ad5f0403e3cfa003973c1c6b863b55",
    "DONDA [V1]": "https://i.ibb.co/8rV5JJ3/children-park-manip-retouched.jpg",
    "Donda [V2]": "https://i.ibb.co/JjzVyMvT/image-2026-05-04-075158690.png",
    "Donda [V3]": "https://i.ibb.co/YX9xy2p/19e339a4-33e0-46ec-bd90-0e4ed62932cc.jpg",
    "Donda 2": "https://i.ibb.co/27D2fTXM/image-2026-05-04-075245507.png",
    "WAR": "https://i.ibb.co/93mVjHZV/WAR-youtube-thumbnail.png",
    "YEBU": "https://i.ibb.co/vxTD8nVh/image-2026-05-04-075337930.png",
    "Bad Bitch Playbook": "https://i.ibb.co/jknzBvyZ/image.png",
    "VULTURES 2": "https://i.ibb.co/35h4bhzG/image-2026-05-04-075431548.png",
    "VULTURES 3": "https://api.pillows.su/api/get/03c8ac234f1eb7ed59e87ef97c2f9ef5",
    "BULLY [V1]": "https://a5.mzstatic.com/us/r1000/0/Music221/v4/4b/38/d1/4b38d146-381d-ace2-73df-24074576e62b/656465138828_cover.jpg",
    "CUCK": "https://api.pillows.su/api/get/c24f4c5a0b2230ffb897cc358c15017c",
    "DONDA 2 (2025)": "https://i.ibb.co/b5ZNpDXk/cover.jpg",
    "Be": "https://i.ibb.co/RGmHbWZk/Common-Be.png",
    "IN A PERFECT WORLD": "https://i.ibb.co/Fqd2crvz/iapwcover.png",
    "BULLY [V2]": "https://a5.mzstatic.com/us/r1000/0/Music221/v4/4b/38/d1/4b38d146-381d-ace2-73df-24074576e62b/656465138828_cover.jpg",
    "The Life Of Pablo": "https://i.ibb.co/n8DkztcP/image-2026-03-22-142914834.png",
    "Wolves": "https://i.ibb.co/ydSS4sG/Wolves.png",
    "Turbo Grafx 16": "https://i.ibb.co/q3fggHMz/image-2026-03-22-143044324.png",
    "Turbo Grafix 16": "https://i.ibb.co/q3fggHMz/image-2026-03-22-143044324.png",
    "TurboGrafx 16": "https://i.ibb.co/q3fggHMz/image-2026-03-22-143044324.png",
    "TurboGrafix 16": "https://i.ibb.co/q3fggHMz/image-2026-03-22-143044324.png",
    "TurboGrafx16": "https://i.ibb.co/q3fggHMz/image-2026-03-22-143044324.png",
    "The Elementary School Dropout": "https://i.ibb.co/Z1RZYGWw/image-2026-03-22-143132521.png",
    "LOVE EVERYONE": "https://i.ibb.co/Tq7HkRKn/cell-Image-199908479-18.png",
    "Cruel Summer": "https://i.ibb.co/wr7sS6DH/cell-Image-199908479-8.png",
    "So Help Me God": "https://i.ibb.co/Lz3b2xDD/cell-Image-199908479-13.png",
    "VULTURES 1": "https://i.ibb.co/5hFN28jM/cell-Image-199908479-37.png",
    "Cruel Winter [V2]": "https://i.ibb.co/bjFdyLjv/image-2026-04-28-131805413.png",
    "Ongoing": "https://i.ibb.co/dwZ4cwmd/image-2026-04-27-185921217.png",
    "DAYTONA": "https://i.ibb.co/1fX0N137/Daytona.jpg",
    "NASIR": "https://a5.mzstatic.com/us/r1000/0/Music125/v4/f9/41/a9/f941a9d4-099d-4b65-484a-e585136ca838/18UMGIM37154.rgb.jpg",
    "K.T.S.E.": "https://i.ibb.co/rfZM2kCp/K-T-S-E.jpg",
    "NEVER STOP": "https://i.ibb.co/vC9c5qFM/never-stop.png",
    "Jesus Is Born": "https://api.pillows.su/api/get/61be2288632189d710fc6865f5efd9c7",
    "Sunday Service Choir": "https://i.ibb.co/nN2LDSxN/SSC.jpg",
    "Late Orchestration": "https://i.ibb.co/whrYVzkr/Late-Orchestration.jpg",
    "Child Rebel Soldier": "https://i.ibb.co/QFLpkFcz/IMG-3998.png",
    "BULLY": "https://a5.mzstatic.com/us/r1000/0/Music221/v4/4b/38/d1/4b38d146-381d-ace2-73df-24074576e62b/656465138828_cover.jpg",
    "Live": "https://i.ibb.co/zhhhyDVq/hq720.jpg",
    "Other": "https://i.ibb.co/G3VqQV3t/IMG-3890.jpg",
    "YE-I": "https://i.ibb.co/Z6HqbBph/IMG-4069.jpg",
  },

  ALBUM_RELEASE_DATES: {
    "Before The College Dropout": "??/??/????",
    "The College Dropout": "02/10/2004",
    "Late Registration": "08/30/2005",
    "Graduation": "09/11/2007",
    "808s & Heartbreak": "11/24/2008",
    "Good Ass Job": "??/??/2009",
    "My Beautiful Dark Twisted Fantasy": "11/22/2010",
    "Watch The Throne": "08/08/2011",
    "Cruel Summer": "09/14/2012",
    "Thank God For Drugs": "??/??/2012",
    "Yeezus": "06/18/2013",
    "Cruel Winter [V1]": "??/??/2013",
    "Yeezus 2": "??/??/2014",
    "So Help Me God": "??/??/????",
    "SWISH": "??/??/2015",
    "The Life Of Pablo": "02/14/2016",
    "Cruel Winter [V2]": "??/??/????",
    "Wolves": "??/??/2016",
    "Turbo Grafx 16": "??/??/2016",
    "LOVE EVERYONE": "??/??/2018",
    "DAYTONA": "05/25/2018",
    "ye": "06/01/2018",
    "KIDS SEE GHOSTS": "06/08/2018",
    "NASIR": "06/15/2018",
    "K.T.S.E.": "06/23/2018",
    "Good Ass Job (2018)": "??/??/2018",
    "Yandhi [V1]": "??/??/2018",
    "Yandhi [V2]": "??/??/????",
    "JESUS IS KING": "10/25/2019",
    "Jesus Is Born": "12/25/2019",
    "God's Country": "??/??/????",
    "JESUS IS KING: The Dr. Dre Version": "??/??/????",
    "DONDA [V1]": "07/18/2020",
    "Donda [V2]": "??/??/????",
    "Donda [V3]": "08/29/2021",
    "Donda 2": "??/??/????",
    "WAR": "04/01/2022",
    "YEBU": "??/??/????",
    "Bad Bitch Playbook": "??/??/2023",
    "VULTURES 1": "02/10/2024",
    "VULTURES 2": "08/03/2024",
    "The Elementary School Dropout": "03/10/2024",
    "VULTURES 3": "??/??/????",
    "BULLY [V1]": "03/18/2025",
    "CUCK": "03/06/2025",
    "DONDA 2 (2025)": "04/29/2025",
    "NEVER STOP": "06/27/2025",
    "IN A PERFECT WORLD": "06/22/2025",
    "BULLY [V2]": "03/28/2026",
    "Ongoing": "??/??/????",
    "YE-I": "10/16/2023",
  },

  HIDDEN_ALBUMS: ['NASIR', 'K.T.S.E.', 'NEVER STOP', 'DAYTONA', 'The Elementary School Dropout', 'Jesus Is Born', 'Sunday Service Choir', 'YE-I'],

  ALBUM_DESCRIPTIONS: {
    "DAYTONA": "DAYTONA is the third studio album by American rapper Pusha T, executive produced by Kanye West. Released May 25, 2018 as one of the Wyoming projects.",
    "Before The College Dropout": "Before Kanye released his first album to critical acclaim in 2004, he pursued many other projects, including a rap trio group named the \"Go Getters\" and production for other rappers. Two years before the release of The College Dropout, Kanye began releasing a series of mixtapes.",
    "The College Dropout": "Following his signing to Roc-A-Fella Records, Kanye released his debut studio album, The College Dropout. It features string arrangements, choirs, and his signature soul sampling, frequently branded as \"chipmunk soul\".",
    "Late Registration": "Late Registration continues the social themes introduced in The College Dropout, but now with orchestral production influenced by co-producer Jon Brion.",
    "Graduation": "Graduation is the third studio album from Kanye West, featuring a much more electronic sound with layering synthesizers.",
    "808s & Heartbreak": "Following the death of his mother and a breakup, Kanye channeled his pain into a sonically stripped-down album dominated by the Roland TR-808 drum machine and Auto-Tune.",
    "Good Ass Job": "The long-planned fourth album in Kanye's college dropout series, never officially released.",
    "My Beautiful Dark Twisted Fantasy": "Conceived during West's self-imposed exile following the 2009 VMA incident, MBDTF is a genre-bending masterpiece earning a rare 10/10 from Pitchfork.",
    "Watch The Throne": "Considered one of the most legendary collab albums of all time, Watch The Throne puts together JAY-Z and Kanye for a full studio album focused on luxury and black excellence.",
    "Cruel Summer": "A compilation of new songs from Kanye's label G.O.O.D. Music, featuring collaborations with Pusha T, Big Sean, 2 Chainz, and marking the first time Kanye worked with Travis Scott.",
    "Thank God For Drugs": "Before Kanye chose the name Yeezus, the album was called Thank God For Drugs with around 3.5 hours of rough material.",
    "Yeezus": "Yeezus marked a complete reverse from MBDTF, swapping lush soul for splintering electro, acid house, and industrial force.",
    "Cruel Winter [V1]": "The 2013 version of Cruel Winter, the first version of the sequel to Cruel Summer, featuring many songs with A Tribe Called Quest member Q-Tip.",
    "Yeezus 2": "After Yeezus was released, Kanye saw potential in cut material and new songs, developing them into a full-fledged follow-up.",
    "So Help Me God": "Announced in February 2015, So Help Me God is one of Kanye's most infamous unreleased projects, featuring \"Wolves,\" \"All Day,\" and \"Only One.\"",
    "SWISH": "After changing the album name from So Help Me God to SWISH, Kanye developed all new songs throughout mid-late 2015.",
    "The Life Of Pablo": "Kanye's 7th studio album, sporadic and scatter-shot, released initially only on TIDAL.",
    "Cruel Winter [V2]": "After the 2013 rendition ended, Kanye revived Cruel Winter in 2016 with trap elements and big music stars.",
    "Wolves": "A planned collaboration album between Kanye West and Drake, reportedly finished but never released.",
    "Turbo Grafx 16": "Immediately after TLOP, Kanye announced a whole new album titled Turbo Grafx 16, intending a futuristic video game sound.",
    "LOVE EVERYONE": "After being released from UCLA Medical Hospital and diagnosed as bipolar, Kanye bought a ranch in Wyoming and began working on new material.",
    "ye": "ye discusses topics in Kanye's life, including mental health, family, and addiction, and includes his explicit announcement of bipolar disorder.",
    "KIDS SEE GHOSTS": "Out of the five Wyoming projects from 2018, KIDS SEE GHOSTS (with Kid Cudi) is one of the best, focusing on overcoming mental health struggles.",
    "Good Ass Job (2018)": "Kanye and Chance collab project that was announced in 2018, seven tracks long, eventually cancelled around 2019.",
    "Yandhi [V1]": "Upon hearing the beat to \"Hurricane,\" Kanye became inspired to create Yandhi, aiming for a September 29 release that never happened.",
    "Yandhi [V2]": "After Kanye delayed Yandhi indefinitely, he began working with Timbaland and underwent a dramatic conversion toward evangelical Christianity.",
    "JESUS IS KING": "Following a revelation on Easter 2019, Kanye scrapped Yandhi and reworked it to focus on God and Christianity.",
    "Jesus Is Born": "The first and only album from the Sunday Service Choir, released on Christmas Day 2019, featuring interpolations of other songs.",
    "God's Country": "Shortly after JESUS IS KING, Kanye immediately started working on new material revolving around faith and dark themes.",
    "JESUS IS KING: The Dr. Dre Version": "Initially conceived as a remix album, this collaborative project with Dr. Dre grew to incorporate mainly unreleased material before being scrapped.",
    "DONDA [V1]": "With inspiration to make an album dedicated to his mother, Kanye created music during his mania while running for President.",
    "Donda [V2]": "After taking a break in early 2021, Kanye worked at the Pio Pico studio in LA with an entirely new vision for the album.",
    "Donda [V3]": "Almost a year after the initial announcement, Donda finally released on August 29, 2021 at 8AM EST, two days after the final listening party.",
    "Donda 2": "Announced by Ye via Instagram, executive produced by Future. Released on the Stem Player but remained incomplete.",
    "WAR": "A collaborative project between Ye and James Blake. Sessions began April 2022 and were presumably scrapped amid Ye's controversies.",
    "YEBU": "Following Ye's numerous controversies, he went silent for months and began working on new material in Italy.",
    "Bad Bitch Playbook": "Ye and Ty Dolla $ign collaborated frequently, hinting at a joint project before the name changed to VULTURES.",
    "VULTURES 1": "After the album's name change from Bad Bitch Playbook, four listening parties were held before release on February 10, 2024.",
    "VULTURES 2": "Announced alongside VULTURES 1 and 3, VULTURES 2 finally dropped August 3, 2024 after multiple failed release dates.",
    "VULTURES 3": "Announced alongside the other VULTURES volumes, thought to be scrapped after the rushed VULTURES 2 release.",
    "BULLY [V1]": "Ye's solo album announced September 28, 2024 in South Korea, featuring AI vocals that Ye promised to re-record.",
    "CUCK": "On March 6, 2025, Ye tweeted \"this next album got that antisemitic sound,\" marking a shift in his soundscape.",
    "DONDA 2 (2025)": "After releasing Donda 2 via the Stem Player in 2022, Ye revisited the project in 2025 to officially finish and release it.",
    "IN A PERFECT WORLD": "After denouncing his antisemitism on Twitter in May 2025, Ye announced another album name change to \"In A Perfect World.\"",
    "BULLY [V2]": "After promising to re-record all AI vocals, BULLY V2 finally dropped March 28, 2026, though some AI remained.",
    "Ongoing": "",
    "YE-I": "Fully AI album made by damn james! and Gabe Shaddow in October 2023, unknown to Ye until November 2025.",
  },

  ALBUM_SONG_COUNTS: {
    "Before The College Dropout": 118,
    "The College Dropout": 114,
    "Late Registration": 65,
    "Graduation": 101,
    "808s & Heartbreak": 127,
    "Good Ass Job": 264,
    "My Beautiful Dark Twisted Fantasy": 130,
    "Watch The Throne": 88,
    "Cruel Summer": 104,
    "Thank God For Drugs": 215,
    "Yeezus": 38,
    "Cruel Winter [V1]": 21,
    "Yeezus 2": 331,
    "So Help Me God": 183,
    "SWISH": 156,
    "The Life Of Pablo": 140,
    "Cruel Winter [V2]": 31,
    "Wolves": 18,
    "Turbo Grafx 16": 93,
    "LOVE EVERYONE": 147,
    "DAYTONA": 82,
    "ye": 84,
    "KIDS SEE GHOSTS": 31,
    "NASIR": 9,
    "K.T.S.E.": 34,
    "Good Ass Job (2018)": 61,
    "Yandhi [V1]": 307,
    "Yandhi [V2]": 369,
    "JESUS IS KING": 392,
    "God's Country": 493,
    "JESUS IS KING: The Dr. Dre Version": 38,
    "DONDA [V1]": 446,
    "Donda [V2]": 342,
    "Donda [V3]": 539,
    "Donda 2": 846,
    "WAR": 79,
    "YEBU": 175,
    "Bad Bitch Playbook": 272,
    "VULTURES 1": 321,
    "VULTURES 2": 293,
    "The Elementary School Dropout": 18,
    "VULTURES 3": 30,
    "BULLY [V1]": 214,
    "CUCK": 296,
    "DONDA 2 (2025)": 81,
    "NEVER STOP": 18,
    "IN A PERFECT WORLD": 154,
    "BULLY [V2]": 93,
    "Ongoing": 1,
  },

  CUSTOM_ALBUM_INFO: {},

  ERA_MAPPINGS: {
    "Turbo Grafix 16": "Turbo Grafx 16",
    "BULLY": "BULLY [V1]",
    "Bully": "BULLY [V1]",
    "Donda [V1]": "DONDA [V1]",
  },

  TAG_MAP: {
    '⭐': 'Best Of',
    '🏆': 'Grails',
    '🥇': 'Wanted',
    '🏅': 'Wanted',
    '✨': 'Special',
    '💛': 'By YƵYGOLD',
    '🗑️': 'Worst Of',
    '🗑': 'Worst Of',
    '🚮': 'Unwanted',
    '🤖': 'AI',
    '⁉️': 'Lost Media',
    '⁉': 'Lost Media',
    '❓': 'Unknown',
  },

  ERA_THEMES: {
    "The College Dropout": {
      topBanner: "/yzygold/TopBannerTCD.png",
      bottomBanner: "/yzygold/BottomBannerTCD.png",
      miniPlayer: "/yzygold/MiniPlayerTCD.png",
      fullPicturePlayer: "/yzygold/FullPicturePlayerTCD.png",
    },
    "Graduation": {
      topBanner: "/yzygold/TopBannerGraduation.png",
      bottomBanner: "/yzygold/BottomBannerGraduation.png",
      miniPlayer: "/yzygold/MiniPlayerGraduation.png",
      fullPicturePlayer: "/yzygold/FullPicturePlayerGraduation.png",
    },
    "Yandhi [V1]": {
      topBanner: "/yzygold/TopBannerYandhi.png",
      bottomBanner: "/yzygold/BottomBannerYandhi.png",
      miniPlayer: "/yzygold/MiniPlayerYandhi.png",
      fullPicturePlayer: "/yzygold/FullPicturePlayerYandhi.png",
    },
    "Yandhi [V2]": {
      topBanner: "/yzygold/TopBannerYandhi.png",
      bottomBanner: "/yzygold/BottomBannerYandhi.png",
      miniPlayer: "/yzygold/MiniPlayerYandhi.png",
      fullPicturePlayer: "/yzygold/FullPicturePlayerYandhi.png",
    },
  },

  TAG_TOOLTIP_MAP: {
    'Best Of': 'some of the best leaks hosted on the tracker.',
    'Grails': 'the most wanted songs that have not yet leaked in full.',
    'Wanted': 'Songs that are wanted, but not as wanted as "Grails".',
    'Special': 'special songs that are not good enough to be in Best Of, but still deserves to be highlighted.',
    'Worst Of': 'some of the worst leaks hosted on the tracker.',
    'Unwanted': "Songs that we don't want to leak in full.",
    'AI': 'Track contains AI vocals.',
    'Lost Media': "Is currently lost, or we don't have a link to the media.",
    'By YƵYGOLD': 'Leaks & Songs that added by the owner of the site.',
  },
};
