// AUTO-GENERATED by scripts/build-socials.py — do not edit by hand.
// Source: ~/Downloads/socials/*.csv

export interface SocialEntry {
  platform: string;
  handle: string;
  notes: string;
  type: string;
  status: string;
  link: string;
}

export const SOCIALS_DATA: Record<string, SocialEntry[]> = {
  "aapgold": [
    {
      "platform": "Amazon Music",
      "handle": "A$AP Rocky",
      "notes": "Subscription based streaming platform where A$AP Rocky's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.amazon.com/artists/B00697GXC2/a-ap-rocky"
    },
    {
      "platform": "Apple Music",
      "handle": "A$AP Rocky",
      "notes": "Subscription based streaming platform where A$AP Rocky's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.apple.com/us/artist/a%24ap-rocky/481488005"
    },
    {
      "platform": "Deezer",
      "handle": "A$AP Rocky",
      "notes": "Subscription based streaming platform where A$AP Rocky's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://www.deezer.com/us/artist/1518490"
    },
    {
      "platform": "Facebook",
      "handle": "ASAP Rocky",
      "notes": "A$AP Rocky's official Facebook page.",
      "type": "Social Media",
      "status": "",
      "link": "https://www.facebook.com/asaprocky?mibextid=LQQJ4d"
    },
    {
      "platform": "Instagram",
      "handle": "asaprocky",
      "notes": "A$AP Rocky's official Instagram page.",
      "type": "Social Media",
      "status": "",
      "link": "https://www.instagram.com/asaprocky?igsh=eXh0NTl5M2ZucjJo"
    },
    {
      "platform": "SoundCloud",
      "handle": "A$AP Rocky",
      "notes": "Subscription based streaming platform where A$AP Rocky's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://on.soundcloud.com/yueYBbBMuoSunNBG7"
    },
    {
      "platform": "Spotify",
      "handle": "A$AP Rocky",
      "notes": "Subscription based streaming platform where A$AP Rocky's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://spotify.link/ayn5jdTPwJb"
    },
    {
      "platform": "Tidal",
      "handle": "A$AP Rocky",
      "notes": "Subscription based streaming platform where A$AP Rocky's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://tidal.com/browse/artist/4315444"
    },
    {
      "platform": "Tumblr",
      "handle": "flackojodyeseason",
      "notes": "A$AP Rocky's temporary Tumblr account where he promoted the release of \"AT.LONG.LAST.A$AP\".",
      "type": "Social Media",
      "status": "",
      "link": "https://flackojodyeseason.tumblr.com/"
    },
    {
      "platform": "𝕏",
      "handle": "asvpxrocky",
      "notes": "A$AP Rocky's official X/Twitter page.",
      "type": "Social Media",
      "status": "",
      "link": "https://x.com/asvpxrocky?s=21&t=uh-P73EpzF3y1U7fbAfMXQ"
    },
    {
      "platform": "YouTube",
      "handle": "ASAPROCKYUPTOWN",
      "notes": "A$AP Rocky's official YouTube channel where a variety of videos can be found, most notably music videos.",
      "type": "Other",
      "status": "",
      "link": "https://youtube.com/@ASAPROCKYUPTOWN?si=kMO_ztGLUwjmEomY"
    },
    {
      "platform": "YouTube Music",
      "handle": "A$AP Rocky",
      "notes": "Subscription based streaming platform where A$AP Rocky's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.youtube.com/channel/UCsfPXoStha2wqN8hB9dFR2g"
    },
    {
      "platform": "Website",
      "handle": "asaprocky",
      "notes": "A$AP Rocky's website where promotion for the artist can be found.",
      "type": "Other",
      "status": "",
      "link": "https://asaprocky.com"
    },
    {
      "platform": "Reddit",
      "handle": "asaprocky",
      "notes": "A$AP Rocky's official Reddit account where he promoted the release of singles \"HIGHJACK\" and \"Ruby Rosary, as well as his fourth studio album \"DON'T BE DUMB\"",
      "type": "Social Media",
      "status": "",
      "link": "https://www.reddit.com/user/asaprocky/"
    },
    {
      "platform": "Amazon Music",
      "handle": "A$AP Mob",
      "notes": "Subscription based streaming platform where the A$AP Mob's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://www.amazon.com/music/player/artists/B00H2ZPB3W/a-ap-mob"
    },
    {
      "platform": "Apple Music",
      "handle": "A$AP Mob",
      "notes": "Subscription based streaming platform where the A$AP Mob's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.apple.com/us/artist/a%24ap-mob/560677601"
    },
    {
      "platform": "Deezer",
      "handle": "A$AP Mob",
      "notes": "Subscription based streaming platform where the A$AP Mob's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://www.deezer.com/us/artist/5392341"
    },
    {
      "platform": "Facebook",
      "handle": "ASAP Mob",
      "notes": "A$AP Mob's official Facebook page.",
      "type": "Social Media",
      "status": "",
      "link": "https://m.facebook.com/asapmobofficial/"
    },
    {
      "platform": "Instagram",
      "handle": "asapmob",
      "notes": "A$AP Mob's official Instagram page.",
      "type": "Social Media",
      "status": "",
      "link": "https://www.instagram.com/asapmob/?hl=en"
    },
    {
      "platform": "SoundCloud",
      "handle": "ASAPMob",
      "notes": "Subscription based streaming platform where the A$AP Mob's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://on.soundcloud.com/GN6w2xE81PBC9w9y9"
    },
    {
      "platform": "SoundCloud",
      "handle": "AWGE",
      "notes": "AWGE SoundCloud account in which songs for \"Wavy Wednesdays\" and \"DUMMIE\" were released.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://m.soundcloud.com/awgeshit"
    },
    {
      "platform": "Spotify",
      "handle": "A$AP Mob",
      "notes": "Subscription based streaming platform where the A$AP Mob's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://open.spotify.com/artist/7yO4IdJjCEPz7YgZMe25iS"
    },
    {
      "platform": "Tidal",
      "handle": "A$AP Mob",
      "notes": "Subscription based streaming platform where the A$AP Mob's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://tidal.com/browse/artist/5588071"
    },
    {
      "platform": "Tumblr",
      "handle": "LONGLIVEA$AP",
      "notes": "Old official A$AP Mob Tumblr account where updates on everything related to the A$AP Mob was posted.",
      "type": "Social Media",
      "status": "",
      "link": "https://longliveasap-blog-blog.tumblr.com/"
    },
    {
      "platform": "𝕏",
      "handle": "ASAPMOB",
      "notes": "A$AP Mob's official X page.",
      "type": "Social Media",
      "status": "",
      "link": "https://x.com/asapmob?s=21&t=uh-P73EpzF3y1U7fbAfMXQ"
    },
    {
      "platform": "YouTube",
      "handle": "ASAP Mob",
      "notes": "A$AP Mob's official YouTube channel where music videos can be found.",
      "type": "Other",
      "status": "",
      "link": "https://youtube.com/@asapmobofficial?si=2kB-dOMCRRHT5THz"
    },
    {
      "platform": "YouTube Music",
      "handle": "A$AP Mob",
      "notes": "Subscription based streaming platform where the A$AP Mob's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.youtube.com/channel/UCaMXFCQMOS0pNxJsOoShTgA"
    },
    {
      "platform": "Website",
      "handle": "asapmob",
      "notes": "A$AP Mob's website where updates on all A$AP Mob members can be found.",
      "type": "Other",
      "status": "",
      "link": "https://www.asapmob.com"
    },
    {
      "platform": "Website",
      "handle": "awge",
      "notes": "AWGE website where you can buy merchandise and watch AWGE DVDs among other things.",
      "type": "Other",
      "status": "",
      "link": "https://awge.com"
    }
  ],
  "wolfgold": [
    {
      "platform": "MySpace",
      "handle": "tylerthecreator (Radio Arcade)",
      "notes": "Tyler's earliest MySpace page, technically an alt page. Originally used to be the Radio Arcade page. (Dec 6, 2005 - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "imaginace (Tyler, The Creator!)",
      "notes": "Tyler's main MySpace page. (Feb 21, 2006 - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "thrashpolo (Tyler, The Creator!)",
      "notes": "Another alt page, has a poll asking \"Your Favorite Sound\" (Feb 21, 2006 - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "acethecreator (Ace, The Creator)",
      "notes": "Another alt page. (Mar 18, 2007 - Oct 23, 2008)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "soundonacid (Poly/Mono)",
      "notes": "Poly/Mono MySpace page. (June 26, 2007 - Feb 12, 2009)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "HYPEBEAST",
      "handle": "bloxheads",
      "notes": "Tyler's Hypebeast Forums account, where he used to post his music back in the day (Comrade Creator, BASTARD, etc.) (Feb 2008 - Aug 31, 2017)",
      "type": "Social Media",
      "status": "",
      "link": "https://web.archive.org/web/20130329064726/http://hypebeast.com/members/bloxheads"
    },
    {
      "platform": "YouTube",
      "handle": "bloxhead (I Smell Panties)",
      "notes": "YouTube account owned by Tyler & Jasper (Bon Bon). Was once the I Smell Panties YouTube. (Jun 25, 2006 - Oct 24, 2009)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.youtube.com/@bloxhead"
    },
    {
      "platform": "YouTube",
      "handle": "tylercreator",
      "notes": "Burner account, has the Bastard music video & a recording of the House of Blues show. (Dec 7, 2008 - Jul 16, 2011)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "𝕏",
      "handle": "tylerthecreator (fucktyler)",
      "notes": "(Jul 2010 - Present)",
      "type": "Social Media",
      "status": "",
      "link": "https://x.com/tylerthecreator"
    },
    {
      "platform": "𝕏",
      "handle": "freeperm",
      "notes": "Private Twitter, archived in its entirety in the Freeperm archive. (Jul 19, 2011 - Sep 19, 2016)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Instagram",
      "handle": "stankdady",
      "notes": "Tyler's old burner instagram account, it has approximatively six thousand posts. Nothing else is known about it. (2012-2016)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Instagram",
      "handle": "feliciathegoat",
      "notes": "(Nov 2012 - Present)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.instagram.com/feliciathegoat/#"
    },
    {
      "platform": "Tumblr",
      "handle": "deadsams",
      "notes": "Burner account, made \"just to look at all the photos on my computer at once when playing music\". Password is supposedly Tyler's favorite word. (2012 - 2013)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.tumblr.com/blog_auth/deadsams"
    },
    {
      "platform": "Instagram",
      "handle": "scumfuckflowerboy",
      "notes": "Tyler's burner Instagram account. From 2016 to 2017, Tyler would post a lot of snippets from the Flower Boy sessions and such more. He would make it public on Flower Boy's one year anniversary in 2018, the account gets posted on from time to time. (April 2016 - Present)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.instagram.com/scumfuckflowerboy"
    },
    {
      "platform": "YouTube",
      "handle": "Tyler, The Creator",
      "notes": "(Oct 1, 2016 - Present)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Discord",
      "handle": "bm200902",
      "notes": "NOTICE: WE DO NOT ENCOURAGE YOU TRY TO CONTACT Tyler's burner Discord, originally discovered by Horse, made to spy on the unreleased community. Found out because when Horse got a cease & desist from SME, screenshots were provided that were taken by that account (I believe there was more to it that linked Tyler to it, but I don't remember). This account used to lurk is a Neptunes fan server (screenshots are had). Most recent activity is joining a groupbuy server for I Dream + Herpes & Cupcakes [BOTH FAKE], before being banned by an admin. The story that \"...he then left when they realized they were being scammed, and the groupbuy was for Al material he'd never made\" is false. \"hi hi hi\" - bm (Oct 26, 2020 - 2025)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Instagram",
      "handle": "chromakopiavision",
      "notes": "Possible unused Instagram burner that could've been used for some sort of promotion, account hasn't posted a single thing. (September 2024 - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Instagram",
      "handle": "chromakopia",
      "notes": "Official Instagram for the album CHROMAKOPIA. (May 2024 - Feb 25, 2025)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Instagram",
      "handle": "donttaptheglass",
      "notes": "Official Instagram for the album DON'T TAP THE GLASS. (June - Sep 9, 2025)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "oddfuture",
      "notes": "Official MySpace for Odd Future, has interviews & such. (Sep 11, 2006 - ???)",
      "type": "Social Media",
      "status": "",
      "link": "https://web.archive.org/web/20121227225013/myspace.com/oddfuture"
    },
    {
      "platform": "YouTube",
      "handle": "OFWGKTA",
      "notes": "(Jan 4, 2010 - Sep 17, 2019)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.youtube.com/@OFWGKTA"
    },
    {
      "platform": "YouTube",
      "handle": "6GOLF6WANG6",
      "notes": "Burner account. (Dec 31, 2010 - Feb 18, 2012)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.youtube.com/@6GOLF6WANG6"
    },
    {
      "platform": "Tumblr",
      "handle": "GOLF WANG",
      "notes": "Golf Wang's official Tumblr page. (Sep 11, 2010 - Feb 13, 2019)",
      "type": "Social Media",
      "status": "",
      "link": "https://golfwang.tumblr.com"
    },
    {
      "platform": "Website",
      "handle": "Golf Wang",
      "notes": "Golf Wang's official website. (2011 - Present)",
      "type": "Other",
      "status": "",
      "link": "https://golfwang.com"
    },
    {
      "platform": "Instagram",
      "handle": "golfwang",
      "notes": "Golf Wang's official Instagram page. (July 2014 - Present)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.instagram.com/golfwang/"
    },
    {
      "platform": "Instagram",
      "handle": "lefleur",
      "notes": "GOLF le FLEUR's official Instagram page. (February 2019 - Present)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.instagram.com/lefleur/#"
    },
    {
      "platform": "Website",
      "handle": "GOLF le FLEUR*",
      "notes": "GOLF le FLEUR's official website. (2019 - Present)",
      "type": "Other",
      "status": "",
      "link": "https://golflefleur.com/"
    },
    {
      "platform": "YouTube",
      "handle": "GOLF le FLEUR*",
      "notes": "GOLF le FLEUR's official YouTube page. (Apr 29, 2021 - Present)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.youtube.com/@golflefleur"
    },
    {
      "platform": "imeem",
      "handle": "thecreator",
      "notes": "Tyler's imeem account, has the following tracks: \"Gloomy Radio\" \"Eargasm\" \"April Fools\" \"909\" \"Hustla Remix\" \"Odd Remix\" \"Celery Sticks\" \"Dope Dealer\" \"Highliter\" \"Herpes INstrumental\" (Supersonic) (??? - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "bloxhead (Team Blox)",
      "notes": "Another alt page, private. (??? - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "aceboxx",
      "notes": "Known to exist, but doesn't have a working archive. (??? - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "arcadetherapy",
      "notes": "Radio Arcade MySpace page, unfortunately lost. (??? - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "MySpace",
      "handle": "aradioarcade",
      "notes": "Radio Arcade MySpace page, unfortunately lost. (??? - ???)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "SoundCloud",
      "handle": "Wolf Haley (Tyler Creator)",
      "notes": "Burner account, had three songs at one point: \"Fuck This Christmas\", \"Dem Hoes\", & \"Let's Dance\". (??? - ???)",
      "type": "Streaming Service",
      "status": "",
      "link": "https://soundcloud.com/wolf-haley"
    },
    {
      "platform": "Website",
      "handle": "rockyandtyler.com",
      "notes": "Official website for the Rocky and Tyler Tour. (??? - ???)",
      "type": "Other",
      "status": "",
      "link": ""
    },
    {
      "platform": "TikTok",
      "handle": "CHROMAKOPIA",
      "notes": "Burner account for CHROMAKOPIA, has a snippet of \"Tomorrow\". (??? - ???)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.tiktok.com/@chromakopia?is_from_webapp=1&sender_device=pc"
    },
    {
      "platform": "TikTok",
      "handle": "DON'T TAP THE GLASS",
      "notes": "Burner account for DON'T TAP THE GLASS. (??? - ???)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.tiktok.com/@donttaptheglass?is_from_webapp=1&sender_device=pc"
    }
  ],
  "drizzygold": [
    {
      "platform": "Amazon Music",
      "handle": "Drake",
      "notes": "Subscription based streaming platform where Drake's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.amazon.com/artists/B001E72M5Y/drake"
    },
    {
      "platform": "Apple Music",
      "handle": "Drake",
      "notes": "Subscription based streaming platform where Drake's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.apple.com/us/artist/drake/271256"
    },
    {
      "platform": "Deezer",
      "handle": "Drake",
      "notes": "Subscription based streaming platform where Drake's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://www.deezer.com/en/artist/246791"
    },
    {
      "platform": "Facebook",
      "handle": "Drake",
      "notes": "Drake's official Facebook page.",
      "type": "Social Media",
      "status": "",
      "link": "http://facebook.com/drake"
    },
    {
      "platform": "Instagram",
      "handle": "champagnepapi",
      "notes": "Drake's official Instagram page.",
      "type": "Social Media",
      "status": "",
      "link": "https://www.instagram.com/champagnepapi/?hl=en"
    },
    {
      "platform": "SoundCloud",
      "handle": "octobersveryown",
      "notes": "Subscription based streaming platform where Drake's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://soundcloud.com/octobersveryown"
    },
    {
      "platform": "Spotify",
      "handle": "Drake",
      "notes": "Subscription based streaming platform where Drake's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4?si=goeqCkG8RA--F8sH_peL3g"
    },
    {
      "platform": "TIDAL",
      "handle": "Drake",
      "notes": "Subscription based streaming platform where Drake's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://tidal.com/browse/artist/3632070"
    },
    {
      "platform": "𝕏",
      "handle": "drake",
      "notes": "Drake's official X page.",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/drake"
    },
    {
      "platform": "YouTube",
      "handle": "Drake",
      "notes": "Drake's official YouTube channel where music videos, interviews and live performances can be found.",
      "type": "Misc",
      "status": "",
      "link": "https://www.youtube.com/@DrakeOfficial"
    },
    {
      "platform": "YouTube Music",
      "handle": "Drake",
      "notes": "Subscription based streaming platform where Drake's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.youtube.com/channel/UCU6cE7pdJPc6DU2jSrKEsdQ"
    },
    {
      "platform": "SiriusXM",
      "handle": "Sound 42",
      "notes": "Drake's official radio station, hosted on SiriusXM.",
      "type": "Radio",
      "status": "",
      "link": "https://www.siriusxm.com/channels/sound-42"
    },
    {
      "platform": "Website",
      "handle": "Drake Related",
      "notes": "Drake's official website.",
      "type": "Website",
      "status": "",
      "link": "https://www.drakerelated.com"
    },
    {
      "platform": "Facebook",
      "handle": "OVO Sound",
      "notes": "OVO Sound's official Facebook page.",
      "type": "Social Media",
      "status": "",
      "link": "http://facebook.com/ovosound"
    },
    {
      "platform": "Instagram",
      "handle": "ovosound",
      "notes": "OVO Sound's official Instagram page.",
      "type": "Social Media",
      "status": "",
      "link": "https://www.instagram.com/ovosound/?hl=en"
    },
    {
      "platform": "𝕏",
      "handle": "OVOSound",
      "notes": "Drake's official X page.",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/ovosound"
    },
    {
      "platform": "Merch",
      "handle": "ovosound.shop",
      "notes": "OVO Sound's official merch store.",
      "type": "Website",
      "status": "",
      "link": "https://www.ovosound.shop"
    },
    {
      "platform": "Website",
      "handle": "OVO Sound",
      "notes": "OVO Sound's official website ran by the company itself.",
      "type": "Website",
      "status": "",
      "link": "https://www.ovosound.com"
    }
  ],
  "jojigold": [
    {
      "platform": "Vine",
      "handle": "Filthy Frank",
      "notes": "Filthy Frank Vine account. The Vine compilations sourced their videos from this account. Deleted in 2014 before any mass Vine archives were made. (2013)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Vine",
      "handle": "M E M E gonzales",
      "notes": "A second account announces on his instagram.",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Twitter / X",
      "handle": "sushitrash",
      "notes": "Joji's official Twitter / X profile.",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "Joji",
      "notes": "Joji's official YouTube profile.",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "2cool4u92",
      "notes": "(Oct 17, 2006)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "jamestravis92",
      "notes": "(Jun 25, 2008)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "AussieAsianBoyz",
      "notes": "(Jul 9, 2008)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "JapanWalkers",
      "notes": "(May 23, 2009)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "hahaglolmoo",
      "notes": "(May 27, 2010)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "NoodleManyne aka. RukussMC",
      "notes": "(Jul 20, 2010)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "StupidGeorgie",
      "notes": "(Jun 19, 2012)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "NoodleMayne",
      "notes": "A second NoodleMayne profile. (Jun 9, 2014)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "MerryChristmasShinji",
      "notes": "(Dec 15, 2011)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Vimeo",
      "handle": "jennyhashimoto",
      "notes": "Joji's official Vimeo profile. (Nov 18, 2014)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "DizastaMusic",
      "notes": "(Mar 8, 2015)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "anna gold aka. CollegeFoodPorn",
      "notes": "(Jan 13, 2016)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "TooDamnFilthy",
      "notes": "(Jan 13, 2017)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "TVFilthyFrank",
      "notes": "(Sep 27, 2017)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "TikTok",
      "handle": "Joji",
      "notes": "Joji's official TikTok profile.",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "jojivlogs",
      "notes": "(May 3, 2014)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "Cosmochino",
      "notes": "(Jun 6, 2006)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Instagram",
      "handle": "sushitrash",
      "notes": "Joji's official Instagram profile.",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "WhatsApp",
      "handle": "",
      "notes": "Joji's official WhatsApp channel (2025)",
      "type": "Channel",
      "status": "",
      "link": ""
    },
    {
      "platform": "Facebook",
      "handle": "jojikansai",
      "notes": "Joji's official Facebook profile. (Aug 28, 2023)",
      "type": "Social Media",
      "status": "",
      "link": ""
    },
    {
      "platform": "Bandcamp",
      "handle": "pinkguy",
      "notes": "Pink Guy's official Bandcamp profile. (Jul 12, 2015)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "Bandcamp",
      "handle": "jojibeats",
      "notes": "Joji's official Bandcamp profile. (Aug 15, 2016)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "Spotify",
      "handle": "Pink Guy",
      "notes": "Pink Guy's official Spotify profile. (May 24, 2017)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube Music",
      "handle": "Pink Guy",
      "notes": "Pink Guy's official YouTube Music profile. (May 24, 2017)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "SoundCloud",
      "handle": "pinkomega",
      "notes": "Pink Guy's official SoundCloud profile. (Jul 18, 2017)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "SoundCloud",
      "handle": "chloeburbank",
      "notes": "Joji's official SoundCloud profile. (Aug 10, 2018)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "Amazon Music",
      "handle": "Joji",
      "notes": "Joji's official Amazon Music profile. (Nov 4, 2022)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "Deezer",
      "handle": "Joji",
      "notes": "Joji's official Deezer profile. (Nov 4, 2022)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "iHeart",
      "handle": "Joji",
      "notes": "Joji's official iHeart profile. (Nov 4, 2022)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "Spotify",
      "handle": "Joji",
      "notes": "Joji's official Spotify profile. (Nov 4, 2022)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "TIDAL",
      "handle": "Joji",
      "notes": "Joji's official TIDAL profile. (Nov 4, 2022)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube Music",
      "handle": "Joji",
      "notes": "Joji's official YouTube Music profile. (Nov 4, 2022)",
      "type": "Streaming",
      "status": "",
      "link": ""
    },
    {
      "platform": "SoundCloud",
      "handle": "jojiofficial",
      "notes": "Joji's second official SoundCloud profile. (Jan 16, 2024)",
      "type": "Streaming",
      "status": "",
      "link": ""
    }
  ],
  "kdotgold": [
    {
      "platform": "Audiomack",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://audiomack.com/kendricklamar"
    },
    {
      "platform": "Amazon Music",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://music.amazon.com/artists/B0042Q3AB4/kendrick-lamar"
    },
    {
      "platform": "Apple Music",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://music.apple.com/us/artist/kendrick-lamar/368183298"
    },
    {
      "platform": "Deezer",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://www.deezer.com/artist/525046"
    },
    {
      "platform": "Facebook",
      "handle": "Kendrick Lamar",
      "notes": "Kendrick's official Facebook page.",
      "type": "Other",
      "status": "",
      "link": "http://facebook.com/kendricklamar"
    },
    {
      "platform": "Instagram",
      "handle": "kendricklamar",
      "notes": "Kendrick's official Instagram page.",
      "type": "Other",
      "status": "",
      "link": "https://www.instagram.com/kendricklamar/"
    },
    {
      "platform": "Instagram",
      "handle": "jojoruski",
      "notes": "Kendrick's unofficial Instagram account created on June 15th, 2023.",
      "type": "Other",
      "status": "",
      "link": "https://instagram.com/jojoruski?igshid=MzRlODBiNWFlZA=="
    },
    {
      "platform": "SoundCloud",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://soundcloud.com/kendrick-lamar-music"
    },
    {
      "platform": "Spotify",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://open.spotify.com/artist/2YZyLoL8N0Wb9xBt1NhZWg"
    },
    {
      "platform": "Tidal",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://tidal.com/browse/artist/3816041"
    },
    {
      "platform": "Pandora",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://www.pandora.com/artist/kendrick-lamar/AR4PwkK9xrwzt6J"
    },
    {
      "platform": "Qobuz",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://www.qobuz.com/us-en/interpreter/kendrick-lamar/617741"
    },
    {
      "platform": "TikTok",
      "handle": "Kendrick Lamar",
      "notes": "Kendrick's official TikTok page.",
      "type": "Other",
      "status": "",
      "link": "https://www.tiktok.com/@kendricklamar"
    },
    {
      "platform": "𝕏",
      "handle": "kendricklamar",
      "notes": "Kendrick's official X page.",
      "type": "Other",
      "status": "",
      "link": "https://twitter.com/kendricklamar"
    },
    {
      "platform": "YouTube",
      "handle": "Kendrick Lamar",
      "notes": "Kendrick's official YouTube channel where music videos, interviews and live performances can be found.",
      "type": "Other",
      "status": "",
      "link": "https://www.youtube.com/channel/UC3lBXcrKFnFAFkfVk5WuKcQ"
    },
    {
      "platform": "YouTube Music",
      "handle": "Kendrick Lamar",
      "notes": "Subscription based streaming platform where Kendrick's commercial discography can be found.",
      "type": "Other",
      "status": "",
      "link": "https://music.youtube.com/channel/UCprAFmT0C6O4X0ToEXpeFTQ"
    },
    {
      "platform": "Website",
      "handle": "oklama",
      "notes": "Kendrick's official website domain to follow updates from himself apparently ran by pgLang.",
      "type": "Other",
      "status": "",
      "link": "http://oklama.com"
    },
    {
      "platform": "Facebook",
      "handle": "PG Lang",
      "notes": "pgLang's official Facebook page.",
      "type": "Other",
      "status": "",
      "link": "https://www.facebook.com/pg.lang.10"
    },
    {
      "platform": "Instagram",
      "handle": "pglang",
      "notes": "pgLang's official Instagram page.",
      "type": "Other",
      "status": "",
      "link": "https://www.instagram.com/pglang/"
    },
    {
      "platform": "TikTok",
      "handle": "pglang",
      "notes": "pgLang's official TikTok page.",
      "type": "Other",
      "status": "",
      "link": "http://tiktok.com/@pglang?lang=en"
    },
    {
      "platform": "𝕏",
      "handle": "pgLang",
      "notes": "pgLang's official X page.",
      "type": "Other",
      "status": "",
      "link": "https://twitter.com/pglang"
    },
    {
      "platform": "YouTube",
      "handle": "pgLang",
      "notes": "pgLang's official YouTube channel where teasers, music videos and footages based off of it's website can be found.",
      "type": "Other",
      "status": "",
      "link": "https://www.youtube.com/c/pgLang"
    },
    {
      "platform": "Website",
      "handle": "pglang",
      "notes": "pgLang's official website ran by company itself.",
      "type": "Other",
      "status": "",
      "link": "http://pg-lang.com"
    }
  ],
  "vampgold": [
    {
      "platform": "TUMBLR",
      "handle": "@yungcarti",
      "notes": "cartis tumblr where he posted and promoted his music in early stages of his career. His first post was on Nov 30, 2010.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://yungcarti.tumblr.com"
    },
    {
      "platform": "Flavors",
      "handle": "JCartier Da Don",
      "notes": "Carti’s Flavors account, a website where you could link all your socials (pretty much Linktree but for the early 2010s) was linked on his Tumblr. The link is now dead since the site shut down in 2017.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "http://flavors.me/jcartier#.Tl1q44NhYoQ.tumblr"
    },
    {
      "platform": "X",
      "handle": "@jceebitchez",
      "notes": "Deleted old X account used by Carti during 2010, found in his Tumblr.",
      "type": "Social Media",
      "status": "Inactive",
      "link": ""
    },
    {
      "platform": "X",
      "handle": "@playboicarti",
      "notes": "Carti's official X account.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://twitter.com/playboicarti"
    },
    {
      "platform": "Soundcloud",
      "handle": "j-tfz-cartier",
      "notes": "Cartis old Soundcloud. Used in 2011-2012. Everything deleted exept blue crystal$.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://soundcloud.com/j-tfz-cartier"
    },
    {
      "platform": "Hotmail",
      "handle": "jctaughtyou@hotmail.com",
      "notes": "First email that Carti made, provided by Carti himself in his Office magazine interview.",
      "type": "Social Media",
      "status": "Inactive",
      "link": ""
    },
    {
      "platform": "Yahoo",
      "handle": "jrdncrtr10@yahoo.com",
      "notes": "Old email. Provided by tame1 on dc.",
      "type": "Social Media",
      "status": "Inactive",
      "link": ""
    },
    {
      "platform": "Youtube",
      "handle": "@sircartier2572",
      "notes": "Carti's old Youtube channel",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.youtube.com/@sircartier2572"
    },
    {
      "platform": "Newgrounds",
      "handle": "sircartier",
      "notes": "Carti's old Newgrounds page.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://sircartier.newgrounds.com/audio"
    },
    {
      "platform": "Soundcloud",
      "handle": "YoungCartierHoe",
      "notes": "Cartis old Soundcloud. Used in 2012 to first week of january 2014",
      "type": "Social Media",
      "status": "Inactive",
      "link": ""
    },
    {
      "platform": "Soundcloud",
      "handle": "678carti",
      "notes": "Carti's old Soundcloud",
      "type": "Social Media",
      "status": "Inactive",
      "link": ""
    },
    {
      "platform": "bandcamp",
      "handle": "jcartier",
      "notes": "Carti's old bandcamp",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://jcartier.bandcamp.com/"
    },
    {
      "platform": "Soundcloud",
      "handle": "@playboicarti",
      "notes": "Carti's soundcloud",
      "type": "Social Media",
      "status": "Active",
      "link": "https://soundcloud.com/playboicarti"
    },
    {
      "platform": "Youtube",
      "handle": "@playboicarti3216",
      "notes": "Carti's old YouTube channel. The only thing he posted there is the Talk (ICYTWAT Remix) music video.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.youtube.com/@playboicarti3216"
    },
    {
      "platform": "Gmail",
      "handle": "playboiconnor@gmail.com",
      "notes": "Carti's email used for his old Youtube also linked to his manager's email and number.",
      "type": "Social Media",
      "status": "Inactive",
      "link": ""
    },
    {
      "platform": "Apple Music",
      "handle": "Playboi Carti",
      "notes": "Carti's official Apple Music account, may have been made even earlier but there is no certain way of knowing.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://music.apple.com/us/artist/playboi-carti/982372505"
    },
    {
      "platform": "Deezer",
      "handle": "Playboi Carti",
      "notes": "Carti's official Deezer account, may have been made even earlier but there is no certain way of knowing.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.deezer.com/us/artist/10002824"
    },
    {
      "platform": "TIDAL",
      "handle": "Playboi Carti",
      "notes": "Carti's official TIDAL account, may have been made even earlier but there is no certain way of knowing.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://tidal.com/browse/artist/7663291"
    },
    {
      "platform": "Pandora",
      "handle": "Playboi Carti",
      "notes": "Carti´s Pandora account, probably made recently but no way of knowing and also was probably made by the label and not Carti.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.pandora.com/artist/playboi-carti/AR7twf45jK6m4c2"
    },
    {
      "platform": "Spotify",
      "handle": "Playboi Carti",
      "notes": "Carti's official Spotify account, may have been made even earlier but there is no certain way of knowing.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://open.spotify.com/artist/699OTQXzgjhIYAHMy9RyPD?si=M-SDq3GFT9OiQlst9PJwbA"
    },
    {
      "platform": "X",
      "handle": "@cartierhoe",
      "notes": "Carti's Twitter burned made in May 2016 just to promote his main account",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://x.com/cartierhoe"
    },
    {
      "platform": "Instagram",
      "handle": "@playboicarti",
      "notes": "Carti's official IG",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.instagram.com/playboicarti/"
    },
    {
      "platform": "Facebook",
      "handle": "Playboi Carti",
      "notes": "Carti's official facebook page.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.facebook.com/PlayboiCarti"
    },
    {
      "platform": "Youtube",
      "handle": "@playboicarti",
      "notes": "Carti's official Youtube channel.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.youtube.com/@playboicarti/videos"
    },
    {
      "platform": "Instagram",
      "handle": "@therealfullmetal2009",
      "notes": "Carti's old instagram burner made in May 2017. Bio is still teasing 16*29.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/therealfullmetal2009/"
    },
    {
      "platform": "Instagram",
      "handle": "@nineninesixteensixteen",
      "notes": "Another old Instagram burner made by Carti in January 2018.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/nineninesixteensixteen/"
    },
    {
      "platform": "Instagram",
      "handle": "@opium_opiumoo",
      "notes": "Carti burner made in 2019, hacked and no longer used.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/opium_opiumoo/"
    },
    {
      "platform": "Instagram",
      "handle": "@opium_00pium",
      "notes": "Carti's ongoing burner IG",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.instagram.com/opium_00pium/"
    },
    {
      "platform": "TikTok",
      "handle": "@playboicarti",
      "notes": "Carti's official TikTok account.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.tiktok.com/@playboicarti?lang=en"
    },
    {
      "platform": "Audiomack",
      "handle": "@playboicarti",
      "notes": "Carti's official Audiomack account.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://audiomack.com/playboicarti"
    },
    {
      "platform": "Instagram",
      "handle": "@00piumlab",
      "notes": "Carti's burner IG. Supposedly meant to promote artists under his Opium label.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/00piumlab"
    },
    {
      "platform": "X",
      "handle": "@swag37964",
      "notes": "Carti Twitter burner made in October 2023 solely for the purpose of defending himself under a Lidestywurld post.",
      "type": "Social Media",
      "status": "Unknown",
      "link": "https://x.com/swag37964"
    },
    {
      "platform": "Instagram",
      "handle": "@gohomeriri",
      "notes": "Carti's new finsta that joined in March 2024 that he ended up leaking himself. Now private and probably no longer used.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/gohomeriri?igsh=NzJvN3d1bnJtbWht"
    },
    {
      "platform": "Instagram",
      "handle": "@???",
      "notes": "According to reliable sources, Carti has a new finsta.",
      "type": "Social Media",
      "status": "Active",
      "link": ""
    },
    {
      "platform": "Instagram",
      "handle": "@a1_infamous",
      "notes": "Followed by Carti's opium_00pium account and other Carti affiliates",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.instagram.com/a1_infamous"
    },
    {
      "platform": "TikTok",
      "handle": "@richardmilly82",
      "notes": "Burner TikTok account where Carti posted 2 videos before deleting them and changing the account's username to @richardmilly1996.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.tiktok.com/@richardmilly1996"
    },
    {
      "platform": "Instagram",
      "handle": "jordancarterpc@gmail.com",
      "notes": "Carti's current email was found after trying to log in into his IG. Unknown when made.",
      "type": "Social Media",
      "status": "Unknown",
      "link": ""
    },
    {
      "platform": "TikTok",
      "handle": "@Blackportland5",
      "notes": "Carti's new alt account on TikTok. Also goes by the name @MOB96",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.tiktok.com/@blackportland5?_r=1&_t=ZS-968VfIbdG4n"
    }
  ],
  "xgold": [
    {
      "platform": "Amazon Music",
      "handle": "XXXTENTACION",
      "notes": "Official Amazon Music page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.amazon.com/artists/B01BM5MW2K/xxxtentacion"
    },
    {
      "platform": "Apple Music",
      "handle": "XXXTENTACION",
      "notes": "Official Apple Music page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.apple.com/us/artist/xxxtentacion/1082533559"
    },
    {
      "platform": "ask.fm",
      "handle": "oddjahseh",
      "notes": "Now Deleted ask.fm page, still can be found through wayback machine.",
      "type": "Other",
      "status": "",
      "link": "https://ask.fm/oddjahseh/"
    },
    {
      "platform": "Audiomack",
      "handle": "XXXTENTACION",
      "notes": "Official Audiomack page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://audiomack.com/xxxtentacion"
    },
    {
      "platform": "Bandcamp",
      "handle": "xxxtentacion",
      "notes": "X's Bandcamp used only so he can upload Members Only Vol. 2 and ♡ ʳ ᵃ ʳ ᵉ ♡.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://xxxtentacion.bandcamp.com"
    },
    {
      "platform": "Deezer",
      "handle": "XXXTENTACION",
      "notes": "Official Deezer page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://www.deezer.com/us/artist/9822974"
    },
    {
      "platform": "Facebook",
      "handle": "Xxxtentacion",
      "notes": "X's official page",
      "type": "Social Media",
      "status": "",
      "link": "https://www.facebook.com/BadVibezForever"
    },
    {
      "platform": "Facebook",
      "handle": "Jahseh Onfroy",
      "notes": "X's original personal page deleted sometime in 2015 (?)",
      "type": "Social Media",
      "status": "",
      "link": "https://www.facebook.com/lecockwad"
    },
    {
      "platform": "Instagram",
      "handle": "frog.onfroy",
      "notes": "Page made for X's dog",
      "type": "Social Media",
      "status": "",
      "link": "https://instagram.com/frog.onfroy"
    },
    {
      "platform": "Instagram",
      "handle": "jahsehonfroy",
      "notes": "First Instagram page X made",
      "type": "Social Media",
      "status": "",
      "link": "https://instagram.com/jahsehonfroy"
    },
    {
      "platform": "Instagram",
      "handle": "members_only954",
      "notes": "Personal account X made",
      "type": "Social Media",
      "status": "",
      "link": "https://instagram.com/members_only954"
    },
    {
      "platform": "Instagram",
      "handle": "titan.onfroy",
      "notes": "Page made for X's dog",
      "type": "Social Media",
      "status": "",
      "link": "https://instagram.com/titan.onfroy"
    },
    {
      "platform": "Instagram",
      "handle": "xxxtentacion",
      "notes": "Official page for XXXTENTACION",
      "type": "Social Media",
      "status": "",
      "link": "https://instagram.com/xxxtentacion"
    },
    {
      "platform": "Instagram",
      "handle": "lildickgirl666",
      "notes": "Now deleted personal private account linked to X's phone number",
      "type": "Social Media",
      "status": "",
      "link": "https://instagram.com/lildickgirl666"
    },
    {
      "platform": "Pandora",
      "handle": "XXXTENTACION",
      "notes": "Official Pandora page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://www.pandora.com/artist/xxxtentacion/ARZKjvvP4nhhfbV"
    },
    {
      "platform": "Playstation",
      "handle": "MAKEOUTHILL",
      "notes": "",
      "type": "Other",
      "status": "",
      "link": ""
    },
    {
      "platform": "Qobus",
      "handle": "XXXTENTACION",
      "notes": "Official Qobus page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": ""
    },
    {
      "platform": "Snapchat",
      "handle": "theheroinfather",
      "notes": "",
      "type": "Social Media",
      "status": "",
      "link": "https://www.snapchat.com/add/theheroinfather"
    },
    {
      "platform": "Snapchat",
      "handle": "heroinfather",
      "notes": "",
      "type": "Social Media",
      "status": "",
      "link": "https://www.snapchat.com/add/heroinfather"
    },
    {
      "platform": "Snapchat",
      "handle": "xxxtentacion",
      "notes": "",
      "type": "Social Media",
      "status": "",
      "link": "https://www.snapchat.com/add/xxxtentacion"
    },
    {
      "platform": "SoundCloud",
      "handle": "Members Only",
      "notes": "Members Only Soundcloud made by X to post Members Only Vol. 2.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://soundcloud.com/members-only666"
    },
    {
      "platform": "SoundCloud",
      "handle": "XXXTENTACION",
      "notes": "X's main Soundcloud page where most of his songs were posted.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://soundcloud.com/jahseh-onfroy"
    },
    {
      "platform": "Spotify",
      "handle": "XXXTENTACION",
      "notes": "Official Spotify page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://open.spotify.com/artist/15UsOTVnJzReFVN1VCnxy4?si=W6Y1uJhNQZ-TAqeAwHfzGg"
    },
    {
      "platform": "Spotify",
      "handle": "XXXTENTACION",
      "notes": "Official Spotify profile for XXXTENTACION.",
      "type": "Other",
      "status": "",
      "link": "https://open.spotify.com/user/soundsmusicgroup?si=4db2217da67b4f5b"
    },
    {
      "platform": "Steam",
      "handle": "lildickgirl666",
      "notes": "",
      "type": "Other",
      "status": "",
      "link": ""
    },
    {
      "platform": "Tidal",
      "handle": "XXXTENTACION",
      "notes": "Official Tidal page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://tidal.com/browse/artist/7589458"
    },
    {
      "platform": "Tumblr",
      "handle": "fuckjahseh-blog",
      "notes": "Tumblr Used by X from April 2012 - January 2013 Most likely more but we will never know.",
      "type": "Social Media",
      "status": "",
      "link": "https://fuckjahseh-blog.tumblr.com/"
    },
    {
      "platform": "Tumblr",
      "handle": "xxxtentacion",
      "notes": "Used from 2014 till he passed in 2018",
      "type": "Social Media",
      "status": "",
      "link": "https://xxxtentacion.tumblr.com/"
    },
    {
      "platform": "MyAnimeList",
      "handle": "heroinfather",
      "notes": "Used from March 28, 2013 to October 29, 2016",
      "type": "Other",
      "status": "",
      "link": "https://myanimelist.net/profile/heroinfather"
    },
    {
      "platform": "Crunchyroll",
      "handle": "jahseh",
      "notes": "Used 2013 till unknown when, vise accessed and secured",
      "type": "Other",
      "status": "",
      "link": "https://www.crunchyroll.com/user/jahseh"
    },
    {
      "platform": "VSCO",
      "handle": "razzleboi",
      "notes": "X's personal VSCO account",
      "type": "Other",
      "status": "",
      "link": "https://vsco.co/razzleboi"
    },
    {
      "platform": "X",
      "handle": "INFO_BADVIBES",
      "notes": "Promo page made by x",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/INFO_BADVIBES"
    },
    {
      "platform": "X",
      "handle": "jahsehO",
      "notes": "Suspended Twitter account made by X.",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/JahsehO"
    },
    {
      "platform": "X",
      "handle": "Jahseh_Boiiii",
      "notes": "X's first Twitter account.",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/jahseh_boiiii"
    },
    {
      "platform": "X",
      "handle": "xxxtentacion",
      "notes": "Official XXXTENTACION twitter",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/xxxtentacion"
    },
    {
      "platform": "X",
      "handle": "xxxmembersonly",
      "notes": "Promo account X made in April 2015",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/xxxmembersonly"
    },
    {
      "platform": "X",
      "handle": "xyxyxxxxxx",
      "notes": "Promo account X made in 2014",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/xyxyxxxxxx"
    },
    {
      "platform": "X",
      "handle": "youngdaggerdick",
      "notes": "Suspended Twitter account made by X.",
      "type": "Social Media",
      "status": "",
      "link": "https://twitter.com/youngdaggerdick"
    },
    {
      "platform": "Xbox",
      "handle": "TRANSGENDERMOMS",
      "notes": "X's only xbox name",
      "type": "Other",
      "status": "",
      "link": ""
    },
    {
      "platform": "Kik",
      "handle": "fuckjahseh",
      "notes": "X's original personal kik account",
      "type": "Other",
      "status": "",
      "link": ""
    },
    {
      "platform": "Kik",
      "handle": "vaginalwarrior666",
      "notes": "Kik account posted on instagram in 2017",
      "type": "Other",
      "status": "",
      "link": ""
    },
    {
      "platform": "YouTube",
      "handle": "Skully Bones (Jahseh Onfroy)",
      "notes": "XXXTENTACION's Oldest known youtube channel that was made in May 25, 2012 could have uploaded other videos beforehand but is in this area due to the only video available was a concert in 2015, He has a playlist with Final Fantasy Songs and his channel name before \"Skully Bones\" Was just \"Jahseh Onfroy\".",
      "type": "Other",
      "status": "",
      "link": "https://www.youtube.com/@CrazyInTheMaking"
    },
    {
      "platform": "YouTube",
      "handle": "XXXTENTACION",
      "notes": "First made to upload a few songs later becoming the place for his official releases and several vlog and gaming videos",
      "type": "Other",
      "status": "",
      "link": "https://www.youtube.com/channel/UCM9r1xn6s30OnlJWb-jc3Sw"
    },
    {
      "platform": "YouTube Music",
      "handle": "XXXTENTACION",
      "notes": "Official YouTube Music page for XXXTENTACION.",
      "type": "Streaming Service",
      "status": "",
      "link": "https://music.youtube.com/channel/UCnAcxgRZ065f_eXK1o85c1w"
    },
    {
      "platform": "Website",
      "handle": "shopxxxtentacion",
      "notes": "Now defunked XXXTENTACION merch site",
      "type": "Website",
      "status": "",
      "link": ""
    },
    {
      "platform": "Website",
      "handle": "xxxtentacion",
      "notes": "Current site for everything on X merch and more",
      "type": "Website",
      "status": "",
      "link": "https://www.xxxtentacion.com/"
    }
  ],
  "twizzygold": [
    {
      "platform": "Amazon Music",
      "handle": "Yeat",
      "notes": "Subscription based streaming platform where Yeat's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "Active",
      "link": "https://music.amazon.com/artists/B078C55TSK/yeat"
    },
    {
      "platform": "Apple Music",
      "handle": "Yeat",
      "notes": "Subscription based streaming platform where Yeat's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "Active",
      "link": "https://music.apple.com/gb/artist/yeat/1318094493"
    },
    {
      "platform": "Chess",
      "handle": "@yeatmus",
      "notes": "Yeat's Chess.com account, created on January 20, 2021.",
      "type": "Other",
      "status": "Inactive",
      "link": "https://www.chess.com/member/yeatmus"
    },
    {
      "platform": "Duolingo",
      "handle": "@Noahsmith639431",
      "notes": "Yeat's Duolingo account, created in July 2015.",
      "type": "Other",
      "status": "Inactive",
      "link": "https://www.duolingo.com/profile/Noahsmith639431"
    },
    {
      "platform": "Deezer",
      "handle": "Yeat",
      "notes": "Subscription based streaming platform where Yeat's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "Active",
      "link": "https://www.deezer.com/us/artist/13639985"
    },
    {
      "platform": "Facebook",
      "handle": "Yeat",
      "notes": "Yeat's official Facebook page. Used purely for promotional purposes.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.facebook.com/yeatmusic"
    },
    {
      "platform": "Instagram",
      "handle": "@_noah_smith",
      "notes": "Seemingly Yeat's first ever Instagram handle.",
      "type": "Social Media",
      "status": "Repurposed",
      "link": "https://www.instagram.com/_noah_smith"
    },
    {
      "platform": "Instagram",
      "handle": "@noahsmith222",
      "notes": "Yeat's old personal private Instagram page",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/noahsmith222"
    },
    {
      "platform": "Instagram",
      "handle": "@yeat1500",
      "notes": "Temporary Yeat Instagram handle.",
      "type": "Social Media",
      "status": "Repurposed",
      "link": "https://www.instagram.com/yeat1500"
    },
    {
      "platform": "Instagram",
      "handle": "@yeat",
      "notes": "Yeat's official Instagram page.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.instagram.com/yeat"
    },
    {
      "platform": "Instagram",
      "handle": "@luhgeeky",
      "notes": "Alternate Yeat Instagram page.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/luhgeeky"
    },
    {
      "platform": "Instagram",
      "handle": "@luhshmooky",
      "notes": "Alternate Yeat Instagram page.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/luhshmooky/"
    },
    {
      "platform": "Instagram",
      "handle": "@tonkablicks",
      "notes": "Alternate Yeat Instagram page.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/tonkablicks"
    },
    {
      "platform": "Instagram",
      "handle": "@kingshmonkkkk",
      "notes": "Alternate Yeat Instagram page.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.instagram.com/kingshmonkkkk/"
    },
    {
      "platform": "Kik",
      "handle": "@NoahSmith12",
      "notes": "Yeat's original Kik account, created on December 22, 2012.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://kik.me/noahsmith12"
    },
    {
      "platform": "Kik",
      "handle": "@____bigboy____",
      "notes": "Yeat's Kik account, created on November 11, 2014. The account was compromised in 2026, and the display name was changed from \"Bick Dig\" to \"moving goated.\"",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://kik.me/____bigboy____"
    },
    {
      "platform": "Quizlet",
      "handle": "@lilgoose",
      "notes": "Yeat's Quizlet account.",
      "type": "Other",
      "status": "Inactive",
      "link": "https://quizlet.com/user/lilgoose"
    },
    {
      "platform": "Roblox",
      "handle": "@DangerousSummer123",
      "notes": "Yeat's original Roblox username.",
      "type": "Other",
      "status": "Repurposed",
      "link": "https://www.roblox.com/users/9983351795/profile"
    },
    {
      "platform": "Roblox",
      "handle": "@yeatofficial",
      "notes": "Yeat's official Roblox account.",
      "type": "Other",
      "status": "Active",
      "link": "https://www.roblox.com/users/9983351795/profile"
    },
    {
      "platform": "SoundCloud",
      "handle": "user166703093",
      "notes": "Yeat's original SoundCloud account, created on October 3, 2014.",
      "type": "Streaming Service",
      "status": "Inactive",
      "link": "https://soundcloud.com/user166703093"
    },
    {
      "platform": "SoundCloud",
      "handle": "yungns503",
      "notes": "Alternate Yeat Soundcloud account from 2015.",
      "type": "Streaming Service",
      "status": "Inactive",
      "link": "https://soundcloud.com/yungns503"
    },
    {
      "platform": "SoundCloud",
      "handle": "PsychoGANG",
      "notes": "Alternate Yeat Soundcloud account from 2017.",
      "type": "Streaming Service",
      "status": "Inactive",
      "link": "https://soundcloud.com/noah-smith-422620005"
    },
    {
      "platform": "SoundCloud",
      "handle": "dinger",
      "notes": "Alternate Yeat Soundcloud account.",
      "type": "Streaming Service",
      "status": "Inactive",
      "link": "https://soundcloud.com/mmm-milk-man-murda"
    },
    {
      "platform": "SoundCloud",
      "handle": "yurntboi",
      "notes": "Alternate Yeat Soundcloud account.",
      "type": "Streaming Service",
      "status": "Inactive",
      "link": "https://soundcloud.com/user-730361990"
    },
    {
      "platform": "SoundCloud",
      "handle": "Yeat",
      "notes": "Subscription based streaming platform where Yeat's commercial discography can be found. Originally titled \"Lil Yeat,\" then \"YEAT.\"",
      "type": "Streaming Service",
      "status": "Active",
      "link": "https://soundcloud.com/lilyeat"
    },
    {
      "platform": "SoundCloud",
      "handle": "Yeat Archive",
      "notes": "Subscription based streaming platform where Yeat's archive discography can be found.",
      "type": "Streaming Service",
      "status": "Inactive",
      "link": "https://soundcloud.com/user-627676340-724428078"
    },
    {
      "platform": "Spotify",
      "handle": "noahsmith12",
      "notes": "Yeat's old personal Spotify account from 2014.",
      "type": "Streaming Service",
      "status": "Inactive",
      "link": "https://open.spotify.com/user/noahsmith12"
    },
    {
      "platform": "Spotify",
      "handle": "Yeat",
      "notes": "Subscription based streaming platform where Yeat's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "Active",
      "link": "https://open.spotify.com/artist/3qiHUAX7zY4Qnjx8TNUzVx"
    },
    {
      "platform": "Smule",
      "handle": "@juicy_killa",
      "notes": "Yeat's Smule account.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.smule.com/juicy_killa"
    },
    {
      "platform": "Tidal",
      "handle": "Yeat",
      "notes": "Subscription based streaming platform where Yeat's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "Active",
      "link": "https://tidal.com/browse/artist/9318056"
    },
    {
      "platform": "TikTok",
      "handle": "@officialyeat",
      "notes": "Yeat's official TikTok page.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.tiktok.com/@officialyeat"
    },
    {
      "platform": "TikTok",
      "handle": "@yeat",
      "notes": "Possibly an official Yeat TikTok account as it was linked in a Universal Music Group page, however, may be inaccurate.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://www.tiktok.com/@yeat"
    },
    {
      "platform": "TikTok",
      "handle": "@lyfe.corp",
      "notes": "Alternate Yeat TikTok account, created on October 19, 2024.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.tiktok.com/@lyfe.corp"
    },
    {
      "platform": "Triller",
      "handle": "@yeatyeatyeat",
      "notes": "One of Yeat's Triller social media accounts.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://triller.co/@yeatyeatyeat"
    },
    {
      "platform": "Triller",
      "handle": "@yeatyeatx20040",
      "notes": "One of Yeat's Triller social media accounts.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://triller.co/@yeatyeatx20040"
    },
    {
      "platform": "Triller",
      "handle": "@yeagokidd",
      "notes": "One of Yeat's Triller social media accounts.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://triller.co/@yeagokidd"
    },
    {
      "platform": "Triller",
      "handle": "@yeatyeat",
      "notes": "One of Yeat's Triller social media accounts.",
      "type": "Social Media",
      "status": "Inactive",
      "link": "https://triller.co/@yeatyeat"
    },
    {
      "platform": "Twitter",
      "handle": "@lil_yeat",
      "notes": "Yeat's original Twitter handle.",
      "type": "Social Media",
      "status": "Repurposed",
      "link": "https://twitter.com/lil_yeat"
    },
    {
      "platform": "Twitter",
      "handle": "@yeatglobal",
      "notes": "Temporary Yeat Twitter handle.",
      "type": "Social Media",
      "status": "Repurposed",
      "link": "https://twitter.com/yeatglobal"
    },
    {
      "platform": "Twitter",
      "handle": "@yeat1_",
      "notes": "Yeat's official Twitter page. Converted to an X account following the July 23, 2023 rebrand.",
      "type": "Social Media",
      "status": "Repurposed",
      "link": "https://twitter.com/yeat1_"
    },
    {
      "platform": "[untitled]",
      "handle": "user0003303994",
      "notes": "Yeat's official [untitled] account.",
      "type": "Other",
      "status": "Active",
      "link": ""
    },
    {
      "platform": "X",
      "handle": "@yeat1_",
      "notes": "Yeat's official X page.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://x.com/yeat1_"
    },
    {
      "platform": "YouTube",
      "handle": "Yeat Music",
      "notes": "Yeat's official YouTube channel where a variety of videos can be found, most notably music videos.",
      "type": "Other",
      "status": "Active",
      "link": "https://www.youtube.com/channel/UCV4UK9LNNLViFP4qZA_Wmfw"
    },
    {
      "platform": "YouTube Music",
      "handle": "Yeat",
      "notes": "Subscription based streaming platform where Yeat's commercial discography can be found.",
      "type": "Streaming Service",
      "status": "Active",
      "link": "https://music.youtube.com/channel/UCXvxWMFHlTAXlhpwkQ4Y2Hw"
    },
    {
      "platform": "Website",
      "handle": "Yeat Official",
      "notes": "Yeat's website where promotion for the artist can be found.",
      "type": "Other",
      "status": "Active",
      "link": "https://yeatofficial.com/"
    },
    {
      "platform": "Instagram",
      "handle": "@twizzyrichent",
      "notes": "Twizzy Rich's official Instagram page. Later repurposed into the Lyfestyle Corporation account.",
      "type": "Social Media",
      "status": "Repurposed",
      "link": "https://www.instagram.com/twizzyrichent"
    },
    {
      "platform": "Instagram",
      "handle": "@lyfestylecorporation",
      "notes": "Lyfestyle Corporation's official Instagram page.",
      "type": "Social Media",
      "status": "Active",
      "link": "https://www.instagram.com/lyfestylecorporation"
    }
  ]
};

export function hasSocials(slug: string): boolean {
  return (SOCIALS_DATA[slug]?.length ?? 0) > 0;
}
